In [17]:
import pandas as pd

from NLP.RNN import vocab_size

dataset=pd.read_csv('/home/hammadali08/Personal/CSV file/eng_-french.csv')
dataset

,English words/sentences,French words/sentences
0,Hi.,Salut!
1,Run!,Cours !
2,Run!,Courez !
3,Who?,Qui ?
4,Wow!,Ça alors !
...,...,...
175616,"Top-down economics never works, said Obama. ""T...","« L'économie en partant du haut vers le bas, ç..."
175617,A carbon footprint is the amount of carbon dio...,Une empreinte carbone est la somme de pollutio...
175618,Death is something that we're often discourage...,La mort est une chose qu'on nous décourage sou...
175619,Since there are usually multiple websites on a...,Puisqu'il y a de multiples sites web sur chaqu...
175620,If someone who doesn't know your background sa...,Si quelqu'un qui ne connaît pas vos antécédent...

In [24]:
dataset = dataset.rename(columns={'English words/sentences': 'English'})
dataset= dataset.rename(columns={'French words/sentences': 'French'})
dataset

,English,French
0,Hi.,Salut!
1,Run!,Cours !
2,Run!,Courez !
3,Who?,Qui ?
4,Wow!,Ça alors !
...,...,...
175616,"Top-down economics never works, said Obama. ""T...","« L'économie en partant du haut vers le bas, ç..."
175617,A carbon footprint is the amount of carbon dio...,Une empreinte carbone est la somme de pollutio...
175618,Death is something that we're often discourage...,La mort est une chose qu'on nous décourage sou...
175619,Since there are usually multiple websites on a...,Puisqu'il y a de multiples sites web sur chaqu...
175620,If someone who doesn't know your background sa...,Si quelqu'un qui ne connaît pas vos antécédent...

In [25]:
import re
corpus = []
for i in range(0, len(dataset)):
    review = re.sub('[^a-zA-Z0-9]', ' ', dataset['English'][i])
    review = review.lower()
    review = review.split()

    review = ' '.join(review)
    corpus.append(review)

In [26]:
corpus

['hi',
 'run',
 'run',
 'who',
 'wow',
 'fire',
 'help',
 'jump',
 'stop',
 'stop',
 'stop',
 'wait',
 'wait',
 'go on',
 'go on',
 'go on',
 'hello',
 'hello',
 'i see',
 'i try',
 'i won',
 'i won',
 'i won',
 'oh no',
 'attack',
 'attack',
 'cheers',
 'cheers',
 'cheers',
 'cheers',
 'get up',
 'go now',
 'go now',
 'go now',
 'got it',
 'got it',
 'got it',
 'got it',
 'got it',
 'hop in',
 'hop in',
 'hug me',
 'hug me',
 'i fell',
 'i fell',
 'i know',
 'i left',
 'i left',
 'i lied',
 'i lost',
 'i paid',
 'i m 19',
 'i m ok',
 'i m ok',
 'listen',
 'no way',
 'no way',
 'no way',
 'no way',
 'no way',
 'no way',
 'no way',
 'no way',
 'no way',
 'really',
 'really',
 'really',
 'thanks',
 'we try',
 'we won',
 'we won',
 'we won',
 'we won',
 'ask tom',
 'awesome',
 'be calm',
 'be calm',
 'be calm',
 'be cool',
 'be fair',
 'be fair',
 'be fair',
 'be fair',
 'be fair',
 'be fair',
 'be kind',
 'be nice',
 'be nice',
 'be nice',
 'be nice',
 'be nice',
 'be nice',
 'beat it',
 'call me',
 'call me',
 'call us',
 'call us',
 'come in',
 'come in',
 'come in',
 'come in',
 'come on',
 'come on',
 'come on',
 'come on',
 'drop it',
 'drop it',
 'drop it',
 'drop it',
 'get tom',
 'get out',
 'get out',
 'get out',
 'get out',
 'get out',
 'go away',
 'go away',
 'go away',
 'go away',
 'go away',
 'go away',
 'go away',
 'go away',
 'go away',
 'go away',
 'go home',
 'go home',
 'go home',
 'go home',
 'go slow',
 'go slow',
 'goodbye',
 'goodbye',
 'hang on',
 'hang on',
 'hang on',
 'hang on',
 'he quit',
 'he quit',
 'he runs',
 'help me',
 'help me',
 'help me',
 'help us',
 'help us',
 'hold it',
 'hold on',
 'hug tom',
 'i agree',
 'i cried',
 'i dozed',
 'i dozed',
 'i drive',
 'i smoke',
 'i snore',
 'i stink',
 'i stood',
 'i stood',
 'i swore',
 'i swore',
 'i tried',
 'i tried',
 'i tried',
 'i waved',
 'i ll go',
 'i m tom',
 'i m fat',
 'i m fat',
 'i m fit',
 'i m hit',
 'i m hit',
 'i m ill',
 'i m sad',
 'i m shy',
 'i m wet',
 'i m wet',
 'it s me',
 'join us',
 'join us',
 'keep it',
 'keep it',
 'kiss me',
 'kiss me',
 'me too',
 'open up',
 'open up',
 'perfect',
 'see you',
 'see you',
 'see you',
 'see you',
 'show me',
 'show me',
 'shut up',
 'shut up',
 'shut up',
 'shut up',
 'shut up',
 'skip it',
 'so long',
 'take it',
 'take it',
 'take it',
 'take it',
 'tell me',
 'tell me',
 'tom won',
 'wake up',
 'wake up',
 'wake up',
 'wake up',
 'wake up',
 'wash up',
 'wash up',
 'we know',
 'we lost',
 'we lost',
 'we lost',
 'we lost',
 'we lost',
 'we lost',
 'we lost',
 'we lost',
 'we lost',
 'we lost',
 'welcome',
 'who won',
 'who won',
 'you run',
 'am i fat',
 'am i fat',
 'ask them',
 'ask them',
 'back off',
 'back off',
 'back off',
 'back off',
 'back off',
 'back off',
 'be a man',
 'be a man',
 'be still',
 'be still',
 'be still',
 'beats me',
 'beats me',
 'call tom',
 'call tom',
 'cheer up',
 'cool off',
 'cuff him',
 'drive on',
 'drive on',
 'drive on',
 'drive on',
 'find tom',
 'find tom',
 'fix this',
 'fix this',
 'get down',
 'get down',
 'get down',
 'get down',
 'get down',
 'get lost',
 'get lost',
 'get lost',
 'get real',
 'go ahead',
 'go ahead',
 'go ahead',
 'go ahead',
 'go ahead',
 'go ahead',
 'go ahead',
 'good job',
 'good job',
 'good job',
 'grab him',
 'grab him',
 'have fun',
 'have fun',
 'he tries',
 'he s wet',
 'help tom',
 'help tom',
 'hi guys',
 'how cute',
 'how deep',
 'how nice',
 'how nice',
 'how nice',
 'how nice',
 'hurry up',
 'hurry up',
 'hurry up',
 'hurry up',
 'i did ok',
 'i did ok',
 'i did it',
 'i did it',
 'i failed',
 'i forgot',
 'i get it',
 'i got it',
 'i got it',
 'i helped',
 'i jumped',
 'i looked',
 'i moaned',
 'i nodded',
 'i obeyed',
 'i phoned',
 'i phoned',
 'i refuse',
 'i refuse',
 'i rested',
 'i rested',
 'i saw it',
 'i saw it',
 'i sighed',
 'i stayed',
 'i stayed',
 'i talked',
 'i use it',
 'i use it',
 'i use it',
 'i ll pay',
 'i ll try',
 'i ll try',
 'i m back',
 'i m back',
 'i m bald',
 'i m busy',
 'i m busy',
 'i m calm',
 'i m cold',
 'i m cool',
 'i m cool',
 'i m deaf',
 'i m deaf',
 'i m done',
 'i m fair',
 'i m fair',
 'i m fair',
 'i m fast',
 'i m fine',
 'i m fine',
 'i m fine',
 'i m free',
 'i m free',
 'i m free',
 'i m full',
 'i m full',
 'i m game',
 'i m game',
 'i m glad',
 'i m home',
 'i m late',
 'i m lazy',
 'i m lazy',
 'i m lazy',
 'i m lazy',
 'i m okay',
 'i m okay',
 'i m rich',
 'i m safe',
 'i m sick',
 'i m sure',
 'i m sure',
 'i m sure',
 'i m sure',
 'i m tall',
 'i m thin',
 'i m tidy',
 'i m tidy',
 'i m ugly',
 'i m ugly',
 'i m weak',
 'i m well',
 'i m well',
 'i ve won',
 'i ve won',
 'it helps',
 'it hurts',
 'it works',
 'it works',
 'it s tom',
 'it s fun',
 'it s fun',
 'it s his',
 'it s his',
 'it s new',
 'it s new',
 'it s odd',
 'it s red',
 'it s sad',
 'keep out',
 'keep out',
 'kiss tom',
 'leave it',
 'leave it',
 'leave me',
 'leave us',
 'leave us',
 'let s go',
 'let s go',
 'look out',
 'look out',
 'marry me',
 'marry me',
 'may i go',
 'may i go',
 'may i go',
 'save tom',
 'save tom',
 'say what',
 'she came',
 'she died',
 'she runs',
 'sit down',
 'sit down',
 'sit down',
 'sit here',
 'sit here',
 'speak up',
 'speak up',
 'stand up',
 'stop tom',
 'stop tom',
 'taste it',
 'taste it',
 'taste it',
 'taste it',
 'tell tom',
 'tell tom',
 'terrific',
 'terrific',
 'terrific',
 'they won',
 'they won',
 'they won',
 'they won',
 'tom came',
 'tom died',
 'tom knew',
 'tom left',
 'tom left',
 'tom lied',
 'tom lies',
 'tom lost',
 'tom paid',
 'too late',
 'trust me',
 'trust me',
 'try hard',
 'try some',
 'try some',
 'try this',
 'try this',
 'use this',
 'use this',
 'use this',
 'use this',
 'warn tom',
 'warn tom',
 'watch me',
 'watch me',
 'watch us',
 'watch us',
 'we agree',
 'we ll go',
 'we re ok',
 'what for',
 'what for',
 'what fun',
 'what fun',
 'who came',
 'who died',
 'who fell',
 'who quit',
 'who s he',
 'write me',
 'write me',
 'you lost',
 'you lost',
 'after you',
 'aim fire',
 'am i late',
 'answer me',
 'be seated',
 'be seated',
 'birds fly',
 'bless you',
 'call home',
 'calm down',
 'calm down',
 'can we go',
 'can we go',
 'can we go',
 'catch tom',
 'catch tom',
 'catch him',
 'chill out',
 'come back',
 'come back',
 'come here',
 'come here',
 'come over',
 'come over',
 'come over',
 'come over',
 'come over',
 'come over',
 'come over',
 'come soon',
 'come soon',
 'cool down',
 'did i win',
 'did i win',
 'did i win',
 'do it now',
 'dogs bark',
 'dogs bark',
 'don t ask',
 'don t cry',
 'don t die',
 'don t die',
 'don t lie',
 'don t run',
 'don t run',
 'excuse me',
 'excuse me',
 'excuse me',
 'excuse me',
 'excuse me',
 'excuse me',
 'excuse me',
 'fantastic',
 'feel this',
 'feel this',
 'feel this',
 'feel this',
 'follow me',
 'follow us',
 'follow us',
 'forget it',
 'forget it',
 'forget it',
 'forget it',
 'forget it',
 'forget it',
 'forget it',
 'get a job',
 'get a job',
 'get a job',
 'get a job',
 'get ready',
 'get ready',
 'go get it',
 'go get it',
 'go inside',
 'go to bed',
 'go to bed',
 'good luck',
 'good luck',
 'grab that',
 'grab that',
 'grab that',
 'grab that',
 'grab this',
 'grab this',
 'hands off',
 'he is ill',
 'he is old',
 'he s a dj',
 'he s good',
 'he s lazy',
 'he s mine',
 'he s rich',
 'he s sexy',
 'here i am',
 'here s 5',
 'hold fire',
 'hold fire',
 'hold this',
 'hold this',
 'hold this',
 'hold this',
 'how awful',
 'how weird',
 'how s tom',
 'how s tom',
 'i am cold',
 'i am good',
 'i am okay',
 'i am sick',
 'i am sure',
 'i am sure',
 'i beg you',
 'i beg you',
 'i beg you',
 'i beg you',
 'i can run',
 'i can ski',
 'i cringed',
 'i cringed',
 'i cringed',
 'i exhaled',
 'i gave up',
 'i give in',
 'i give up',
 'i got hot',
 'i got hot',
 'i had fun',
 'i had fun',
 'i had fun',
 'i had fun',
 'i hate it',
 'i have it',
 'i hit tom',
 'i hope so',
 'i hurried',
 'i hurried',
 'i inhaled',
 'i knew it',
 'i like it',
 'i lost it',
 'i love it',
 'i love it',
 'i mean it',
 'i mean it',
 'i must go',
 'i must go',
 'i must go',
 'i must go',
 'i must go',
 'i must go',
 'i must go',
 'i must go',
 'i need it',
 'i need it',
 'i noticed',
 'i prepaid',
 'i promise',
 'i relaxed',
 'i relaxed',
 'i retired',
 'i said no',
 'i said so',
 'i saw him',
 'i saw him',
 'i saw him',
 'i saw one',
 'i saw one',
 'i saw you',
 'i saw you',
 'i saw you',
 'i saw you',
 'i saw you',
 'i saw you',
 'i saw you',
 'i saw you',
 'i see tom',
 'i shouted',
 'i tripped',
 'i tripped',
 'i want it',
 'i was new',
 'i was new',
 'i will go',
 'i woke up',
 'i woke up',
 'i d agree',
 'i d leave',
 'i ll call',
 'i ll cook',
 'i ll help',
 'i ll live',
 'i ll obey',
 'i ll pack',
 'i ll pack',
 'i ll pack',
 'i ll pass',
 'i ll quit',
 'i ll sing',
 'i ll stop',
 'i ll swim',
 'i ll talk',
 'i ll talk',
 'i ll wait',
 'i ll walk',
 'i ll work',
 'i ll work',
 'i m a cop',
 'i m a man',
 'i m alive',
 'i m alive',
 'i m alive',
 'i m alone',
 'i m alone',
 'i m angry',
 'i m angry',
 'i m armed',
 'i m armed',
 'i m awake',
 'i m blind',
 'i m broke',
 'i m clean',
 'i m clean',
 'i m crazy',
 'i m crazy',
 'i m cured',
 'i m cured',
 'i m dizzy',
 'i m drunk',
 'i m drunk',
 'i m drunk',
 'i m dying',
 'i m early',
 'i m first',
 'i m fussy',
 'i m fussy',
 'i m fussy',
 'i m going',
 'i m going',
 'i m going',
 'i m going',
 'i m loyal',
 'i m loyal',
 'i m lucky',
 'i m lucky',
 'i m lucky',
 'i m lucky',
 'i m lucky',
 'i m lying',
 'i m naked',
 'i m naked',
 'i m naked',
 'i m naked',
 'i m naked',
 'i m quiet',
 'i m ready',
 'i m ready',
 'i m ready',
 'i m right',
 'i m sober',
 'i m sorry',
 'i m sorry',
 'i m sorry',
 'i m sorry',
 'i m sorry',
 'i m sorry',
 'i m stuck',
 'i m timid',
 'i m tired',
 'i m tough',
 'i m tough',
 'i m tough',
 'i m tough',
 'i m yours',
 'i m yours',
 'i ve lost',
 'is tom ok',
 'is tom ok',
 'is it bad',
 'is it far',
 'is it far',
 'is it hot',
 'is it you',
 'is it you',
 'is it you',
 'it failed',
 'it snowed',
 'it stinks',
 'it stinks',
 'it was ok',
 'it was ok',
 'it was ok',
 'it worked',
 'it worked',
 'it s 3 30',
 'it s 8 30',
 'it s 8 30',
 'it s a tv',
 'it s cold',
 'it s cold',
 'it s dark',
 'it s dead',
 'it s dead',
 'it s dead',
 'it s done',
 'it s easy',
 'it s food',
 'it s free',
 'it s here',
 'it s here',
 'it s hers',
 'it s hers',
 'it s late',
 'it s lost',
 'it s mine',
 'it s mine',
 'it s mine',
 'it s mine',
 'it s open',
 'it s ours',
 'it s ours',
 'it s ours',
 'it s sand',
 'it s time',
 'it s time',
 'it s true',
 'it s work',
 'keep calm',
 'keep that',
 'keep that',
 'keep this',
 'keep this',
 'let it be',
 'let it be',
 'let me go',
 'let me go',
 'let me go',
 'let me go',
 'let me go',
 'let me go',
 'let me go',
 'let me go',
 'let me go',
 'let me go',
 'let me go',
 'let me go',
 'let me in',
 'let me in',
 'let s ask',
 'let s eat',
 'let s see',
 'lie still',
 'lie still',
 'lie still',
 'lie still',
 'lie still',
 'lie still',
 'look away',
 'look away',
 'look back',
 'look back',
 'look here',
 'look here',
 'loosen up',
 'loosen up',
 'loosen up',
 'loosen up',
 'loosen up',
 'move over',
 'move over',
 'move over',
 'nice shot',
 'of course',
 'of course',
 'of course',
 'of course',
 'of course',
 'oh please',
 'oh please',
 'pardon me',
 'pardon me',
 'pardon me',
 'read this',
 'say hello',
 'see above',
 'see below',
 'see below',
 'seize him',
 'seize him',
 'seriously',
 'seriously',
 'seriously',
 'she cried',
 'she cried',
 'she tried',
 'she walks',
 'she s hot',
 'she s hot',
 'sign here',
 'sign here',
 'sign this',
 'sign this',
 'slow down',
 'slow down',
 'stay away',
 'stay away',
 'stay back',
 'stay back',
 'stay calm',
 'stay calm',
 'stay calm',
 'stay calm',
 'stay calm',
 'stay down',
 'stay down',
 'stay down',
 'stay down',
 'stay here',
 'stay here',
 'stay here',
 'stay thin',
 'step back',
 'step back',
 'stop that',
 'stop that',
 'stop that',
 'stop that',
 'stop them',
 'take care',
 'take care',
 'take care',
 'take care',
 'take mine',
 'take mine',
 'take mine',
 'take mine',
 'take mine',
 'take mine',
 'take mine',
 'take mine',
 'take this',
 'take this',
 'thank you',
 'thank you',
 'that s ok',
 'that s ok',
 'that s ok',
 'that s ok',
 'that s it',
 'then what',
 'they fell',
 'they fell',
 'they left',
 'they left',
 'they lied',
 'they lied',
 'they lost',
 'they lost',
 'they swam',
 'they swam',
 'they swam',
 'they swam',
 'time s up',
 'tom cooks',
 'tom cried',
 'tom is ok',
 'tom knits',
 'tom knows',
 'tom rocks',
 'tom spoke',
 'tom waved',
 'tom works',
 'tom s fat',
 'tom s mad',
 'tom s mad',
 'tom s sad',
 'trust tom',
 'trust tom',
 'try again',
 'try again',
 'try again',
 'try it on',
 'turn left',
 'wait here',
 'wait here',
 'wait here',
 'wait here',
 'watch out',
 'watch out',
 'watch out',
 'we agreed',
 'we did it',
 'we did it',
 'we did it',
 'we forgot',
 'we saw it',
 'we saw it',
 'we smiled',
 'we talked',
 'we talked',
 'we talked',
 'we talked',
 'we talked',
 'we waited',
 'we waited',
 'we walked',
 'we walked',
 'we ll try',
 'we ll try',
 'we ll win',
 'we ll win',
 'we re hot',
 'we re sad',
 ...]

In [27]:
from nltk.tokenize import sent_tokenize
from gensim.utils import simple_preprocess
words=[]
for sent in corpus:
    sent_token=sent_tokenize(sent)
    for sent in sent_token:
        words.append(simple_preprocess(sent))   # Simple Preprcoess make it lowe r case
words

[['hi'],
 ['run'],
 ['run'],
 ['who'],
 ['wow'],
 ['fire'],
 ['help'],
 ['jump'],
 ['stop'],
 ['stop'],
 ['stop'],
 ['wait'],
 ['wait'],
 ['go', 'on'],
 ['go', 'on'],
 ['go', 'on'],
 ['hello'],
 ['hello'],
 ['see'],
 ['try'],
 ['won'],
 ['won'],
 ['won'],
 ['oh', 'no'],
 ['attack'],
 ['attack'],
 ['cheers'],
 ['cheers'],
 ['cheers'],
 ['cheers'],
 ['get', 'up'],
 ['go', 'now'],
 ['go', 'now'],
 ['go', 'now'],
 ['got', 'it'],
 ['got', 'it'],
 ['got', 'it'],
 ['got', 'it'],
 ['got', 'it'],
 ['hop', 'in'],
 ['hop', 'in'],
 ['hug', 'me'],
 ['hug', 'me'],
 ['fell'],
 ['fell'],
 ['know'],
 ['left'],
 ['left'],
 ['lied'],
 ['lost'],
 ['paid'],
 [],
 ['ok'],
 ['ok'],
 ['listen'],
 ['no', 'way'],
 ['no', 'way'],
 ['no', 'way'],
 ['no', 'way'],
 ['no', 'way'],
 ['no', 'way'],
 ['no', 'way'],
 ['no', 'way'],
 ['no', 'way'],
 ['really'],
 ['really'],
 ['really'],
 ['thanks'],
 ['we', 'try'],
 ['we', 'won'],
 ['we', 'won'],
 ['we', 'won'],
 ['we', 'won'],
 ['ask', 'tom'],
 ['awesome'],
 ['be', 'calm'],
 ['be', 'calm'],
 ['be', 'calm'],
 ['be', 'cool'],
 ['be', 'fair'],
 ['be', 'fair'],
 ['be', 'fair'],
 ['be', 'fair'],
 ['be', 'fair'],
 ['be', 'fair'],
 ['be', 'kind'],
 ['be', 'nice'],
 ['be', 'nice'],
 ['be', 'nice'],
 ['be', 'nice'],
 ['be', 'nice'],
 ['be', 'nice'],
 ['beat', 'it'],
 ['call', 'me'],
 ['call', 'me'],
 ['call', 'us'],
 ['call', 'us'],
 ['come', 'in'],
 ['come', 'in'],
 ['come', 'in'],
 ['come', 'in'],
 ['come', 'on'],
 ['come', 'on'],
 ['come', 'on'],
 ['come', 'on'],
 ['drop', 'it'],
 ['drop', 'it'],
 ['drop', 'it'],
 ['drop', 'it'],
 ['get', 'tom'],
 ['get', 'out'],
 ['get', 'out'],
 ['get', 'out'],
 ['get', 'out'],
 ['get', 'out'],
 ['go', 'away'],
 ['go', 'away'],
 ['go', 'away'],
 ['go', 'away'],
 ['go', 'away'],
 ['go', 'away'],
 ['go', 'away'],
 ['go', 'away'],
 ['go', 'away'],
 ['go', 'away'],
 ['go', 'home'],
 ['go', 'home'],
 ['go', 'home'],
 ['go', 'home'],
 ['go', 'slow'],
 ['go', 'slow'],
 ['goodbye'],
 ['goodbye'],
 ['hang', 'on'],
 ['hang', 'on'],
 ['hang', 'on'],
 ['hang', 'on'],
 ['he', 'quit'],
 ['he', 'quit'],
 ['he', 'runs'],
 ['help', 'me'],
 ['help', 'me'],
 ['help', 'me'],
 ['help', 'us'],
 ['help', 'us'],
 ['hold', 'it'],
 ['hold', 'on'],
 ['hug', 'tom'],
 ['agree'],
 ['cried'],
 ['dozed'],
 ['dozed'],
 ['drive'],
 ['smoke'],
 ['snore'],
 ['stink'],
 ['stood'],
 ['stood'],
 ['swore'],
 ['swore'],
 ['tried'],
 ['tried'],
 ['tried'],
 ['waved'],
 ['ll', 'go'],
 ['tom'],
 ['fat'],
 ['fat'],
 ['fit'],
 ['hit'],
 ['hit'],
 ['ill'],
 ['sad'],
 ['shy'],
 ['wet'],
 ['wet'],
 ['it', 'me'],
 ['join', 'us'],
 ['join', 'us'],
 ['keep', 'it'],
 ['keep', 'it'],
 ['kiss', 'me'],
 ['kiss', 'me'],
 ['me', 'too'],
 ['open', 'up'],
 ['open', 'up'],
 ['perfect'],
 ['see', 'you'],
 ['see', 'you'],
 ['see', 'you'],
 ['see', 'you'],
 ['show', 'me'],
 ['show', 'me'],
 ['shut', 'up'],
 ['shut', 'up'],
 ['shut', 'up'],
 ['shut', 'up'],
 ['shut', 'up'],
 ['skip', 'it'],
 ['so', 'long'],
 ['take', 'it'],
 ['take', 'it'],
 ['take', 'it'],
 ['take', 'it'],
 ['tell', 'me'],
 ['tell', 'me'],
 ['tom', 'won'],
 ['wake', 'up'],
 ['wake', 'up'],
 ['wake', 'up'],
 ['wake', 'up'],
 ['wake', 'up'],
 ['wash', 'up'],
 ['wash', 'up'],
 ['we', 'know'],
 ['we', 'lost'],
 ['we', 'lost'],
 ['we', 'lost'],
 ['we', 'lost'],
 ['we', 'lost'],
 ['we', 'lost'],
 ['we', 'lost'],
 ['we', 'lost'],
 ['we', 'lost'],
 ['we', 'lost'],
 ['welcome'],
 ['who', 'won'],
 ['who', 'won'],
 ['you', 'run'],
 ['am', 'fat'],
 ['am', 'fat'],
 ['ask', 'them'],
 ['ask', 'them'],
 ['back', 'off'],
 ['back', 'off'],
 ['back', 'off'],
 ['back', 'off'],
 ['back', 'off'],
 ['back', 'off'],
 ['be', 'man'],
 ['be', 'man'],
 ['be', 'still'],
 ['be', 'still'],
 ['be', 'still'],
 ['beats', 'me'],
 ['beats', 'me'],
 ['call', 'tom'],
 ['call', 'tom'],
 ['cheer', 'up'],
 ['cool', 'off'],
 ['cuff', 'him'],
 ['drive', 'on'],
 ['drive', 'on'],
 ['drive', 'on'],
 ['drive', 'on'],
 ['find', 'tom'],
 ['find', 'tom'],
 ['fix', 'this'],
 ['fix', 'this'],
 ['get', 'down'],
 ['get', 'down'],
 ['get', 'down'],
 ['get', 'down'],
 ['get', 'down'],
 ['get', 'lost'],
 ['get', 'lost'],
 ['get', 'lost'],
 ['get', 'real'],
 ['go', 'ahead'],
 ['go', 'ahead'],
 ['go', 'ahead'],
 ['go', 'ahead'],
 ['go', 'ahead'],
 ['go', 'ahead'],
 ['go', 'ahead'],
 ['good', 'job'],
 ['good', 'job'],
 ['good', 'job'],
 ['grab', 'him'],
 ['grab', 'him'],
 ['have', 'fun'],
 ['have', 'fun'],
 ['he', 'tries'],
 ['he', 'wet'],
 ['help', 'tom'],
 ['help', 'tom'],
 ['hi', 'guys'],
 ['how', 'cute'],
 ['how', 'deep'],
 ['how', 'nice'],
 ['how', 'nice'],
 ['how', 'nice'],
 ['how', 'nice'],
 ['hurry', 'up'],
 ['hurry', 'up'],
 ['hurry', 'up'],
 ['hurry', 'up'],
 ['did', 'ok'],
 ['did', 'ok'],
 ['did', 'it'],
 ['did', 'it'],
 ['failed'],
 ['forgot'],
 ['get', 'it'],
 ['got', 'it'],
 ['got', 'it'],
 ['helped'],
 ['jumped'],
 ['looked'],
 ['moaned'],
 ['nodded'],
 ['obeyed'],
 ['phoned'],
 ['phoned'],
 ['refuse'],
 ['refuse'],
 ['rested'],
 ['rested'],
 ['saw', 'it'],
 ['saw', 'it'],
 ['sighed'],
 ['stayed'],
 ['stayed'],
 ['talked'],
 ['use', 'it'],
 ['use', 'it'],
 ['use', 'it'],
 ['ll', 'pay'],
 ['ll', 'try'],
 ['ll', 'try'],
 ['back'],
 ['back'],
 ['bald'],
 ['busy'],
 ['busy'],
 ['calm'],
 ['cold'],
 ['cool'],
 ['cool'],
 ['deaf'],
 ['deaf'],
 ['done'],
 ['fair'],
 ['fair'],
 ['fair'],
 ['fast'],
 ['fine'],
 ['fine'],
 ['fine'],
 ['free'],
 ['free'],
 ['free'],
 ['full'],
 ['full'],
 ['game'],
 ['game'],
 ['glad'],
 ['home'],
 ['late'],
 ['lazy'],
 ['lazy'],
 ['lazy'],
 ['lazy'],
 ['okay'],
 ['okay'],
 ['rich'],
 ['safe'],
 ['sick'],
 ['sure'],
 ['sure'],
 ['sure'],
 ['sure'],
 ['tall'],
 ['thin'],
 ['tidy'],
 ['tidy'],
 ['ugly'],
 ['ugly'],
 ['weak'],
 ['well'],
 ['well'],
 ['ve', 'won'],
 ['ve', 'won'],
 ['it', 'helps'],
 ['it', 'hurts'],
 ['it', 'works'],
 ['it', 'works'],
 ['it', 'tom'],
 ['it', 'fun'],
 ['it', 'fun'],
 ['it', 'his'],
 ['it', 'his'],
 ['it', 'new'],
 ['it', 'new'],
 ['it', 'odd'],
 ['it', 'red'],
 ['it', 'sad'],
 ['keep', 'out'],
 ['keep', 'out'],
 ['kiss', 'tom'],
 ['leave', 'it'],
 ['leave', 'it'],
 ['leave', 'me'],
 ['leave', 'us'],
 ['leave', 'us'],
 ['let', 'go'],
 ['let', 'go'],
 ['look', 'out'],
 ['look', 'out'],
 ['marry', 'me'],
 ['marry', 'me'],
 ['may', 'go'],
 ['may', 'go'],
 ['may', 'go'],
 ['save', 'tom'],
 ['save', 'tom'],
 ['say', 'what'],
 ['she', 'came'],
 ['she', 'died'],
 ['she', 'runs'],
 ['sit', 'down'],
 ['sit', 'down'],
 ['sit', 'down'],
 ['sit', 'here'],
 ['sit', 'here'],
 ['speak', 'up'],
 ['speak', 'up'],
 ['stand', 'up'],
 ['stop', 'tom'],
 ['stop', 'tom'],
 ['taste', 'it'],
 ['taste', 'it'],
 ['taste', 'it'],
 ['taste', 'it'],
 ['tell', 'tom'],
 ['tell', 'tom'],
 ['terrific'],
 ['terrific'],
 ['terrific'],
 ['they', 'won'],
 ['they', 'won'],
 ['they', 'won'],
 ['they', 'won'],
 ['tom', 'came'],
 ['tom', 'died'],
 ['tom', 'knew'],
 ['tom', 'left'],
 ['tom', 'left'],
 ['tom', 'lied'],
 ['tom', 'lies'],
 ['tom', 'lost'],
 ['tom', 'paid'],
 ['too', 'late'],
 ['trust', 'me'],
 ['trust', 'me'],
 ['try', 'hard'],
 ['try', 'some'],
 ['try', 'some'],
 ['try', 'this'],
 ['try', 'this'],
 ['use', 'this'],
 ['use', 'this'],
 ['use', 'this'],
 ['use', 'this'],
 ['warn', 'tom'],
 ['warn', 'tom'],
 ['watch', 'me'],
 ['watch', 'me'],
 ['watch', 'us'],
 ['watch', 'us'],
 ['we', 'agree'],
 ['we', 'll', 'go'],
 ['we', 're', 'ok'],
 ['what', 'for'],
 ['what', 'for'],
 ['what', 'fun'],
 ['what', 'fun'],
 ['who', 'came'],
 ['who', 'died'],
 ['who', 'fell'],
 ['who', 'quit'],
 ['who', 'he'],
 ['write', 'me'],
 ['write', 'me'],
 ['you', 'lost'],
 ['you', 'lost'],
 ['after', 'you'],
 ['aim', 'fire'],
 ['am', 'late'],
 ['answer', 'me'],
 ['be', 'seated'],
 ['be', 'seated'],
 ['birds', 'fly'],
 ['bless', 'you'],
 ['call', 'home'],
 ['calm', 'down'],
 ['calm', 'down'],
 ['can', 'we', 'go'],
 ['can', 'we', 'go'],
 ['can', 'we', 'go'],
 ['catch', 'tom'],
 ['catch', 'tom'],
 ['catch', 'him'],
 ['chill', 'out'],
 ['come', 'back'],
 ['come', 'back'],
 ['come', 'here'],
 ['come', 'here'],
 ['come', 'over'],
 ['come', 'over'],
 ['come', 'over'],
 ['come', 'over'],
 ['come', 'over'],
 ['come', 'over'],
 ['come', 'over'],
 ['come', 'soon'],
 ['come', 'soon'],
 ['cool', 'down'],
 ['did', 'win'],
 ['did', 'win'],
 ['did', 'win'],
 ['do', 'it', 'now'],
 ['dogs', 'bark'],
 ['dogs', 'bark'],
 ['don', 'ask'],
 ['don', 'cry'],
 ['don', 'die'],
 ['don', 'die'],
 ['don', 'lie'],
 ['don', 'run'],
 ['don', 'run'],
 ['excuse', 'me'],
 ['excuse', 'me'],
 ['excuse', 'me'],
 ['excuse', 'me'],
 ['excuse', 'me'],
 ['excuse', 'me'],
 ['excuse', 'me'],
 ['fantastic'],
 ['feel', 'this'],
 ['feel', 'this'],
 ['feel', 'this'],
 ['feel', 'this'],
 ['follow', 'me'],
 ['follow', 'us'],
 ['follow', 'us'],
 ['forget', 'it'],
 ['forget', 'it'],
 ['forget', 'it'],
 ['forget', 'it'],
 ['forget', 'it'],
 ['forget', 'it'],
 ['forget', 'it'],
 ['get', 'job'],
 ['get', 'job'],
 ['get', 'job'],
 ['get', 'job'],
 ['get', 'ready'],
 ['get', 'ready'],
 ['go', 'get', 'it'],
 ['go', 'get', 'it'],
 ['go', 'inside'],
 ['go', 'to', 'bed'],
 ['go', 'to', 'bed'],
 ['good', 'luck'],
 ['good', 'luck'],
 ['grab', 'that'],
 ['grab', 'that'],
 ['grab', 'that'],
 ['grab', 'that'],
 ['grab', 'this'],
 ['grab', 'this'],
 ['hands', 'off'],
 ['he', 'is', 'ill'],
 ['he', 'is', 'old'],
 ['he', 'dj'],
 ['he', 'good'],
 ['he', 'lazy'],
 ['he', 'mine'],
 ['he', 'rich'],
 ['he', 'sexy'],
 ['here', 'am'],
 ['here'],
 ['hold', 'fire'],
 ['hold', 'fire'],
 ['hold', 'this'],
 ['hold', 'this'],
 ['hold', 'this'],
 ['hold', 'this'],
 ['how', 'awful'],
 ['how', 'weird'],
 ['how', 'tom'],
 ['how', 'tom'],
 ['am', 'cold'],
 ['am', 'good'],
 ['am', 'okay'],
 ['am', 'sick'],
 ['am', 'sure'],
 ['am', 'sure'],
 ['beg', 'you'],
 ['beg', 'you'],
 ['beg', 'you'],
 ['beg', 'you'],
 ['can', 'run'],
 ['can', 'ski'],
 ['cringed'],
 ['cringed'],
 ['cringed'],
 ['exhaled'],
 ['gave', 'up'],
 ['give', 'in'],
 ['give', 'up'],
 ['got', 'hot'],
 ['got', 'hot'],
 ['had', 'fun'],
 ['had', 'fun'],
 ['had', 'fun'],
 ['had', 'fun'],
 ['hate', 'it'],
 ['have', 'it'],
 ['hit', 'tom'],
 ['hope', 'so'],
 ['hurried'],
 ['hurried'],
 ['inhaled'],
 ['knew', 'it'],
 ['like', 'it'],
 ['lost', 'it'],
 ['love', 'it'],
 ['love', 'it'],
 ['mean', 'it'],
 ['mean', 'it'],
 ['must', 'go'],
 ['must', 'go'],
 ['must', 'go'],
 ['must', 'go'],
 ['must', 'go'],
 ['must', 'go'],
 ['must', 'go'],
 ['must', 'go'],
 ['need', 'it'],
 ['need', 'it'],
 ['noticed'],
 ['prepaid'],
 ['promise'],
 ['relaxed'],
 ['relaxed'],
 ['retired'],
 ['said', 'no'],
 ['said', 'so'],
 ['saw', 'him'],
 ['saw', 'him'],
 ['saw', 'him'],
 ['saw', 'one'],
 ['saw', 'one'],
 ['saw', 'you'],
 ['saw', 'you'],
 ['saw', 'you'],
 ['saw', 'you'],
 ['saw', 'you'],
 ['saw', 'you'],
 ['saw', 'you'],
 ['saw', 'you'],
 ['see', 'tom'],
 ['shouted'],
 ['tripped'],
 ['tripped'],
 ['want', 'it'],
 ['was', 'new'],
 ['was', 'new'],
 ['will', 'go'],
 ['woke', 'up'],
 ['woke', 'up'],
 ['agree'],
 ['leave'],
 ['ll', 'call'],
 ['ll', 'cook'],
 ['ll', 'help'],
 ['ll', 'live'],
 ['ll', 'obey'],
 ['ll', 'pack'],
 ['ll', 'pack'],
 ['ll', 'pack'],
 ['ll', 'pass'],
 ['ll', 'quit'],
 ['ll', 'sing'],
 ['ll', 'stop'],
 ['ll', 'swim'],
 ['ll', 'talk'],
 ['ll', 'talk'],
 ['ll', 'wait'],
 ['ll', 'walk'],
 ['ll', 'work'],
 ['ll', 'work'],
 ['cop'],
 ['man'],
 ['alive'],
 ['alive'],
 ['alive'],
 ['alone'],
 ['alone'],
 ['angry'],
 ['angry'],
 ['armed'],
 ['armed'],
 ['awake'],
 ['blind'],
 ['broke'],
 ['clean'],
 ['clean'],
 ['crazy'],
 ['crazy'],
 ['cured'],
 ['cured'],
 ['dizzy'],
 ['drunk'],
 ['drunk'],
 ['drunk'],
 ['dying'],
 ['early'],
 ['first'],
 ['fussy'],
 ['fussy'],
 ['fussy'],
 ['going'],
 ['going'],
 ['going'],
 ['going'],
 ['loyal'],
 ['loyal'],
 ['lucky'],
 ['lucky'],
 ['lucky'],
 ['lucky'],
 ['lucky'],
 ['lying'],
 ['naked'],
 ['naked'],
 ['naked'],
 ['naked'],
 ['naked'],
 ['quiet'],
 ['ready'],
 ['ready'],
 ['ready'],
 ['right'],
 ['sober'],
 ['sorry'],
 ['sorry'],
 ['sorry'],
 ['sorry'],
 ['sorry'],
 ['sorry'],
 ['stuck'],
 ['timid'],
 ['tired'],
 ['tough'],
 ['tough'],
 ['tough'],
 ['tough'],
 ['yours'],
 ['yours'],
 ['ve', 'lost'],
 ['is', 'tom', 'ok'],
 ['is', 'tom', 'ok'],
 ['is', 'it', 'bad'],
 ['is', 'it', 'far'],
 ['is', 'it', 'far'],
 ['is', 'it', 'hot'],
 ['is', 'it', 'you'],
 ['is', 'it', 'you'],
 ['is', 'it', 'you'],
 ['it', 'failed'],
 ['it', 'snowed'],
 ['it', 'stinks'],
 ['it', 'stinks'],
 ['it', 'was', 'ok'],
 ['it', 'was', 'ok'],
 ['it', 'was', 'ok'],
 ['it', 'worked'],
 ['it', 'worked'],
 ['it'],
 ['it'],
 ['it'],
 ['it', 'tv'],
 ['it', 'cold'],
 ['it', 'cold'],
 ['it', 'dark'],
 ['it', 'dead'],
 ['it', 'dead'],
 ['it', 'dead'],
 ['it', 'done'],
 ['it', 'easy'],
 ['it', 'food'],
 ['it', 'free'],
 ['it', 'here'],
 ['it', 'here'],
 ['it', 'hers'],
 ['it', 'hers'],
 ['it', 'late'],
 ['it', 'lost'],
 ['it', 'mine'],
 ['it', 'mine'],
 ['it', 'mine'],
 ['it', 'mine'],
 ['it', 'open'],
 ['it', 'ours'],
 ['it', 'ours'],
 ['it', 'ours'],
 ['it', 'sand'],
 ['it', 'time'],
 ['it', 'time'],
 ['it', 'true'],
 ['it', 'work'],
 ['keep', 'calm'],
 ['keep', 'that'],
 ['keep', 'that'],
 ['keep', 'this'],
 ['keep', 'this'],
 ['let', 'it', 'be'],
 ['let', 'it', 'be'],
 ['let', 'me', 'go'],
 ['let', 'me', 'go'],
 ['let', 'me', 'go'],
 ['let', 'me', 'go'],
 ['let', 'me', 'go'],
 ['let', 'me', 'go'],
 ['let', 'me', 'go'],
 ['let', 'me', 'go'],
 ['let', 'me', 'go'],
 ['let', 'me', 'go'],
 ['let', 'me', 'go'],
 ['let', 'me', 'go'],
 ['let', 'me', 'in'],
 ['let', 'me', 'in'],
 ['let', 'ask'],
 ['let', 'eat'],
 ['let', 'see'],
 ['lie', 'still'],
 ['lie', 'still'],
 ['lie', 'still'],
 ['lie', 'still'],
 ['lie', 'still'],
 ['lie', 'still'],
 ['look', 'away'],
 ['look', 'away'],
 ['look', 'back'],
 ['look', 'back'],
 ['look', 'here'],
 ['look', 'here'],
 ['loosen', 'up'],
 ['loosen', 'up'],
 ['loosen', 'up'],
 ['loosen', 'up'],
 ['loosen', 'up'],
 ['move', 'over'],
 ['move', 'over'],
 ['move', 'over'],
 ['nice', 'shot'],
 ['of', 'course'],
 ['of', 'course'],
 ['of', 'course'],
 ['of', 'course'],
 ['of', 'course'],
 ['oh', 'please'],
 ['oh', 'please'],
 ['pardon', 'me'],
 ['pardon', 'me'],
 ['pardon', 'me'],
 ['read', 'this'],
 ['say', 'hello'],
 ['see', 'above'],
 ['see', 'below'],
 ['see', 'below'],
 ['seize', 'him'],
 ['seize', 'him'],
 ['seriously'],
 ['seriously'],
 ['seriously'],
 ['she', 'cried'],
 ['she', 'cried'],
 ['she', 'tried'],
 ['she', 'walks'],
 ['she', 'hot'],
 ['she', 'hot'],
 ['sign', 'here'],
 ['sign', 'here'],
 ['sign', 'this'],
 ['sign', 'this'],
 ['slow', 'down'],
 ['slow', 'down'],
 ['stay', 'away'],
 ['stay', 'away'],
 ['stay', 'back'],
 ['stay', 'back'],
 ['stay', 'calm'],
 ['stay', 'calm'],
 ['stay', 'calm'],
 ['stay', 'calm'],
 ['stay', 'calm'],
 ['stay', 'down'],
 ['stay', 'down'],
 ['stay', 'down'],
 ['stay', 'down'],
 ['stay', 'here'],
 ['stay', 'here'],
 ['stay', 'here'],
 ['stay', 'thin'],
 ['step', 'back'],
 ['step', 'back'],
 ['stop', 'that'],
 ['stop', 'that'],
 ['stop', 'that'],
 ['stop', 'that'],
 ['stop', 'them'],
 ['take', 'care'],
 ['take', 'care'],
 ['take', 'care'],
 ['take', 'care'],
 ['take', 'mine'],
 ['take', 'mine'],
 ['take', 'mine'],
 ['take', 'mine'],
 ['take', 'mine'],
 ['take', 'mine'],
 ['take', 'mine'],
 ['take', 'mine'],
 ['take', 'this'],
 ['take', 'this'],
 ['thank', 'you'],
 ['thank', 'you'],
 ['that', 'ok'],
 ['that', 'ok'],
 ['that', 'ok'],
 ['that', 'ok'],
 ['that', 'it'],
 ['then', 'what'],
 ['they', 'fell'],
 ['they', 'fell'],
 ['they', 'left'],
 ['they', 'left'],
 ['they', 'lied'],
 ['they', 'lied'],
 ['they', 'lost'],
 ['they', 'lost'],
 ['they', 'swam'],
 ['they', 'swam'],
 ['they', 'swam'],
 ['they', 'swam'],
 ['time', 'up'],
 ['tom', 'cooks'],
 ['tom', 'cried'],
 ['tom', 'is', 'ok'],
 ['tom', 'knits'],
 ['tom', 'knows'],
 ['tom', 'rocks'],
 ['tom', 'spoke'],
 ['tom', 'waved'],
 ['tom', 'works'],
 ['tom', 'fat'],
 ['tom', 'mad'],
 ['tom', 'mad'],
 ['tom', 'sad'],
 ['trust', 'tom'],
 ['trust', 'tom'],
 ['try', 'again'],
 ['try', 'again'],
 ['try', 'again'],
 ['try', 'it', 'on'],
 ['turn', 'left'],
 ['wait', 'here'],
 ['wait', 'here'],
 ['wait', 'here'],
 ['wait', 'here'],
 ['watch', 'out'],
 ['watch', 'out'],
 ['watch', 'out'],
 ['we', 'agreed'],
 ['we', 'did', 'it'],
 ['we', 'did', 'it'],
 ['we', 'did', 'it'],
 ['we', 'forgot'],
 ['we', 'saw', 'it'],
 ['we', 'saw', 'it'],
 ['we', 'smiled'],
 ['we', 'talked'],
 ['we', 'talked'],
 ['we', 'talked'],
 ['we', 'talked'],
 ['we', 'talked'],
 ['we', 'waited'],
 ['we', 'waited'],
 ['we', 'walked'],
 ['we', 'walked'],
 ['we', 'll', 'try'],
 ['we', 'll', 'try'],
 ['we', 'll', 'win'],
 ['we', 'll', 'win'],
 ['we', 're', 'hot'],
 ['we', 're', 'sad'],
 ...]

In [52]:
all_words = [word for sentence in words for word in sentence]

# Get unique words
unique_words_input = set(all_words)

# Count them
print("Number of unique words:", len(unique_words_input))
print("Unique words:", unique_words)

Number of unique words: 13871

In [53]:
max_len_input = max(len(sentence) for sentence in words)
longest_sentence = max(words, key=len)

print("Max number of words:", max_len_input)
print("Sentence with max words:", longest_sentence)

Max number of words: 41
Sentence with max words: ['since', 'there', 'are', 'usually', 'multiple', 'websites', 'on', 'any', 'given', 'topic', 'usually', 'just', 'click', 'the', 'back', 'button', 'when', 'arrive', 'on', 'any', 'webpage', 'that', 'has', 'pop', 'up', 'advertising', 'just', 'go', 'to', 'the', 'next', 'page', 'found', 'by', 'google', 'and', 'hope', 'for', 'something', 'less', 'irritating']

## Input Encoding:

In [54]:
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [58]:
one_hot_input=[one_hot(word, len(unique_words_input)) for word in corpus]
one_hot_input

[[2406],
 [5178],
 [5178],
 [5950],
 [12784],
 [1780],
 [10358],
 [13012],
 [9065],
 [9065],
 [9065],
 [8343],
 [8343],
 [11009, 11437],
 [11009, 11437],
 [11009, 11437],
 [6253],
 [6253],
 [11755, 11413],
 [11755, 744],
 [11755, 7396],
 [11755, 7396],
 [11755, 7396],
 [9892, 12823],
 [4024],
 [4024],
 [4112],
 [4112],
 [4112],
 [4112],
 [12606, 2993],
 [11009, 8961],
 [11009, 8961],
 [11009, 8961],
 [5115, 4573],
 [5115, 4573],
 [5115, 4573],
 [5115, 4573],
 [5115, 4573],
 [6784, 5651],
 [6784, 5651],
 [13233, 2483],
 [13233, 2483],
 [11755, 11821],
 [11755, 11821],
 [11755, 507],
 [11755, 7810],
 [11755, 7810],
 [11755, 75],
 [11755, 3700],
 [11755, 8080],
 [11755, 2164, 8771],
 [11755, 2164, 4207],
 [11755, 2164, 4207],
 [12311],
 [12823, 1661],
 [12823, 1661],
 [12823, 1661],
 [12823, 1661],
 [12823, 1661],
 [12823, 1661],
 [12823, 1661],
 [12823, 1661],
 [12823, 1661],
 [793],
 [793],
 [793],
 [10210],
 [10240, 744],
 [10240, 7396],
 [10240, 7396],
 [10240, 7396],
 [10240, 7396],
 [13397, 2898],
 [11765],
 [9683, 9705],
 [9683, 9705],
 [9683, 9705],
 [9683, 1870],
 [9683, 11798],
 [9683, 11798],
 [9683, 11798],
 [9683, 11798],
 [9683, 11798],
 [9683, 11798],
 [9683, 4716],
 [9683, 9411],
 [9683, 9411],
 [9683, 9411],
 [9683, 9411],
 [9683, 9411],
 [9683, 9411],
 [3201, 4573],
 [8306, 2483],
 [8306, 2483],
 [8306, 13666],
 [8306, 13666],
 [3191, 5651],
 [3191, 5651],
 [3191, 5651],
 [3191, 5651],
 [3191, 11437],
 [3191, 11437],
 [3191, 11437],
 [3191, 11437],
 [12900, 4573],
 [12900, 4573],
 [12900, 4573],
 [12900, 4573],
 [12606, 2898],
 [12606, 7667],
 [12606, 7667],
 [12606, 7667],
 [12606, 7667],
 [12606, 7667],
 [11009, 4172],
 [11009, 4172],
 [11009, 4172],
 [11009, 4172],
 [11009, 4172],
 [11009, 4172],
 [11009, 4172],
 [11009, 4172],
 [11009, 4172],
 [11009, 4172],
 [11009, 8669],
 [11009, 8669],
 [11009, 8669],
 [11009, 8669],
 [11009, 3650],
 [11009, 3650],
 [5185],
 [5185],
 [8330, 11437],
 [8330, 11437],
 [8330, 11437],
 [8330, 11437],
 [10777, 4543],
 [10777, 4543],
 [10777, 9117],
 [10358, 2483],
 [10358, 2483],
 [10358, 2483],
 [10358, 13666],
 [10358, 13666],
 [3620, 4573],
 [3620, 11437],
 [13233, 2898],
 [11755, 3111],
 [11755, 5411],
 [11755, 6589],
 [11755, 6589],
 [11755, 9536],
 [11755, 8004],
 [11755, 12675],
 [11755, 8849],
 [11755, 3897],
 [11755, 3897],
 [11755, 6356],
 [11755, 6356],
 [11755, 5068],
 [11755, 5068],
 [11755, 5068],
 [11755, 3989],
 [11755, 1367, 11009],
 [11755, 2164, 2898],
 [11755, 2164, 8001],
 [11755, 2164, 8001],
 [11755, 2164, 5736],
 [11755, 2164, 3387],
 [11755, 2164, 3387],
 [11755, 2164, 759],
 [11755, 2164, 8724],
 [11755, 2164, 7833],
 [11755, 2164, 8399],
 [11755, 2164, 8399],
 [4573, 10776, 2483],
 [7287, 13666],
 [7287, 13666],
 [11010, 4573],
 [11010, 4573],
 [6993, 2483],
 [6993, 2483],
 [2483, 2356],
 [1615, 2993],
 [1615, 2993],
 [11166],
 [11413, 1816],
 [11413, 1816],
 [11413, 1816],
 [11413, 1816],
 [13277, 2483],
 [13277, 2483],
 [1670, 2993],
 [1670, 2993],
 [1670, 2993],
 [1670, 2993],
 [1670, 2993],
 [12641, 4573],
 [3485, 10499],
 [5706, 4573],
 [5706, 4573],
 [5706, 4573],
 [5706, 4573],
 [6670, 2483],
 [6670, 2483],
 [2898, 7396],
 [9359, 2993],
 [9359, 2993],
 [9359, 2993],
 [9359, 2993],
 [9359, 2993],
 [7329, 2993],
 [7329, 2993],
 [10240, 507],
 [10240, 3700],
 [10240, 3700],
 [10240, 3700],
 [10240, 3700],
 [10240, 3700],
 [10240, 3700],
 [10240, 3700],
 [10240, 3700],
 [10240, 3700],
 [10240, 3700],
 [8672],
 [5950, 7396],
 [5950, 7396],
 [1816, 5178],
 [9, 11755, 8001],
 [9, 11755, 8001],
 [13397, 1775],
 [13397, 1775],
 [12939, 10257],
 [12939, 10257],
 [12939, 10257],
 [12939, 10257],
 [12939, 10257],
 [12939, 10257],
 [9683, 11085, 5639],
 [9683, 11085, 5639],
 [9683, 11070],
 [9683, 11070],
 [9683, 11070],
 [3372, 2483],
 [3372, 2483],
 [8306, 2898],
 [8306, 2898],
 [3150, 2993],
 [1870, 10257],
 [12483, 11145],
 [9536, 11437],
 [9536, 11437],
 [9536, 11437],
 [9536, 11437],
 [9026, 2898],
 [9026, 2898],
 [7191, 3874],
 [7191, 3874],
 [12606, 4323],
 [12606, 4323],
 [12606, 4323],
 [12606, 4323],
 [12606, 4323],
 [12606, 3700],
 [12606, 3700],
 [12606, 3700],
 [12606, 3895],
 [11009, 12579],
 [11009, 12579],
 [11009, 12579],
 [11009, 12579],
 [11009, 12579],
 [11009, 12579],
 [11009, 12579],
 [6355, 11927],
 [6355, 11927],
 [6355, 11927],
 [9257, 11145],
 [9257, 11145],
 [8228, 2297],
 [8228, 2297],
 [10777, 8201],
 [10777, 10776, 8399],
 [10358, 2898],
 [10358, 2898],
 [2406, 4277],
 [12706, 12636],
 [12706, 2489],
 [12706, 9411],
 [12706, 9411],
 [12706, 9411],
 [12706, 9411],
 [4996, 2993],
 [4996, 2993],
 [4996, 2993],
 [4996, 2993],
 [11755, 10988, 4207],
 [11755, 10988, 4207],
 [11755, 10988, 4573],
 [11755, 10988, 4573],
 [11755, 11842],
 [11755, 13086],
 [11755, 12606, 4573],
 [11755, 5115, 4573],
 [11755, 5115, 4573],
 [11755, 10845],
 [11755, 671],
 [11755, 7931],
 [11755, 13773],
 [11755, 11624],
 [11755, 10444],
 [11755, 7778],
 [11755, 7778],
 [11755, 11778],
 [11755, 11778],
 [11755, 3623],
 [11755, 3623],
 [11755, 10164, 4573],
 [11755, 10164, 4573],
 [11755, 2040],
 [11755, 8180],
 [11755, 8180],
 [11755, 270],
 [11755, 12947, 4573],
 [11755, 12947, 4573],
 [11755, 12947, 4573],
 [11755, 1367, 8263],
 [11755, 1367, 744],
 [11755, 1367, 744],
 [11755, 2164, 12939],
 [11755, 2164, 12939],
 [11755, 2164, 2554],
 [11755, 2164, 12807],
 [11755, 2164, 12807],
 [11755, 2164, 9705],
 [11755, 2164, 5362],
 [11755, 2164, 1870],
 [11755, 2164, 1870],
 [11755, 2164, 12560],
 [11755, 2164, 12560],
 [11755, 2164, 9072],
 [11755, 2164, 11798],
 [11755, 2164, 11798],
 [11755, 2164, 11798],
 [11755, 2164, 11189],
 [11755, 2164, 1633],
 [11755, 2164, 1633],
 [11755, 2164, 1633],
 [11755, 2164, 1594],
 [11755, 2164, 1594],
 [11755, 2164, 1594],
 [11755, 2164, 9034],
 [11755, 2164, 9034],
 [11755, 2164, 5780],
 [11755, 2164, 5780],
 [11755, 2164, 9019],
 [11755, 2164, 8669],
 [11755, 2164, 8568],
 [11755, 2164, 8883],
 [11755, 2164, 8883],
 [11755, 2164, 8883],
 [11755, 2164, 8883],
 [11755, 2164, 10675],
 [11755, 2164, 10675],
 [11755, 2164, 2019],
 [11755, 2164, 1752],
 [11755, 2164, 8814],
 [11755, 2164, 3664],
 [11755, 2164, 3664],
 [11755, 2164, 3664],
 [11755, 2164, 3664],
 [11755, 2164, 835],
 [11755, 2164, 1416],
 [11755, 2164, 12648],
 [11755, 2164, 12648],
 [11755, 2164, 2868],
 [11755, 2164, 2868],
 [11755, 2164, 5414],
 [11755, 2164, 5691],
 [11755, 2164, 5691],
 [11755, 3724, 7396],
 [11755, 3724, 7396],
 [4573, 12605],
 [4573, 4944],
 [4573, 11446],
 [4573, 11446],
 [4573, 10776, 2898],
 [4573, 10776, 2297],
 [4573, 10776, 2297],
 [4573, 10776, 10047],
 [4573, 10776, 10047],
 [4573, 10776, 9337],
 [4573, 10776, 9337],
 [4573, 10776, 8712],
 [4573, 10776, 6209],
 [4573, 10776, 8724],
 [11010, 7667],
 [11010, 7667],
 [6993, 2898],
 [8396, 4573],
 [8396, 4573],
 [8396, 2483],
 [8396, 13666],
 [8396, 13666],
 [11800, 10776, 11009],
 [11800, 10776, 11009],
 [8024, 7667],
 [8024, 7667],
 [7534, 2483],
 [7534, 2483],
 [5681, 11755, 11009],
 [5681, 11755, 11009],
 [5681, 11755, 11009],
 [12154, 2898],
 [12154, 2898],
 [279, 3571],
 [7899, 11289],
 [7899, 4220],
 [7899, 9117],
 [10623, 4323],
 [10623, 4323],
 [10623, 4323],
 [10623, 8702],
 [10623, 8702],
 [5063, 2993],
 [5063, 2993],
 [5237, 2993],
 [9065, 2898],
 [9065, 2898],
 [13814, 4573],
 [13814, 4573],
 [13814, 4573],
 [13814, 4573],
 [6670, 2898],
 [6670, 2898],
 [8200],
 [8200],
 [8200],
 [9389, 7396],
 [9389, 7396],
 [9389, 7396],
 [9389, 7396],
 [2898, 11289],
 [2898, 4220],
 [2898, 9659],
 [2898, 7810],
 [2898, 7810],
 [2898, 75],
 [2898, 8009],
 [2898, 3700],
 [2898, 8080],
 [2356, 8568],
 [5453, 2483],
 [5453, 2483],
 [744, 492],
 [744, 11814],
 [744, 11814],
 [744, 3874],
 [744, 3874],
 [12947, 3874],
 [12947, 3874],
 [12947, 3874],
 [12947, 3874],
 [1420, 2898],
 [1420, 2898],
 [2414, 2483],
 [2414, 2483],
 [2414, 13666],
 [2414, 13666],
 [10240, 3111],
 [10240, 1367, 11009],
 [10240, 7707, 4207],
 [3571, 12694],
 [3571, 12694],
 [3571, 2297],
 [3571, 2297],
 [5950, 11289],
 [5950, 4220],
 [5950, 11821],
 [5950, 4543],
 [5950, 10776, 10777],
 [9527, 2483],
 [9527, 2483],
 [1816, 3700],
 [1816, 3700],
 [7205, 1816],
 [2909, 1780],
 [9, 11755, 8568],
 [12549, 2483],
 [9683, 7179],
 [9683, 7179],
 [11014, 4451],
 [1031, 1816],
 [8306, 8669],
 [9705, 4323],
 [9705, 4323],
 [6050, 10240, 11009],
 [6050, 10240, 11009],
 [6050, 10240, 11009],
 [10730, 2898],
 [10730, 2898],
 [10730, 11145],
 [3790, 7667],
 [3191, 12939],
 [3191, 12939],
 [3191, 8702],
 [3191, 8702],
 [3191, 9734],
 [3191, 9734],
 [3191, 9734],
 [3191, 9734],
 [3191, 9734],
 [3191, 9734],
 [3191, 9734],
 [3191, 4819],
 [3191, 4819],
 [1870, 4323],
 [10988, 11755, 10069],
 [10988, 11755, 10069],
 [10988, 11755, 10069],
 [10249, 4573, 8961],
 [9556, 10868],
 [9556, 10868],
 [5716, 12406, 13397],
 [5716, 12406, 7432],
 [5716, 12406, 1181],
 [5716, 12406, 1181],
 [5716, 12406, 2572],
 [5716, 12406, 5178],
 [5716, 12406, 5178],
 [4067, 2483],
 [4067, 2483],
 [4067, 2483],
 [4067, 2483],
 [4067, 2483],
 [4067, 2483],
 [4067, 2483],
 [3497],
 [4208, 3874],
 [4208, 3874],
 [4208, 3874],
 [4208, 3874],
 [2077, 2483],
 [2077, 13666],
 [2077, 13666],
 [1836, 4573],
 [1836, 4573],
 [1836, 4573],
 [1836, 4573],
 [1836, 4573],
 [1836, 4573],
 [1836, 4573],
 [12606, 11085, 11927],
 [12606, 11085, 11927],
 [12606, 11085, 11927],
 [12606, 11085, 11927],
 [12606, 10776],
 [12606, 10776],
 [11009, 12606, 4573],
 [11009, 12606, 4573],
 [11009, 12285],
 [11009, 12628, 5261],
 [11009, 12628, 5261],
 [6355, 12325],
 [6355, 12325],
 [9257, 4191],
 [9257, 4191],
 [9257, 4191],
 [9257, 4191],
 [9257, 3874],
 [9257, 3874],
 [583, 10257],
 [10777, 4270, 759],
 [10777, 4270, 653],
 [10777, 10776, 11085, 3809],
 [10777, 10776, 6355],
 [10777, 10776, 8883],
 [10777, 10776, 13147],
 [10777, 10776, 2019],
 [10777, 10776, 8409],
 [8702, 11755, 9],
 [8702, 10776, 5620],
 [3620, 1780],
 [3620, 1780],
 [3620, 3874],
 [3620, 3874],
 [3620, 3874],
 [3620, 3874],
 [12706, 3783],
 [12706, 12209],
 [12706, 10776, 2898],
 [12706, 10776, 2898],
 [11755, 9, 5362],
 [11755, 9, 6355],
 [11755, 9, 10675],
 [11755, 9, 8814],
 [11755, 9, 3664],
 [11755, 9, 3664],
 [11755, 3541, 1816],
 [11755, 3541, 1816],
 [11755, 3541, 1816],
 [11755, 3541, 1816],
 [11755, 6050, 5178],
 [11755, 6050, 13044],
 [11755, 5790],
 [11755, 5790],
 [11755, 5790],
 [11755, 8290],
 [11755, 4895, 2993],
 [11755, 11153, 5651],
 [11755, 11153, 2993],
 [11755, 5115, 8500],
 [11755, 5115, 8500],
 [11755, 9131, 2297],
 [11755, 9131, 2297],
 [11755, 9131, 2297],
 [11755, 9131, 2297],
 [11755, 5243, 4573],
 [11755, 8228, 4573],
 [11755, 3387, 2898],
 [11755, 5406, 3485],
 [11755, 11789],
 [11755, 11789],
 [11755, 9619],
 [11755, 9659, 4573],
 [11755, 3338, 4573],
 [11755, 3700, 4573],
 [11755, 3147, 4573],
 [11755, 3147, 4573],
 [11755, 12102, 4573],
 [11755, 12102, 4573],
 [11755, 8153, 11009],
 [11755, 8153, 11009],
 [11755, 8153, 11009],
 [11755, 8153, 11009],
 [11755, 8153, 11009],
 [11755, 8153, 11009],
 [11755, 8153, 11009],
 [11755, 8153, 11009],
 [11755, 1113, 4573],
 [11755, 1113, 4573],
 [11755, 5693],
 [11755, 4570],
 [11755, 12299],
 [11755, 3989],
 [11755, 3989],
 [11755, 2503],
 [11755, 3030, 12823],
 [11755, 3030, 3485],
 [11755, 10164, 11145],
 [11755, 10164, 11145],
 [11755, 10164, 11145],
 [11755, 10164, 1505],
 [11755, 10164, 1505],
 [11755, 10164, 1816],
 [11755, 10164, 1816],
 [11755, 10164, 1816],
 [11755, 10164, 1816],
 [11755, 10164, 1816],
 [11755, 10164, 1816],
 [11755, 10164, 1816],
 [11755, 10164, 1816],
 [11755, 11413, 2898],
 [11755, 957],
 [11755, 8158],
 [11755, 8158],
 [11755, 673, 4573],
 [11755, 1709, 9337],
 [11755, 1709, 9337],
 [11755, 2229, 11009],
 [11755, 12350, 2993],
 [11755, 12350, 2993],
 [11755, 878, 3111],
 [11755, 878, 8396],
 [11755, 1367, 8306],
 [11755, 1367, 11793],
 [11755, 1367, 10358],
 [11755, 1367, 8441],
 [11755, 1367, 12254],
 [11755, 1367, 9228],
 [11755, 1367, 9228],
 [11755, 1367, 9228],
 [11755, 1367, 21],
 [11755, 1367, 4543],
 [11755, 1367, 3294],
 [11755, 1367, 9065],
 [11755, 1367, 9158],
 [11755, 1367, 11178],
 [11755, 1367, 11178],
 [11755, 1367, 8343],
 [11755, 1367, 1279],
 [11755, 1367, 455],
 [11755, 1367, 455],
 [11755, 2164, 11085, 9427],
 [11755, 2164, 11085, 5639],
 [11755, 2164, 8928],
 [11755, 2164, 8928],
 [11755, 2164, 8928],
 [11755, 2164, 1326],
 [11755, 2164, 1326],
 [11755, 2164, 10069],
 [11755, 2164, 10069],
 [11755, 2164, 6122],
 [11755, 2164, 6122],
 [11755, 2164, 9669],
 [11755, 2164, 6155],
 [11755, 2164, 8296],
 [11755, 2164, 2366],
 [11755, 2164, 2366],
 [11755, 2164, 10988],
 [11755, 2164, 10988],
 [11755, 2164, 3988],
 [11755, 2164, 3988],
 [11755, 2164, 8288],
 [11755, 2164, 11694],
 [11755, 2164, 11694],
 [11755, 2164, 11694],
 [11755, 2164, 2925],
 [11755, 2164, 1713],
 [11755, 2164, 5224],
 [11755, 2164, 3434],
 [11755, 2164, 3434],
 [11755, 2164, 3434],
 [11755, 2164, 12005],
 [11755, 2164, 12005],
 [11755, 2164, 12005],
 [11755, 2164, 12005],
 [11755, 2164, 1512],
 [11755, 2164, 1512],
 [11755, 2164, 1963],
 [11755, 2164, 1963],
 [11755, 2164, 1963],
 [11755, 2164, 1963],
 [11755, 2164, 1963],
 [11755, 2164, 5909],
 [11755, 2164, 6260],
 [11755, 2164, 6260],
 [11755, 2164, 6260],
 [11755, 2164, 6260],
 [11755, 2164, 6260],
 [11755, 2164, 1060],
 [11755, 2164, 10776],
 [11755, 2164, 10776],
 [11755, 2164, 10776],
 [11755, 2164, 13298],
 [11755, 2164, 1812],
 [11755, 2164, 8852],
 [11755, 2164, 8852],
 [11755, 2164, 8852],
 [11755, 2164, 8852],
 [11755, 2164, 8852],
 [11755, 2164, 8852],
 [11755, 2164, 10461],
 [11755, 2164, 98],
 [11755, 2164, 12349],
 [11755, 2164, 330],
 [11755, 2164, 330],
 [11755, 2164, 330],
 [11755, 2164, 330],
 [11755, 2164, 13170],
 [11755, 2164, 13170],
 [11755, 3724, 3700],
 [4270, 2898, 4207],
 [4270, 2898, 4207],
 [4270, 4573, 9453],
 [4270, 4573, 7654],
 [4270, 4573, 7654],
 [4270, 4573, 8500],
 [4270, 4573, 1816],
 [4270, 4573, 1816],
 [4270, 4573, 1816],
 [4573, 11842],
 [4573, 11598],
 [4573, 11663],
 [4573, 11663],
 [4573, 1709, 4207],
 [4573, 1709, 4207],
 [4573, 1709, 4207],
 [4573, 6509],
 [4573, 6509],
 [4573, 10776, 2766, 11892],
 [4573, 10776, 351, 11892],
 [4573, 10776, 351, 11892],
 [4573, 10776, 11085, 10824],
 [4573, 10776, 5362],
 [4573, 10776, 5362],
 [4573, 10776, 7664],
 [4573, 10776, 299],
 [4573, 10776, 299],
 [4573, 10776, 299],
 [4573, 10776, 9072],
 [4573, 10776, 949],
 [4573, 10776, 1773],
 [4573, 10776, 1594],
 [4573, 10776, 8702],
 [4573, 10776, 8702],
 [4573, 10776, 13516],
 [4573, 10776, 13516],
 [4573, 10776, 8568],
 [4573, 10776, 3700],
 [4573, 10776, 13147],
 [4573, 10776, 13147],
 [4573, 10776, 13147],
 [4573, 10776, 13147],
 [4573, 10776, 1615],
 [4573, 10776, 13054],
 [4573, 10776, 13054],
 [4573, 10776, 13054],
 [4573, 10776, 5472],
 [4573, 10776, 8500],
 [4573, 10776, 8500],
 [4573, 10776, 13020],
 [4573, 10776, 455],
 [11010, 9705],
 [11010, 4191],
 [11010, 4191],
 [11010, 3874],
 [11010, 3874],
 [11800, 4573, 9683],
 [11800, 4573, 9683],
 [11800, 2483, 11009],
 [11800, 2483, 11009],
 [11800, 2483, 11009],
 [11800, 2483, 11009],
 [11800, 2483, 11009],
 [11800, 2483, 11009],
 [11800, 2483, 11009],
 [11800, 2483, 11009],
 [11800, 2483, 11009],
 [11800, 2483, 11009],
 [11800, 2483, 11009],
 [11800, 2483, 11009],
 [11800, 2483, 5651],
 [11800, 2483, 5651],
 [11800, 10776, 13397],
 [11800, 10776, 11039],
 [11800, 10776, 11413],
 [2572, 11070],
 [2572, 11070],
 [2572, 11070],
 [2572, 11070],
 [2572, 11070],
 [2572, 11070],
 [8024, 4172],
 [8024, 4172],
 [8024, 12939],
 [8024, 12939],
 [8024, 8702],
 [8024, 8702],
 [2790, 2993],
 [2790, 2993],
 [2790, 2993],
 [2790, 2993],
 [2790, 2993],
 [10860, 9734],
 [10860, 9734],
 [10860, 9734],
 [9411, 12185],
 [6430, 5514],
 [6430, 5514],
 [6430, 5514],
 [6430, 5514],
 [6430, 5514],
 [9892, 6834],
 [9892, 6834],
 [12317, 2483],
 [12317, 2483],
 [12317, 2483],
 [8873, 3874],
 [279, 6253],
 [11413, 2263],
 [11413, 4677],
 [11413, 4677],
 [12318, 11145],
 [12318, 11145],
 [1345],
 [1345],
 [1345],
 [7899, 5411],
 [7899, 5411],
 [7899, 5068],
 [7899, 2663],
 [7899, 10776, 8500],
 [7899, 10776, 8500],
 [10236, 8702],
 [10236, 8702],
 [10236, 3874],
 [10236, 3874],
 [3650, 4323],
 [3650, 4323],
 [10294, 4172],
 [10294, 4172],
 [10294, 12939],
 [10294, 12939],
 [10294, 9705],
 [10294, 9705],
 [10294, 9705],
 [10294, 9705],
 [10294, 9705],
 [10294, 4323],
 [10294, 4323],
 [10294, 4323],
 [10294, 4323],
 [10294, 8702],
 [10294, 8702],
 [10294, 8702],
 [10294, 1416],
 [2980, 12939],
 [2980, 12939],
 [9065, 4191],
 [9065, 4191],
 [9065, 4191],
 [9065, 4191],
 [9065, 1775],
 [5706, 3933],
 [5706, 3933],
 [5706, 3933],
 [5706, 3933],
 [5706, 13147],
 [5706, 13147],
 [5706, 13147],
 [5706, 13147],
 [5706, 13147],
 [5706, 13147],
 [5706, 13147],
 [5706, 13147],
 [5706, 3874],
 [5706, 3874],
 [1396, 1816],
 [1396, 1816],
 [4191, 10776, 4207],
 [4191, 10776, 4207],
 [4191, 10776, 4207],
 [4191, 10776, 4207],
 [4191, 10776, 4573],
 [4070, 3571],
 [9389, 11821],
 [9389, 11821],
 [9389, 7810],
 [9389, 7810],
 [9389, 75],
 [9389, 75],
 [9389, 3700],
 [9389, 3700],
 [9389, 986],
 [9389, 986],
 [9389, 986],
 [9389, 986],
 [8500, 10776, 2993],
 [2898, 9940],
 [2898, 5411],
 [2898, 4270, 4207],
 [2898, 12094],
 [2898, 2099],
 [2898, 12954],
 [2898, 13259],
 [2898, 3989],
 [2898, 11446],
 [2898, 10776, 8001],
 [2898, 10776, 9547],
 [2898, 10776, 9547],
 [2898, 10776, 8724],
 [5453, 2898],
 [5453, 2898],
 [744, 10924],
 [744, 10924],
 [744, 10924],
 [744, 4573, 11437],
 [13548, 7810],
 [8343, 8702],
 [8343, 8702],
 [8343, 8702],
 [8343, 8702],
 [2414, 7667],
 [2414, 7667],
 [2414, 7667],
 [10240, 5648],
 [10240, 10988, 4573],
 [10240, 10988, 4573],
 [10240, 10988, 4573],
 [10240, 13086],
 [10240, 10164, 4573],
 [10240, 10164, 4573],
 [10240, 3586],
 [10240, 270],
 [10240, 270],
 [10240, 270],
 [10240, 270],
 [10240, 270],
 [10240, 12914],
 [10240, 12914],
 [10240, 12550],
 [10240, 12550],
 [10240, 1367, 744],
 [10240, 1367, 744],
 [10240, 1367, 10069],
 [10240, 1367, 10069],
 [10240, 7707, 8500],
 [10240, 7707, 8724],
 ...]

In [56]:
input_padding=pad_sequences(one_hot_input, maxlen=max_len_input, padding='post')
input_padding

array([[ 2406,     0,     0, ...,     0,     0,     0],
       [ 5178,     0,     0, ...,     0,     0,     0],
       [ 5178,     0,     0, ...,     0,     0,     0],
       ...,
       [12747,  4270,  7497, ..., 11253,     0,     0],
       [ 2374,  1995,  7940, ...,  7497,  9106,   375],
       [ 7174,  1167,  7493, ..., 11085, 13159,  7775]], dtype=int32)

In [72]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, Dense, Dropout

vocab_size = len(unique_words_input) + 1  # total words in vocab
embedding_dim = 64

model = Sequential()
model.add(Embedding(input_dim=vocab_size, output_dim=embedding_dim, input_length=max_len))
model.add(Dropout(0.2))
model.add(LSTM(128, return_sequences=False))
model.add(Dense(1, activation='sigmoid'))

model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
model.summary()

/home/hammadali08/.local/lib/python3.12/site-packages/keras/src/layers/core/embedding.py:97: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_1 (Embedding)         │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_1 (Dropout)             │ ?                      │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_1 (LSTM)                   │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

# Output Preprocessing

In [32]:
corpus1 = []
for i in range(0, len(dataset)):
    review = re.sub('[^a-zA-Z0-9]', ' ', dataset['French'][i])
    review = review.lower()
    review = review.split()

    review = ' '.join(review)
    corpus1.append(review)

In [33]:
corpus1

['salut',
 'cours',
 'courez',
 'qui',
 'a alors',
 'au feu',
 'l aide',
 'saute',
 'a suffit',
 'stop',
 'arr te toi',
 'attends',
 'attendez',
 'poursuis',
 'continuez',
 'poursuivez',
 'bonjour',
 'salut',
 'je comprends',
 'j essaye',
 'j ai gagn',
 'je l ai emport',
 'j ai gagn',
 'oh non',
 'attaque',
 'attaquez',
 'sant',
 'votre sant',
 'merci',
 'tchin tchin',
 'l ve toi',
 'va maintenant',
 'allez y maintenant',
 'vas y maintenant',
 'j ai pig',
 'compris',
 'pig',
 'compris',
 't as capt',
 'monte',
 'montez',
 'serre moi dans tes bras',
 'serrez moi dans vos bras',
 'je suis tomb e',
 'je suis tomb',
 'je sais',
 'je suis parti',
 'je suis partie',
 'j ai menti',
 'j ai perdu',
 'j ai pay',
 'j ai 19 ans',
 'je vais bien',
 'a va',
 'coutez',
 'c est pas possible',
 'impossible',
 'en aucun cas',
 'sans fa ons',
 'c est hors de question',
 'il n en est pas question',
 'c est exclu',
 'en aucune mani re',
 'hors de question',
 'vraiment',
 'vrai',
 'ah bon',
 'merci',
 'on essaye',
 'nous avons gagn',
 'nous gagn mes',
 'nous l avons emport',
 'nous l emport mes',
 'demande tom',
 'fantastique',
 'sois calme',
 'soyez calme',
 'soyez calmes',
 'sois d tendu',
 'sois juste',
 'soyez juste',
 'soyez justes',
 'sois quitable',
 'soyez quitable',
 'soyez quitables',
 'sois gentil',
 'sois gentil',
 'sois gentille',
 'soyez gentil',
 'soyez gentille',
 'soyez gentils',
 'soyez gentilles',
 'd gage',
 'appelle moi',
 'appellez moi',
 'appelle nous',
 'appelez nous',
 'entrez',
 'entre',
 'entre',
 'entrez',
 'allez',
 'allez',
 'viens',
 'venez',
 'laisse tomber',
 'laissez tomber',
 'laisse le tomber',
 'laissez le tomber',
 'va chercher tom',
 'sortez',
 'sors',
 'sortez',
 'sors',
 'casse toi',
 'd gage',
 'pars',
 'va te faire foutre',
 'pars',
 'd gage',
 'fous le camp',
 'pars d ici',
 'va t en',
 'disparais',
 'allez vous en',
 'rentrez la maison',
 'rentre la maison',
 'rentre chez toi',
 'rentrez chez vous',
 'va doucement',
 'allez doucement',
 'adieu',
 'la revoyure',
 'attends un peu',
 'attendez un peu',
 'tiens bon',
 'tenez bon',
 'il laissa tomber',
 'il a laiss tomber',
 'il court',
 'aide moi',
 'aide moi',
 'aidez moi',
 'aidez nous',
 'aide nous',
 'ne bouge plus',
 'ne quittez pas',
 'fais un c lin tom',
 'je suis du m me avis',
 'j ai pleur',
 'je me suis assoupi',
 'je me suis assoupie',
 'je conduis',
 'je fume',
 'je ronfle',
 'je pue',
 'je me suis tenu debout',
 'je me suis tenue debout',
 'j ai promis',
 'j ai jur',
 'j essayai',
 'j ai essay',
 'j ai tent',
 'j ai fait signe',
 'j irai',
 'je suis tom',
 'je suis gras',
 'je suis gros',
 'je suis en forme',
 'je suis touch',
 'je suis touch e',
 'je suis malade',
 'je suis triste',
 'je suis timide',
 'je suis mouill',
 'je suis mouill e',
 'c est bibi',
 'joignez vous',
 'joignez vous nous',
 'garde le',
 'gardez le',
 'embrasse moi',
 'embrassez moi',
 'moi aussi',
 'ouvre moi',
 'ouvre',
 'parfait',
 'plus tard',
 'bient t',
 'la prochaine',
 'plus',
 'montre moi',
 'montrez moi',
 'taisez vous',
 'ferme la',
 'tais toi',
 'ferme la',
 'la ferme',
 'pas grave',
 'plus tard',
 'prends le',
 'prenez le',
 'prends le',
 'prenez le',
 'dis moi',
 'dites moi',
 'tom a gagn',
 'r veille toi',
 'r veille toi',
 'r veillez vous',
 'r veille toi',
 'r veillez vous',
 'lave toi',
 'lavez vous',
 'nous savons',
 'nous perd mes',
 'nous avons perdu',
 'nous f mes battus',
 'nous f mes battues',
 'nous f mes d faits',
 'nous f mes d faites',
 'nous avons t d faits',
 'nous avons t d faites',
 'nous avons t battus',
 'nous avons t battues',
 'bienvenue',
 'qui a gagn',
 'qui l a emport',
 'tu cours',
 'suis je gros',
 'suis je grosse',
 'demande leur',
 'demandez leur',
 'recule',
 'reculez',
 'recule',
 'reculez',
 'retire toi',
 'retirez vous',
 'sois un homme',
 'soyez un homme',
 'sois calme',
 'soyez calme',
 'soyez calmes',
 'aucune id e',
 'j en sais foutre rien',
 'appelle tom',
 'appelez tom',
 'courage',
 'd tends toi',
 'menottez le',
 'avance',
 'avancez',
 'continue rouler',
 'continuez rouler',
 'trouve tom',
 'trouvez tom',
 'r parez ceci',
 'r pare a',
 'l che toi',
 'descends',
 'descendez',
 'l che toi',
 'l chez vous',
 'va voir ailleurs si j y suis',
 'd gage',
 'va au diable',
 'sois r aliste',
 'passe devant',
 'vas y',
 'avance',
 'vas y',
 'poursuis',
 'passe devant',
 'vas y',
 'bien jou',
 'bon boulot',
 'beau travail',
 'attrape le',
 'attrapez le',
 'amuse toi bien',
 'amusez vous bien',
 'il essaye',
 'il est mouill',
 'aide tom',
 'aidez tom',
 'salut les mecs',
 'comme c est mignon',
 'quelle profondeur',
 'comme c est chouette',
 'comme c est gentil',
 'c est du joli',
 'comme c est agr able',
 'd p che toi',
 'grouille',
 'pressez vous',
 'fi a',
 'je m en suis bien sorti',
 'je m en suis bien sortie',
 'je l ai fait',
 'c est moi qui l ai fait',
 'j ai chou',
 'j ai oubli',
 'j ai compris',
 'j ai compris',
 'j ai capt',
 'j ai aid',
 'j ai saut',
 'j ai regard',
 'j ai r l',
 'j ai fait signe de la t te',
 'j ai ob i',
 'je t l phonai',
 'j ai t l phon',
 'je refuse',
 'je le refuse',
 'je me suis repos',
 'je me suis repos e',
 'je l ai vu',
 'je l ai vu',
 'j ai soupir',
 'je suis rest',
 'je suis rest e',
 'j ai parl',
 'je l utilise',
 'j en fais usage',
 'je m en sers',
 'je paierai',
 'je vais essayer',
 'j essaierai',
 'je suis revenu',
 'me revoil',
 'je suis chauve',
 'je suis occup',
 'je suis occup e',
 'je suis calme',
 'j ai froid',
 'je suis d tendu',
 'je suis d tendue',
 'je suis sourd',
 'je suis sourde',
 'j en ai fini',
 'je suis juste',
 'j ai la peau claire',
 'j ai le teint clair',
 'je suis rapide',
 'tout va bien',
 'je vais bien',
 'a va',
 'je suis libre',
 'je suis libre',
 'je suis disponible',
 'je suis repu',
 'je suis rassasi',
 'j en suis',
 'je suis de la partie',
 'je suis content',
 'je suis chez moi',
 'je suis en retard',
 'je suis paresseux',
 'je suis fain ant',
 'je suis paresseuse',
 'je suis fain ante',
 'je vais bien',
 'je me porte bien',
 'je suis riche',
 'je suis en s curit',
 'je suis malade',
 'j en suis certain',
 'je suis certain',
 'j en suis s r',
 'j en suis s re',
 'je suis grande',
 'je suis mince',
 'je suis ordonn',
 'je suis ordonn e',
 'je suis laid',
 'je suis laide',
 'je suis faible',
 'je vais bien',
 'je me porte bien',
 'j ai gagn',
 'je l ai emport',
 'a aide',
 'a fait mal',
 'elle marche',
 'a fonctionne',
 'c est tom',
 'c est marrant',
 'c est rigolo',
 'c est le sien',
 'c est la sienne',
 'c est nouveau',
 'c est neuf',
 'c est bizarre',
 'il est rouge',
 'c est triste',
 'd fense d entrer',
 'n entrez pas',
 'embrasse tom',
 'laisse tomber',
 'laissez tomber',
 'laissez moi',
 'laisse nous',
 'laissez nous',
 'allons y',
 'allons y',
 'attention',
 'regarde donc',
 'pouse moi',
 'pousez moi',
 'puis je partir',
 'puis je y aller',
 'puis je m y rendre',
 'sauve tom',
 'sauvez tom',
 'de quoi',
 'elle est venue',
 'elle est morte',
 'elle court',
 'assieds toi',
 'asseyez vous',
 'assieds toi',
 'assieds toi ici',
 'asseyez vous ici',
 'parle plus fort',
 'parlez plus fort',
 'l ve toi',
 'arr te tom',
 'stoppez tom',
 'go te le',
 'go te la',
 'go tez le',
 'go tez la',
 'dis le tom',
 'informez en tom',
 'g nial',
 'excellent',
 'formidable',
 'ils gagn rent',
 'elles gagn rent',
 'ils ont gagn',
 'elles ont gagn',
 'tom est venu',
 'tom est mort',
 'tom savait',
 'tom est parti',
 'tom partit',
 'tom a menti',
 'tom ment',
 'tom a perdu',
 'tom a pay',
 'trop tard',
 'faites moi confiance',
 'fais moi confiance',
 'fais un effort',
 'essaies en',
 'essayez en',
 'essaie ceci',
 'essayez ceci',
 'utilise ceci',
 'utilisez ceci',
 'emploie ceci',
 'employez ceci',
 'avertis tom',
 'pr viens tom',
 'regarde moi',
 'regardez moi',
 'regardez nous',
 'regarde nous',
 'nous sommes d accord',
 'nous irons',
 'nous allons bien',
 'pour quoi faire',
 'quoi bon',
 'qu est ce qu on s est marr s',
 'qu est ce qu on s est marr es',
 'qui est venu',
 'qui est mort',
 'qui est tomb',
 'qui d missionne',
 'qui est il',
 'cris moi',
 'crivez moi',
 'tu as perdu',
 'vous avez perdu',
 'apr s vous',
 'en joue feu',
 'suis je en retard',
 'r pondez moi',
 'assieds toi',
 'asseyez vous',
 'les oiseaux volent',
 'tes souhaits',
 'appelle la maison',
 'calmez vous',
 'calme toi',
 'pouvons nous partir',
 'pouvons nous nous en aller',
 'pouvons nous y aller',
 'attrape tom',
 'attrapez tom',
 'rattrape le',
 'calme toi',
 'reviens',
 'revenez',
 'viens ici',
 'venez l',
 'viens',
 'venez',
 'venez ici',
 'viens chez nous',
 'venez chez nous',
 'viens chez moi',
 'venez chez moi',
 'viens bient t',
 'venez bient t',
 'calmez vous',
 'ai je gagn',
 'l ai je emport',
 'est ce moi qui ai gagn',
 'faites le maintenant',
 'des chiens aboient',
 'les chiens aboient',
 'ne demande pas',
 'ne pleure pas',
 'ne meurs pas',
 'ne mourez pas',
 'ne mens pas',
 'ne courez pas',
 'ne cours pas',
 'excuse moi',
 'excusez moi',
 'pardon',
 'je vous demande pardon',
 'pla t il',
 'plait il',
 'pardon',
 'fantastique',
 'sens a',
 'sentez a',
 'touche a',
 'touchez a',
 'suis moi',
 'suis nous',
 'suivez nous',
 'oublie',
 'oublie le',
 'oubliez',
 'oubliez le',
 'laisse tomber',
 'oublie',
 'oublie le',
 'trouve un emploi',
 'trouve un boulot',
 'trouvez un emploi',
 'trouvez un boulot',
 'pr pare toi',
 'pr parez vous',
 'va le chercher',
 'allez le chercher',
 'entrez',
 'va au lit',
 'allez au lit',
 'bonne chance',
 'bonne chance',
 'attrape a',
 'attrapez a',
 'saisis toi de a',
 'saisissez vous de a',
 'attrape a',
 'attrapez a',
 'pas touche',
 'il est malade',
 'il est vieux',
 'il est dj',
 'il est bon',
 'il est paresseux',
 'il est moi',
 'il est riche',
 'il est sexy',
 'me voici',
 'voil cinq dollars',
 'halte au feu',
 'cessez le feu',
 'tiens a',
 'tenez a',
 'tenez ceci',
 'tiens ceci',
 'c est affreux',
 'comme c est bizarre',
 'comment tom va t il',
 'comment va tom',
 'j ai froid',
 'je suis bon',
 'je vais bien',
 'je suis malade',
 'je suis s r',
 'je suis certain',
 'je vous en prie',
 'je vous en conjure',
 'je vous en supplie',
 'je te prie',
 'je sais courir',
 'je sais skier',
 'j eus un mouvement de recul',
 'j ai eu un mouvement de recul',
 'je suis rentr en moi m me',
 'j ai expir',
 'j ai abandonn',
 'je donne ma langue au chat',
 'j abandonne',
 'je me suis mis avoir chaud',
 'je me suis mise avoir chaud',
 'je me suis amus',
 'je me suis amus e',
 'je me suis marr',
 'je me suis marr e',
 'je d teste a',
 'je l ai',
 'j ai frapp tom',
 'j esp re bien',
 'je me suis d p ch',
 'je me suis d p ch e',
 'j ai inspir',
 'je le savais',
 'j aime a',
 'je l ai perdu',
 'j adore a',
 'j adore a',
 'je suis s rieux',
 'je suis s rieux',
 'je dois y aller',
 'il faut que j y aille',
 'il me faut y aller',
 'il me faut partir',
 'il me faut m en aller',
 'je dois partir',
 'je dois m en aller',
 'il faut que je m en aille',
 'j en ai besoin',
 'il me le faut',
 'j ai remarqu',
 'j ai pay d avance',
 'je le promets',
 'je me suis d tendu',
 'je me suis d tendue',
 'j ai pris ma retraite',
 'j ai dit non',
 'je l ai dit',
 'je l ai vu',
 'je l ai vu',
 'je le vis',
 'j en ai vu une',
 'j en ai vu un',
 'je vous vis',
 'je te vis',
 'je t ai vue',
 'je t ai vu',
 'je vous ai vues',
 'je vous ai vus',
 'je vous ai vue',
 'je vous ai vu',
 'je vois tom',
 'j ai cri',
 'j ai tr buch',
 'j ai plan',
 'je le veux',
 'j tais nouveau',
 'j tais nouvelle',
 'j irai',
 'je me suis r veill',
 'je me suis veill',
 'je serais d accord',
 'je partirais',
 'j appellerai',
 'je cuisinerai',
 'j aiderai',
 'je vivrai',
 'j ob irai',
 'je ferai mon sac',
 'je ferai ma valise',
 'je plierai mes gaules',
 'je passerai',
 'j abandonnerai',
 'je chanterai',
 'j arr terai',
 'je nagerai',
 'je parlerai',
 'je vais parler',
 'j attendrai',
 'je marcherai',
 'je vais travailler',
 'je travaillerai',
 'je suis flic',
 'je suis un homme',
 'je suis en vie',
 'je suis vivant',
 'je suis vivante',
 'je suis seule',
 'je suis seul',
 'je suis nerv',
 'je suis en col re',
 'je suis arm',
 'je suis arm e',
 'je suis r veill',
 'je suis aveugle',
 'je suis fauch',
 'j ai d croch',
 'je suis propre',
 'je suis fou',
 'je suis folle',
 'je suis gu ri',
 'je suis gu rie',
 'j ai la t te qui tourne',
 'je suis saoul',
 'je suis so l',
 'je suis ivre',
 'je me meurs',
 'je suis en avance',
 'je suis en premier',
 'je suis difficile',
 'je suis tatillon',
 'je suis tatillonne',
 'je pars maintenant',
 'je me tire',
 'j y vais',
 'je pars',
 'je suis loyal',
 'je suis loyale',
 'je suis veinard',
 'je suis veinarde',
 'j ai du pot',
 'je suis chanceux',
 'je suis chanceuse',
 'je suis en train de mentir',
 'je suis nu',
 'je suis nue',
 'je me trouve nu',
 'je me trouve nue',
 'je suis poil',
 'je suis tranquille',
 'je suis pr te',
 'je suis pr t',
 'je suis pr t',
 'j ai raison',
 'je suis sobre',
 'excuse moi',
 'd sol',
 'excusez moi',
 'd sol',
 'je suis d sol',
 'je suis d sol e',
 'je suis coinc e',
 'je suis timide',
 'je suis fatigu',
 'je suis dur',
 'je suis dure',
 'je suis dur cuire',
 'je suis dure cuire',
 'je suis toi',
 'je suis vous',
 'j ai perdu',
 'est ce que tom va bien',
 'tom va t il bien',
 'c est grave',
 'est ce loign',
 'est ce loin',
 'est ce chaud',
 'est ce toi',
 'est ce vous',
 'est ce que c est vous',
 'a a chou',
 'il a neig',
 'a sent mauvais',
 'a pue',
 'c tait bon',
 'c tait correct',
 'c tait ok',
 'a a fonctionn',
 'a a march',
 'il est trois heures et demie',
 'il est huit heures trente',
 'il est 8 h 30',
 'c est une t l',
 'il fait froid',
 'c est froid',
 'c est sombre',
 'elle est morte',
 'c est mort',
 'il est mort',
 'c est fait',
 'c est simple',
 'c est de la nourriture',
 'c est gratuit',
 'elle est ici',
 'c est ici',
 'c est le sien',
 'c est la sienne',
 'il est tard',
 'c est perdu',
 'c est le mien',
 'c est la mienne',
 'c est moi',
 'il s agit du mien',
 'c est ouvert',
 'c est le n tre',
 'c est la n tre',
 'c est nous',
 'c est du sable',
 'il est temps',
 'c est l heure',
 'c est vrai',
 'c est du boulot',
 'restez calme',
 'garde a',
 'gardez cela',
 'garde a',
 'gardez ceci',
 'ainsi soit il',
 'laisse faire',
 'laisse moi partir',
 'laissez moi partir',
 'l che moi',
 'l chez moi',
 'laisse moi m en aller',
 'laissez moi m en aller',
 'laissez moi y aller',
 'laisse moi y aller',
 'laisse moi partir',
 'laissez moi partir',
 'laisse moi m en aller',
 'laissez moi m en aller',
 'laissez moi rentrer',
 'laissez moi entrer',
 'demandons',
 'mangeons',
 'voyons voir',
 'reste allong immobile',
 'reste allong e immobile',
 'restez allong immobile',
 'restez allong e immobile',
 'restez allong s immobiles',
 'restez allong es immobiles',
 'd tourne le regard',
 'regardez ailleurs',
 'regarde derri re toi',
 'regarde derri re',
 'regarde ici',
 'regardez ici',
 'chauffe toi',
 'chauffez vous',
 'd tends toi',
 'laisse toi aller',
 'laissez vous aller',
 'bouge de l',
 'poussez vous',
 'pousse toi',
 'joli coup',
 'pour s r',
 'mais ouais',
 'pardi',
 'bien s r',
 'pour s r',
 'je vous en prie',
 'je t en prie',
 'pardon',
 'je vous demande pardon',
 'pla t il',
 'lis ceci',
 'dis bonjour',
 'voyez ci dessus',
 'voyez ci dessous',
 'voir ci dessous',
 'capturez le',
 'attrapez le',
 'vraiment',
 'est ce s rieux',
 's rieusement',
 'elle pleurait',
 'elle pleura',
 'elle a essay',
 'elle marche',
 'elle est chaude',
 'elle est tr s attirante',
 'signe ici',
 'signez ici',
 'signe a',
 'signez ceci',
 'ralentis',
 'ralentissez',
 'reste l cart',
 'restez l cart',
 'reste en arri re',
 'restez en arri re',
 'restez calme',
 'reste calme',
 'garde ton calme',
 'garde ton sang froid',
 'reste tranquille',
 'reste baiss',
 'restez baiss',
 'reste baiss',
 'restez baiss',
 'restez l',
 'reste ici',
 'restez ici',
 'reste mince',
 'recule',
 'reculez',
 'arr tez',
 'arr te a',
 'arr tez a',
 'arr te a',
 'arr tez les',
 'prends soin de toi',
 'soyez prudente',
 'prends soin de toi',
 'prenez soin de vous',
 'prends le mien',
 'prends la mienne',
 'prenez le mien',
 'prenez la mienne',
 'prends les miens',
 'prends les miennes',
 'prenez les miens',
 'prenez les miennes',
 'prends a',
 'prenez a',
 'merci',
 'merci',
 'il n y a pas de probl me',
 'pas de probl me',
 'ce n est pas grave',
 'a va',
 'c est a',
 'et alors',
 'ils sont tomb s',
 'elles sont tomb es',
 'ils sont partis',
 'elles sont parties',
 'ils ont menti',
 'elles ont menti',
 'ils ont perdu',
 'elles ont perdu',
 'ils nageaient',
 'elles nageaient',
 'ils nag rent',
 'elles nag rent',
 'le temps est coul',
 'tom cuisine',
 'tom pleura',
 'tom va bien',
 'tom tricote',
 'tom sait',
 'tom assure',
 'tom a parl',
 'tom a fait signe de la main',
 'tom est en train de travailler',
 'tom est gros',
 'tom est en col re',
 'tom est fou',
 'tom est triste',
 'fais confiance tom',
 'faites confiance tom',
 'essaie encore',
 'essayez de nouveau',
 'essaie de nouveau',
 'essaie le',
 'tourne gauche',
 'attends ici',
 'attends l',
 'attendez ici',
 'attendez l',
 'attention',
 'faites attention',
 'fais attention',
 'nous sommes tomb s d accord',
 'nous avons r ussi',
 'nous avons r ussi',
 'nous l avons fait',
 'nous avons oubli',
 'nous l avons vu',
 'nous l avons vue',
 'nous avons souri',
 'nous discut mes',
 'nous avons discut',
 'nous nous sommes entretenus',
 'nous nous sommes entretenues',
 'nous nous entret nmes',
 'nous attend mes',
 'nous avons attendu',
 'nous sommes all s pied',
 'nous sommes all es pied',
 'nous essayerons',
 'nous tenterons',
 'nous l emporterons',
 'nous gagnerons',
 'nous avons chaud',
 'nous sommes tristes',
 ...]

In [36]:
words1=[]
for sent in corpus1:
    sent_token=sent_tokenize(sent)
    for sent in sent_token:
        words1.append(simple_preprocess(sent))
words1

[['salut'],
 ['cours'],
 ['courez'],
 ['qui'],
 ['alors'],
 ['au', 'feu'],
 ['aide'],
 ['saute'],
 ['suffit'],
 ['stop'],
 ['arr', 'te', 'toi'],
 ['attends'],
 ['attendez'],
 ['poursuis'],
 ['continuez'],
 ['poursuivez'],
 ['bonjour'],
 ['salut'],
 ['je', 'comprends'],
 ['essaye'],
 ['ai', 'gagn'],
 ['je', 'ai', 'emport'],
 ['ai', 'gagn'],
 ['oh', 'non'],
 ['attaque'],
 ['attaquez'],
 ['sant'],
 ['votre', 'sant'],
 ['merci'],
 ['tchin', 'tchin'],
 ['ve', 'toi'],
 ['va', 'maintenant'],
 ['allez', 'maintenant'],
 ['vas', 'maintenant'],
 ['ai', 'pig'],
 ['compris'],
 ['pig'],
 ['compris'],
 ['as', 'capt'],
 ['monte'],
 ['montez'],
 ['serre', 'moi', 'dans', 'tes', 'bras'],
 ['serrez', 'moi', 'dans', 'vos', 'bras'],
 ['je', 'suis', 'tomb'],
 ['je', 'suis', 'tomb'],
 ['je', 'sais'],
 ['je', 'suis', 'parti'],
 ['je', 'suis', 'partie'],
 ['ai', 'menti'],
 ['ai', 'perdu'],
 ['ai', 'pay'],
 ['ai', 'ans'],
 ['je', 'vais', 'bien'],
 ['va'],
 ['coutez'],
 ['est', 'pas', 'possible'],
 ['impossible'],
 ['en', 'aucun', 'cas'],
 ['sans', 'fa', 'ons'],
 ['est', 'hors', 'de', 'question'],
 ['il', 'en', 'est', 'pas', 'question'],
 ['est', 'exclu'],
 ['en', 'aucune', 'mani', 're'],
 ['hors', 'de', 'question'],
 ['vraiment'],
 ['vrai'],
 ['ah', 'bon'],
 ['merci'],
 ['on', 'essaye'],
 ['nous', 'avons', 'gagn'],
 ['nous', 'gagn', 'mes'],
 ['nous', 'avons', 'emport'],
 ['nous', 'emport', 'mes'],
 ['demande', 'tom'],
 ['fantastique'],
 ['sois', 'calme'],
 ['soyez', 'calme'],
 ['soyez', 'calmes'],
 ['sois', 'tendu'],
 ['sois', 'juste'],
 ['soyez', 'juste'],
 ['soyez', 'justes'],
 ['sois', 'quitable'],
 ['soyez', 'quitable'],
 ['soyez', 'quitables'],
 ['sois', 'gentil'],
 ['sois', 'gentil'],
 ['sois', 'gentille'],
 ['soyez', 'gentil'],
 ['soyez', 'gentille'],
 ['soyez', 'gentils'],
 ['soyez', 'gentilles'],
 ['gage'],
 ['appelle', 'moi'],
 ['appellez', 'moi'],
 ['appelle', 'nous'],
 ['appelez', 'nous'],
 ['entrez'],
 ['entre'],
 ['entre'],
 ['entrez'],
 ['allez'],
 ['allez'],
 ['viens'],
 ['venez'],
 ['laisse', 'tomber'],
 ['laissez', 'tomber'],
 ['laisse', 'le', 'tomber'],
 ['laissez', 'le', 'tomber'],
 ['va', 'chercher', 'tom'],
 ['sortez'],
 ['sors'],
 ['sortez'],
 ['sors'],
 ['casse', 'toi'],
 ['gage'],
 ['pars'],
 ['va', 'te', 'faire', 'foutre'],
 ['pars'],
 ['gage'],
 ['fous', 'le', 'camp'],
 ['pars', 'ici'],
 ['va', 'en'],
 ['disparais'],
 ['allez', 'vous', 'en'],
 ['rentrez', 'la', 'maison'],
 ['rentre', 'la', 'maison'],
 ['rentre', 'chez', 'toi'],
 ['rentrez', 'chez', 'vous'],
 ['va', 'doucement'],
 ['allez', 'doucement'],
 ['adieu'],
 ['la', 'revoyure'],
 ['attends', 'un', 'peu'],
 ['attendez', 'un', 'peu'],
 ['tiens', 'bon'],
 ['tenez', 'bon'],
 ['il', 'laissa', 'tomber'],
 ['il', 'laiss', 'tomber'],
 ['il', 'court'],
 ['aide', 'moi'],
 ['aide', 'moi'],
 ['aidez', 'moi'],
 ['aidez', 'nous'],
 ['aide', 'nous'],
 ['ne', 'bouge', 'plus'],
 ['ne', 'quittez', 'pas'],
 ['fais', 'un', 'lin', 'tom'],
 ['je', 'suis', 'du', 'me', 'avis'],
 ['ai', 'pleur'],
 ['je', 'me', 'suis', 'assoupi'],
 ['je', 'me', 'suis', 'assoupie'],
 ['je', 'conduis'],
 ['je', 'fume'],
 ['je', 'ronfle'],
 ['je', 'pue'],
 ['je', 'me', 'suis', 'tenu', 'debout'],
 ['je', 'me', 'suis', 'tenue', 'debout'],
 ['ai', 'promis'],
 ['ai', 'jur'],
 ['essayai'],
 ['ai', 'essay'],
 ['ai', 'tent'],
 ['ai', 'fait', 'signe'],
 ['irai'],
 ['je', 'suis', 'tom'],
 ['je', 'suis', 'gras'],
 ['je', 'suis', 'gros'],
 ['je', 'suis', 'en', 'forme'],
 ['je', 'suis', 'touch'],
 ['je', 'suis', 'touch'],
 ['je', 'suis', 'malade'],
 ['je', 'suis', 'triste'],
 ['je', 'suis', 'timide'],
 ['je', 'suis', 'mouill'],
 ['je', 'suis', 'mouill'],
 ['est', 'bibi'],
 ['joignez', 'vous'],
 ['joignez', 'vous', 'nous'],
 ['garde', 'le'],
 ['gardez', 'le'],
 ['embrasse', 'moi'],
 ['embrassez', 'moi'],
 ['moi', 'aussi'],
 ['ouvre', 'moi'],
 ['ouvre'],
 ['parfait'],
 ['plus', 'tard'],
 ['bient'],
 ['la', 'prochaine'],
 ['plus'],
 ['montre', 'moi'],
 ['montrez', 'moi'],
 ['taisez', 'vous'],
 ['ferme', 'la'],
 ['tais', 'toi'],
 ['ferme', 'la'],
 ['la', 'ferme'],
 ['pas', 'grave'],
 ['plus', 'tard'],
 ['prends', 'le'],
 ['prenez', 'le'],
 ['prends', 'le'],
 ['prenez', 'le'],
 ['dis', 'moi'],
 ['dites', 'moi'],
 ['tom', 'gagn'],
 ['veille', 'toi'],
 ['veille', 'toi'],
 ['veillez', 'vous'],
 ['veille', 'toi'],
 ['veillez', 'vous'],
 ['lave', 'toi'],
 ['lavez', 'vous'],
 ['nous', 'savons'],
 ['nous', 'perd', 'mes'],
 ['nous', 'avons', 'perdu'],
 ['nous', 'mes', 'battus'],
 ['nous', 'mes', 'battues'],
 ['nous', 'mes', 'faits'],
 ['nous', 'mes', 'faites'],
 ['nous', 'avons', 'faits'],
 ['nous', 'avons', 'faites'],
 ['nous', 'avons', 'battus'],
 ['nous', 'avons', 'battues'],
 ['bienvenue'],
 ['qui', 'gagn'],
 ['qui', 'emport'],
 ['tu', 'cours'],
 ['suis', 'je', 'gros'],
 ['suis', 'je', 'grosse'],
 ['demande', 'leur'],
 ['demandez', 'leur'],
 ['recule'],
 ['reculez'],
 ['recule'],
 ['reculez'],
 ['retire', 'toi'],
 ['retirez', 'vous'],
 ['sois', 'un', 'homme'],
 ['soyez', 'un', 'homme'],
 ['sois', 'calme'],
 ['soyez', 'calme'],
 ['soyez', 'calmes'],
 ['aucune', 'id'],
 ['en', 'sais', 'foutre', 'rien'],
 ['appelle', 'tom'],
 ['appelez', 'tom'],
 ['courage'],
 ['tends', 'toi'],
 ['menottez', 'le'],
 ['avance'],
 ['avancez'],
 ['continue', 'rouler'],
 ['continuez', 'rouler'],
 ['trouve', 'tom'],
 ['trouvez', 'tom'],
 ['parez', 'ceci'],
 ['pare'],
 ['che', 'toi'],
 ['descends'],
 ['descendez'],
 ['che', 'toi'],
 ['chez', 'vous'],
 ['va', 'voir', 'ailleurs', 'si', 'suis'],
 ['gage'],
 ['va', 'au', 'diable'],
 ['sois', 'aliste'],
 ['passe', 'devant'],
 ['vas'],
 ['avance'],
 ['vas'],
 ['poursuis'],
 ['passe', 'devant'],
 ['vas'],
 ['bien', 'jou'],
 ['bon', 'boulot'],
 ['beau', 'travail'],
 ['attrape', 'le'],
 ['attrapez', 'le'],
 ['amuse', 'toi', 'bien'],
 ['amusez', 'vous', 'bien'],
 ['il', 'essaye'],
 ['il', 'est', 'mouill'],
 ['aide', 'tom'],
 ['aidez', 'tom'],
 ['salut', 'les', 'mecs'],
 ['comme', 'est', 'mignon'],
 ['quelle', 'profondeur'],
 ['comme', 'est', 'chouette'],
 ['comme', 'est', 'gentil'],
 ['est', 'du', 'joli'],
 ['comme', 'est', 'agr', 'able'],
 ['che', 'toi'],
 ['grouille'],
 ['pressez', 'vous'],
 ['fi'],
 ['je', 'en', 'suis', 'bien', 'sorti'],
 ['je', 'en', 'suis', 'bien', 'sortie'],
 ['je', 'ai', 'fait'],
 ['est', 'moi', 'qui', 'ai', 'fait'],
 ['ai', 'chou'],
 ['ai', 'oubli'],
 ['ai', 'compris'],
 ['ai', 'compris'],
 ['ai', 'capt'],
 ['ai', 'aid'],
 ['ai', 'saut'],
 ['ai', 'regard'],
 ['ai'],
 ['ai', 'fait', 'signe', 'de', 'la', 'te'],
 ['ai', 'ob'],
 ['je', 'phonai'],
 ['ai', 'phon'],
 ['je', 'refuse'],
 ['je', 'le', 'refuse'],
 ['je', 'me', 'suis', 'repos'],
 ['je', 'me', 'suis', 'repos'],
 ['je', 'ai', 'vu'],
 ['je', 'ai', 'vu'],
 ['ai', 'soupir'],
 ['je', 'suis', 'rest'],
 ['je', 'suis', 'rest'],
 ['ai', 'parl'],
 ['je', 'utilise'],
 ['en', 'fais', 'usage'],
 ['je', 'en', 'sers'],
 ['je', 'paierai'],
 ['je', 'vais', 'essayer'],
 ['essaierai'],
 ['je', 'suis', 'revenu'],
 ['me', 'revoil'],
 ['je', 'suis', 'chauve'],
 ['je', 'suis', 'occup'],
 ['je', 'suis', 'occup'],
 ['je', 'suis', 'calme'],
 ['ai', 'froid'],
 ['je', 'suis', 'tendu'],
 ['je', 'suis', 'tendue'],
 ['je', 'suis', 'sourd'],
 ['je', 'suis', 'sourde'],
 ['en', 'ai', 'fini'],
 ['je', 'suis', 'juste'],
 ['ai', 'la', 'peau', 'claire'],
 ['ai', 'le', 'teint', 'clair'],
 ['je', 'suis', 'rapide'],
 ['tout', 'va', 'bien'],
 ['je', 'vais', 'bien'],
 ['va'],
 ['je', 'suis', 'libre'],
 ['je', 'suis', 'libre'],
 ['je', 'suis', 'disponible'],
 ['je', 'suis', 'repu'],
 ['je', 'suis', 'rassasi'],
 ['en', 'suis'],
 ['je', 'suis', 'de', 'la', 'partie'],
 ['je', 'suis', 'content'],
 ['je', 'suis', 'chez', 'moi'],
 ['je', 'suis', 'en', 'retard'],
 ['je', 'suis', 'paresseux'],
 ['je', 'suis', 'fain', 'ant'],
 ['je', 'suis', 'paresseuse'],
 ['je', 'suis', 'fain', 'ante'],
 ['je', 'vais', 'bien'],
 ['je', 'me', 'porte', 'bien'],
 ['je', 'suis', 'riche'],
 ['je', 'suis', 'en', 'curit'],
 ['je', 'suis', 'malade'],
 ['en', 'suis', 'certain'],
 ['je', 'suis', 'certain'],
 ['en', 'suis'],
 ['en', 'suis', 're'],
 ['je', 'suis', 'grande'],
 ['je', 'suis', 'mince'],
 ['je', 'suis', 'ordonn'],
 ['je', 'suis', 'ordonn'],
 ['je', 'suis', 'laid'],
 ['je', 'suis', 'laide'],
 ['je', 'suis', 'faible'],
 ['je', 'vais', 'bien'],
 ['je', 'me', 'porte', 'bien'],
 ['ai', 'gagn'],
 ['je', 'ai', 'emport'],
 ['aide'],
 ['fait', 'mal'],
 ['elle', 'marche'],
 ['fonctionne'],
 ['est', 'tom'],
 ['est', 'marrant'],
 ['est', 'rigolo'],
 ['est', 'le', 'sien'],
 ['est', 'la', 'sienne'],
 ['est', 'nouveau'],
 ['est', 'neuf'],
 ['est', 'bizarre'],
 ['il', 'est', 'rouge'],
 ['est', 'triste'],
 ['fense', 'entrer'],
 ['entrez', 'pas'],
 ['embrasse', 'tom'],
 ['laisse', 'tomber'],
 ['laissez', 'tomber'],
 ['laissez', 'moi'],
 ['laisse', 'nous'],
 ['laissez', 'nous'],
 ['allons'],
 ['allons'],
 ['attention'],
 ['regarde', 'donc'],
 ['pouse', 'moi'],
 ['pousez', 'moi'],
 ['puis', 'je', 'partir'],
 ['puis', 'je', 'aller'],
 ['puis', 'je', 'rendre'],
 ['sauve', 'tom'],
 ['sauvez', 'tom'],
 ['de', 'quoi'],
 ['elle', 'est', 'venue'],
 ['elle', 'est', 'morte'],
 ['elle', 'court'],
 ['assieds', 'toi'],
 ['asseyez', 'vous'],
 ['assieds', 'toi'],
 ['assieds', 'toi', 'ici'],
 ['asseyez', 'vous', 'ici'],
 ['parle', 'plus', 'fort'],
 ['parlez', 'plus', 'fort'],
 ['ve', 'toi'],
 ['arr', 'te', 'tom'],
 ['stoppez', 'tom'],
 ['go', 'te', 'le'],
 ['go', 'te', 'la'],
 ['go', 'tez', 'le'],
 ['go', 'tez', 'la'],
 ['dis', 'le', 'tom'],
 ['informez', 'en', 'tom'],
 ['nial'],
 ['excellent'],
 ['formidable'],
 ['ils', 'gagn', 'rent'],
 ['elles', 'gagn', 'rent'],
 ['ils', 'ont', 'gagn'],
 ['elles', 'ont', 'gagn'],
 ['tom', 'est', 'venu'],
 ['tom', 'est', 'mort'],
 ['tom', 'savait'],
 ['tom', 'est', 'parti'],
 ['tom', 'partit'],
 ['tom', 'menti'],
 ['tom', 'ment'],
 ['tom', 'perdu'],
 ['tom', 'pay'],
 ['trop', 'tard'],
 ['faites', 'moi', 'confiance'],
 ['fais', 'moi', 'confiance'],
 ['fais', 'un', 'effort'],
 ['essaies', 'en'],
 ['essayez', 'en'],
 ['essaie', 'ceci'],
 ['essayez', 'ceci'],
 ['utilise', 'ceci'],
 ['utilisez', 'ceci'],
 ['emploie', 'ceci'],
 ['employez', 'ceci'],
 ['avertis', 'tom'],
 ['pr', 'viens', 'tom'],
 ['regarde', 'moi'],
 ['regardez', 'moi'],
 ['regardez', 'nous'],
 ['regarde', 'nous'],
 ['nous', 'sommes', 'accord'],
 ['nous', 'irons'],
 ['nous', 'allons', 'bien'],
 ['pour', 'quoi', 'faire'],
 ['quoi', 'bon'],
 ['qu', 'est', 'ce', 'qu', 'on', 'est', 'marr'],
 ['qu', 'est', 'ce', 'qu', 'on', 'est', 'marr', 'es'],
 ['qui', 'est', 'venu'],
 ['qui', 'est', 'mort'],
 ['qui', 'est', 'tomb'],
 ['qui', 'missionne'],
 ['qui', 'est', 'il'],
 ['cris', 'moi'],
 ['crivez', 'moi'],
 ['tu', 'as', 'perdu'],
 ['vous', 'avez', 'perdu'],
 ['apr', 'vous'],
 ['en', 'joue', 'feu'],
 ['suis', 'je', 'en', 'retard'],
 ['pondez', 'moi'],
 ['assieds', 'toi'],
 ['asseyez', 'vous'],
 ['les', 'oiseaux', 'volent'],
 ['tes', 'souhaits'],
 ['appelle', 'la', 'maison'],
 ['calmez', 'vous'],
 ['calme', 'toi'],
 ['pouvons', 'nous', 'partir'],
 ['pouvons', 'nous', 'nous', 'en', 'aller'],
 ['pouvons', 'nous', 'aller'],
 ['attrape', 'tom'],
 ['attrapez', 'tom'],
 ['rattrape', 'le'],
 ['calme', 'toi'],
 ['reviens'],
 ['revenez'],
 ['viens', 'ici'],
 ['venez'],
 ['viens'],
 ['venez'],
 ['venez', 'ici'],
 ['viens', 'chez', 'nous'],
 ['venez', 'chez', 'nous'],
 ['viens', 'chez', 'moi'],
 ['venez', 'chez', 'moi'],
 ['viens', 'bient'],
 ['venez', 'bient'],
 ['calmez', 'vous'],
 ['ai', 'je', 'gagn'],
 ['ai', 'je', 'emport'],
 ['est', 'ce', 'moi', 'qui', 'ai', 'gagn'],
 ['faites', 'le', 'maintenant'],
 ['des', 'chiens', 'aboient'],
 ['les', 'chiens', 'aboient'],
 ['ne', 'demande', 'pas'],
 ['ne', 'pleure', 'pas'],
 ['ne', 'meurs', 'pas'],
 ['ne', 'mourez', 'pas'],
 ['ne', 'mens', 'pas'],
 ['ne', 'courez', 'pas'],
 ['ne', 'cours', 'pas'],
 ['excuse', 'moi'],
 ['excusez', 'moi'],
 ['pardon'],
 ['je', 'vous', 'demande', 'pardon'],
 ['pla', 'il'],
 ['plait', 'il'],
 ['pardon'],
 ['fantastique'],
 ['sens'],
 ['sentez'],
 ['touche'],
 ['touchez'],
 ['suis', 'moi'],
 ['suis', 'nous'],
 ['suivez', 'nous'],
 ['oublie'],
 ['oublie', 'le'],
 ['oubliez'],
 ['oubliez', 'le'],
 ['laisse', 'tomber'],
 ['oublie'],
 ['oublie', 'le'],
 ['trouve', 'un', 'emploi'],
 ['trouve', 'un', 'boulot'],
 ['trouvez', 'un', 'emploi'],
 ['trouvez', 'un', 'boulot'],
 ['pr', 'pare', 'toi'],
 ['pr', 'parez', 'vous'],
 ['va', 'le', 'chercher'],
 ['allez', 'le', 'chercher'],
 ['entrez'],
 ['va', 'au', 'lit'],
 ['allez', 'au', 'lit'],
 ['bonne', 'chance'],
 ['bonne', 'chance'],
 ['attrape'],
 ['attrapez'],
 ['saisis', 'toi', 'de'],
 ['saisissez', 'vous', 'de'],
 ['attrape'],
 ['attrapez'],
 ['pas', 'touche'],
 ['il', 'est', 'malade'],
 ['il', 'est', 'vieux'],
 ['il', 'est', 'dj'],
 ['il', 'est', 'bon'],
 ['il', 'est', 'paresseux'],
 ['il', 'est', 'moi'],
 ['il', 'est', 'riche'],
 ['il', 'est', 'sexy'],
 ['me', 'voici'],
 ['voil', 'cinq', 'dollars'],
 ['halte', 'au', 'feu'],
 ['cessez', 'le', 'feu'],
 ['tiens'],
 ['tenez'],
 ['tenez', 'ceci'],
 ['tiens', 'ceci'],
 ['est', 'affreux'],
 ['comme', 'est', 'bizarre'],
 ['comment', 'tom', 'va', 'il'],
 ['comment', 'va', 'tom'],
 ['ai', 'froid'],
 ['je', 'suis', 'bon'],
 ['je', 'vais', 'bien'],
 ['je', 'suis', 'malade'],
 ['je', 'suis'],
 ['je', 'suis', 'certain'],
 ['je', 'vous', 'en', 'prie'],
 ['je', 'vous', 'en', 'conjure'],
 ['je', 'vous', 'en', 'supplie'],
 ['je', 'te', 'prie'],
 ['je', 'sais', 'courir'],
 ['je', 'sais', 'skier'],
 ['eus', 'un', 'mouvement', 'de', 'recul'],
 ['ai', 'eu', 'un', 'mouvement', 'de', 'recul'],
 ['je', 'suis', 'rentr', 'en', 'moi', 'me'],
 ['ai', 'expir'],
 ['ai', 'abandonn'],
 ['je', 'donne', 'ma', 'langue', 'au', 'chat'],
 ['abandonne'],
 ['je', 'me', 'suis', 'mis', 'avoir', 'chaud'],
 ['je', 'me', 'suis', 'mise', 'avoir', 'chaud'],
 ['je', 'me', 'suis', 'amus'],
 ['je', 'me', 'suis', 'amus'],
 ['je', 'me', 'suis', 'marr'],
 ['je', 'me', 'suis', 'marr'],
 ['je', 'teste'],
 ['je', 'ai'],
 ['ai', 'frapp', 'tom'],
 ['esp', 're', 'bien'],
 ['je', 'me', 'suis', 'ch'],
 ['je', 'me', 'suis', 'ch'],
 ['ai', 'inspir'],
 ['je', 'le', 'savais'],
 ['aime'],
 ['je', 'ai', 'perdu'],
 ['adore'],
 ['adore'],
 ['je', 'suis', 'rieux'],
 ['je', 'suis', 'rieux'],
 ['je', 'dois', 'aller'],
 ['il', 'faut', 'que', 'aille'],
 ['il', 'me', 'faut', 'aller'],
 ['il', 'me', 'faut', 'partir'],
 ['il', 'me', 'faut', 'en', 'aller'],
 ['je', 'dois', 'partir'],
 ['je', 'dois', 'en', 'aller'],
 ['il', 'faut', 'que', 'je', 'en', 'aille'],
 ['en', 'ai', 'besoin'],
 ['il', 'me', 'le', 'faut'],
 ['ai', 'remarqu'],
 ['ai', 'pay', 'avance'],
 ['je', 'le', 'promets'],
 ['je', 'me', 'suis', 'tendu'],
 ['je', 'me', 'suis', 'tendue'],
 ['ai', 'pris', 'ma', 'retraite'],
 ['ai', 'dit', 'non'],
 ['je', 'ai', 'dit'],
 ['je', 'ai', 'vu'],
 ['je', 'ai', 'vu'],
 ['je', 'le', 'vis'],
 ['en', 'ai', 'vu', 'une'],
 ['en', 'ai', 'vu', 'un'],
 ['je', 'vous', 'vis'],
 ['je', 'te', 'vis'],
 ['je', 'ai', 'vue'],
 ['je', 'ai', 'vu'],
 ['je', 'vous', 'ai', 'vues'],
 ['je', 'vous', 'ai', 'vus'],
 ['je', 'vous', 'ai', 'vue'],
 ['je', 'vous', 'ai', 'vu'],
 ['je', 'vois', 'tom'],
 ['ai', 'cri'],
 ['ai', 'tr', 'buch'],
 ['ai', 'plan'],
 ['je', 'le', 'veux'],
 ['tais', 'nouveau'],
 ['tais', 'nouvelle'],
 ['irai'],
 ['je', 'me', 'suis', 'veill'],
 ['je', 'me', 'suis', 'veill'],
 ['je', 'serais', 'accord'],
 ['je', 'partirais'],
 ['appellerai'],
 ['je', 'cuisinerai'],
 ['aiderai'],
 ['je', 'vivrai'],
 ['ob', 'irai'],
 ['je', 'ferai', 'mon', 'sac'],
 ['je', 'ferai', 'ma', 'valise'],
 ['je', 'plierai', 'mes', 'gaules'],
 ['je', 'passerai'],
 ['abandonnerai'],
 ['je', 'chanterai'],
 ['arr', 'terai'],
 ['je', 'nagerai'],
 ['je', 'parlerai'],
 ['je', 'vais', 'parler'],
 ['attendrai'],
 ['je', 'marcherai'],
 ['je', 'vais', 'travailler'],
 ['je', 'travaillerai'],
 ['je', 'suis', 'flic'],
 ['je', 'suis', 'un', 'homme'],
 ['je', 'suis', 'en', 'vie'],
 ['je', 'suis', 'vivant'],
 ['je', 'suis', 'vivante'],
 ['je', 'suis', 'seule'],
 ['je', 'suis', 'seul'],
 ['je', 'suis', 'nerv'],
 ['je', 'suis', 'en', 'col', 're'],
 ['je', 'suis', 'arm'],
 ['je', 'suis', 'arm'],
 ['je', 'suis', 'veill'],
 ['je', 'suis', 'aveugle'],
 ['je', 'suis', 'fauch'],
 ['ai', 'croch'],
 ['je', 'suis', 'propre'],
 ['je', 'suis', 'fou'],
 ['je', 'suis', 'folle'],
 ['je', 'suis', 'gu', 'ri'],
 ['je', 'suis', 'gu', 'rie'],
 ['ai', 'la', 'te', 'qui', 'tourne'],
 ['je', 'suis', 'saoul'],
 ['je', 'suis', 'so'],
 ['je', 'suis', 'ivre'],
 ['je', 'me', 'meurs'],
 ['je', 'suis', 'en', 'avance'],
 ['je', 'suis', 'en', 'premier'],
 ['je', 'suis', 'difficile'],
 ['je', 'suis', 'tatillon'],
 ['je', 'suis', 'tatillonne'],
 ['je', 'pars', 'maintenant'],
 ['je', 'me', 'tire'],
 ['vais'],
 ['je', 'pars'],
 ['je', 'suis', 'loyal'],
 ['je', 'suis', 'loyale'],
 ['je', 'suis', 'veinard'],
 ['je', 'suis', 'veinarde'],
 ['ai', 'du', 'pot'],
 ['je', 'suis', 'chanceux'],
 ['je', 'suis', 'chanceuse'],
 ['je', 'suis', 'en', 'train', 'de', 'mentir'],
 ['je', 'suis', 'nu'],
 ['je', 'suis', 'nue'],
 ['je', 'me', 'trouve', 'nu'],
 ['je', 'me', 'trouve', 'nue'],
 ['je', 'suis', 'poil'],
 ['je', 'suis', 'tranquille'],
 ['je', 'suis', 'pr', 'te'],
 ['je', 'suis', 'pr'],
 ['je', 'suis', 'pr'],
 ['ai', 'raison'],
 ['je', 'suis', 'sobre'],
 ['excuse', 'moi'],
 ['sol'],
 ['excusez', 'moi'],
 ['sol'],
 ['je', 'suis', 'sol'],
 ['je', 'suis', 'sol'],
 ['je', 'suis', 'coinc'],
 ['je', 'suis', 'timide'],
 ['je', 'suis', 'fatigu'],
 ['je', 'suis', 'dur'],
 ['je', 'suis', 'dure'],
 ['je', 'suis', 'dur', 'cuire'],
 ['je', 'suis', 'dure', 'cuire'],
 ['je', 'suis', 'toi'],
 ['je', 'suis', 'vous'],
 ['ai', 'perdu'],
 ['est', 'ce', 'que', 'tom', 'va', 'bien'],
 ['tom', 'va', 'il', 'bien'],
 ['est', 'grave'],
 ['est', 'ce', 'loign'],
 ['est', 'ce', 'loin'],
 ['est', 'ce', 'chaud'],
 ['est', 'ce', 'toi'],
 ['est', 'ce', 'vous'],
 ['est', 'ce', 'que', 'est', 'vous'],
 ['chou'],
 ['il', 'neig'],
 ['sent', 'mauvais'],
 ['pue'],
 ['tait', 'bon'],
 ['tait', 'correct'],
 ['tait', 'ok'],
 ['fonctionn'],
 ['march'],
 ['il', 'est', 'trois', 'heures', 'et', 'demie'],
 ['il', 'est', 'huit', 'heures', 'trente'],
 ['il', 'est'],
 ['est', 'une'],
 ['il', 'fait', 'froid'],
 ['est', 'froid'],
 ['est', 'sombre'],
 ['elle', 'est', 'morte'],
 ['est', 'mort'],
 ['il', 'est', 'mort'],
 ['est', 'fait'],
 ['est', 'simple'],
 ['est', 'de', 'la', 'nourriture'],
 ['est', 'gratuit'],
 ['elle', 'est', 'ici'],
 ['est', 'ici'],
 ['est', 'le', 'sien'],
 ['est', 'la', 'sienne'],
 ['il', 'est', 'tard'],
 ['est', 'perdu'],
 ['est', 'le', 'mien'],
 ['est', 'la', 'mienne'],
 ['est', 'moi'],
 ['il', 'agit', 'du', 'mien'],
 ['est', 'ouvert'],
 ['est', 'le', 'tre'],
 ['est', 'la', 'tre'],
 ['est', 'nous'],
 ['est', 'du', 'sable'],
 ['il', 'est', 'temps'],
 ['est', 'heure'],
 ['est', 'vrai'],
 ['est', 'du', 'boulot'],
 ['restez', 'calme'],
 ['garde'],
 ['gardez', 'cela'],
 ['garde'],
 ['gardez', 'ceci'],
 ['ainsi', 'soit', 'il'],
 ['laisse', 'faire'],
 ['laisse', 'moi', 'partir'],
 ['laissez', 'moi', 'partir'],
 ['che', 'moi'],
 ['chez', 'moi'],
 ['laisse', 'moi', 'en', 'aller'],
 ['laissez', 'moi', 'en', 'aller'],
 ['laissez', 'moi', 'aller'],
 ['laisse', 'moi', 'aller'],
 ['laisse', 'moi', 'partir'],
 ['laissez', 'moi', 'partir'],
 ['laisse', 'moi', 'en', 'aller'],
 ['laissez', 'moi', 'en', 'aller'],
 ['laissez', 'moi', 'rentrer'],
 ['laissez', 'moi', 'entrer'],
 ['demandons'],
 ['mangeons'],
 ['voyons', 'voir'],
 ['reste', 'allong', 'immobile'],
 ['reste', 'allong', 'immobile'],
 ['restez', 'allong', 'immobile'],
 ['restez', 'allong', 'immobile'],
 ['restez', 'allong', 'immobiles'],
 ['restez', 'allong', 'es', 'immobiles'],
 ['tourne', 'le', 'regard'],
 ['regardez', 'ailleurs'],
 ['regarde', 'derri', 're', 'toi'],
 ['regarde', 'derri', 're'],
 ['regarde', 'ici'],
 ['regardez', 'ici'],
 ['chauffe', 'toi'],
 ['chauffez', 'vous'],
 ['tends', 'toi'],
 ['laisse', 'toi', 'aller'],
 ['laissez', 'vous', 'aller'],
 ['bouge', 'de'],
 ['poussez', 'vous'],
 ['pousse', 'toi'],
 ['joli', 'coup'],
 ['pour'],
 ['mais', 'ouais'],
 ['pardi'],
 ['bien'],
 ['pour'],
 ['je', 'vous', 'en', 'prie'],
 ['je', 'en', 'prie'],

In [44]:
max_len_output = max(len(sentence) for sentence in words1)
longest_sentence = max(words1, key=len)

print("Max number of words:", max_len_output)
print("Sentence with max words:", longest_sentence)

Max number of words: 55
Sentence with max words: ['si', 'quelqu', 'un', 'qui', 'ne', 'conna', 'pas', 'vos', 'ant', 'dents', 'dit', 'que', 'vous', 'parlez', 'comme', 'un', 'locuteur', 'natif', 'cela', 'veut', 'dire', 'qu', 'il', 'probablement', 'remarqu', 'quelque', 'chose', 'propos', 'de', 'votre', 'locution', 'qui', 'lui', 'fait', 'prendre', 'conscience', 'que', 'vous', 'tes', 'pas', 'un', 'locuteur', 'natif', 'en', 'autres', 'termes', 'vous', 'ne', 'parlez', 'pas', 'vraiment', 'comme', 'un', 'locuteur', 'natif']

In [57]:
all_words1 = [word for sentence in words1 for word in sentence]

# Get unique words
unique_words_output = set(all_words1)

# Count them
print("Number of unique words:", len(unique_words_output))
print("Unique words:", unique_words)

Number of unique words: 19931

In [60]:
one_hot_output=[one_hot(word, len(unique_words_output)) for word in corpus1]
one_hot_output

[[8369],
 [16781],
 [4187],
 [18991],
 [3985, 1004],
 [16863, 12880],
 [6817, 15026],
 [15375],
 [3985, 17923],
 [11055],
 [1281, 11791, 4702],
 [11910],
 [4178],
 [13919],
 [10495],
 [1460],
 [2369],
 [8369],
 [19304, 9441],
 [2963, 1136],
 [2963, 4224, 6277],
 [19304, 6817, 4224, 9604],
 [2963, 4224, 6277],
 [19892, 19380],
 [2765],
 [12133],
 [4551],
 [8985, 4551],
 [18547],
 [1750, 1750],
 [6817, 16314, 4702],
 [9662, 19440],
 [9765, 13512, 19440],
 [9089, 13512, 19440],
 [2963, 4224, 18087],
 [10373],
 [18087],
 [10373],
 [8116, 7557, 2644],
 [5788],
 [1869],
 [15029, 13172, 3390, 3215, 12753],
 [11511, 13172, 3390, 17657, 12753],
 [19304, 7315, 6442, 18888],
 [19304, 7315, 6442],
 [19304, 6353],
 [19304, 7315, 9002],
 [19304, 7315, 5220],
 [2963, 4224, 12213],
 [2963, 4224, 5485],
 [2963, 4224, 11013],
 [2963, 4224, 1, 17310],
 [19304, 2185, 17571],
 [3985, 9662],
 [14377],
 [6319, 11037, 17547, 13487],
 [13101],
 [7159, 8919, 1162],
 [8671, 19247, 14217],
 [6319, 11037, 9306, 7520, 4202],
 [15570, 16365, 7159, 11037, 17547, 4202],
 [6319, 11037, 2071],
 [7159, 2480, 3337, 7737],
 [9306, 7520, 4202],
 [12390],
 [5695],
 [1199, 9156],
 [18547],
 [6707, 1136],
 [9386, 1791, 6277],
 [9386, 6277, 2642],
 [9386, 6817, 1791, 9604],
 [9386, 6817, 9604, 2642],
 [10441, 18838],
 [15750],
 [17130, 11723],
 [2832, 11723],
 [2832, 4222],
 [17130, 13108, 232],
 [17130, 15247],
 [2832, 15247],
 [2832, 8144],
 [17130, 11452],
 [2832, 11452],
 [2832, 14983],
 [17130, 13308],
 [17130, 13308],
 [17130, 5564],
 [2832, 13308],
 [2832, 5564],
 [2832, 10217],
 [2832, 6402],
 [13108, 14456],
 [16702, 13172],
 [10362, 13172],
 [16702, 9386],
 [12248, 9386],
 [15666],
 [19887],
 [19887],
 [15666],
 [9765],
 [9765],
 [19105],
 [16197],
 [15049, 10337],
 [13603, 10337],
 [15049, 1497, 10337],
 [13603, 1497, 10337],
 [9662, 3656, 18838],
 [8912],
 [717],
 [8912],
 [717],
 [12415, 4702],
 [13108, 14456],
 [1667],
 [9662, 11791, 1416, 10292],
 [1667],
 [13108, 14456],
 [15005, 1497, 11809],
 [1667, 13108, 6393],
 [9662, 8116, 7159],
 [1957],
 [9765, 2682, 7159],
 [5920, 18114, 10525],
 [18612, 18114, 10525],
 [18612, 4407, 4702],
 [5920, 4407, 2682],
 [9662, 91],
 [9765, 91],
 [16570],
 [18114, 4095],
 [11910, 15863, 6690],
 [4178, 15863, 6690],
 [19179, 9156],
 [7969, 9156],
 [15570, 10213, 10337],
 [15570, 3985, 3068, 10337],
 [15570, 7560],
 [15026, 13172],
 [15026, 13172],
 [15465, 13172],
 [15465, 9386],
 [15026, 9386],
 [11120, 76, 17532],
 [11120, 13300, 17547],
 [4191, 15863, 6319, 18787, 18838],
 [19304, 7315, 19924, 14174, 18983, 4574],
 [2963, 4224, 5210],
 [19304, 18983, 7315, 15201],
 [19304, 18983, 7315, 13801],
 [19304, 13433],
 [19304, 7502],
 [19304, 17551],
 [19304, 17982],
 [19304, 18983, 7315, 16888, 6659],
 [19304, 18983, 7315, 7312, 6659],
 [2963, 4224, 3923],
 [2963, 4224, 12364],
 [2963, 10521],
 [2963, 4224, 16461],
 [2963, 4224, 17002],
 [2963, 4224, 15400, 18128],
 [2963, 6550],
 [19304, 7315, 18838],
 [19304, 7315, 1997],
 [19304, 7315, 5650],
 [19304, 7315, 7159, 5269],
 [19304, 7315, 19580],
 [19304, 7315, 19580, 18888],
 [19304, 7315, 5586],
 [19304, 7315, 18175],
 [19304, 7315, 15248],
 [19304, 7315, 6214],
 [19304, 7315, 6214, 18888],
 [6319, 11037, 3324],
 [9765, 2682],
 [9765, 2682, 9386],
 [12222, 1497],
 [16434, 1497],
 [301, 13172],
 [17772, 13172],
 [13172, 8789],
 [1395, 13172],
 [1395],
 [8507],
 [17532, 5047],
 [3254, 8116],
 [18114, 19269],
 [17532],
 [7723, 13172],
 [2254, 13172],
 [4081, 2682],
 [16983, 18114],
 [4849, 4702],
 [16983, 18114],
 [18114, 16983],
 [17547, 2980],
 [17532, 5047],
 [3311, 1497],
 [11893, 1497],
 [3311, 1497],
 [11893, 1497],
 [11285, 13172],
 [1114, 13172],
 [18838, 3985, 6277],
 [4718, 3944, 4702],
 [4718, 3944, 4702],
 [4718, 4681, 2682],
 [4718, 3944, 4702],
 [4718, 4681, 2682],
 [8127, 4702],
 [16216, 2682],
 [9386, 17173],
 [9386, 8872, 2642],
 [9386, 1791, 5485],
 [9386, 4429, 2642, 13348],
 [9386, 4429, 2642, 4353],
 [9386, 4429, 2642, 13108, 17198],
 [9386, 4429, 2642, 13108, 17858],
 [9386, 1791, 8116, 13108, 17198],
 [9386, 1791, 8116, 13108, 17858],
 [9386, 1791, 8116, 13348],
 [9386, 1791, 8116, 4353],
 [19769],
 [18991, 3985, 6277],
 [18991, 6817, 3985, 9604],
 [10191, 16781],
 [7315, 19304, 5650],
 [7315, 19304, 7364],
 [10441, 324],
 [17645, 324],
 [170],
 [11761],
 [170],
 [11761],
 [15842, 4702],
 [16555, 2682],
 [17130, 15863, 19700],
 [2832, 15863, 19700],
 [17130, 11723],
 [2832, 11723],
 [2832, 4222],
 [2480, 15632, 18888],
 [2963, 7159, 6353, 10292, 9421],
 [16702, 18838],
 [12248, 18838],
 [4323],
 [13108, 10810, 4702],
 [16848, 1497],
 [7261],
 [14],
 [1576, 3568],
 [10495, 3568],
 [6694, 18838],
 [15339, 18838],
 [4718, 8487, 2404],
 [4718, 15055, 3985],
 [6817, 10476, 4702],
 [2104],
 [15348],
 [6817, 10476, 4702],
 [6817, 4407, 2682],
 [9662, 8205, 10127, 14111, 2963, 13512, 7315],
 [13108, 14456],
 [9662, 16863, 17676],
 [17130, 4718, 6714],
 [10102, 13780],
 [9089, 13512],
 [7261],
 [9089, 13512],
 [13919],
 [10102, 13780],
 [9089, 13512],
 [17571, 7539],
 [9156, 2527],
 [12065, 10759],
 [8564, 1497],
 [17939, 1497],
 [785, 4702, 17571],
 [2595, 2682, 17571],
 [15570, 1136],
 [15570, 11037, 6214],
 [15026, 18838],
 [15465, 18838],
 [8369, 10323, 11804],
 [232, 6319, 11037, 12441],
 [8688, 4131],
 [232, 6319, 11037, 13885],
 [232, 6319, 11037, 13308],
 [6319, 11037, 19924, 4157],
 [232, 6319, 11037, 15481, 3816],
 [13108, 16471, 10476, 4702],
 [19790],
 [15685, 2682],
 [7897, 3985],
 [19304, 14174, 7159, 7315, 17571, 5194],
 [19304, 14174, 7159, 7315, 17571, 16580],
 [19304, 6817, 4224, 15400],
 [6319, 11037, 13172, 18991, 6817, 4224, 15400],
 [2963, 4224, 10619],
 [2963, 4224, 13694],
 [2963, 4224, 10373],
 [2963, 4224, 10373],
 [2963, 4224, 2644],
 [2963, 4224, 17790],
 [2963, 4224, 13151],
 [2963, 4224, 14457],
 [2963, 4224, 4718, 6817],
 [2963, 4224, 15400, 18128, 7520, 18114, 8116, 11791],
 [2963, 4224, 17704, 16365],
 [19304, 8116, 6817, 13902],
 [2963, 4224, 8116, 6817, 2442],
 [19304, 13678],
 [19304, 1497, 13678],
 [19304, 18983, 7315, 9349],
 [19304, 18983, 7315, 9349, 18888],
 [19304, 6817, 4224, 10199],
 [19304, 6817, 4224, 10199],
 [2963, 4224, 6506],
 [19304, 7315, 2728],
 [19304, 7315, 2728, 18888],
 [2963, 4224, 14404],
 [19304, 6817, 7795],
 [2963, 7159, 4191, 6010],
 [19304, 14174, 7159, 11162],
 [19304, 158],
 [19304, 2185, 1972],
 [2963, 5129],
 [19304, 7315, 10878],
 [18983, 19352],
 [19304, 7315, 15540],
 [19304, 7315, 12120],
 [19304, 7315, 12120, 18888],
 [19304, 7315, 11723],
 [2963, 4224, 3031],
 [19304, 7315, 13108, 232],
 [19304, 7315, 13108, 5914],
 [19304, 7315, 13505],
 [19304, 7315, 6130],
 [2963, 7159, 4224, 19183],
 [19304, 7315, 15247],
 [2963, 4224, 18114, 101, 13920],
 [2963, 4224, 1497, 7409, 11036],
 [19304, 7315, 9356],
 [17159, 9662, 17571],
 [19304, 2185, 17571],
 [3985, 9662],
 [19304, 7315, 15431],
 [19304, 7315, 15431],
 [19304, 7315, 18010],
 [19304, 7315, 5845],
 [19304, 7315, 11676],
 [2963, 7159, 7315],
 [19304, 7315, 7520, 18114, 5220],
 [19304, 7315, 3345],
 [19304, 7315, 4407, 13172],
 [19304, 7315, 7159, 2446],
 [19304, 7315, 452],
 [19304, 7315, 15033, 14601],
 [19304, 7315, 6092],
 [19304, 7315, 15033, 1575],
 [19304, 2185, 17571],
 [19304, 18983, 11500, 17571],
 [19304, 7315, 15713],
 [19304, 7315, 7159, 4276, 18630],
 [19304, 7315, 5586],
 [2963, 7159, 7315, 10481],
 [19304, 7315, 10481],
 [2963, 7159, 7315, 4276, 4718],
 [2963, 7159, 7315, 4276, 7737],
 [19304, 7315, 4487],
 [19304, 7315, 15129],
 [19304, 7315, 19631],
 [19304, 7315, 19631, 18888],
 [19304, 7315, 18366],
 [19304, 7315, 6113],
 [19304, 7315, 7019],
 [19304, 2185, 17571],
 [19304, 18983, 11500, 17571],
 [2963, 4224, 6277],
 [19304, 6817, 4224, 9604],
 [3985, 15026],
 [3985, 15400, 12432],
 [19649, 9643],
 [3985, 15574],
 [6319, 11037, 18838],
 [6319, 11037, 2150],
 [6319, 11037, 4666],
 [6319, 11037, 1497, 6346],
 [6319, 11037, 18114, 16526],
 [6319, 11037, 12896],
 [6319, 11037, 1987],
 [6319, 11037, 12458],
 [15570, 11037, 14340],
 [6319, 11037, 18175],
 [13108, 11801, 13108, 9523],
 [16365, 15666, 17547],
 [301, 18838],
 [15049, 10337],
 [13603, 10337],
 [13603, 13172],
 [15049, 9386],
 [13603, 9386],
 [230, 13512],
 [230, 13512],
 [6511],
 [12610, 2754],
 [5695, 13172],
 [8896, 13172],
 [4236, 19304, 753],
 [4236, 19304, 13512, 4432],
 [4236, 19304, 14174, 13512, 7176],
 [18762, 18838],
 [6530, 18838],
 [7520, 12329],
 [19649, 11037, 16852],
 [19649, 11037, 8804],
 [19649, 7560],
 [2718, 4702],
 [13502, 2682],
 [2718, 4702],
 [2718, 4702, 6393],
 [13502, 2682, 6393],
 [11612, 17532, 10549],
 [751, 17532, 10549],
 [6817, 16314, 4702],
 [1281, 11791, 18838],
 [9483, 18838],
 [17099, 11791, 1497],
 [17099, 11791, 18114],
 [17099, 11909, 1497],
 [17099, 11909, 18114],
 [11285, 1497, 18838],
 [18713, 7159, 18838],
 [5281, 19308],
 [2124],
 [14572],
 [8032, 6277, 3004],
 [10331, 6277, 3004],
 [8032, 414, 6277],
 [10331, 414, 6277],
 [18838, 11037, 261],
 [18838, 11037, 19307],
 [18838, 13010],
 [18838, 11037, 9002],
 [18838, 6821],
 [18838, 3985, 12213],
 [18838, 5427],
 [18838, 3985, 5485],
 [18838, 3985, 11013],
 [6223, 5047],
 [17858, 13172, 9952],
 [4191, 13172, 9952],
 [4191, 15863, 9019],
 [3814, 7159],
 [18743, 7159],
 [6915, 2404],
 [18743, 2404],
 [7795, 2404],
 [6439, 2404],
 [8764, 2404],
 [12900, 2404],
 [17404, 18838],
 [12050, 19105, 18838],
 [12610, 13172],
 [8032, 13172],
 [8032, 9386],
 [12610, 9386],
 [9386, 19746, 13108, 16425],
 [9386, 17845],
 [9386, 230, 17571],
 [9193, 12329, 1416],
 [12329, 9156],
 [2722, 11037, 8286, 2722, 6707, 4276, 11037, 17621, 4276],
 [2722, 11037, 8286, 2722, 6707, 4276, 11037, 17621, 4195],
 [18991, 11037, 261],
 [18991, 11037, 19307],
 [18991, 11037, 6442],
 [18991, 13108, 7213],
 [18991, 11037, 15570],
 [15846, 13172],
 [10869, 13172],
 [10191, 7557, 5485],
 [2682, 17875, 5485],
 [7690, 4276, 2682],
 [7159, 17072, 12880],
 [7315, 19304, 7159, 2446],
 [4718, 2738, 13172],
 [2718, 4702],
 [13502, 2682],
 [10323, 525, 12073],
 [3215, 3509],
 [16702, 18114, 10525],
 [7897, 2682],
 [11723, 4702],
 [1458, 9386, 753],
 [1458, 9386, 9386, 7159, 4432],
 [1458, 9386, 13512, 4432],
 [8564, 18838],
 [17939, 18838],
 [5457, 1497],
 [11723, 4702],
 [6009],
 [13366],
 [19105, 6393],
 [16197, 6817],
 [19105],
 [16197],
 [16197, 6393],
 [19105, 4407, 9386],
 [16197, 4407, 9386],
 [19105, 4407, 13172],
 [16197, 4407, 13172],
 [19105, 3254, 8116],
 [16197, 3254, 8116],
 [7897, 2682],
 [4224, 19304, 6277],
 [6817, 4224, 19304, 9604],
 [11037, 8286, 13172, 18991, 4224, 6277],
 [17858, 1497, 19440],
 [3552, 9333, 3450],
 [10323, 9333, 3450],
 [11120, 10441, 17547],
 [11120, 18473, 17547],
 [11120, 5121, 17547],
 [11120, 19133, 17547],
 [11120, 10174, 17547],
 [11120, 4187, 17547],
 [11120, 16781, 17547],
 [2967, 13172],
 [8534, 13172],
 [19237],
 [19304, 2682, 10441, 19237],
 [6783, 8116, 15570],
 [8856, 15570],
 [19237],
 [15750],
 [9607, 3985],
 [10697, 3985],
 [4643, 3985],
 [18761, 3985],
 [7315, 13172],
 [7315, 9386],
 [17636, 9386],
 [1896],
 [1896, 1497],
 [1652],
 [1652, 1497],
 [15049, 10337],
 [1896],
 [1896, 1497],
 [6694, 15863, 6335],
 [6694, 15863, 2527],
 [15339, 15863, 6335],
 [15339, 15863, 2527],
 [12050, 15055, 4702],
 [12050, 8487, 2682],
 [9662, 1497, 3656],
 [9765, 1497, 3656],
 [15666],
 [9662, 16863, 13834],
 [9765, 16863, 13834],
 [4732, 11342],
 [4732, 11342],
 [8564, 3985],
 [17939, 3985],
 [469, 4702, 7520, 3985],
 [15407, 2682, 7520, 3985],
 [8564, 3985],
 [17939, 3985],
 [17547, 4643],
 [15570, 11037, 5586],
 [15570, 11037, 5472],
 [15570, 11037, 11079],
 [15570, 11037, 9156],
 [15570, 11037, 452],
 [15570, 11037, 13172],
 [15570, 11037, 15713],
 [15570, 11037, 5709],
 [18983, 3898],
 [19350, 5178, 2046],
 [368, 16863, 12880],
 [15883, 1497, 12880],
 [19179, 3985],
 [7969, 3985],
 [7969, 2404],
 [19179, 2404],
 [6319, 11037, 1663],
 [232, 6319, 11037, 12458],
 [16405, 18838, 9662, 8116, 15570],
 [16405, 9662, 18838],
 [2963, 4224, 3031],
 [19304, 7315, 9156],
 [19304, 2185, 17571],
 [19304, 7315, 5586],
 [19304, 7315, 4276, 4718],
 [19304, 7315, 10481],
 [19304, 2682, 7159, 1596],
 [19304, 2682, 7159, 11959],
 [19304, 2682, 7159, 5066],
 [19304, 11791, 1596],
 [19304, 6353, 16853],
 [19304, 6353, 11280],
 [2963, 9341, 15863, 395, 7520, 7893],
 [2963, 4224, 16537, 15863, 395, 7520, 7893],
 [19304, 7315, 1840, 7159, 13172, 14174, 18983],
 [2963, 4224, 9678],
 [2963, 4224, 18721],
 [19304, 19077, 15834, 5357, 16863, 3821],
 [2963, 14961],
 [19304, 18983, 7315, 8922, 2172, 1109],
 [19304, 18983, 7315, 17705, 2172, 1109],
 [19304, 18983, 7315, 798],
 [19304, 18983, 7315, 798, 18888],
 [19304, 18983, 7315, 17621],
 [19304, 18983, 7315, 17621, 18888],
 [19304, 13108, 13193, 3985],
 [19304, 6817, 4224],
 [2963, 4224, 7819, 18838],
 [2963, 16636, 7737, 17571],
 [19304, 18983, 7315, 13108, 16471, 17689],
 [19304, 18983, 7315, 13108, 16471, 17689, 18888],
 [2963, 4224, 18645],
 [19304, 1497, 218],
 [2963, 486, 3985],
 [19304, 6817, 4224, 5485],
 [2963, 18933, 3985],
 [2963, 18933, 3985],
 [19304, 7315, 4276, 15573],
 [19304, 7315, 4276, 15573],
 [19304, 19172, 13512, 4432],
 [15570, 11181, 6416, 2963, 13512, 11710],
 [15570, 18983, 11181, 13512, 4432],
 [15570, 18983, 11181, 753],
 [15570, 18983, 11181, 14174, 7159, 4432],
 [19304, 19172, 753],
 [19304, 19172, 14174, 7159, 4432],
 [15570, 11181, 6416, 19304, 14174, 7159, 11710],
 [2963, 7159, 4224, 4902],
 [15570, 18983, 1497, 11181],
 [2963, 4224, 15777],
 [2963, 4224, 11013, 13108, 7261],
 [19304, 1497, 13590],
 [19304, 18983, 7315, 13108, 232],
 [19304, 18983, 7315, 13108, 5914],
 [2963, 4224, 12858, 15834, 11481],
 [2963, 4224, 17537, 19380],
 [19304, 6817, 4224, 17537],
 [19304, 6817, 4224, 10199],
 [19304, 6817, 4224, 10199],
 [19304, 1497, 8242],
 [2963, 7159, 4224, 10199, 8234],
 [2963, 7159, 4224, 10199, 15863],
 [19304, 2682, 8242],
 [19304, 11791, 8242],
 [19304, 8116, 4224, 3215],
 [19304, 8116, 4224, 10199],
 [19304, 2682, 4224, 2439],
 [19304, 2682, 4224, 13404],
 [19304, 2682, 4224, 3215],
 [19304, 2682, 4224, 10199],
 [19304, 3654, 18838],
 [2963, 4224, 722],
 [2963, 4224, 6211, 228],
 [2963, 4224, 4593],
 [19304, 1497, 5669],
 [2963, 4849, 12896],
 [2963, 4849, 12454],
 [2963, 6550],
 [19304, 18983, 7315, 4718, 392],
 [19304, 18983, 7315, 392],
 [19304, 13986, 13108, 16425],
 [19304, 126],
 [2963, 14550],
 [19304, 1572],
 [2963, 17189],
 [19304, 19638],
 [2963, 17704, 6550],
 [19304, 9558, 11734, 1316],
 [19304, 9558, 15834, 6877],
 [19304, 10112, 2642, 18809],
 [19304, 11099],
 [2963, 6796],
 [19304, 18677],
 [2963, 1281, 10723],
 [19304, 8713],
 [19304, 12502],
 [19304, 2185, 12841],
 [2963, 7741],
 [19304, 842],
 [19304, 2185, 16801],
 [19304, 4477],
 [19304, 7315, 14189],
 [19304, 7315, 15863, 19700],
 [19304, 7315, 7159, 3050],
 [19304, 7315, 19684],
 [19304, 7315, 14710],
 [19304, 7315, 14286],
 [19304, 7315, 10808],
 [19304, 7315, 13449],
 [19304, 7315, 7159, 19476, 7737],
 [19304, 7315, 9402],
 [19304, 7315, 9402, 18888],
 [19304, 7315, 4718, 392],
 [19304, 7315, 14068],
 [19304, 7315, 6387],
 [2963, 4224, 13108, 18269],
 [19304, 7315, 8862],
 [19304, 7315, 11256],
 [19304, 7315, 5156],
 [19304, 7315, 11715, 2881],
 [19304, 7315, 11715, 14863],
 [2963, 4224, 18114, 8116, 11791, 18991, 2252],
 [19304, 7315, 3608],
 [19304, 7315, 14575, 6817],
 [19304, 7315, 2023],
 [19304, 18983, 5121],
 [19304, 7315, 7159, 7261],
 [19304, 7315, 7159, 369],
 [19304, 7315, 13881],
 [19304, 7315, 16095],
 [19304, 7315, 19667],
 [19304, 1667, 19440],
 [19304, 18983, 6823],
 [2963, 13512, 2185],
 [19304, 1667],
 [19304, 7315, 12942],
 [19304, 7315, 11582],
 [19304, 7315, 12660],
 [19304, 7315, 15929],
 [2963, 4224, 19924, 14539],
 [19304, 7315, 404],
 [19304, 7315, 1709],
 [19304, 7315, 7159, 16355, 7520, 241],
 [19304, 7315, 6117],
 [19304, 7315, 2047],
 [19304, 18983, 6694, 6117],
 [19304, 18983, 6694, 2047],
 [19304, 7315, 9509],
 [19304, 7315, 7131],
 [19304, 7315, 12050, 11791],
 [19304, 7315, 12050, 8116],
 [19304, 7315, 12050, 8116],
 [2963, 4224, 15545],
 [19304, 7315, 12593],
 [2967, 13172],
 [13108, 5221],
 [8534, 13172],
 [13108, 5221],
 [19304, 7315, 13108, 5221],
 [19304, 7315, 13108, 5221, 18888],
 [19304, 7315, 18906, 18888],
 [19304, 7315, 15248],
 [19304, 7315, 10731],
 [19304, 7315, 10505],
 [19304, 7315, 9483],
 [19304, 7315, 10505, 16585],
 [19304, 7315, 9483, 16585],
 [19304, 7315, 4702],
 [19304, 7315, 2682],
 [2963, 4224, 5485],
 [11037, 8286, 6416, 18838, 9662, 17571],
 [18838, 9662, 8116, 15570, 17571],
 [6319, 11037, 2980],
 [11037, 8286, 14180],
 [11037, 8286, 12793],
 [11037, 8286, 1109],
 [11037, 8286, 4702],
 [11037, 8286, 2682],
 [11037, 8286, 6416, 6319, 11037, 2682],
 [3985, 3985, 10619],
 [15570, 3985, 9441],
 [3985, 18804, 6037],
 [3985, 17982],
 [6319, 4691, 9156],
 [6319, 4691, 17130],
 [6319, 4691, 9067],
 [3985, 3985, 15438],
 [3985, 3985, 16593],
 [15570, 11037, 8298, 17914, 14606, 1622],
 [15570, 11037, 4573, 17914, 10526],
 [15570, 11037, 12321, 16266, 1432],
 [6319, 11037, 8234, 8116, 6817],
 [15570, 15400, 3031],
 [6319, 11037, 3031],
 [6319, 11037, 4206],
 [19649, 11037, 8804],
 [6319, 11037, 19307],
 [15570, 11037, 19307],
 [6319, 11037, 15400],
 [6319, 11037, 13373],
 [6319, 11037, 7520, 18114, 3449],
 [6319, 11037, 15724],
 [19649, 11037, 6393],
 [6319, 11037, 6393],
 [6319, 11037, 1497, 6346],
 [6319, 11037, 18114, 16526],
 [15570, 11037, 5047],
 [6319, 11037, 5485],
 [6319, 11037, 1497, 3976],
 [6319, 11037, 18114, 9474],
 [6319, 11037, 13172],
 [15570, 4276, 5927, 19924, 3976],
 [6319, 11037, 17887],
 [6319, 11037, 1497, 16365, 14907],
 [6319, 11037, 18114, 16365, 14907],
 [6319, 11037, 9386],
 [6319, 11037, 19924, 18178],
 [15570, 11037, 6333],
 [6319, 11037, 6817, 5344],
 [6319, 11037, 5695],
 [6319, 11037, 19924, 2527],
 [13066, 11723],
 [12222, 3985],
 [16434, 12112],
 [12222, 3985],
 [16434, 2404],
 [28, 11196, 15570],
 [15049, 1416],
 [15049, 13172, 753],
 [13603, 13172, 753],
 [6817, 10476, 13172],
 [6817, 4407, 13172],
 [15049, 13172, 14174, 7159, 4432],
 [13603, 13172, 14174, 7159, 4432],
 [13603, 13172, 13512, 4432],
 [15049, 13172, 13512, 4432],
 [15049, 13172, 753],
 [13603, 13172, 753],
 [15049, 13172, 14174, 7159, 4432],
 [13603, 13172, 14174, 7159, 4432],
 [13603, 13172, 3055],
 [13603, 13172, 9523],
 [10381],
 [6308],
 [15967, 8205],
 [2182, 1947, 14204],
 [2182, 1947, 18888, 14204],
 [13066, 1947, 14204],
 [13066, 1947, 18888, 14204],
 [13066, 1947, 4276, 2738],
 [13066, 1947, 4195, 2738],
 [13108, 2252, 1497, 14457],
 [8032, 10127],
 [12610, 631, 7737, 4702],
 [12610, 631, 7737],
 [12610, 6393],
 [8032, 6393],
 [14060, 4702],
 [2261, 2682],
 [13108, 10810, 4702],
 [15049, 4702, 4432],
 [13603, 2682, 4432],
 [76, 7520, 6817],
 [9158, 2682],
 [14470, 4702],
 [4157, 19210],
 [9193, 4276, 4718],
 [4120, 9781],
 [893],
 [17571, 4276, 4718],
 [9193, 4276, 4718],
 [19304, 2682, 7159, 1596],
 [19304, 8116, 7159, 1596],
 [19237],
 [19304, 2682, 10441, 19237],
 [6783, 8116, 15570],
 [4478, 2404],
 [11285, 2369],
 [14238, 10547, 16587],
 [14238, 10547, 1579],
 [8205, 10547, 1579],
 [722, 1497],
 [17939, 1497],
 [12390],
 [11037, 8286, 4276, 15573],
 [4276, 2256],
 [19649, 2221],
 [19649, 7614],
 [19649, 3985, 16461],
 [19649, 9643],
 [19649, 11037, 5555],
 [19649, 11037, 6211, 4276, 5890],
 [18128, 6393],
 [9547, 6393],
 [18128, 3985],
 [9547, 2404],
 [16029],
 [1428],
 [2182, 6817, 65],
 [13066, 6817, 65],
 [2182, 7159, 14650, 7737],
 [13066, 7159, 14650, 7737],
 [13066, 11723],
 [2182, 11723],
 [12222, 10791, 11723],
 [12222, 10791, 10321, 3031],
 [2182, 7131],
 [2182, 6130],
 [13066, 6130],
 [2182, 6130],
 [13066, 6130],
 [13066, 6817],
 [2182, 6393],
 [13066, 6393],
 [2182, 15129],
 [170],
 [11761],
 [1281, 11909],
 [1281, 11791, 3985],
 [1281, 11909, 3985],
 [1281, 11791, 3985],
 [1281, 11909, 10323],
 [3311, 16359, 7520, 4702],
 [2832, 1993],
 [3311, 16359, 7520, 4702],
 [11893, 16359, 7520, 2682],
 [3311, 1497, 3976],
 [3311, 18114, 9474],
 [11893, 1497, 3976],
 [11893, 18114, 9474],
 [3311, 10323, 10567],
 [3311, 10323, 8381],
 [11893, 10323, 10567],

In [69]:
output_padding=pad_sequences(one_hot_output, maxlen=max_len_output, padding='post')
output_padding

array([[ 8369,     0,     0, ...,     0,     0,     0],
       [16781,     0,     0, ...,     0,     0,     0],
       [ 4187,     0,     0, ...,     0,     0,     0],
       ...,
       [18114, 19307, 11037, ...,  3050,     0,     0],
       [13512,  3985,  7520, ...,  7520,  9239,  4081],
       [ 8116, 17547, 17657, ..., 15863,  1318, 13129]], dtype=int32)

In [71]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, Dense, Dropout

vocab_size = len(unique_words_output) + 1  # total words in vocab
embedding_dim = 64

model = Sequential()
model.add(Embedding(input_dim=vocab_size, output_dim=embedding_dim, input_length=max_len))
model.add(Dropout(0.2))
model.add(LSTM(128, return_sequences=False))
model.add(Dense(1, activation='sigmoid'))

model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
model.summary()

/home/hammadali08/.local/lib/python3.12/site-packages/keras/src/layers/core/embedding.py:97: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(
2025-08-27 22:06:19.626127: E external/local_xla/xla/stream_executor/cuda/cuda_platform.cc:51] failed call to cuInit: INTERNAL: CUDA error: Failed call to cuInit: UNKNOWN ERROR (303)

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout (Dropout)               │ ?                      │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm (LSTM)                     │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [73]:
import tensorflow as tf
encoder_lstm = LSTM(256, return_state=True, name="encoder_lstm")
encoder_outputs, state_h, state_c = encoder_lstm(input_padding)

# Save the states as encoder_states
encoder_states = [state_h, state_c]

ValueError: Input 0 of layer "encoder_lstm" is incompatible with the layer: expected ndim=3, found ndim=2. Full shape received: (175621, 41)