In [53]:
import pandas as pd

dataset=pd.read_csv('/home/hammadali08/Personal/CSV file/eng_-french.csv')
dataset

,English words/sentences,French words/sentences
0,Hi.,Salut!
1,Run!,Cours !
2,Run!,Courez !
3,Who?,Qui ?
4,Wow!,Ça alors !
...,...,...
175616,"Top-down economics never works, said Obama. ""T...","« L'économie en partant du haut vers le bas, ç..."
175617,A carbon footprint is the amount of carbon dio...,Une empreinte carbone est la somme de pollutio...
175618,Death is something that we're often discourage...,La mort est une chose qu'on nous décourage sou...
175619,Since there are usually multiple websites on a...,Puisqu'il y a de multiples sites web sur chaqu...
175620,If someone who doesn't know your background sa...,Si quelqu'un qui ne connaît pas vos antécédent...

In [54]:
dataset = dataset.rename(columns={'English words/sentences': 'English'})
dataset= dataset.rename(columns={'French words/sentences': 'French'})
dataset

,English,French
0,Hi.,Salut!
1,Run!,Cours !
2,Run!,Courez !
3,Who?,Qui ?
4,Wow!,Ça alors !
...,...,...
175616,"Top-down economics never works, said Obama. ""T...","« L'économie en partant du haut vers le bas, ç..."
175617,A carbon footprint is the amount of carbon dio...,Une empreinte carbone est la somme de pollutio...
175618,Death is something that we're often discourage...,La mort est une chose qu'on nous décourage sou...
175619,Since there are usually multiple websites on a...,Puisqu'il y a de multiples sites web sur chaqu...
175620,If someone who doesn't know your background sa...,Si quelqu'un qui ne connaît pas vos antécédent...

In [55]:
import re
corpus = []
for i in range(0, len(dataset)):
    review = re.sub('[^a-zA-Z0-9]', ' ', dataset['English'][i])
    review = review.lower()
    review = review.split()

    review = ' '.join(review)
    corpus.append(review)

In [56]:
corpus

['hi',
 'run',
 'run',
 'who',
 'wow',
 'fire',
 'help',
 'jump',
 'stop',
 'stop',
 'stop',
 'wait',
 'wait',
 'go on',
 'go on',
 'go on',
 'hello',
 'hello',
 'i see',
 'i try',
 'i won',
 'i won',
 'i won',
 'oh no',
 'attack',
 'attack',
 'cheers',
 'cheers',
 'cheers',
 'cheers',
 'get up',
 'go now',
 'go now',
 'go now',
 'got it',
 'got it',
 'got it',
 'got it',
 'got it',
 'hop in',
 'hop in',
 'hug me',
 'hug me',
 'i fell',
 'i fell',
 'i know',
 'i left',
 'i left',
 'i lied',
 'i lost',
 'i paid',
 'i m 19',
 'i m ok',
 'i m ok',
 'listen',
 'no way',
 'no way',
 'no way',
 'no way',
 'no way',
 'no way',
 'no way',
 'no way',
 'no way',
 'really',
 'really',
 'really',
 'thanks',
 'we try',
 'we won',
 'we won',
 'we won',
 'we won',
 'ask tom',
 'awesome',
 'be calm',
 'be calm',
 'be calm',
 'be cool',
 'be fair',
 'be fair',
 'be fair',
 'be fair',
 'be fair',
 'be fair',
 'be kind',
 'be nice',
 'be nice',
 'be nice',
 'be nice',
 'be nice',
 'be nice',
 'beat it',
 'call me',
 'call me',
 'call us',
 'call us',
 'come in',
 'come in',
 'come in',
 'come in',
 'come on',
 'come on',
 'come on',
 'come on',
 'drop it',
 'drop it',
 'drop it',
 'drop it',
 'get tom',
 'get out',
 'get out',
 'get out',
 'get out',
 'get out',
 'go away',
 'go away',
 'go away',
 'go away',
 'go away',
 'go away',
 'go away',
 'go away',
 'go away',
 'go away',
 'go home',
 'go home',
 'go home',
 'go home',
 'go slow',
 'go slow',
 'goodbye',
 'goodbye',
 'hang on',
 'hang on',
 'hang on',
 'hang on',
 'he quit',
 'he quit',
 'he runs',
 'help me',
 'help me',
 'help me',
 'help us',
 'help us',
 'hold it',
 'hold on',
 'hug tom',
 'i agree',
 'i cried',
 'i dozed',
 'i dozed',
 'i drive',
 'i smoke',
 'i snore',
 'i stink',
 'i stood',
 'i stood',
 'i swore',
 'i swore',
 'i tried',
 'i tried',
 'i tried',
 'i waved',
 'i ll go',
 'i m tom',
 'i m fat',
 'i m fat',
 'i m fit',
 'i m hit',
 'i m hit',
 'i m ill',
 'i m sad',
 'i m shy',
 'i m wet',
 'i m wet',
 'it s me',
 'join us',
 'join us',
 'keep it',
 'keep it',
 'kiss me',
 'kiss me',
 'me too',
 'open up',
 'open up',
 'perfect',
 'see you',
 'see you',
 'see you',
 'see you',
 'show me',
 'show me',
 'shut up',
 'shut up',
 'shut up',
 'shut up',
 'shut up',
 'skip it',
 'so long',
 'take it',
 'take it',
 'take it',
 'take it',
 'tell me',
 'tell me',
 'tom won',
 'wake up',
 'wake up',
 'wake up',
 'wake up',
 'wake up',
 'wash up',
 'wash up',
 'we know',
 'we lost',
 'we lost',
 'we lost',
 'we lost',
 'we lost',
 'we lost',
 'we lost',
 'we lost',
 'we lost',
 'we lost',
 'welcome',
 'who won',
 'who won',
 'you run',
 'am i fat',
 'am i fat',
 'ask them',
 'ask them',
 'back off',
 'back off',
 'back off',
 'back off',
 'back off',
 'back off',
 'be a man',
 'be a man',
 'be still',
 'be still',
 'be still',
 'beats me',
 'beats me',
 'call tom',
 'call tom',
 'cheer up',
 'cool off',
 'cuff him',
 'drive on',
 'drive on',
 'drive on',
 'drive on',
 'find tom',
 'find tom',
 'fix this',
 'fix this',
 'get down',
 'get down',
 'get down',
 'get down',
 'get down',
 'get lost',
 'get lost',
 'get lost',
 'get real',
 'go ahead',
 'go ahead',
 'go ahead',
 'go ahead',
 'go ahead',
 'go ahead',
 'go ahead',
 'good job',
 'good job',
 'good job',
 'grab him',
 'grab him',
 'have fun',
 'have fun',
 'he tries',
 'he s wet',
 'help tom',
 'help tom',
 'hi guys',
 'how cute',
 'how deep',
 'how nice',
 'how nice',
 'how nice',
 'how nice',
 'hurry up',
 'hurry up',
 'hurry up',
 'hurry up',
 'i did ok',
 'i did ok',
 'i did it',
 'i did it',
 'i failed',
 'i forgot',
 'i get it',
 'i got it',
 'i got it',
 'i helped',
 'i jumped',
 'i looked',
 'i moaned',
 'i nodded',
 'i obeyed',
 'i phoned',
 'i phoned',
 'i refuse',
 'i refuse',
 'i rested',
 'i rested',
 'i saw it',
 'i saw it',
 'i sighed',
 'i stayed',
 'i stayed',
 'i talked',
 'i use it',
 'i use it',
 'i use it',
 'i ll pay',
 'i ll try',
 'i ll try',
 'i m back',
 'i m back',
 'i m bald',
 'i m busy',
 'i m busy',
 'i m calm',
 'i m cold',
 'i m cool',
 'i m cool',
 'i m deaf',
 'i m deaf',
 'i m done',
 'i m fair',
 'i m fair',
 'i m fair',
 'i m fast',
 'i m fine',
 'i m fine',
 'i m fine',
 'i m free',
 'i m free',
 'i m free',
 'i m full',
 'i m full',
 'i m game',
 'i m game',
 'i m glad',
 'i m home',
 'i m late',
 'i m lazy',
 'i m lazy',
 'i m lazy',
 'i m lazy',
 'i m okay',
 'i m okay',
 'i m rich',
 'i m safe',
 'i m sick',
 'i m sure',
 'i m sure',
 'i m sure',
 'i m sure',
 'i m tall',
 'i m thin',
 'i m tidy',
 'i m tidy',
 'i m ugly',
 'i m ugly',
 'i m weak',
 'i m well',
 'i m well',
 'i ve won',
 'i ve won',
 'it helps',
 'it hurts',
 'it works',
 'it works',
 'it s tom',
 'it s fun',
 'it s fun',
 'it s his',
 'it s his',
 'it s new',
 'it s new',
 'it s odd',
 'it s red',
 'it s sad',
 'keep out',
 'keep out',
 'kiss tom',
 'leave it',
 'leave it',
 'leave me',
 'leave us',
 'leave us',
 'let s go',
 'let s go',
 'look out',
 'look out',
 'marry me',
 'marry me',
 'may i go',
 'may i go',
 'may i go',
 'save tom',
 'save tom',
 'say what',
 'she came',
 'she died',
 'she runs',
 'sit down',
 'sit down',
 'sit down',
 'sit here',
 'sit here',
 'speak up',
 'speak up',
 'stand up',
 'stop tom',
 'stop tom',
 'taste it',
 'taste it',
 'taste it',
 'taste it',
 'tell tom',
 'tell tom',
 'terrific',
 'terrific',
 'terrific',
 'they won',
 'they won',
 'they won',
 'they won',
 'tom came',
 'tom died',
 'tom knew',
 'tom left',
 'tom left',
 'tom lied',
 'tom lies',
 'tom lost',
 'tom paid',
 'too late',
 'trust me',
 'trust me',
 'try hard',
 'try some',
 'try some',
 'try this',
 'try this',
 'use this',
 'use this',
 'use this',
 'use this',
 'warn tom',
 'warn tom',
 'watch me',
 'watch me',
 'watch us',
 'watch us',
 'we agree',
 'we ll go',
 'we re ok',
 'what for',
 'what for',
 'what fun',
 'what fun',
 'who came',
 'who died',
 'who fell',
 'who quit',
 'who s he',
 'write me',
 'write me',
 'you lost',
 'you lost',
 'after you',
 'aim fire',
 'am i late',
 'answer me',
 'be seated',
 'be seated',
 'birds fly',
 'bless you',
 'call home',
 'calm down',
 'calm down',
 'can we go',
 'can we go',
 'can we go',
 'catch tom',
 'catch tom',
 'catch him',
 'chill out',
 'come back',
 'come back',
 'come here',
 'come here',
 'come over',
 'come over',
 'come over',
 'come over',
 'come over',
 'come over',
 'come over',
 'come soon',
 'come soon',
 'cool down',
 'did i win',
 'did i win',
 'did i win',
 'do it now',
 'dogs bark',
 'dogs bark',
 'don t ask',
 'don t cry',
 'don t die',
 'don t die',
 'don t lie',
 'don t run',
 'don t run',
 'excuse me',
 'excuse me',
 'excuse me',
 'excuse me',
 'excuse me',
 'excuse me',
 'excuse me',
 'fantastic',
 'feel this',
 'feel this',
 'feel this',
 'feel this',
 'follow me',
 'follow us',
 'follow us',
 'forget it',
 'forget it',
 'forget it',
 'forget it',
 'forget it',
 'forget it',
 'forget it',
 'get a job',
 'get a job',
 'get a job',
 'get a job',
 'get ready',
 'get ready',
 'go get it',
 'go get it',
 'go inside',
 'go to bed',
 'go to bed',
 'good luck',
 'good luck',
 'grab that',
 'grab that',
 'grab that',
 'grab that',
 'grab this',
 'grab this',
 'hands off',
 'he is ill',
 'he is old',
 'he s a dj',
 'he s good',
 'he s lazy',
 'he s mine',
 'he s rich',
 'he s sexy',
 'here i am',
 'here s 5',
 'hold fire',
 'hold fire',
 'hold this',
 'hold this',
 'hold this',
 'hold this',
 'how awful',
 'how weird',
 'how s tom',
 'how s tom',
 'i am cold',
 'i am good',
 'i am okay',
 'i am sick',
 'i am sure',
 'i am sure',
 'i beg you',
 'i beg you',
 'i beg you',
 'i beg you',
 'i can run',
 'i can ski',
 'i cringed',
 'i cringed',
 'i cringed',
 'i exhaled',
 'i gave up',
 'i give in',
 'i give up',
 'i got hot',
 'i got hot',
 'i had fun',
 'i had fun',
 'i had fun',
 'i had fun',
 'i hate it',
 'i have it',
 'i hit tom',
 'i hope so',
 'i hurried',
 'i hurried',
 'i inhaled',
 'i knew it',
 'i like it',
 'i lost it',
 'i love it',
 'i love it',
 'i mean it',
 'i mean it',
 'i must go',
 'i must go',
 'i must go',
 'i must go',
 'i must go',
 'i must go',
 'i must go',
 'i must go',
 'i need it',
 'i need it',
 'i noticed',
 'i prepaid',
 'i promise',
 'i relaxed',
 'i relaxed',
 'i retired',
 'i said no',
 'i said so',
 'i saw him',
 'i saw him',
 'i saw him',
 'i saw one',
 'i saw one',
 'i saw you',
 'i saw you',
 'i saw you',
 'i saw you',
 'i saw you',
 'i saw you',
 'i saw you',
 'i saw you',
 'i see tom',
 'i shouted',
 'i tripped',
 'i tripped',
 'i want it',
 'i was new',
 'i was new',
 'i will go',
 'i woke up',
 'i woke up',
 'i d agree',
 'i d leave',
 'i ll call',
 'i ll cook',
 'i ll help',
 'i ll live',
 'i ll obey',
 'i ll pack',
 'i ll pack',
 'i ll pack',
 'i ll pass',
 'i ll quit',
 'i ll sing',
 'i ll stop',
 'i ll swim',
 'i ll talk',
 'i ll talk',
 'i ll wait',
 'i ll walk',
 'i ll work',
 'i ll work',
 'i m a cop',
 'i m a man',
 'i m alive',
 'i m alive',
 'i m alive',
 'i m alone',
 'i m alone',
 'i m angry',
 'i m angry',
 'i m armed',
 'i m armed',
 'i m awake',
 'i m blind',
 'i m broke',
 'i m clean',
 'i m clean',
 'i m crazy',
 'i m crazy',
 'i m cured',
 'i m cured',
 'i m dizzy',
 'i m drunk',
 'i m drunk',
 'i m drunk',
 'i m dying',
 'i m early',
 'i m first',
 'i m fussy',
 'i m fussy',
 'i m fussy',
 'i m going',
 'i m going',
 'i m going',
 'i m going',
 'i m loyal',
 'i m loyal',
 'i m lucky',
 'i m lucky',
 'i m lucky',
 'i m lucky',
 'i m lucky',
 'i m lying',
 'i m naked',
 'i m naked',
 'i m naked',
 'i m naked',
 'i m naked',
 'i m quiet',
 'i m ready',
 'i m ready',
 'i m ready',
 'i m right',
 'i m sober',
 'i m sorry',
 'i m sorry',
 'i m sorry',
 'i m sorry',
 'i m sorry',
 'i m sorry',
 'i m stuck',
 'i m timid',
 'i m tired',
 'i m tough',
 'i m tough',
 'i m tough',
 'i m tough',
 'i m yours',
 'i m yours',
 'i ve lost',
 'is tom ok',
 'is tom ok',
 'is it bad',
 'is it far',
 'is it far',
 'is it hot',
 'is it you',
 'is it you',
 'is it you',
 'it failed',
 'it snowed',
 'it stinks',
 'it stinks',
 'it was ok',
 'it was ok',
 'it was ok',
 'it worked',
 'it worked',
 'it s 3 30',
 'it s 8 30',
 'it s 8 30',
 'it s a tv',
 'it s cold',
 'it s cold',
 'it s dark',
 'it s dead',
 'it s dead',
 'it s dead',
 'it s done',
 'it s easy',
 'it s food',
 'it s free',
 'it s here',
 'it s here',
 'it s hers',
 'it s hers',
 'it s late',
 'it s lost',
 'it s mine',
 'it s mine',
 'it s mine',
 'it s mine',
 'it s open',
 'it s ours',
 'it s ours',
 'it s ours',
 'it s sand',
 'it s time',
 'it s time',
 'it s true',
 'it s work',
 'keep calm',
 'keep that',
 'keep that',
 'keep this',
 'keep this',
 'let it be',
 'let it be',
 'let me go',
 'let me go',
 'let me go',
 'let me go',
 'let me go',
 'let me go',
 'let me go',
 'let me go',
 'let me go',
 'let me go',
 'let me go',
 'let me go',
 'let me in',
 'let me in',
 'let s ask',
 'let s eat',
 'let s see',
 'lie still',
 'lie still',
 'lie still',
 'lie still',
 'lie still',
 'lie still',
 'look away',
 'look away',
 'look back',
 'look back',
 'look here',
 'look here',
 'loosen up',
 'loosen up',
 'loosen up',
 'loosen up',
 'loosen up',
 'move over',
 'move over',
 'move over',
 'nice shot',
 'of course',
 'of course',
 'of course',
 'of course',
 'of course',
 'oh please',
 'oh please',
 'pardon me',
 'pardon me',
 'pardon me',
 'read this',
 'say hello',
 'see above',
 'see below',
 'see below',
 'seize him',
 'seize him',
 'seriously',
 'seriously',
 'seriously',
 'she cried',
 'she cried',
 'she tried',
 'she walks',
 'she s hot',
 'she s hot',
 'sign here',
 'sign here',
 'sign this',
 'sign this',
 'slow down',
 'slow down',
 'stay away',
 'stay away',
 'stay back',
 'stay back',
 'stay calm',
 'stay calm',
 'stay calm',
 'stay calm',
 'stay calm',
 'stay down',
 'stay down',
 'stay down',
 'stay down',
 'stay here',
 'stay here',
 'stay here',
 'stay thin',
 'step back',
 'step back',
 'stop that',
 'stop that',
 'stop that',
 'stop that',
 'stop them',
 'take care',
 'take care',
 'take care',
 'take care',
 'take mine',
 'take mine',
 'take mine',
 'take mine',
 'take mine',
 'take mine',
 'take mine',
 'take mine',
 'take this',
 'take this',
 'thank you',
 'thank you',
 'that s ok',
 'that s ok',
 'that s ok',
 'that s ok',
 'that s it',
 'then what',
 'they fell',
 'they fell',
 'they left',
 'they left',
 'they lied',
 'they lied',
 'they lost',
 'they lost',
 'they swam',
 'they swam',
 'they swam',
 'they swam',
 'time s up',
 'tom cooks',
 'tom cried',
 'tom is ok',
 'tom knits',
 'tom knows',
 'tom rocks',
 'tom spoke',
 'tom waved',
 'tom works',
 'tom s fat',
 'tom s mad',
 'tom s mad',
 'tom s sad',
 'trust tom',
 'trust tom',
 'try again',
 'try again',
 'try again',
 'try it on',
 'turn left',
 'wait here',
 'wait here',
 'wait here',
 'wait here',
 'watch out',
 'watch out',
 'watch out',
 'we agreed',
 'we did it',
 'we did it',
 'we did it',
 'we forgot',
 'we saw it',
 'we saw it',
 'we smiled',
 'we talked',
 'we talked',
 'we talked',
 'we talked',
 'we talked',
 'we waited',
 'we waited',
 'we walked',
 'we walked',
 'we ll try',
 'we ll try',
 'we ll win',
 'we ll win',
 'we re hot',
 'we re sad',
 ...]

In [57]:
from nltk.tokenize import sent_tokenize
from gensim.utils import simple_preprocess
words=[]
for sent in corpus:
    sent_token=sent_tokenize(sent)
    for sent in sent_token:
        words.append(simple_preprocess(sent))   # Simple Preprcoess make it lowe r case
words

[['hi'],
 ['run'],
 ['run'],
 ['who'],
 ['wow'],
 ['fire'],
 ['help'],
 ['jump'],
 ['stop'],
 ['stop'],
 ['stop'],
 ['wait'],
 ['wait'],
 ['go', 'on'],
 ['go', 'on'],
 ['go', 'on'],
 ['hello'],
 ['hello'],
 ['see'],
 ['try'],
 ['won'],
 ['won'],
 ['won'],
 ['oh', 'no'],
 ['attack'],
 ['attack'],
 ['cheers'],
 ['cheers'],
 ['cheers'],
 ['cheers'],
 ['get', 'up'],
 ['go', 'now'],
 ['go', 'now'],
 ['go', 'now'],
 ['got', 'it'],
 ['got', 'it'],
 ['got', 'it'],
 ['got', 'it'],
 ['got', 'it'],
 ['hop', 'in'],
 ['hop', 'in'],
 ['hug', 'me'],
 ['hug', 'me'],
 ['fell'],
 ['fell'],
 ['know'],
 ['left'],
 ['left'],
 ['lied'],
 ['lost'],
 ['paid'],
 [],
 ['ok'],
 ['ok'],
 ['listen'],
 ['no', 'way'],
 ['no', 'way'],
 ['no', 'way'],
 ['no', 'way'],
 ['no', 'way'],
 ['no', 'way'],
 ['no', 'way'],
 ['no', 'way'],
 ['no', 'way'],
 ['really'],
 ['really'],
 ['really'],
 ['thanks'],
 ['we', 'try'],
 ['we', 'won'],
 ['we', 'won'],
 ['we', 'won'],
 ['we', 'won'],
 ['ask', 'tom'],
 ['awesome'],
 ['be', 'calm'],
 ['be', 'calm'],
 ['be', 'calm'],
 ['be', 'cool'],
 ['be', 'fair'],
 ['be', 'fair'],
 ['be', 'fair'],
 ['be', 'fair'],
 ['be', 'fair'],
 ['be', 'fair'],
 ['be', 'kind'],
 ['be', 'nice'],
 ['be', 'nice'],
 ['be', 'nice'],
 ['be', 'nice'],
 ['be', 'nice'],
 ['be', 'nice'],
 ['beat', 'it'],
 ['call', 'me'],
 ['call', 'me'],
 ['call', 'us'],
 ['call', 'us'],
 ['come', 'in'],
 ['come', 'in'],
 ['come', 'in'],
 ['come', 'in'],
 ['come', 'on'],
 ['come', 'on'],
 ['come', 'on'],
 ['come', 'on'],
 ['drop', 'it'],
 ['drop', 'it'],
 ['drop', 'it'],
 ['drop', 'it'],
 ['get', 'tom'],
 ['get', 'out'],
 ['get', 'out'],
 ['get', 'out'],
 ['get', 'out'],
 ['get', 'out'],
 ['go', 'away'],
 ['go', 'away'],
 ['go', 'away'],
 ['go', 'away'],
 ['go', 'away'],
 ['go', 'away'],
 ['go', 'away'],
 ['go', 'away'],
 ['go', 'away'],
 ['go', 'away'],
 ['go', 'home'],
 ['go', 'home'],
 ['go', 'home'],
 ['go', 'home'],
 ['go', 'slow'],
 ['go', 'slow'],
 ['goodbye'],
 ['goodbye'],
 ['hang', 'on'],
 ['hang', 'on'],
 ['hang', 'on'],
 ['hang', 'on'],
 ['he', 'quit'],
 ['he', 'quit'],
 ['he', 'runs'],
 ['help', 'me'],
 ['help', 'me'],
 ['help', 'me'],
 ['help', 'us'],
 ['help', 'us'],
 ['hold', 'it'],
 ['hold', 'on'],
 ['hug', 'tom'],
 ['agree'],
 ['cried'],
 ['dozed'],
 ['dozed'],
 ['drive'],
 ['smoke'],
 ['snore'],
 ['stink'],
 ['stood'],
 ['stood'],
 ['swore'],
 ['swore'],
 ['tried'],
 ['tried'],
 ['tried'],
 ['waved'],
 ['ll', 'go'],
 ['tom'],
 ['fat'],
 ['fat'],
 ['fit'],
 ['hit'],
 ['hit'],
 ['ill'],
 ['sad'],
 ['shy'],
 ['wet'],
 ['wet'],
 ['it', 'me'],
 ['join', 'us'],
 ['join', 'us'],
 ['keep', 'it'],
 ['keep', 'it'],
 ['kiss', 'me'],
 ['kiss', 'me'],
 ['me', 'too'],
 ['open', 'up'],
 ['open', 'up'],
 ['perfect'],
 ['see', 'you'],
 ['see', 'you'],
 ['see', 'you'],
 ['see', 'you'],
 ['show', 'me'],
 ['show', 'me'],
 ['shut', 'up'],
 ['shut', 'up'],
 ['shut', 'up'],
 ['shut', 'up'],
 ['shut', 'up'],
 ['skip', 'it'],
 ['so', 'long'],
 ['take', 'it'],
 ['take', 'it'],
 ['take', 'it'],
 ['take', 'it'],
 ['tell', 'me'],
 ['tell', 'me'],
 ['tom', 'won'],
 ['wake', 'up'],
 ['wake', 'up'],
 ['wake', 'up'],
 ['wake', 'up'],
 ['wake', 'up'],
 ['wash', 'up'],
 ['wash', 'up'],
 ['we', 'know'],
 ['we', 'lost'],
 ['we', 'lost'],
 ['we', 'lost'],
 ['we', 'lost'],
 ['we', 'lost'],
 ['we', 'lost'],
 ['we', 'lost'],
 ['we', 'lost'],
 ['we', 'lost'],
 ['we', 'lost'],
 ['welcome'],
 ['who', 'won'],
 ['who', 'won'],
 ['you', 'run'],
 ['am', 'fat'],
 ['am', 'fat'],
 ['ask', 'them'],
 ['ask', 'them'],
 ['back', 'off'],
 ['back', 'off'],
 ['back', 'off'],
 ['back', 'off'],
 ['back', 'off'],
 ['back', 'off'],
 ['be', 'man'],
 ['be', 'man'],
 ['be', 'still'],
 ['be', 'still'],
 ['be', 'still'],
 ['beats', 'me'],
 ['beats', 'me'],
 ['call', 'tom'],
 ['call', 'tom'],
 ['cheer', 'up'],
 ['cool', 'off'],
 ['cuff', 'him'],
 ['drive', 'on'],
 ['drive', 'on'],
 ['drive', 'on'],
 ['drive', 'on'],
 ['find', 'tom'],
 ['find', 'tom'],
 ['fix', 'this'],
 ['fix', 'this'],
 ['get', 'down'],
 ['get', 'down'],
 ['get', 'down'],
 ['get', 'down'],
 ['get', 'down'],
 ['get', 'lost'],
 ['get', 'lost'],
 ['get', 'lost'],
 ['get', 'real'],
 ['go', 'ahead'],
 ['go', 'ahead'],
 ['go', 'ahead'],
 ['go', 'ahead'],
 ['go', 'ahead'],
 ['go', 'ahead'],
 ['go', 'ahead'],
 ['good', 'job'],
 ['good', 'job'],
 ['good', 'job'],
 ['grab', 'him'],
 ['grab', 'him'],
 ['have', 'fun'],
 ['have', 'fun'],
 ['he', 'tries'],
 ['he', 'wet'],
 ['help', 'tom'],
 ['help', 'tom'],
 ['hi', 'guys'],
 ['how', 'cute'],
 ['how', 'deep'],
 ['how', 'nice'],
 ['how', 'nice'],
 ['how', 'nice'],
 ['how', 'nice'],
 ['hurry', 'up'],
 ['hurry', 'up'],
 ['hurry', 'up'],
 ['hurry', 'up'],
 ['did', 'ok'],
 ['did', 'ok'],
 ['did', 'it'],
 ['did', 'it'],
 ['failed'],
 ['forgot'],
 ['get', 'it'],
 ['got', 'it'],
 ['got', 'it'],
 ['helped'],
 ['jumped'],
 ['looked'],
 ['moaned'],
 ['nodded'],
 ['obeyed'],
 ['phoned'],
 ['phoned'],
 ['refuse'],
 ['refuse'],
 ['rested'],
 ['rested'],
 ['saw', 'it'],
 ['saw', 'it'],
 ['sighed'],
 ['stayed'],
 ['stayed'],
 ['talked'],
 ['use', 'it'],
 ['use', 'it'],
 ['use', 'it'],
 ['ll', 'pay'],
 ['ll', 'try'],
 ['ll', 'try'],
 ['back'],
 ['back'],
 ['bald'],
 ['busy'],
 ['busy'],
 ['calm'],
 ['cold'],
 ['cool'],
 ['cool'],
 ['deaf'],
 ['deaf'],
 ['done'],
 ['fair'],
 ['fair'],
 ['fair'],
 ['fast'],
 ['fine'],
 ['fine'],
 ['fine'],
 ['free'],
 ['free'],
 ['free'],
 ['full'],
 ['full'],
 ['game'],
 ['game'],
 ['glad'],
 ['home'],
 ['late'],
 ['lazy'],
 ['lazy'],
 ['lazy'],
 ['lazy'],
 ['okay'],
 ['okay'],
 ['rich'],
 ['safe'],
 ['sick'],
 ['sure'],
 ['sure'],
 ['sure'],
 ['sure'],
 ['tall'],
 ['thin'],
 ['tidy'],
 ['tidy'],
 ['ugly'],
 ['ugly'],
 ['weak'],
 ['well'],
 ['well'],
 ['ve', 'won'],
 ['ve', 'won'],
 ['it', 'helps'],
 ['it', 'hurts'],
 ['it', 'works'],
 ['it', 'works'],
 ['it', 'tom'],
 ['it', 'fun'],
 ['it', 'fun'],
 ['it', 'his'],
 ['it', 'his'],
 ['it', 'new'],
 ['it', 'new'],
 ['it', 'odd'],
 ['it', 'red'],
 ['it', 'sad'],
 ['keep', 'out'],
 ['keep', 'out'],
 ['kiss', 'tom'],
 ['leave', 'it'],
 ['leave', 'it'],
 ['leave', 'me'],
 ['leave', 'us'],
 ['leave', 'us'],
 ['let', 'go'],
 ['let', 'go'],
 ['look', 'out'],
 ['look', 'out'],
 ['marry', 'me'],
 ['marry', 'me'],
 ['may', 'go'],
 ['may', 'go'],
 ['may', 'go'],
 ['save', 'tom'],
 ['save', 'tom'],
 ['say', 'what'],
 ['she', 'came'],
 ['she', 'died'],
 ['she', 'runs'],
 ['sit', 'down'],
 ['sit', 'down'],
 ['sit', 'down'],
 ['sit', 'here'],
 ['sit', 'here'],
 ['speak', 'up'],
 ['speak', 'up'],
 ['stand', 'up'],
 ['stop', 'tom'],
 ['stop', 'tom'],
 ['taste', 'it'],
 ['taste', 'it'],
 ['taste', 'it'],
 ['taste', 'it'],
 ['tell', 'tom'],
 ['tell', 'tom'],
 ['terrific'],
 ['terrific'],
 ['terrific'],
 ['they', 'won'],
 ['they', 'won'],
 ['they', 'won'],
 ['they', 'won'],
 ['tom', 'came'],
 ['tom', 'died'],
 ['tom', 'knew'],
 ['tom', 'left'],
 ['tom', 'left'],
 ['tom', 'lied'],
 ['tom', 'lies'],
 ['tom', 'lost'],
 ['tom', 'paid'],
 ['too', 'late'],
 ['trust', 'me'],
 ['trust', 'me'],
 ['try', 'hard'],
 ['try', 'some'],
 ['try', 'some'],
 ['try', 'this'],
 ['try', 'this'],
 ['use', 'this'],
 ['use', 'this'],
 ['use', 'this'],
 ['use', 'this'],
 ['warn', 'tom'],
 ['warn', 'tom'],
 ['watch', 'me'],
 ['watch', 'me'],
 ['watch', 'us'],
 ['watch', 'us'],
 ['we', 'agree'],
 ['we', 'll', 'go'],
 ['we', 're', 'ok'],
 ['what', 'for'],
 ['what', 'for'],
 ['what', 'fun'],
 ['what', 'fun'],
 ['who', 'came'],
 ['who', 'died'],
 ['who', 'fell'],
 ['who', 'quit'],
 ['who', 'he'],
 ['write', 'me'],
 ['write', 'me'],
 ['you', 'lost'],
 ['you', 'lost'],
 ['after', 'you'],
 ['aim', 'fire'],
 ['am', 'late'],
 ['answer', 'me'],
 ['be', 'seated'],
 ['be', 'seated'],
 ['birds', 'fly'],
 ['bless', 'you'],
 ['call', 'home'],
 ['calm', 'down'],
 ['calm', 'down'],
 ['can', 'we', 'go'],
 ['can', 'we', 'go'],
 ['can', 'we', 'go'],
 ['catch', 'tom'],
 ['catch', 'tom'],
 ['catch', 'him'],
 ['chill', 'out'],
 ['come', 'back'],
 ['come', 'back'],
 ['come', 'here'],
 ['come', 'here'],
 ['come', 'over'],
 ['come', 'over'],
 ['come', 'over'],
 ['come', 'over'],
 ['come', 'over'],
 ['come', 'over'],
 ['come', 'over'],
 ['come', 'soon'],
 ['come', 'soon'],
 ['cool', 'down'],
 ['did', 'win'],
 ['did', 'win'],
 ['did', 'win'],
 ['do', 'it', 'now'],
 ['dogs', 'bark'],
 ['dogs', 'bark'],
 ['don', 'ask'],
 ['don', 'cry'],
 ['don', 'die'],
 ['don', 'die'],
 ['don', 'lie'],
 ['don', 'run'],
 ['don', 'run'],
 ['excuse', 'me'],
 ['excuse', 'me'],
 ['excuse', 'me'],
 ['excuse', 'me'],
 ['excuse', 'me'],
 ['excuse', 'me'],
 ['excuse', 'me'],
 ['fantastic'],
 ['feel', 'this'],
 ['feel', 'this'],
 ['feel', 'this'],
 ['feel', 'this'],
 ['follow', 'me'],
 ['follow', 'us'],
 ['follow', 'us'],
 ['forget', 'it'],
 ['forget', 'it'],
 ['forget', 'it'],
 ['forget', 'it'],
 ['forget', 'it'],
 ['forget', 'it'],
 ['forget', 'it'],
 ['get', 'job'],
 ['get', 'job'],
 ['get', 'job'],
 ['get', 'job'],
 ['get', 'ready'],
 ['get', 'ready'],
 ['go', 'get', 'it'],
 ['go', 'get', 'it'],
 ['go', 'inside'],
 ['go', 'to', 'bed'],
 ['go', 'to', 'bed'],
 ['good', 'luck'],
 ['good', 'luck'],
 ['grab', 'that'],
 ['grab', 'that'],
 ['grab', 'that'],
 ['grab', 'that'],
 ['grab', 'this'],
 ['grab', 'this'],
 ['hands', 'off'],
 ['he', 'is', 'ill'],
 ['he', 'is', 'old'],
 ['he', 'dj'],
 ['he', 'good'],
 ['he', 'lazy'],
 ['he', 'mine'],
 ['he', 'rich'],
 ['he', 'sexy'],
 ['here', 'am'],
 ['here'],
 ['hold', 'fire'],
 ['hold', 'fire'],
 ['hold', 'this'],
 ['hold', 'this'],
 ['hold', 'this'],
 ['hold', 'this'],
 ['how', 'awful'],
 ['how', 'weird'],
 ['how', 'tom'],
 ['how', 'tom'],
 ['am', 'cold'],
 ['am', 'good'],
 ['am', 'okay'],
 ['am', 'sick'],
 ['am', 'sure'],
 ['am', 'sure'],
 ['beg', 'you'],
 ['beg', 'you'],
 ['beg', 'you'],
 ['beg', 'you'],
 ['can', 'run'],
 ['can', 'ski'],
 ['cringed'],
 ['cringed'],
 ['cringed'],
 ['exhaled'],
 ['gave', 'up'],
 ['give', 'in'],
 ['give', 'up'],
 ['got', 'hot'],
 ['got', 'hot'],
 ['had', 'fun'],
 ['had', 'fun'],
 ['had', 'fun'],
 ['had', 'fun'],
 ['hate', 'it'],
 ['have', 'it'],
 ['hit', 'tom'],
 ['hope', 'so'],
 ['hurried'],
 ['hurried'],
 ['inhaled'],
 ['knew', 'it'],
 ['like', 'it'],
 ['lost', 'it'],
 ['love', 'it'],
 ['love', 'it'],
 ['mean', 'it'],
 ['mean', 'it'],
 ['must', 'go'],
 ['must', 'go'],
 ['must', 'go'],
 ['must', 'go'],
 ['must', 'go'],
 ['must', 'go'],
 ['must', 'go'],
 ['must', 'go'],
 ['need', 'it'],
 ['need', 'it'],
 ['noticed'],
 ['prepaid'],
 ['promise'],
 ['relaxed'],
 ['relaxed'],
 ['retired'],
 ['said', 'no'],
 ['said', 'so'],
 ['saw', 'him'],
 ['saw', 'him'],
 ['saw', 'him'],
 ['saw', 'one'],
 ['saw', 'one'],
 ['saw', 'you'],
 ['saw', 'you'],
 ['saw', 'you'],
 ['saw', 'you'],
 ['saw', 'you'],
 ['saw', 'you'],
 ['saw', 'you'],
 ['saw', 'you'],
 ['see', 'tom'],
 ['shouted'],
 ['tripped'],
 ['tripped'],
 ['want', 'it'],
 ['was', 'new'],
 ['was', 'new'],
 ['will', 'go'],
 ['woke', 'up'],
 ['woke', 'up'],
 ['agree'],
 ['leave'],
 ['ll', 'call'],
 ['ll', 'cook'],
 ['ll', 'help'],
 ['ll', 'live'],
 ['ll', 'obey'],
 ['ll', 'pack'],
 ['ll', 'pack'],
 ['ll', 'pack'],
 ['ll', 'pass'],
 ['ll', 'quit'],
 ['ll', 'sing'],
 ['ll', 'stop'],
 ['ll', 'swim'],
 ['ll', 'talk'],
 ['ll', 'talk'],
 ['ll', 'wait'],
 ['ll', 'walk'],
 ['ll', 'work'],
 ['ll', 'work'],
 ['cop'],
 ['man'],
 ['alive'],
 ['alive'],
 ['alive'],
 ['alone'],
 ['alone'],
 ['angry'],
 ['angry'],
 ['armed'],
 ['armed'],
 ['awake'],
 ['blind'],
 ['broke'],
 ['clean'],
 ['clean'],
 ['crazy'],
 ['crazy'],
 ['cured'],
 ['cured'],
 ['dizzy'],
 ['drunk'],
 ['drunk'],
 ['drunk'],
 ['dying'],
 ['early'],
 ['first'],
 ['fussy'],
 ['fussy'],
 ['fussy'],
 ['going'],
 ['going'],
 ['going'],
 ['going'],
 ['loyal'],
 ['loyal'],
 ['lucky'],
 ['lucky'],
 ['lucky'],
 ['lucky'],
 ['lucky'],
 ['lying'],
 ['naked'],
 ['naked'],
 ['naked'],
 ['naked'],
 ['naked'],
 ['quiet'],
 ['ready'],
 ['ready'],
 ['ready'],
 ['right'],
 ['sober'],
 ['sorry'],
 ['sorry'],
 ['sorry'],
 ['sorry'],
 ['sorry'],
 ['sorry'],
 ['stuck'],
 ['timid'],
 ['tired'],
 ['tough'],
 ['tough'],
 ['tough'],
 ['tough'],
 ['yours'],
 ['yours'],
 ['ve', 'lost'],
 ['is', 'tom', 'ok'],
 ['is', 'tom', 'ok'],
 ['is', 'it', 'bad'],
 ['is', 'it', 'far'],
 ['is', 'it', 'far'],
 ['is', 'it', 'hot'],
 ['is', 'it', 'you'],
 ['is', 'it', 'you'],
 ['is', 'it', 'you'],
 ['it', 'failed'],
 ['it', 'snowed'],
 ['it', 'stinks'],
 ['it', 'stinks'],
 ['it', 'was', 'ok'],
 ['it', 'was', 'ok'],
 ['it', 'was', 'ok'],
 ['it', 'worked'],
 ['it', 'worked'],
 ['it'],
 ['it'],
 ['it'],
 ['it', 'tv'],
 ['it', 'cold'],
 ['it', 'cold'],
 ['it', 'dark'],
 ['it', 'dead'],
 ['it', 'dead'],
 ['it', 'dead'],
 ['it', 'done'],
 ['it', 'easy'],
 ['it', 'food'],
 ['it', 'free'],
 ['it', 'here'],
 ['it', 'here'],
 ['it', 'hers'],
 ['it', 'hers'],
 ['it', 'late'],
 ['it', 'lost'],
 ['it', 'mine'],
 ['it', 'mine'],
 ['it', 'mine'],
 ['it', 'mine'],
 ['it', 'open'],
 ['it', 'ours'],
 ['it', 'ours'],
 ['it', 'ours'],
 ['it', 'sand'],
 ['it', 'time'],
 ['it', 'time'],
 ['it', 'true'],
 ['it', 'work'],
 ['keep', 'calm'],
 ['keep', 'that'],
 ['keep', 'that'],
 ['keep', 'this'],
 ['keep', 'this'],
 ['let', 'it', 'be'],
 ['let', 'it', 'be'],
 ['let', 'me', 'go'],
 ['let', 'me', 'go'],
 ['let', 'me', 'go'],
 ['let', 'me', 'go'],
 ['let', 'me', 'go'],
 ['let', 'me', 'go'],
 ['let', 'me', 'go'],
 ['let', 'me', 'go'],
 ['let', 'me', 'go'],
 ['let', 'me', 'go'],
 ['let', 'me', 'go'],
 ['let', 'me', 'go'],
 ['let', 'me', 'in'],
 ['let', 'me', 'in'],
 ['let', 'ask'],
 ['let', 'eat'],
 ['let', 'see'],
 ['lie', 'still'],
 ['lie', 'still'],
 ['lie', 'still'],
 ['lie', 'still'],
 ['lie', 'still'],
 ['lie', 'still'],
 ['look', 'away'],
 ['look', 'away'],
 ['look', 'back'],
 ['look', 'back'],
 ['look', 'here'],
 ['look', 'here'],
 ['loosen', 'up'],
 ['loosen', 'up'],
 ['loosen', 'up'],
 ['loosen', 'up'],
 ['loosen', 'up'],
 ['move', 'over'],
 ['move', 'over'],
 ['move', 'over'],
 ['nice', 'shot'],
 ['of', 'course'],
 ['of', 'course'],
 ['of', 'course'],
 ['of', 'course'],
 ['of', 'course'],
 ['oh', 'please'],
 ['oh', 'please'],
 ['pardon', 'me'],
 ['pardon', 'me'],
 ['pardon', 'me'],
 ['read', 'this'],
 ['say', 'hello'],
 ['see', 'above'],
 ['see', 'below'],
 ['see', 'below'],
 ['seize', 'him'],
 ['seize', 'him'],
 ['seriously'],
 ['seriously'],
 ['seriously'],
 ['she', 'cried'],
 ['she', 'cried'],
 ['she', 'tried'],
 ['she', 'walks'],
 ['she', 'hot'],
 ['she', 'hot'],
 ['sign', 'here'],
 ['sign', 'here'],
 ['sign', 'this'],
 ['sign', 'this'],
 ['slow', 'down'],
 ['slow', 'down'],
 ['stay', 'away'],
 ['stay', 'away'],
 ['stay', 'back'],
 ['stay', 'back'],
 ['stay', 'calm'],
 ['stay', 'calm'],
 ['stay', 'calm'],
 ['stay', 'calm'],
 ['stay', 'calm'],
 ['stay', 'down'],
 ['stay', 'down'],
 ['stay', 'down'],
 ['stay', 'down'],
 ['stay', 'here'],
 ['stay', 'here'],
 ['stay', 'here'],
 ['stay', 'thin'],
 ['step', 'back'],
 ['step', 'back'],
 ['stop', 'that'],
 ['stop', 'that'],
 ['stop', 'that'],
 ['stop', 'that'],
 ['stop', 'them'],
 ['take', 'care'],
 ['take', 'care'],
 ['take', 'care'],
 ['take', 'care'],
 ['take', 'mine'],
 ['take', 'mine'],
 ['take', 'mine'],
 ['take', 'mine'],
 ['take', 'mine'],
 ['take', 'mine'],
 ['take', 'mine'],
 ['take', 'mine'],
 ['take', 'this'],
 ['take', 'this'],
 ['thank', 'you'],
 ['thank', 'you'],
 ['that', 'ok'],
 ['that', 'ok'],
 ['that', 'ok'],
 ['that', 'ok'],
 ['that', 'it'],
 ['then', 'what'],
 ['they', 'fell'],
 ['they', 'fell'],
 ['they', 'left'],
 ['they', 'left'],
 ['they', 'lied'],
 ['they', 'lied'],
 ['they', 'lost'],
 ['they', 'lost'],
 ['they', 'swam'],
 ['they', 'swam'],
 ['they', 'swam'],
 ['they', 'swam'],
 ['time', 'up'],
 ['tom', 'cooks'],
 ['tom', 'cried'],
 ['tom', 'is', 'ok'],
 ['tom', 'knits'],
 ['tom', 'knows'],
 ['tom', 'rocks'],
 ['tom', 'spoke'],
 ['tom', 'waved'],
 ['tom', 'works'],
 ['tom', 'fat'],
 ['tom', 'mad'],
 ['tom', 'mad'],
 ['tom', 'sad'],
 ['trust', 'tom'],
 ['trust', 'tom'],
 ['try', 'again'],
 ['try', 'again'],
 ['try', 'again'],
 ['try', 'it', 'on'],
 ['turn', 'left'],
 ['wait', 'here'],
 ['wait', 'here'],
 ['wait', 'here'],
 ['wait', 'here'],
 ['watch', 'out'],
 ['watch', 'out'],
 ['watch', 'out'],
 ['we', 'agreed'],
 ['we', 'did', 'it'],
 ['we', 'did', 'it'],
 ['we', 'did', 'it'],
 ['we', 'forgot'],
 ['we', 'saw', 'it'],
 ['we', 'saw', 'it'],
 ['we', 'smiled'],
 ['we', 'talked'],
 ['we', 'talked'],
 ['we', 'talked'],
 ['we', 'talked'],
 ['we', 'talked'],
 ['we', 'waited'],
 ['we', 'waited'],
 ['we', 'walked'],
 ['we', 'walked'],
 ['we', 'll', 'try'],
 ['we', 'll', 'try'],
 ['we', 'll', 'win'],
 ['we', 'll', 'win'],
 ['we', 're', 'hot'],
 ['we', 're', 'sad'],
 ...]

In [58]:
all_words = [word for sentence in words for word in sentence]

# Get unique words
unique_words_input = set(all_words)

# Count them
print("Number of unique words:", len(unique_words_input))
print("Unique words:", unique_words_input)

Number of unique words: 13871

In [59]:
max_len_input = max(len(sentence) for sentence in words)
longest_sentence = max(words, key=len)

print("Max number of words:", max_len_input)
print("Sentence with max words:", longest_sentence)

Max number of words: 41
Sentence with max words: ['since', 'there', 'are', 'usually', 'multiple', 'websites', 'on', 'any', 'given', 'topic', 'usually', 'just', 'click', 'the', 'back', 'button', 'when', 'arrive', 'on', 'any', 'webpage', 'that', 'has', 'pop', 'up', 'advertising', 'just', 'go', 'to', 'the', 'next', 'page', 'found', 'by', 'google', 'and', 'hope', 'for', 'something', 'less', 'irritating']

## Input Encoding:

In [60]:
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [61]:
one_hot_input=[one_hot(word, len(unique_words_input)) for word in corpus]
one_hot_input

[[495],
 [2869],
 [2869],
 [12120],
 [3221],
 [4017],
 [4468],
 [11524],
 [4528],
 [4528],
 [4528],
 [10306],
 [10306],
 [2011, 376],
 [2011, 376],
 [2011, 376],
 [4914],
 [4914],
 [13011, 7014],
 [13011, 6254],
 [13011, 12022],
 [13011, 12022],
 [13011, 12022],
 [8987, 6556],
 [4399],
 [4399],
 [11804],
 [11804],
 [11804],
 [11804],
 [3158, 8687],
 [2011, 5444],
 [2011, 5444],
 [2011, 5444],
 [710, 5092],
 [710, 5092],
 [710, 5092],
 [710, 5092],
 [710, 5092],
 [10230, 8496],
 [10230, 8496],
 [10036, 2979],
 [10036, 2979],
 [13011, 12656],
 [13011, 12656],
 [13011, 10828],
 [13011, 11011],
 [13011, 11011],
 [13011, 4331],
 [13011, 10208],
 [13011, 1458],
 [13011, 11702, 5725],
 [13011, 11702, 9241],
 [13011, 11702, 9241],
 [5577],
 [6556, 12345],
 [6556, 12345],
 [6556, 12345],
 [6556, 12345],
 [6556, 12345],
 [6556, 12345],
 [6556, 12345],
 [6556, 12345],
 [6556, 12345],
 [12421],
 [12421],
 [12421],
 [9972],
 [8350, 6254],
 [8350, 12022],
 [8350, 12022],
 [8350, 12022],
 [8350, 12022],
 [8361, 263],
 [13572],
 [878, 6972],
 [878, 6972],
 [878, 6972],
 [878, 6124],
 [878, 5757],
 [878, 5757],
 [878, 5757],
 [878, 5757],
 [878, 5757],
 [878, 5757],
 [878, 4040],
 [878, 10566],
 [878, 10566],
 [878, 10566],
 [878, 10566],
 [878, 10566],
 [878, 10566],
 [7102, 5092],
 [3202, 2979],
 [3202, 2979],
 [3202, 5076],
 [3202, 5076],
 [8137, 8496],
 [8137, 8496],
 [8137, 8496],
 [8137, 8496],
 [8137, 376],
 [8137, 376],
 [8137, 376],
 [8137, 376],
 [44, 5092],
 [44, 5092],
 [44, 5092],
 [44, 5092],
 [3158, 263],
 [3158, 7627],
 [3158, 7627],
 [3158, 7627],
 [3158, 7627],
 [3158, 7627],
 [2011, 6048],
 [2011, 6048],
 [2011, 6048],
 [2011, 6048],
 [2011, 6048],
 [2011, 6048],
 [2011, 6048],
 [2011, 6048],
 [2011, 6048],
 [2011, 6048],
 [2011, 13476],
 [2011, 13476],
 [2011, 13476],
 [2011, 13476],
 [2011, 12548],
 [2011, 12548],
 [4147],
 [4147],
 [3783, 376],
 [3783, 376],
 [3783, 376],
 [3783, 376],
 [1870, 12651],
 [1870, 12651],
 [1870, 301],
 [4468, 2979],
 [4468, 2979],
 [4468, 2979],
 [4468, 5076],
 [4468, 5076],
 [11039, 5092],
 [11039, 376],
 [10036, 263],
 [13011, 2126],
 [13011, 2784],
 [13011, 1790],
 [13011, 1790],
 [13011, 9425],
 [13011, 880],
 [13011, 7360],
 [13011, 11421],
 [13011, 13637],
 [13011, 13637],
 [13011, 758],
 [13011, 758],
 [13011, 10634],
 [13011, 10634],
 [13011, 10634],
 [13011, 12769],
 [13011, 13311, 2011],
 [13011, 11702, 263],
 [13011, 11702, 6537],
 [13011, 11702, 6537],
 [13011, 11702, 1673],
 [13011, 11702, 9684],
 [13011, 11702, 9684],
 [13011, 11702, 7547],
 [13011, 11702, 12583],
 [13011, 11702, 7372],
 [13011, 11702, 12934],
 [13011, 11702, 12934],
 [5092, 9855, 2979],
 [6446, 5076],
 [6446, 5076],
 [11099, 5092],
 [11099, 5092],
 [4743, 2979],
 [4743, 2979],
 [2979, 7482],
 [968, 8687],
 [968, 8687],
 [12829],
 [7014, 1166],
 [7014, 1166],
 [7014, 1166],
 [7014, 1166],
 [12181, 2979],
 [12181, 2979],
 [9796, 8687],
 [9796, 8687],
 [9796, 8687],
 [9796, 8687],
 [9796, 8687],
 [8452, 5092],
 [13645, 8605],
 [5484, 5092],
 [5484, 5092],
 [5484, 5092],
 [5484, 5092],
 [8468, 2979],
 [8468, 2979],
 [263, 12022],
 [2580, 8687],
 [2580, 8687],
 [2580, 8687],
 [2580, 8687],
 [2580, 8687],
 [13423, 8687],
 [13423, 8687],
 [8350, 10828],
 [8350, 10208],
 [8350, 10208],
 [8350, 10208],
 [8350, 10208],
 [8350, 10208],
 [8350, 10208],
 [8350, 10208],
 [8350, 10208],
 [8350, 10208],
 [8350, 10208],
 [13056],
 [12120, 12022],
 [12120, 12022],
 [1166, 2869],
 [12536, 13011, 6537],
 [12536, 13011, 6537],
 [8361, 13850],
 [8361, 13850],
 [9613, 8588],
 [9613, 8588],
 [9613, 8588],
 [9613, 8588],
 [9613, 8588],
 [9613, 8588],
 [878, 4717, 11518],
 [878, 4717, 11518],
 [878, 7726],
 [878, 7726],
 [878, 7726],
 [3057, 2979],
 [3057, 2979],
 [3202, 263],
 [3202, 263],
 [12028, 8687],
 [6124, 8588],
 [8410, 8638],
 [9425, 376],
 [9425, 376],
 [9425, 376],
 [9425, 376],
 [2731, 263],
 [2731, 263],
 [2131, 7764],
 [2131, 7764],
 [3158, 5453],
 [3158, 5453],
 [3158, 5453],
 [3158, 5453],
 [3158, 5453],
 [3158, 10208],
 [3158, 10208],
 [3158, 10208],
 [3158, 11775],
 [2011, 12693],
 [2011, 12693],
 [2011, 12693],
 [2011, 12693],
 [2011, 12693],
 [2011, 12693],
 [2011, 12693],
 [10787, 8449],
 [10787, 8449],
 [10787, 8449],
 [2030, 8638],
 [2030, 8638],
 [3268, 11217],
 [3268, 11217],
 [1870, 5207],
 [1870, 9855, 12934],
 [4468, 263],
 [4468, 263],
 [495, 12927],
 [3840, 11896],
 [3840, 12341],
 [3840, 10566],
 [3840, 10566],
 [3840, 10566],
 [3840, 10566],
 [13112, 8687],
 [13112, 8687],
 [13112, 8687],
 [13112, 8687],
 [13011, 1308, 9241],
 [13011, 1308, 9241],
 [13011, 1308, 5092],
 [13011, 1308, 5092],
 [13011, 11308],
 [13011, 11162],
 [13011, 3158, 5092],
 [13011, 710, 5092],
 [13011, 710, 5092],
 [13011, 7163],
 [13011, 846],
 [13011, 6824],
 [13011, 9671],
 [13011, 2491],
 [13011, 7742],
 [13011, 6762],
 [13011, 6762],
 [13011, 4147],
 [13011, 4147],
 [13011, 11843],
 [13011, 11843],
 [13011, 12505, 5092],
 [13011, 12505, 5092],
 [13011, 1690],
 [13011, 9634],
 [13011, 9634],
 [13011, 9564],
 [13011, 4702, 5092],
 [13011, 4702, 5092],
 [13011, 4702, 5092],
 [13011, 13311, 7032],
 [13011, 13311, 6254],
 [13011, 13311, 6254],
 [13011, 11702, 9613],
 [13011, 11702, 9613],
 [13011, 11702, 9596],
 [13011, 11702, 784],
 [13011, 11702, 784],
 [13011, 11702, 6972],
 [13011, 11702, 8982],
 [13011, 11702, 6124],
 [13011, 11702, 6124],
 [13011, 11702, 12598],
 [13011, 11702, 12598],
 [13011, 11702, 6675],
 [13011, 11702, 5757],
 [13011, 11702, 5757],
 [13011, 11702, 5757],
 [13011, 11702, 10260],
 [13011, 11702, 5256],
 [13011, 11702, 5256],
 [13011, 11702, 5256],
 [13011, 11702, 11089],
 [13011, 11702, 11089],
 [13011, 11702, 11089],
 [13011, 11702, 13501],
 [13011, 11702, 13501],
 [13011, 11702, 3234],
 [13011, 11702, 3234],
 [13011, 11702, 11430],
 [13011, 11702, 13476],
 [13011, 11702, 8617],
 [13011, 11702, 1938],
 [13011, 11702, 1938],
 [13011, 11702, 1938],
 [13011, 11702, 1938],
 [13011, 11702, 40],
 [13011, 11702, 40],
 [13011, 11702, 8847],
 [13011, 11702, 9888],
 [13011, 11702, 10115],
 [13011, 11702, 5656],
 [13011, 11702, 5656],
 [13011, 11702, 5656],
 [13011, 11702, 5656],
 [13011, 11702, 1462],
 [13011, 11702, 2335],
 [13011, 11702, 3870],
 [13011, 11702, 3870],
 [13011, 11702, 3480],
 [13011, 11702, 3480],
 [13011, 11702, 3814],
 [13011, 11702, 3883],
 [13011, 11702, 3883],
 [13011, 5939, 12022],
 [13011, 5939, 12022],
 [5092, 11293],
 [5092, 1084],
 [5092, 13010],
 [5092, 13010],
 [5092, 9855, 263],
 [5092, 9855, 11217],
 [5092, 9855, 11217],
 [5092, 9855, 11523],
 [5092, 9855, 11523],
 [5092, 9855, 7007],
 [5092, 9855, 7007],
 [5092, 9855, 4792],
 [5092, 9855, 3215],
 [5092, 9855, 12583],
 [11099, 7627],
 [11099, 7627],
 [4743, 263],
 [7350, 5092],
 [7350, 5092],
 [7350, 2979],
 [7350, 5076],
 [7350, 5076],
 [10494, 9855, 2011],
 [10494, 9855, 2011],
 [11942, 7627],
 [11942, 7627],
 [9363, 2979],
 [9363, 2979],
 [8633, 13011, 2011],
 [8633, 13011, 2011],
 [8633, 13011, 2011],
 [2059, 263],
 [2059, 263],
 [2419, 9223],
 [3038, 12526],
 [3038, 8822],
 [3038, 301],
 [10270, 5453],
 [10270, 5453],
 [10270, 5453],
 [10270, 6965],
 [10270, 6965],
 [3331, 8687],
 [3331, 8687],
 [1825, 8687],
 [4528, 263],
 [4528, 263],
 [4686, 5092],
 [4686, 5092],
 [4686, 5092],
 [4686, 5092],
 [8468, 263],
 [8468, 263],
 [12206],
 [12206],
 [12206],
 [5587, 12022],
 [5587, 12022],
 [5587, 12022],
 [5587, 12022],
 [263, 12526],
 [263, 8822],
 [263, 6479],
 [263, 11011],
 [263, 11011],
 [263, 4331],
 [263, 6599],
 [263, 10208],
 [263, 1458],
 [7482, 8617],
 [10769, 2979],
 [10769, 2979],
 [6254, 5365],
 [6254, 3389],
 [6254, 3389],
 [6254, 7764],
 [6254, 7764],
 [4702, 7764],
 [4702, 7764],
 [4702, 7764],
 [4702, 7764],
 [4794, 263],
 [4794, 263],
 [9212, 2979],
 [9212, 2979],
 [9212, 5076],
 [9212, 5076],
 [8350, 2126],
 [8350, 13311, 2011],
 [8350, 1729, 9241],
 [9223, 4752],
 [9223, 4752],
 [9223, 11217],
 [9223, 11217],
 [12120, 12526],
 [12120, 8822],
 [12120, 12656],
 [12120, 12651],
 [12120, 9855, 1870],
 [585, 2979],
 [585, 2979],
 [1166, 10208],
 [1166, 10208],
 [8200, 1166],
 [10280, 4017],
 [12536, 13011, 8617],
 [13150, 2979],
 [878, 9633],
 [878, 9633],
 [1620, 240],
 [1973, 1166],
 [3202, 13476],
 [6972, 5453],
 [6972, 5453],
 [7414, 8350, 2011],
 [7414, 8350, 2011],
 [7414, 8350, 2011],
 [5738, 263],
 [5738, 263],
 [5738, 8638],
 [5481, 7627],
 [8137, 9613],
 [8137, 9613],
 [8137, 6965],
 [8137, 6965],
 [8137, 9273],
 [8137, 9273],
 [8137, 9273],
 [8137, 9273],
 [8137, 9273],
 [8137, 9273],
 [8137, 9273],
 [8137, 6029],
 [8137, 6029],
 [6124, 5453],
 [1308, 13011, 9593],
 [1308, 13011, 9593],
 [1308, 13011, 9593],
 [1792, 5092, 5444],
 [12711, 4912],
 [12711, 4912],
 [6947, 1108, 8361],
 [6947, 1108, 8971],
 [6947, 1108, 11840],
 [6947, 1108, 11840],
 [6947, 1108, 5822],
 [6947, 1108, 2869],
 [6947, 1108, 2869],
 [5112, 2979],
 [5112, 2979],
 [5112, 2979],
 [5112, 2979],
 [5112, 2979],
 [5112, 2979],
 [5112, 2979],
 [1325],
 [4577, 7764],
 [4577, 7764],
 [4577, 7764],
 [4577, 7764],
 [447, 2979],
 [447, 5076],
 [447, 5076],
 [38, 5092],
 [38, 5092],
 [38, 5092],
 [38, 5092],
 [38, 5092],
 [38, 5092],
 [38, 5092],
 [3158, 4717, 8449],
 [3158, 4717, 8449],
 [3158, 4717, 8449],
 [3158, 4717, 8449],
 [3158, 12034],
 [3158, 12034],
 [2011, 3158, 5092],
 [2011, 3158, 5092],
 [2011, 8715],
 [2011, 753, 779],
 [2011, 753, 779],
 [10787, 8042],
 [10787, 8042],
 [2030, 1817],
 [2030, 1817],
 [2030, 1817],
 [2030, 1817],
 [2030, 7764],
 [2030, 7764],
 [4452, 8588],
 [1870, 9998, 7547],
 [1870, 9998, 7994],
 [1870, 9855, 4717, 13527],
 [1870, 9855, 10787],
 [1870, 9855, 1938],
 [1870, 9855, 11882],
 [1870, 9855, 8847],
 [1870, 9855, 1888],
 [6965, 13011, 12536],
 [6965, 9855, 5470],
 [11039, 4017],
 [11039, 4017],
 [11039, 7764],
 [11039, 7764],
 [11039, 7764],
 [11039, 7764],
 [3840, 8786],
 [3840, 13832],
 [3840, 9855, 263],
 [3840, 9855, 263],
 [13011, 12536, 8982],
 [13011, 12536, 10787],
 [13011, 12536, 40],
 [13011, 12536, 10115],
 [13011, 12536, 5656],
 [13011, 12536, 5656],
 [13011, 8036, 1166],
 [13011, 8036, 1166],
 [13011, 8036, 1166],
 [13011, 8036, 1166],
 [13011, 7414, 2869],
 [13011, 7414, 1666],
 [13011, 10190],
 [13011, 10190],
 [13011, 10190],
 [13011, 6390],
 [13011, 13852, 8687],
 [13011, 12196, 8496],
 [13011, 12196, 8687],
 [13011, 710, 4046],
 [13011, 710, 4046],
 [13011, 4865, 11217],
 [13011, 4865, 11217],
 [13011, 4865, 11217],
 [13011, 4865, 11217],
 [13011, 12641, 5092],
 [13011, 3268, 5092],
 [13011, 9684, 263],
 [13011, 6276, 13645],
 [13011, 5516],
 [13011, 5516],
 [13011, 11293],
 [13011, 6479, 5092],
 [13011, 67, 5092],
 [13011, 10208, 5092],
 [13011, 8703, 5092],
 [13011, 8703, 5092],
 [13011, 12575, 5092],
 [13011, 12575, 5092],
 [13011, 13732, 2011],
 [13011, 13732, 2011],
 [13011, 13732, 2011],
 [13011, 13732, 2011],
 [13011, 13732, 2011],
 [13011, 13732, 2011],
 [13011, 13732, 2011],
 [13011, 13732, 2011],
 [13011, 3927, 5092],
 [13011, 3927, 5092],
 [13011, 7145],
 [13011, 11764],
 [13011, 10511],
 [13011, 9580],
 [13011, 9580],
 [13011, 4415],
 [13011, 8959, 6556],
 [13011, 8959, 13645],
 [13011, 12505, 8638],
 [13011, 12505, 8638],
 [13011, 12505, 8638],
 [13011, 12505, 3691],
 [13011, 12505, 3691],
 [13011, 12505, 1166],
 [13011, 12505, 1166],
 [13011, 12505, 1166],
 [13011, 12505, 1166],
 [13011, 12505, 1166],
 [13011, 12505, 1166],
 [13011, 12505, 1166],
 [13011, 12505, 1166],
 [13011, 7014, 263],
 [13011, 911],
 [13011, 1422],
 [13011, 1422],
 [13011, 9, 5092],
 [13011, 13297, 7007],
 [13011, 13297, 7007],
 [13011, 2564, 2011],
 [13011, 6100, 8687],
 [13011, 6100, 8687],
 [13011, 6921, 2126],
 [13011, 6921, 7350],
 [13011, 13311, 3202],
 [13011, 13311, 6459],
 [13011, 13311, 4468],
 [13011, 13311, 4058],
 [13011, 13311, 7299],
 [13011, 13311, 2412],
 [13011, 13311, 2412],
 [13011, 13311, 2412],
 [13011, 13311, 5130],
 [13011, 13311, 12651],
 [13011, 13311, 8803],
 [13011, 13311, 4528],
 [13011, 13311, 11469],
 [13011, 13311, 12408],
 [13011, 13311, 12408],
 [13011, 13311, 10306],
 [13011, 13311, 7047],
 [13011, 13311, 9581],
 [13011, 13311, 9581],
 [13011, 11702, 4717, 6456],
 [13011, 11702, 4717, 11518],
 [13011, 11702, 5303],
 [13011, 11702, 5303],
 [13011, 11702, 5303],
 [13011, 11702, 3673],
 [13011, 11702, 3673],
 [13011, 11702, 4466],
 [13011, 11702, 4466],
 [13011, 11702, 12177],
 [13011, 11702, 12177],
 [13011, 11702, 5638],
 [13011, 11702, 4195],
 [13011, 11702, 8358],
 [13011, 11702, 1329],
 [13011, 11702, 1329],
 [13011, 11702, 13547],
 [13011, 11702, 13547],
 [13011, 11702, 4719],
 [13011, 11702, 4719],
 [13011, 11702, 2105],
 [13011, 11702, 1181],
 [13011, 11702, 1181],
 [13011, 11702, 1181],
 [13011, 11702, 9043],
 [13011, 11702, 12349],
 [13011, 11702, 5373],
 [13011, 11702, 9077],
 [13011, 11702, 9077],
 [13011, 11702, 9077],
 [13011, 11702, 5419],
 [13011, 11702, 5419],
 [13011, 11702, 5419],
 [13011, 11702, 5419],
 [13011, 11702, 7443],
 [13011, 11702, 7443],
 [13011, 11702, 3090],
 [13011, 11702, 3090],
 [13011, 11702, 3090],
 [13011, 11702, 3090],
 [13011, 11702, 3090],
 [13011, 11702, 12770],
 [13011, 11702, 12762],
 [13011, 11702, 12762],
 [13011, 11702, 12762],
 [13011, 11702, 12762],
 [13011, 11702, 12762],
 [13011, 11702, 9780],
 [13011, 11702, 12034],
 [13011, 11702, 12034],
 [13011, 11702, 12034],
 [13011, 11702, 7997],
 [13011, 11702, 11159],
 [13011, 11702, 7167],
 [13011, 11702, 7167],
 [13011, 11702, 7167],
 [13011, 11702, 7167],
 [13011, 11702, 7167],
 [13011, 11702, 7167],
 [13011, 11702, 10494],
 [13011, 11702, 1485],
 [13011, 11702, 2271],
 [13011, 11702, 6527],
 [13011, 11702, 6527],
 [13011, 11702, 6527],
 [13011, 11702, 6527],
 [13011, 11702, 5853],
 [13011, 11702, 5853],
 [13011, 5939, 10208],
 [9998, 263, 9241],
 [9998, 263, 9241],
 [9998, 5092, 10503],
 [9998, 5092, 3397],
 [9998, 5092, 3397],
 [9998, 5092, 4046],
 [9998, 5092, 1166],
 [9998, 5092, 1166],
 [9998, 5092, 1166],
 [5092, 11308],
 [5092, 10237],
 [5092, 1826],
 [5092, 1826],
 [5092, 13297, 9241],
 [5092, 13297, 9241],
 [5092, 13297, 9241],
 [5092, 6203],
 [5092, 6203],
 [5092, 9855, 2208, 8429],
 [5092, 9855, 6907, 8429],
 [5092, 9855, 6907, 8429],
 [5092, 9855, 4717, 4781],
 [5092, 9855, 8982],
 [5092, 9855, 8982],
 [5092, 9855, 3861],
 [5092, 9855, 8269],
 [5092, 9855, 8269],
 [5092, 9855, 8269],
 [5092, 9855, 6675],
 [5092, 9855, 8],
 [5092, 9855, 517],
 [5092, 9855, 11089],
 [5092, 9855, 6965],
 [5092, 9855, 6965],
 [5092, 9855, 13303],
 [5092, 9855, 13303],
 [5092, 9855, 8617],
 [5092, 9855, 10208],
 [5092, 9855, 11882],
 [5092, 9855, 11882],
 [5092, 9855, 11882],
 [5092, 9855, 11882],
 [5092, 9855, 968],
 [5092, 9855, 3141],
 [5092, 9855, 3141],
 [5092, 9855, 3141],
 [5092, 9855, 6469],
 [5092, 9855, 10102],
 [5092, 9855, 10102],
 [5092, 9855, 10288],
 [5092, 9855, 9581],
 [11099, 6972],
 [11099, 1817],
 [11099, 1817],
 [11099, 7764],
 [11099, 7764],
 [10494, 5092, 878],
 [10494, 5092, 878],
 [10494, 2979, 2011],
 [10494, 2979, 2011],
 [10494, 2979, 2011],
 [10494, 2979, 2011],
 [10494, 2979, 2011],
 [10494, 2979, 2011],
 [10494, 2979, 2011],
 [10494, 2979, 2011],
 [10494, 2979, 2011],
 [10494, 2979, 2011],
 [10494, 2979, 2011],
 [10494, 2979, 2011],
 [10494, 2979, 8496],
 [10494, 2979, 8496],
 [10494, 9855, 8361],
 [10494, 9855, 885],
 [10494, 9855, 7014],
 [5822, 7726],
 [5822, 7726],
 [5822, 7726],
 [5822, 7726],
 [5822, 7726],
 [5822, 7726],
 [11942, 6048],
 [11942, 6048],
 [11942, 9613],
 [11942, 9613],
 [11942, 6965],
 [11942, 6965],
 [12058, 8687],
 [12058, 8687],
 [12058, 8687],
 [12058, 8687],
 [12058, 8687],
 [7679, 9273],
 [7679, 9273],
 [7679, 9273],
 [10566, 11941],
 [11031, 4143],
 [11031, 4143],
 [11031, 4143],
 [11031, 4143],
 [11031, 4143],
 [8987, 10959],
 [8987, 10959],
 [5984, 2979],
 [5984, 2979],
 [5984, 2979],
 [5992, 7764],
 [2419, 4914],
 [7014, 1243],
 [7014, 13728],
 [7014, 13728],
 [2146, 8638],
 [2146, 8638],
 [12444],
 [12444],
 [12444],
 [3038, 2784],
 [3038, 2784],
 [3038, 10634],
 [3038, 12036],
 [3038, 9855, 4046],
 [3038, 9855, 4046],
 [432, 6965],
 [432, 6965],
 [432, 7764],
 [432, 7764],
 [12548, 5453],
 [12548, 5453],
 [8578, 6048],
 [8578, 6048],
 [8578, 9613],
 [8578, 9613],
 [8578, 6972],
 [8578, 6972],
 [8578, 6972],
 [8578, 6972],
 [8578, 6972],
 [8578, 5453],
 [8578, 5453],
 [8578, 5453],
 [8578, 5453],
 [8578, 6965],
 [8578, 6965],
 [8578, 6965],
 [8578, 2335],
 [4905, 9613],
 [4905, 9613],
 [4528, 1817],
 [4528, 1817],
 [4528, 1817],
 [4528, 1817],
 [4528, 13850],
 [5484, 11457],
 [5484, 11457],
 [5484, 11457],
 [5484, 11457],
 [5484, 11882],
 [5484, 11882],
 [5484, 11882],
 [5484, 11882],
 [5484, 11882],
 [5484, 11882],
 [5484, 11882],
 [5484, 11882],
 [5484, 7764],
 [5484, 7764],
 [2345, 1166],
 [2345, 1166],
 [1817, 9855, 9241],
 [1817, 9855, 9241],
 [1817, 9855, 9241],
 [1817, 9855, 9241],
 [1817, 9855, 5092],
 [9182, 9223],
 [5587, 12656],
 [5587, 12656],
 [5587, 11011],
 [5587, 11011],
 [5587, 4331],
 [5587, 4331],
 [5587, 10208],
 [5587, 10208],
 [5587, 13687],
 [5587, 13687],
 [5587, 13687],
 [5587, 13687],
 [10102, 9855, 8687],
 [263, 11311],
 [263, 2784],
 [263, 9998, 9241],
 [263, 6072],
 [263, 7543],
 [263, 56],
 [263, 13404],
 [263, 12769],
 [263, 13010],
 [263, 9855, 6537],
 [263, 9855, 11867],
 [263, 9855, 11867],
 [263, 9855, 12583],
 [10769, 263],
 [10769, 263],
 [6254, 5945],
 [6254, 5945],
 [6254, 5945],
 [6254, 5092, 376],
 [2551, 11011],
 [10306, 6965],
 [10306, 6965],
 [10306, 6965],
 [10306, 6965],
 [9212, 7627],
 [9212, 7627],
 [9212, 7627],
 [8350, 6249],
 [8350, 1308, 5092],
 [8350, 1308, 5092],
 [8350, 1308, 5092],
 [8350, 11162],
 [8350, 12505, 5092],
 [8350, 12505, 5092],
 [8350, 7777],
 [8350, 9564],
 [8350, 9564],
 [8350, 9564],
 [8350, 9564],
 [8350, 9564],
 [8350, 1514],
 [8350, 1514],
 [8350, 10002],
 [8350, 10002],
 [8350, 13311, 6254],
 [8350, 13311, 6254],
 [8350, 13311, 9593],
 [8350, 13311, 9593],
 [8350, 1729, 4046],
 [8350, 1729, 12583],
 ...]

In [62]:
input_padding=pad_sequences(one_hot_input, maxlen=max_len_input, padding='post')
input_padding

array([[  495,     0,     0, ...,     0,     0,     0],
       [ 2869,     0,     0, ...,     0,     0,     0],
       [ 2869,     0,     0, ...,     0,     0,     0],
       ...,
       [ 2630,  9998,  4806, ...,  2149,     0,     0],
       [12335,  3346,  4219, ...,  4806,  2195,  5664],
       [  544,  7547,  5965, ...,  4717,  2377,   677]], dtype=int32)

In [94]:

from keras.layers import Embedding, LSTM, Input

encoder_inputs = Input(shape=(None,))
embedding_layer = Embedding(input_dim=len(unique_words_input), output_dim=256)
encoder_embeddings = embedding_layer(encoder_inputs)
encoder_outputs, state_h, state_c = LSTM(256, return_state=True)(encoder_embeddings)

(None, None)

# Output Preprocessing

In [64]:
corpus1 = []
for i in range(0, len(dataset)):
    review = re.sub('[^a-zA-Z0-9]', ' ', dataset['French'][i])
    review = review.lower()
    review = review.split()

    review = ' '.join(review)
    corpus1.append(review)

In [65]:
decoder_input_data = ["<start> " + txt + "" for txt in corpus1]
decoder_target_data= ["" + txt + " <end>" for txt in corpus1]
decoder_input_data

['<start> salut',
 '<start> cours',
 '<start> courez',
 '<start> qui',
 '<start> a alors',
 '<start> au feu',
 '<start> l aide',
 '<start> saute',
 '<start> a suffit',
 '<start> stop',
 '<start> arr te toi',
 '<start> attends',
 '<start> attendez',
 '<start> poursuis',
 '<start> continuez',
 '<start> poursuivez',
 '<start> bonjour',
 '<start> salut',
 '<start> je comprends',
 '<start> j essaye',
 '<start> j ai gagn',
 '<start> je l ai emport',
 '<start> j ai gagn',
 '<start> oh non',
 '<start> attaque',
 '<start> attaquez',
 '<start> sant',
 '<start> votre sant',
 '<start> merci',
 '<start> tchin tchin',
 '<start> l ve toi',
 '<start> va maintenant',
 '<start> allez y maintenant',
 '<start> vas y maintenant',
 '<start> j ai pig',
 '<start> compris',
 '<start> pig',
 '<start> compris',
 '<start> t as capt',
 '<start> monte',
 '<start> montez',
 '<start> serre moi dans tes bras',
 '<start> serrez moi dans vos bras',
 '<start> je suis tomb e',
 '<start> je suis tomb',
 '<start> je sais',
 '<start> je suis parti',
 '<start> je suis partie',
 '<start> j ai menti',
 '<start> j ai perdu',
 '<start> j ai pay',
 '<start> j ai 19 ans',
 '<start> je vais bien',
 '<start> a va',
 '<start> coutez',
 '<start> c est pas possible',
 '<start> impossible',
 '<start> en aucun cas',
 '<start> sans fa ons',
 '<start> c est hors de question',
 '<start> il n en est pas question',
 '<start> c est exclu',
 '<start> en aucune mani re',
 '<start> hors de question',
 '<start> vraiment',
 '<start> vrai',
 '<start> ah bon',
 '<start> merci',
 '<start> on essaye',
 '<start> nous avons gagn',
 '<start> nous gagn mes',
 '<start> nous l avons emport',
 '<start> nous l emport mes',
 '<start> demande tom',
 '<start> fantastique',
 '<start> sois calme',
 '<start> soyez calme',
 '<start> soyez calmes',
 '<start> sois d tendu',
 '<start> sois juste',
 '<start> soyez juste',
 '<start> soyez justes',
 '<start> sois quitable',
 '<start> soyez quitable',
 '<start> soyez quitables',
 '<start> sois gentil',
 '<start> sois gentil',
 '<start> sois gentille',
 '<start> soyez gentil',
 '<start> soyez gentille',
 '<start> soyez gentils',
 '<start> soyez gentilles',
 '<start> d gage',
 '<start> appelle moi',
 '<start> appellez moi',
 '<start> appelle nous',
 '<start> appelez nous',
 '<start> entrez',
 '<start> entre',
 '<start> entre',
 '<start> entrez',
 '<start> allez',
 '<start> allez',
 '<start> viens',
 '<start> venez',
 '<start> laisse tomber',
 '<start> laissez tomber',
 '<start> laisse le tomber',
 '<start> laissez le tomber',
 '<start> va chercher tom',
 '<start> sortez',
 '<start> sors',
 '<start> sortez',
 '<start> sors',
 '<start> casse toi',
 '<start> d gage',
 '<start> pars',
 '<start> va te faire foutre',
 '<start> pars',
 '<start> d gage',
 '<start> fous le camp',
 '<start> pars d ici',
 '<start> va t en',
 '<start> disparais',
 '<start> allez vous en',
 '<start> rentrez la maison',
 '<start> rentre la maison',
 '<start> rentre chez toi',
 '<start> rentrez chez vous',
 '<start> va doucement',
 '<start> allez doucement',
 '<start> adieu',
 '<start> la revoyure',
 '<start> attends un peu',
 '<start> attendez un peu',
 '<start> tiens bon',
 '<start> tenez bon',
 '<start> il laissa tomber',
 '<start> il a laiss tomber',
 '<start> il court',
 '<start> aide moi',
 '<start> aide moi',
 '<start> aidez moi',
 '<start> aidez nous',
 '<start> aide nous',
 '<start> ne bouge plus',
 '<start> ne quittez pas',
 '<start> fais un c lin tom',
 '<start> je suis du m me avis',
 '<start> j ai pleur',
 '<start> je me suis assoupi',
 '<start> je me suis assoupie',
 '<start> je conduis',
 '<start> je fume',
 '<start> je ronfle',
 '<start> je pue',
 '<start> je me suis tenu debout',
 '<start> je me suis tenue debout',
 '<start> j ai promis',
 '<start> j ai jur',
 '<start> j essayai',
 '<start> j ai essay',
 '<start> j ai tent',
 '<start> j ai fait signe',
 '<start> j irai',
 '<start> je suis tom',
 '<start> je suis gras',
 '<start> je suis gros',
 '<start> je suis en forme',
 '<start> je suis touch',
 '<start> je suis touch e',
 '<start> je suis malade',
 '<start> je suis triste',
 '<start> je suis timide',
 '<start> je suis mouill',
 '<start> je suis mouill e',
 '<start> c est bibi',
 '<start> joignez vous',
 '<start> joignez vous nous',
 '<start> garde le',
 '<start> gardez le',
 '<start> embrasse moi',
 '<start> embrassez moi',
 '<start> moi aussi',
 '<start> ouvre moi',
 '<start> ouvre',
 '<start> parfait',
 '<start> plus tard',
 '<start> bient t',
 '<start> la prochaine',
 '<start> plus',
 '<start> montre moi',
 '<start> montrez moi',
 '<start> taisez vous',
 '<start> ferme la',
 '<start> tais toi',
 '<start> ferme la',
 '<start> la ferme',
 '<start> pas grave',
 '<start> plus tard',
 '<start> prends le',
 '<start> prenez le',
 '<start> prends le',
 '<start> prenez le',
 '<start> dis moi',
 '<start> dites moi',
 '<start> tom a gagn',
 '<start> r veille toi',
 '<start> r veille toi',
 '<start> r veillez vous',
 '<start> r veille toi',
 '<start> r veillez vous',
 '<start> lave toi',
 '<start> lavez vous',
 '<start> nous savons',
 '<start> nous perd mes',
 '<start> nous avons perdu',
 '<start> nous f mes battus',
 '<start> nous f mes battues',
 '<start> nous f mes d faits',
 '<start> nous f mes d faites',
 '<start> nous avons t d faits',
 '<start> nous avons t d faites',
 '<start> nous avons t battus',
 '<start> nous avons t battues',
 '<start> bienvenue',
 '<start> qui a gagn',
 '<start> qui l a emport',
 '<start> tu cours',
 '<start> suis je gros',
 '<start> suis je grosse',
 '<start> demande leur',
 '<start> demandez leur',
 '<start> recule',
 '<start> reculez',
 '<start> recule',
 '<start> reculez',
 '<start> retire toi',
 '<start> retirez vous',
 '<start> sois un homme',
 '<start> soyez un homme',
 '<start> sois calme',
 '<start> soyez calme',
 '<start> soyez calmes',
 '<start> aucune id e',
 '<start> j en sais foutre rien',
 '<start> appelle tom',
 '<start> appelez tom',
 '<start> courage',
 '<start> d tends toi',
 '<start> menottez le',
 '<start> avance',
 '<start> avancez',
 '<start> continue rouler',
 '<start> continuez rouler',
 '<start> trouve tom',
 '<start> trouvez tom',
 '<start> r parez ceci',
 '<start> r pare a',
 '<start> l che toi',
 '<start> descends',
 '<start> descendez',
 '<start> l che toi',
 '<start> l chez vous',
 '<start> va voir ailleurs si j y suis',
 '<start> d gage',
 '<start> va au diable',
 '<start> sois r aliste',
 '<start> passe devant',
 '<start> vas y',
 '<start> avance',
 '<start> vas y',
 '<start> poursuis',
 '<start> passe devant',
 '<start> vas y',
 '<start> bien jou',
 '<start> bon boulot',
 '<start> beau travail',
 '<start> attrape le',
 '<start> attrapez le',
 '<start> amuse toi bien',
 '<start> amusez vous bien',
 '<start> il essaye',
 '<start> il est mouill',
 '<start> aide tom',
 '<start> aidez tom',
 '<start> salut les mecs',
 '<start> comme c est mignon',
 '<start> quelle profondeur',
 '<start> comme c est chouette',
 '<start> comme c est gentil',
 '<start> c est du joli',
 '<start> comme c est agr able',
 '<start> d p che toi',
 '<start> grouille',
 '<start> pressez vous',
 '<start> fi a',
 '<start> je m en suis bien sorti',
 '<start> je m en suis bien sortie',
 '<start> je l ai fait',
 '<start> c est moi qui l ai fait',
 '<start> j ai chou',
 '<start> j ai oubli',
 '<start> j ai compris',
 '<start> j ai compris',
 '<start> j ai capt',
 '<start> j ai aid',
 '<start> j ai saut',
 '<start> j ai regard',
 '<start> j ai r l',
 '<start> j ai fait signe de la t te',
 '<start> j ai ob i',
 '<start> je t l phonai',
 '<start> j ai t l phon',
 '<start> je refuse',
 '<start> je le refuse',
 '<start> je me suis repos',
 '<start> je me suis repos e',
 '<start> je l ai vu',
 '<start> je l ai vu',
 '<start> j ai soupir',
 '<start> je suis rest',
 '<start> je suis rest e',
 '<start> j ai parl',
 '<start> je l utilise',
 '<start> j en fais usage',
 '<start> je m en sers',
 '<start> je paierai',
 '<start> je vais essayer',
 '<start> j essaierai',
 '<start> je suis revenu',
 '<start> me revoil',
 '<start> je suis chauve',
 '<start> je suis occup',
 '<start> je suis occup e',
 '<start> je suis calme',
 '<start> j ai froid',
 '<start> je suis d tendu',
 '<start> je suis d tendue',
 '<start> je suis sourd',
 '<start> je suis sourde',
 '<start> j en ai fini',
 '<start> je suis juste',
 '<start> j ai la peau claire',
 '<start> j ai le teint clair',
 '<start> je suis rapide',
 '<start> tout va bien',
 '<start> je vais bien',
 '<start> a va',
 '<start> je suis libre',
 '<start> je suis libre',
 '<start> je suis disponible',
 '<start> je suis repu',
 '<start> je suis rassasi',
 '<start> j en suis',
 '<start> je suis de la partie',
 '<start> je suis content',
 '<start> je suis chez moi',
 '<start> je suis en retard',
 '<start> je suis paresseux',
 '<start> je suis fain ant',
 '<start> je suis paresseuse',
 '<start> je suis fain ante',
 '<start> je vais bien',
 '<start> je me porte bien',
 '<start> je suis riche',
 '<start> je suis en s curit',
 '<start> je suis malade',
 '<start> j en suis certain',
 '<start> je suis certain',
 '<start> j en suis s r',
 '<start> j en suis s re',
 '<start> je suis grande',
 '<start> je suis mince',
 '<start> je suis ordonn',
 '<start> je suis ordonn e',
 '<start> je suis laid',
 '<start> je suis laide',
 '<start> je suis faible',
 '<start> je vais bien',
 '<start> je me porte bien',
 '<start> j ai gagn',
 '<start> je l ai emport',
 '<start> a aide',
 '<start> a fait mal',
 '<start> elle marche',
 '<start> a fonctionne',
 '<start> c est tom',
 '<start> c est marrant',
 '<start> c est rigolo',
 '<start> c est le sien',
 '<start> c est la sienne',
 '<start> c est nouveau',
 '<start> c est neuf',
 '<start> c est bizarre',
 '<start> il est rouge',
 '<start> c est triste',
 '<start> d fense d entrer',
 '<start> n entrez pas',
 '<start> embrasse tom',
 '<start> laisse tomber',
 '<start> laissez tomber',
 '<start> laissez moi',
 '<start> laisse nous',
 '<start> laissez nous',
 '<start> allons y',
 '<start> allons y',
 '<start> attention',
 '<start> regarde donc',
 '<start> pouse moi',
 '<start> pousez moi',
 '<start> puis je partir',
 '<start> puis je y aller',
 '<start> puis je m y rendre',
 '<start> sauve tom',
 '<start> sauvez tom',
 '<start> de quoi',
 '<start> elle est venue',
 '<start> elle est morte',
 '<start> elle court',
 '<start> assieds toi',
 '<start> asseyez vous',
 '<start> assieds toi',
 '<start> assieds toi ici',
 '<start> asseyez vous ici',
 '<start> parle plus fort',
 '<start> parlez plus fort',
 '<start> l ve toi',
 '<start> arr te tom',
 '<start> stoppez tom',
 '<start> go te le',
 '<start> go te la',
 '<start> go tez le',
 '<start> go tez la',
 '<start> dis le tom',
 '<start> informez en tom',
 '<start> g nial',
 '<start> excellent',
 '<start> formidable',
 '<start> ils gagn rent',
 '<start> elles gagn rent',
 '<start> ils ont gagn',
 '<start> elles ont gagn',
 '<start> tom est venu',
 '<start> tom est mort',
 '<start> tom savait',
 '<start> tom est parti',
 '<start> tom partit',
 '<start> tom a menti',
 '<start> tom ment',
 '<start> tom a perdu',
 '<start> tom a pay',
 '<start> trop tard',
 '<start> faites moi confiance',
 '<start> fais moi confiance',
 '<start> fais un effort',
 '<start> essaies en',
 '<start> essayez en',
 '<start> essaie ceci',
 '<start> essayez ceci',
 '<start> utilise ceci',
 '<start> utilisez ceci',
 '<start> emploie ceci',
 '<start> employez ceci',
 '<start> avertis tom',
 '<start> pr viens tom',
 '<start> regarde moi',
 '<start> regardez moi',
 '<start> regardez nous',
 '<start> regarde nous',
 '<start> nous sommes d accord',
 '<start> nous irons',
 '<start> nous allons bien',
 '<start> pour quoi faire',
 '<start> quoi bon',
 '<start> qu est ce qu on s est marr s',
 '<start> qu est ce qu on s est marr es',
 '<start> qui est venu',
 '<start> qui est mort',
 '<start> qui est tomb',
 '<start> qui d missionne',
 '<start> qui est il',
 '<start> cris moi',
 '<start> crivez moi',
 '<start> tu as perdu',
 '<start> vous avez perdu',
 '<start> apr s vous',
 '<start> en joue feu',
 '<start> suis je en retard',
 '<start> r pondez moi',
 '<start> assieds toi',
 '<start> asseyez vous',
 '<start> les oiseaux volent',
 '<start> tes souhaits',
 '<start> appelle la maison',
 '<start> calmez vous',
 '<start> calme toi',
 '<start> pouvons nous partir',
 '<start> pouvons nous nous en aller',
 '<start> pouvons nous y aller',
 '<start> attrape tom',
 '<start> attrapez tom',
 '<start> rattrape le',
 '<start> calme toi',
 '<start> reviens',
 '<start> revenez',
 '<start> viens ici',
 '<start> venez l',
 '<start> viens',
 '<start> venez',
 '<start> venez ici',
 '<start> viens chez nous',
 '<start> venez chez nous',
 '<start> viens chez moi',
 '<start> venez chez moi',
 '<start> viens bient t',
 '<start> venez bient t',
 '<start> calmez vous',
 '<start> ai je gagn',
 '<start> l ai je emport',
 '<start> est ce moi qui ai gagn',
 '<start> faites le maintenant',
 '<start> des chiens aboient',
 '<start> les chiens aboient',
 '<start> ne demande pas',
 '<start> ne pleure pas',
 '<start> ne meurs pas',
 '<start> ne mourez pas',
 '<start> ne mens pas',
 '<start> ne courez pas',
 '<start> ne cours pas',
 '<start> excuse moi',
 '<start> excusez moi',
 '<start> pardon',
 '<start> je vous demande pardon',
 '<start> pla t il',
 '<start> plait il',
 '<start> pardon',
 '<start> fantastique',
 '<start> sens a',
 '<start> sentez a',
 '<start> touche a',
 '<start> touchez a',
 '<start> suis moi',
 '<start> suis nous',
 '<start> suivez nous',
 '<start> oublie',
 '<start> oublie le',
 '<start> oubliez',
 '<start> oubliez le',
 '<start> laisse tomber',
 '<start> oublie',
 '<start> oublie le',
 '<start> trouve un emploi',
 '<start> trouve un boulot',
 '<start> trouvez un emploi',
 '<start> trouvez un boulot',
 '<start> pr pare toi',
 '<start> pr parez vous',
 '<start> va le chercher',
 '<start> allez le chercher',
 '<start> entrez',
 '<start> va au lit',
 '<start> allez au lit',
 '<start> bonne chance',
 '<start> bonne chance',
 '<start> attrape a',
 '<start> attrapez a',
 '<start> saisis toi de a',
 '<start> saisissez vous de a',
 '<start> attrape a',
 '<start> attrapez a',
 '<start> pas touche',
 '<start> il est malade',
 '<start> il est vieux',
 '<start> il est dj',
 '<start> il est bon',
 '<start> il est paresseux',
 '<start> il est moi',
 '<start> il est riche',
 '<start> il est sexy',
 '<start> me voici',
 '<start> voil cinq dollars',
 '<start> halte au feu',
 '<start> cessez le feu',
 '<start> tiens a',
 '<start> tenez a',
 '<start> tenez ceci',
 '<start> tiens ceci',
 '<start> c est affreux',
 '<start> comme c est bizarre',
 '<start> comment tom va t il',
 '<start> comment va tom',
 '<start> j ai froid',
 '<start> je suis bon',
 '<start> je vais bien',
 '<start> je suis malade',
 '<start> je suis s r',
 '<start> je suis certain',
 '<start> je vous en prie',
 '<start> je vous en conjure',
 '<start> je vous en supplie',
 '<start> je te prie',
 '<start> je sais courir',
 '<start> je sais skier',
 '<start> j eus un mouvement de recul',
 '<start> j ai eu un mouvement de recul',
 '<start> je suis rentr en moi m me',
 '<start> j ai expir',
 '<start> j ai abandonn',
 '<start> je donne ma langue au chat',
 '<start> j abandonne',
 '<start> je me suis mis avoir chaud',
 '<start> je me suis mise avoir chaud',
 '<start> je me suis amus',
 '<start> je me suis amus e',
 '<start> je me suis marr',
 '<start> je me suis marr e',
 '<start> je d teste a',
 '<start> je l ai',
 '<start> j ai frapp tom',
 '<start> j esp re bien',
 '<start> je me suis d p ch',
 '<start> je me suis d p ch e',
 '<start> j ai inspir',
 '<start> je le savais',
 '<start> j aime a',
 '<start> je l ai perdu',
 '<start> j adore a',
 '<start> j adore a',
 '<start> je suis s rieux',
 '<start> je suis s rieux',
 '<start> je dois y aller',
 '<start> il faut que j y aille',
 '<start> il me faut y aller',
 '<start> il me faut partir',
 '<start> il me faut m en aller',
 '<start> je dois partir',
 '<start> je dois m en aller',
 '<start> il faut que je m en aille',
 '<start> j en ai besoin',
 '<start> il me le faut',
 '<start> j ai remarqu',
 '<start> j ai pay d avance',
 '<start> je le promets',
 '<start> je me suis d tendu',
 '<start> je me suis d tendue',
 '<start> j ai pris ma retraite',
 '<start> j ai dit non',
 '<start> je l ai dit',
 '<start> je l ai vu',
 '<start> je l ai vu',
 '<start> je le vis',
 '<start> j en ai vu une',
 '<start> j en ai vu un',
 '<start> je vous vis',
 '<start> je te vis',
 '<start> je t ai vue',
 '<start> je t ai vu',
 '<start> je vous ai vues',
 '<start> je vous ai vus',
 '<start> je vous ai vue',
 '<start> je vous ai vu',
 '<start> je vois tom',
 '<start> j ai cri',
 '<start> j ai tr buch',
 '<start> j ai plan',
 '<start> je le veux',
 '<start> j tais nouveau',
 '<start> j tais nouvelle',
 '<start> j irai',
 '<start> je me suis r veill',
 '<start> je me suis veill',
 '<start> je serais d accord',
 '<start> je partirais',
 '<start> j appellerai',
 '<start> je cuisinerai',
 '<start> j aiderai',
 '<start> je vivrai',
 '<start> j ob irai',
 '<start> je ferai mon sac',
 '<start> je ferai ma valise',
 '<start> je plierai mes gaules',
 '<start> je passerai',
 '<start> j abandonnerai',
 '<start> je chanterai',
 '<start> j arr terai',
 '<start> je nagerai',
 '<start> je parlerai',
 '<start> je vais parler',
 '<start> j attendrai',
 '<start> je marcherai',
 '<start> je vais travailler',
 '<start> je travaillerai',
 '<start> je suis flic',
 '<start> je suis un homme',
 '<start> je suis en vie',
 '<start> je suis vivant',
 '<start> je suis vivante',
 '<start> je suis seule',
 '<start> je suis seul',
 '<start> je suis nerv',
 '<start> je suis en col re',
 '<start> je suis arm',
 '<start> je suis arm e',
 '<start> je suis r veill',
 '<start> je suis aveugle',
 '<start> je suis fauch',
 '<start> j ai d croch',
 '<start> je suis propre',
 '<start> je suis fou',
 '<start> je suis folle',
 '<start> je suis gu ri',
 '<start> je suis gu rie',
 '<start> j ai la t te qui tourne',
 '<start> je suis saoul',
 '<start> je suis so l',
 '<start> je suis ivre',
 '<start> je me meurs',
 '<start> je suis en avance',
 '<start> je suis en premier',
 '<start> je suis difficile',
 '<start> je suis tatillon',
 '<start> je suis tatillonne',
 '<start> je pars maintenant',
 '<start> je me tire',
 '<start> j y vais',
 '<start> je pars',
 '<start> je suis loyal',
 '<start> je suis loyale',
 '<start> je suis veinard',
 '<start> je suis veinarde',
 '<start> j ai du pot',
 '<start> je suis chanceux',
 '<start> je suis chanceuse',
 '<start> je suis en train de mentir',
 '<start> je suis nu',
 '<start> je suis nue',
 '<start> je me trouve nu',
 '<start> je me trouve nue',
 '<start> je suis poil',
 '<start> je suis tranquille',
 '<start> je suis pr te',
 '<start> je suis pr t',
 '<start> je suis pr t',
 '<start> j ai raison',
 '<start> je suis sobre',
 '<start> excuse moi',
 '<start> d sol',
 '<start> excusez moi',
 '<start> d sol',
 '<start> je suis d sol',
 '<start> je suis d sol e',
 '<start> je suis coinc e',
 '<start> je suis timide',
 '<start> je suis fatigu',
 '<start> je suis dur',
 '<start> je suis dure',
 '<start> je suis dur cuire',
 '<start> je suis dure cuire',
 '<start> je suis toi',
 '<start> je suis vous',
 '<start> j ai perdu',
 '<start> est ce que tom va bien',
 '<start> tom va t il bien',
 '<start> c est grave',
 '<start> est ce loign',
 '<start> est ce loin',
 '<start> est ce chaud',
 '<start> est ce toi',
 '<start> est ce vous',
 '<start> est ce que c est vous',
 '<start> a a chou',
 '<start> il a neig',
 '<start> a sent mauvais',
 '<start> a pue',
 '<start> c tait bon',
 '<start> c tait correct',
 '<start> c tait ok',
 '<start> a a fonctionn',
 '<start> a a march',
 '<start> il est trois heures et demie',
 '<start> il est huit heures trente',
 '<start> il est 8 h 30',
 '<start> c est une t l',
 '<start> il fait froid',
 '<start> c est froid',
 '<start> c est sombre',
 '<start> elle est morte',
 '<start> c est mort',
 '<start> il est mort',
 '<start> c est fait',

In [66]:
words1=[]
for sent in corpus1:
    sent_token=sent_tokenize(sent)
    for sent in sent_token:
        words1.append(simple_preprocess(sent))
words1

[['salut'],
 ['cours'],
 ['courez'],
 ['qui'],
 ['alors'],
 ['au', 'feu'],
 ['aide'],
 ['saute'],
 ['suffit'],
 ['stop'],
 ['arr', 'te', 'toi'],
 ['attends'],
 ['attendez'],
 ['poursuis'],
 ['continuez'],
 ['poursuivez'],
 ['bonjour'],
 ['salut'],
 ['je', 'comprends'],
 ['essaye'],
 ['ai', 'gagn'],
 ['je', 'ai', 'emport'],
 ['ai', 'gagn'],
 ['oh', 'non'],
 ['attaque'],
 ['attaquez'],
 ['sant'],
 ['votre', 'sant'],
 ['merci'],
 ['tchin', 'tchin'],
 ['ve', 'toi'],
 ['va', 'maintenant'],
 ['allez', 'maintenant'],
 ['vas', 'maintenant'],
 ['ai', 'pig'],
 ['compris'],
 ['pig'],
 ['compris'],
 ['as', 'capt'],
 ['monte'],
 ['montez'],
 ['serre', 'moi', 'dans', 'tes', 'bras'],
 ['serrez', 'moi', 'dans', 'vos', 'bras'],
 ['je', 'suis', 'tomb'],
 ['je', 'suis', 'tomb'],
 ['je', 'sais'],
 ['je', 'suis', 'parti'],
 ['je', 'suis', 'partie'],
 ['ai', 'menti'],
 ['ai', 'perdu'],
 ['ai', 'pay'],
 ['ai', 'ans'],
 ['je', 'vais', 'bien'],
 ['va'],
 ['coutez'],
 ['est', 'pas', 'possible'],
 ['impossible'],
 ['en', 'aucun', 'cas'],
 ['sans', 'fa', 'ons'],
 ['est', 'hors', 'de', 'question'],
 ['il', 'en', 'est', 'pas', 'question'],
 ['est', 'exclu'],
 ['en', 'aucune', 'mani', 're'],
 ['hors', 'de', 'question'],
 ['vraiment'],
 ['vrai'],
 ['ah', 'bon'],
 ['merci'],
 ['on', 'essaye'],
 ['nous', 'avons', 'gagn'],
 ['nous', 'gagn', 'mes'],
 ['nous', 'avons', 'emport'],
 ['nous', 'emport', 'mes'],
 ['demande', 'tom'],
 ['fantastique'],
 ['sois', 'calme'],
 ['soyez', 'calme'],
 ['soyez', 'calmes'],
 ['sois', 'tendu'],
 ['sois', 'juste'],
 ['soyez', 'juste'],
 ['soyez', 'justes'],
 ['sois', 'quitable'],
 ['soyez', 'quitable'],
 ['soyez', 'quitables'],
 ['sois', 'gentil'],
 ['sois', 'gentil'],
 ['sois', 'gentille'],
 ['soyez', 'gentil'],
 ['soyez', 'gentille'],
 ['soyez', 'gentils'],
 ['soyez', 'gentilles'],
 ['gage'],
 ['appelle', 'moi'],
 ['appellez', 'moi'],
 ['appelle', 'nous'],
 ['appelez', 'nous'],
 ['entrez'],
 ['entre'],
 ['entre'],
 ['entrez'],
 ['allez'],
 ['allez'],
 ['viens'],
 ['venez'],
 ['laisse', 'tomber'],
 ['laissez', 'tomber'],
 ['laisse', 'le', 'tomber'],
 ['laissez', 'le', 'tomber'],
 ['va', 'chercher', 'tom'],
 ['sortez'],
 ['sors'],
 ['sortez'],
 ['sors'],
 ['casse', 'toi'],
 ['gage'],
 ['pars'],
 ['va', 'te', 'faire', 'foutre'],
 ['pars'],
 ['gage'],
 ['fous', 'le', 'camp'],
 ['pars', 'ici'],
 ['va', 'en'],
 ['disparais'],
 ['allez', 'vous', 'en'],
 ['rentrez', 'la', 'maison'],
 ['rentre', 'la', 'maison'],
 ['rentre', 'chez', 'toi'],
 ['rentrez', 'chez', 'vous'],
 ['va', 'doucement'],
 ['allez', 'doucement'],
 ['adieu'],
 ['la', 'revoyure'],
 ['attends', 'un', 'peu'],
 ['attendez', 'un', 'peu'],
 ['tiens', 'bon'],
 ['tenez', 'bon'],
 ['il', 'laissa', 'tomber'],
 ['il', 'laiss', 'tomber'],
 ['il', 'court'],
 ['aide', 'moi'],
 ['aide', 'moi'],
 ['aidez', 'moi'],
 ['aidez', 'nous'],
 ['aide', 'nous'],
 ['ne', 'bouge', 'plus'],
 ['ne', 'quittez', 'pas'],
 ['fais', 'un', 'lin', 'tom'],
 ['je', 'suis', 'du', 'me', 'avis'],
 ['ai', 'pleur'],
 ['je', 'me', 'suis', 'assoupi'],
 ['je', 'me', 'suis', 'assoupie'],
 ['je', 'conduis'],
 ['je', 'fume'],
 ['je', 'ronfle'],
 ['je', 'pue'],
 ['je', 'me', 'suis', 'tenu', 'debout'],
 ['je', 'me', 'suis', 'tenue', 'debout'],
 ['ai', 'promis'],
 ['ai', 'jur'],
 ['essayai'],
 ['ai', 'essay'],
 ['ai', 'tent'],
 ['ai', 'fait', 'signe'],
 ['irai'],
 ['je', 'suis', 'tom'],
 ['je', 'suis', 'gras'],
 ['je', 'suis', 'gros'],
 ['je', 'suis', 'en', 'forme'],
 ['je', 'suis', 'touch'],
 ['je', 'suis', 'touch'],
 ['je', 'suis', 'malade'],
 ['je', 'suis', 'triste'],
 ['je', 'suis', 'timide'],
 ['je', 'suis', 'mouill'],
 ['je', 'suis', 'mouill'],
 ['est', 'bibi'],
 ['joignez', 'vous'],
 ['joignez', 'vous', 'nous'],
 ['garde', 'le'],
 ['gardez', 'le'],
 ['embrasse', 'moi'],
 ['embrassez', 'moi'],
 ['moi', 'aussi'],
 ['ouvre', 'moi'],
 ['ouvre'],
 ['parfait'],
 ['plus', 'tard'],
 ['bient'],
 ['la', 'prochaine'],
 ['plus'],
 ['montre', 'moi'],
 ['montrez', 'moi'],
 ['taisez', 'vous'],
 ['ferme', 'la'],
 ['tais', 'toi'],
 ['ferme', 'la'],
 ['la', 'ferme'],
 ['pas', 'grave'],
 ['plus', 'tard'],
 ['prends', 'le'],
 ['prenez', 'le'],
 ['prends', 'le'],
 ['prenez', 'le'],
 ['dis', 'moi'],
 ['dites', 'moi'],
 ['tom', 'gagn'],
 ['veille', 'toi'],
 ['veille', 'toi'],
 ['veillez', 'vous'],
 ['veille', 'toi'],
 ['veillez', 'vous'],
 ['lave', 'toi'],
 ['lavez', 'vous'],
 ['nous', 'savons'],
 ['nous', 'perd', 'mes'],
 ['nous', 'avons', 'perdu'],
 ['nous', 'mes', 'battus'],
 ['nous', 'mes', 'battues'],
 ['nous', 'mes', 'faits'],
 ['nous', 'mes', 'faites'],
 ['nous', 'avons', 'faits'],
 ['nous', 'avons', 'faites'],
 ['nous', 'avons', 'battus'],
 ['nous', 'avons', 'battues'],
 ['bienvenue'],
 ['qui', 'gagn'],
 ['qui', 'emport'],
 ['tu', 'cours'],
 ['suis', 'je', 'gros'],
 ['suis', 'je', 'grosse'],
 ['demande', 'leur'],
 ['demandez', 'leur'],
 ['recule'],
 ['reculez'],
 ['recule'],
 ['reculez'],
 ['retire', 'toi'],
 ['retirez', 'vous'],
 ['sois', 'un', 'homme'],
 ['soyez', 'un', 'homme'],
 ['sois', 'calme'],
 ['soyez', 'calme'],
 ['soyez', 'calmes'],
 ['aucune', 'id'],
 ['en', 'sais', 'foutre', 'rien'],
 ['appelle', 'tom'],
 ['appelez', 'tom'],
 ['courage'],
 ['tends', 'toi'],
 ['menottez', 'le'],
 ['avance'],
 ['avancez'],
 ['continue', 'rouler'],
 ['continuez', 'rouler'],
 ['trouve', 'tom'],
 ['trouvez', 'tom'],
 ['parez', 'ceci'],
 ['pare'],
 ['che', 'toi'],
 ['descends'],
 ['descendez'],
 ['che', 'toi'],
 ['chez', 'vous'],
 ['va', 'voir', 'ailleurs', 'si', 'suis'],
 ['gage'],
 ['va', 'au', 'diable'],
 ['sois', 'aliste'],
 ['passe', 'devant'],
 ['vas'],
 ['avance'],
 ['vas'],
 ['poursuis'],
 ['passe', 'devant'],
 ['vas'],
 ['bien', 'jou'],
 ['bon', 'boulot'],
 ['beau', 'travail'],
 ['attrape', 'le'],
 ['attrapez', 'le'],
 ['amuse', 'toi', 'bien'],
 ['amusez', 'vous', 'bien'],
 ['il', 'essaye'],
 ['il', 'est', 'mouill'],
 ['aide', 'tom'],
 ['aidez', 'tom'],
 ['salut', 'les', 'mecs'],
 ['comme', 'est', 'mignon'],
 ['quelle', 'profondeur'],
 ['comme', 'est', 'chouette'],
 ['comme', 'est', 'gentil'],
 ['est', 'du', 'joli'],
 ['comme', 'est', 'agr', 'able'],
 ['che', 'toi'],
 ['grouille'],
 ['pressez', 'vous'],
 ['fi'],
 ['je', 'en', 'suis', 'bien', 'sorti'],
 ['je', 'en', 'suis', 'bien', 'sortie'],
 ['je', 'ai', 'fait'],
 ['est', 'moi', 'qui', 'ai', 'fait'],
 ['ai', 'chou'],
 ['ai', 'oubli'],
 ['ai', 'compris'],
 ['ai', 'compris'],
 ['ai', 'capt'],
 ['ai', 'aid'],
 ['ai', 'saut'],
 ['ai', 'regard'],
 ['ai'],
 ['ai', 'fait', 'signe', 'de', 'la', 'te'],
 ['ai', 'ob'],
 ['je', 'phonai'],
 ['ai', 'phon'],
 ['je', 'refuse'],
 ['je', 'le', 'refuse'],
 ['je', 'me', 'suis', 'repos'],
 ['je', 'me', 'suis', 'repos'],
 ['je', 'ai', 'vu'],
 ['je', 'ai', 'vu'],
 ['ai', 'soupir'],
 ['je', 'suis', 'rest'],
 ['je', 'suis', 'rest'],
 ['ai', 'parl'],
 ['je', 'utilise'],
 ['en', 'fais', 'usage'],
 ['je', 'en', 'sers'],
 ['je', 'paierai'],
 ['je', 'vais', 'essayer'],
 ['essaierai'],
 ['je', 'suis', 'revenu'],
 ['me', 'revoil'],
 ['je', 'suis', 'chauve'],
 ['je', 'suis', 'occup'],
 ['je', 'suis', 'occup'],
 ['je', 'suis', 'calme'],
 ['ai', 'froid'],
 ['je', 'suis', 'tendu'],
 ['je', 'suis', 'tendue'],
 ['je', 'suis', 'sourd'],
 ['je', 'suis', 'sourde'],
 ['en', 'ai', 'fini'],
 ['je', 'suis', 'juste'],
 ['ai', 'la', 'peau', 'claire'],
 ['ai', 'le', 'teint', 'clair'],
 ['je', 'suis', 'rapide'],
 ['tout', 'va', 'bien'],
 ['je', 'vais', 'bien'],
 ['va'],
 ['je', 'suis', 'libre'],
 ['je', 'suis', 'libre'],
 ['je', 'suis', 'disponible'],
 ['je', 'suis', 'repu'],
 ['je', 'suis', 'rassasi'],
 ['en', 'suis'],
 ['je', 'suis', 'de', 'la', 'partie'],
 ['je', 'suis', 'content'],
 ['je', 'suis', 'chez', 'moi'],
 ['je', 'suis', 'en', 'retard'],
 ['je', 'suis', 'paresseux'],
 ['je', 'suis', 'fain', 'ant'],
 ['je', 'suis', 'paresseuse'],
 ['je', 'suis', 'fain', 'ante'],
 ['je', 'vais', 'bien'],
 ['je', 'me', 'porte', 'bien'],
 ['je', 'suis', 'riche'],
 ['je', 'suis', 'en', 'curit'],
 ['je', 'suis', 'malade'],
 ['en', 'suis', 'certain'],
 ['je', 'suis', 'certain'],
 ['en', 'suis'],
 ['en', 'suis', 're'],
 ['je', 'suis', 'grande'],
 ['je', 'suis', 'mince'],
 ['je', 'suis', 'ordonn'],
 ['je', 'suis', 'ordonn'],
 ['je', 'suis', 'laid'],
 ['je', 'suis', 'laide'],
 ['je', 'suis', 'faible'],
 ['je', 'vais', 'bien'],
 ['je', 'me', 'porte', 'bien'],
 ['ai', 'gagn'],
 ['je', 'ai', 'emport'],
 ['aide'],
 ['fait', 'mal'],
 ['elle', 'marche'],
 ['fonctionne'],
 ['est', 'tom'],
 ['est', 'marrant'],
 ['est', 'rigolo'],
 ['est', 'le', 'sien'],
 ['est', 'la', 'sienne'],
 ['est', 'nouveau'],
 ['est', 'neuf'],
 ['est', 'bizarre'],
 ['il', 'est', 'rouge'],
 ['est', 'triste'],
 ['fense', 'entrer'],
 ['entrez', 'pas'],
 ['embrasse', 'tom'],
 ['laisse', 'tomber'],
 ['laissez', 'tomber'],
 ['laissez', 'moi'],
 ['laisse', 'nous'],
 ['laissez', 'nous'],
 ['allons'],
 ['allons'],
 ['attention'],
 ['regarde', 'donc'],
 ['pouse', 'moi'],
 ['pousez', 'moi'],
 ['puis', 'je', 'partir'],
 ['puis', 'je', 'aller'],
 ['puis', 'je', 'rendre'],
 ['sauve', 'tom'],
 ['sauvez', 'tom'],
 ['de', 'quoi'],
 ['elle', 'est', 'venue'],
 ['elle', 'est', 'morte'],
 ['elle', 'court'],
 ['assieds', 'toi'],
 ['asseyez', 'vous'],
 ['assieds', 'toi'],
 ['assieds', 'toi', 'ici'],
 ['asseyez', 'vous', 'ici'],
 ['parle', 'plus', 'fort'],
 ['parlez', 'plus', 'fort'],
 ['ve', 'toi'],
 ['arr', 'te', 'tom'],
 ['stoppez', 'tom'],
 ['go', 'te', 'le'],
 ['go', 'te', 'la'],
 ['go', 'tez', 'le'],
 ['go', 'tez', 'la'],
 ['dis', 'le', 'tom'],
 ['informez', 'en', 'tom'],
 ['nial'],
 ['excellent'],
 ['formidable'],
 ['ils', 'gagn', 'rent'],
 ['elles', 'gagn', 'rent'],
 ['ils', 'ont', 'gagn'],
 ['elles', 'ont', 'gagn'],
 ['tom', 'est', 'venu'],
 ['tom', 'est', 'mort'],
 ['tom', 'savait'],
 ['tom', 'est', 'parti'],
 ['tom', 'partit'],
 ['tom', 'menti'],
 ['tom', 'ment'],
 ['tom', 'perdu'],
 ['tom', 'pay'],
 ['trop', 'tard'],
 ['faites', 'moi', 'confiance'],
 ['fais', 'moi', 'confiance'],
 ['fais', 'un', 'effort'],
 ['essaies', 'en'],
 ['essayez', 'en'],
 ['essaie', 'ceci'],
 ['essayez', 'ceci'],
 ['utilise', 'ceci'],
 ['utilisez', 'ceci'],
 ['emploie', 'ceci'],
 ['employez', 'ceci'],
 ['avertis', 'tom'],
 ['pr', 'viens', 'tom'],
 ['regarde', 'moi'],
 ['regardez', 'moi'],
 ['regardez', 'nous'],
 ['regarde', 'nous'],
 ['nous', 'sommes', 'accord'],
 ['nous', 'irons'],
 ['nous', 'allons', 'bien'],
 ['pour', 'quoi', 'faire'],
 ['quoi', 'bon'],
 ['qu', 'est', 'ce', 'qu', 'on', 'est', 'marr'],
 ['qu', 'est', 'ce', 'qu', 'on', 'est', 'marr', 'es'],
 ['qui', 'est', 'venu'],
 ['qui', 'est', 'mort'],
 ['qui', 'est', 'tomb'],
 ['qui', 'missionne'],
 ['qui', 'est', 'il'],
 ['cris', 'moi'],
 ['crivez', 'moi'],
 ['tu', 'as', 'perdu'],
 ['vous', 'avez', 'perdu'],
 ['apr', 'vous'],
 ['en', 'joue', 'feu'],
 ['suis', 'je', 'en', 'retard'],
 ['pondez', 'moi'],
 ['assieds', 'toi'],
 ['asseyez', 'vous'],
 ['les', 'oiseaux', 'volent'],
 ['tes', 'souhaits'],
 ['appelle', 'la', 'maison'],
 ['calmez', 'vous'],
 ['calme', 'toi'],
 ['pouvons', 'nous', 'partir'],
 ['pouvons', 'nous', 'nous', 'en', 'aller'],
 ['pouvons', 'nous', 'aller'],
 ['attrape', 'tom'],
 ['attrapez', 'tom'],
 ['rattrape', 'le'],
 ['calme', 'toi'],
 ['reviens'],
 ['revenez'],
 ['viens', 'ici'],
 ['venez'],
 ['viens'],
 ['venez'],
 ['venez', 'ici'],
 ['viens', 'chez', 'nous'],
 ['venez', 'chez', 'nous'],
 ['viens', 'chez', 'moi'],
 ['venez', 'chez', 'moi'],
 ['viens', 'bient'],
 ['venez', 'bient'],
 ['calmez', 'vous'],
 ['ai', 'je', 'gagn'],
 ['ai', 'je', 'emport'],
 ['est', 'ce', 'moi', 'qui', 'ai', 'gagn'],
 ['faites', 'le', 'maintenant'],
 ['des', 'chiens', 'aboient'],
 ['les', 'chiens', 'aboient'],
 ['ne', 'demande', 'pas'],
 ['ne', 'pleure', 'pas'],
 ['ne', 'meurs', 'pas'],
 ['ne', 'mourez', 'pas'],
 ['ne', 'mens', 'pas'],
 ['ne', 'courez', 'pas'],
 ['ne', 'cours', 'pas'],
 ['excuse', 'moi'],
 ['excusez', 'moi'],
 ['pardon'],
 ['je', 'vous', 'demande', 'pardon'],
 ['pla', 'il'],
 ['plait', 'il'],
 ['pardon'],
 ['fantastique'],
 ['sens'],
 ['sentez'],
 ['touche'],
 ['touchez'],
 ['suis', 'moi'],
 ['suis', 'nous'],
 ['suivez', 'nous'],
 ['oublie'],
 ['oublie', 'le'],
 ['oubliez'],
 ['oubliez', 'le'],
 ['laisse', 'tomber'],
 ['oublie'],
 ['oublie', 'le'],
 ['trouve', 'un', 'emploi'],
 ['trouve', 'un', 'boulot'],
 ['trouvez', 'un', 'emploi'],
 ['trouvez', 'un', 'boulot'],
 ['pr', 'pare', 'toi'],
 ['pr', 'parez', 'vous'],
 ['va', 'le', 'chercher'],
 ['allez', 'le', 'chercher'],
 ['entrez'],
 ['va', 'au', 'lit'],
 ['allez', 'au', 'lit'],
 ['bonne', 'chance'],
 ['bonne', 'chance'],
 ['attrape'],
 ['attrapez'],
 ['saisis', 'toi', 'de'],
 ['saisissez', 'vous', 'de'],
 ['attrape'],
 ['attrapez'],
 ['pas', 'touche'],
 ['il', 'est', 'malade'],
 ['il', 'est', 'vieux'],
 ['il', 'est', 'dj'],
 ['il', 'est', 'bon'],
 ['il', 'est', 'paresseux'],
 ['il', 'est', 'moi'],
 ['il', 'est', 'riche'],
 ['il', 'est', 'sexy'],
 ['me', 'voici'],
 ['voil', 'cinq', 'dollars'],
 ['halte', 'au', 'feu'],
 ['cessez', 'le', 'feu'],
 ['tiens'],
 ['tenez'],
 ['tenez', 'ceci'],
 ['tiens', 'ceci'],
 ['est', 'affreux'],
 ['comme', 'est', 'bizarre'],
 ['comment', 'tom', 'va', 'il'],
 ['comment', 'va', 'tom'],
 ['ai', 'froid'],
 ['je', 'suis', 'bon'],
 ['je', 'vais', 'bien'],
 ['je', 'suis', 'malade'],
 ['je', 'suis'],
 ['je', 'suis', 'certain'],
 ['je', 'vous', 'en', 'prie'],
 ['je', 'vous', 'en', 'conjure'],
 ['je', 'vous', 'en', 'supplie'],
 ['je', 'te', 'prie'],
 ['je', 'sais', 'courir'],
 ['je', 'sais', 'skier'],
 ['eus', 'un', 'mouvement', 'de', 'recul'],
 ['ai', 'eu', 'un', 'mouvement', 'de', 'recul'],
 ['je', 'suis', 'rentr', 'en', 'moi', 'me'],
 ['ai', 'expir'],
 ['ai', 'abandonn'],
 ['je', 'donne', 'ma', 'langue', 'au', 'chat'],
 ['abandonne'],
 ['je', 'me', 'suis', 'mis', 'avoir', 'chaud'],
 ['je', 'me', 'suis', 'mise', 'avoir', 'chaud'],
 ['je', 'me', 'suis', 'amus'],
 ['je', 'me', 'suis', 'amus'],
 ['je', 'me', 'suis', 'marr'],
 ['je', 'me', 'suis', 'marr'],
 ['je', 'teste'],
 ['je', 'ai'],
 ['ai', 'frapp', 'tom'],
 ['esp', 're', 'bien'],
 ['je', 'me', 'suis', 'ch'],
 ['je', 'me', 'suis', 'ch'],
 ['ai', 'inspir'],
 ['je', 'le', 'savais'],
 ['aime'],
 ['je', 'ai', 'perdu'],
 ['adore'],
 ['adore'],
 ['je', 'suis', 'rieux'],
 ['je', 'suis', 'rieux'],
 ['je', 'dois', 'aller'],
 ['il', 'faut', 'que', 'aille'],
 ['il', 'me', 'faut', 'aller'],
 ['il', 'me', 'faut', 'partir'],
 ['il', 'me', 'faut', 'en', 'aller'],
 ['je', 'dois', 'partir'],
 ['je', 'dois', 'en', 'aller'],
 ['il', 'faut', 'que', 'je', 'en', 'aille'],
 ['en', 'ai', 'besoin'],
 ['il', 'me', 'le', 'faut'],
 ['ai', 'remarqu'],
 ['ai', 'pay', 'avance'],
 ['je', 'le', 'promets'],
 ['je', 'me', 'suis', 'tendu'],
 ['je', 'me', 'suis', 'tendue'],
 ['ai', 'pris', 'ma', 'retraite'],
 ['ai', 'dit', 'non'],
 ['je', 'ai', 'dit'],
 ['je', 'ai', 'vu'],
 ['je', 'ai', 'vu'],
 ['je', 'le', 'vis'],
 ['en', 'ai', 'vu', 'une'],
 ['en', 'ai', 'vu', 'un'],
 ['je', 'vous', 'vis'],
 ['je', 'te', 'vis'],
 ['je', 'ai', 'vue'],
 ['je', 'ai', 'vu'],
 ['je', 'vous', 'ai', 'vues'],
 ['je', 'vous', 'ai', 'vus'],
 ['je', 'vous', 'ai', 'vue'],
 ['je', 'vous', 'ai', 'vu'],
 ['je', 'vois', 'tom'],
 ['ai', 'cri'],
 ['ai', 'tr', 'buch'],
 ['ai', 'plan'],
 ['je', 'le', 'veux'],
 ['tais', 'nouveau'],
 ['tais', 'nouvelle'],
 ['irai'],
 ['je', 'me', 'suis', 'veill'],
 ['je', 'me', 'suis', 'veill'],
 ['je', 'serais', 'accord'],
 ['je', 'partirais'],
 ['appellerai'],
 ['je', 'cuisinerai'],
 ['aiderai'],
 ['je', 'vivrai'],
 ['ob', 'irai'],
 ['je', 'ferai', 'mon', 'sac'],
 ['je', 'ferai', 'ma', 'valise'],
 ['je', 'plierai', 'mes', 'gaules'],
 ['je', 'passerai'],
 ['abandonnerai'],
 ['je', 'chanterai'],
 ['arr', 'terai'],
 ['je', 'nagerai'],
 ['je', 'parlerai'],
 ['je', 'vais', 'parler'],
 ['attendrai'],
 ['je', 'marcherai'],
 ['je', 'vais', 'travailler'],
 ['je', 'travaillerai'],
 ['je', 'suis', 'flic'],
 ['je', 'suis', 'un', 'homme'],
 ['je', 'suis', 'en', 'vie'],
 ['je', 'suis', 'vivant'],
 ['je', 'suis', 'vivante'],
 ['je', 'suis', 'seule'],
 ['je', 'suis', 'seul'],
 ['je', 'suis', 'nerv'],
 ['je', 'suis', 'en', 'col', 're'],
 ['je', 'suis', 'arm'],
 ['je', 'suis', 'arm'],
 ['je', 'suis', 'veill'],
 ['je', 'suis', 'aveugle'],
 ['je', 'suis', 'fauch'],
 ['ai', 'croch'],
 ['je', 'suis', 'propre'],
 ['je', 'suis', 'fou'],
 ['je', 'suis', 'folle'],
 ['je', 'suis', 'gu', 'ri'],
 ['je', 'suis', 'gu', 'rie'],
 ['ai', 'la', 'te', 'qui', 'tourne'],
 ['je', 'suis', 'saoul'],
 ['je', 'suis', 'so'],
 ['je', 'suis', 'ivre'],
 ['je', 'me', 'meurs'],
 ['je', 'suis', 'en', 'avance'],
 ['je', 'suis', 'en', 'premier'],
 ['je', 'suis', 'difficile'],
 ['je', 'suis', 'tatillon'],
 ['je', 'suis', 'tatillonne'],
 ['je', 'pars', 'maintenant'],
 ['je', 'me', 'tire'],
 ['vais'],
 ['je', 'pars'],
 ['je', 'suis', 'loyal'],
 ['je', 'suis', 'loyale'],
 ['je', 'suis', 'veinard'],
 ['je', 'suis', 'veinarde'],
 ['ai', 'du', 'pot'],
 ['je', 'suis', 'chanceux'],
 ['je', 'suis', 'chanceuse'],
 ['je', 'suis', 'en', 'train', 'de', 'mentir'],
 ['je', 'suis', 'nu'],
 ['je', 'suis', 'nue'],
 ['je', 'me', 'trouve', 'nu'],
 ['je', 'me', 'trouve', 'nue'],
 ['je', 'suis', 'poil'],
 ['je', 'suis', 'tranquille'],
 ['je', 'suis', 'pr', 'te'],
 ['je', 'suis', 'pr'],
 ['je', 'suis', 'pr'],
 ['ai', 'raison'],
 ['je', 'suis', 'sobre'],
 ['excuse', 'moi'],
 ['sol'],
 ['excusez', 'moi'],
 ['sol'],
 ['je', 'suis', 'sol'],
 ['je', 'suis', 'sol'],
 ['je', 'suis', 'coinc'],
 ['je', 'suis', 'timide'],
 ['je', 'suis', 'fatigu'],
 ['je', 'suis', 'dur'],
 ['je', 'suis', 'dure'],
 ['je', 'suis', 'dur', 'cuire'],
 ['je', 'suis', 'dure', 'cuire'],
 ['je', 'suis', 'toi'],
 ['je', 'suis', 'vous'],
 ['ai', 'perdu'],
 ['est', 'ce', 'que', 'tom', 'va', 'bien'],
 ['tom', 'va', 'il', 'bien'],
 ['est', 'grave'],
 ['est', 'ce', 'loign'],
 ['est', 'ce', 'loin'],
 ['est', 'ce', 'chaud'],
 ['est', 'ce', 'toi'],
 ['est', 'ce', 'vous'],
 ['est', 'ce', 'que', 'est', 'vous'],
 ['chou'],
 ['il', 'neig'],
 ['sent', 'mauvais'],
 ['pue'],
 ['tait', 'bon'],
 ['tait', 'correct'],
 ['tait', 'ok'],
 ['fonctionn'],
 ['march'],
 ['il', 'est', 'trois', 'heures', 'et', 'demie'],
 ['il', 'est', 'huit', 'heures', 'trente'],
 ['il', 'est'],
 ['est', 'une'],
 ['il', 'fait', 'froid'],
 ['est', 'froid'],
 ['est', 'sombre'],
 ['elle', 'est', 'morte'],
 ['est', 'mort'],
 ['il', 'est', 'mort'],
 ['est', 'fait'],
 ['est', 'simple'],
 ['est', 'de', 'la', 'nourriture'],
 ['est', 'gratuit'],
 ['elle', 'est', 'ici'],
 ['est', 'ici'],
 ['est', 'le', 'sien'],
 ['est', 'la', 'sienne'],
 ['il', 'est', 'tard'],
 ['est', 'perdu'],
 ['est', 'le', 'mien'],
 ['est', 'la', 'mienne'],
 ['est', 'moi'],
 ['il', 'agit', 'du', 'mien'],
 ['est', 'ouvert'],
 ['est', 'le', 'tre'],
 ['est', 'la', 'tre'],
 ['est', 'nous'],
 ['est', 'du', 'sable'],
 ['il', 'est', 'temps'],
 ['est', 'heure'],
 ['est', 'vrai'],
 ['est', 'du', 'boulot'],
 ['restez', 'calme'],
 ['garde'],
 ['gardez', 'cela'],
 ['garde'],
 ['gardez', 'ceci'],
 ['ainsi', 'soit', 'il'],
 ['laisse', 'faire'],
 ['laisse', 'moi', 'partir'],
 ['laissez', 'moi', 'partir'],
 ['che', 'moi'],
 ['chez', 'moi'],
 ['laisse', 'moi', 'en', 'aller'],
 ['laissez', 'moi', 'en', 'aller'],
 ['laissez', 'moi', 'aller'],
 ['laisse', 'moi', 'aller'],
 ['laisse', 'moi', 'partir'],
 ['laissez', 'moi', 'partir'],
 ['laisse', 'moi', 'en', 'aller'],
 ['laissez', 'moi', 'en', 'aller'],
 ['laissez', 'moi', 'rentrer'],
 ['laissez', 'moi', 'entrer'],
 ['demandons'],
 ['mangeons'],
 ['voyons', 'voir'],
 ['reste', 'allong', 'immobile'],
 ['reste', 'allong', 'immobile'],
 ['restez', 'allong', 'immobile'],
 ['restez', 'allong', 'immobile'],
 ['restez', 'allong', 'immobiles'],
 ['restez', 'allong', 'es', 'immobiles'],
 ['tourne', 'le', 'regard'],
 ['regardez', 'ailleurs'],
 ['regarde', 'derri', 're', 'toi'],
 ['regarde', 'derri', 're'],
 ['regarde', 'ici'],
 ['regardez', 'ici'],
 ['chauffe', 'toi'],
 ['chauffez', 'vous'],
 ['tends', 'toi'],
 ['laisse', 'toi', 'aller'],
 ['laissez', 'vous', 'aller'],
 ['bouge', 'de'],
 ['poussez', 'vous'],
 ['pousse', 'toi'],
 ['joli', 'coup'],
 ['pour'],
 ['mais', 'ouais'],
 ['pardi'],
 ['bien'],
 ['pour'],
 ['je', 'vous', 'en', 'prie'],
 ['je', 'en', 'prie'],

In [67]:
max_len_output = max(len(sentence) for sentence in words1)
longest_sentence = max(words1, key=len)

print("Max number of words:", max_len_output)
print("Sentence with max words:", longest_sentence)

Max number of words: 55
Sentence with max words: ['si', 'quelqu', 'un', 'qui', 'ne', 'conna', 'pas', 'vos', 'ant', 'dents', 'dit', 'que', 'vous', 'parlez', 'comme', 'un', 'locuteur', 'natif', 'cela', 'veut', 'dire', 'qu', 'il', 'probablement', 'remarqu', 'quelque', 'chose', 'propos', 'de', 'votre', 'locution', 'qui', 'lui', 'fait', 'prendre', 'conscience', 'que', 'vous', 'tes', 'pas', 'un', 'locuteur', 'natif', 'en', 'autres', 'termes', 'vous', 'ne', 'parlez', 'pas', 'vraiment', 'comme', 'un', 'locuteur', 'natif']

In [68]:
all_words1 = [word for sentence in words1 for word in sentence]

# Get unique words
unique_words_output = set(all_words1)

# Count them
print("Number of unique words:", len(unique_words_output))
print("Unique words:", unique_words_output)

Number of unique words: 19931

In [69]:
decoder_input=[one_hot(word, len(unique_words_output)) for word in decoder_input_data]
decoder_input

[[15984, 3727],
 [15984, 1093],
 [15984, 19221],
 [15984, 1560],
 [15984, 5907, 6280],
 [15984, 12112, 5212],
 [15984, 18760, 2341],
 [15984, 19635],
 [15984, 5907, 4033],
 [15984, 15408],
 [15984, 17658, 5048, 8603],
 [15984, 7777],
 [15984, 17859],
 [15984, 10362],
 [15984, 14157],
 [15984, 1873],
 [15984, 2571],
 [15984, 3727],
 [15984, 6182, 11514],
 [15984, 11516, 2026],
 [15984, 11516, 18494, 3552],
 [15984, 6182, 18760, 18494, 8543],
 [15984, 11516, 18494, 3552],
 [15984, 6047, 5257],
 [15984, 19902],
 [15984, 3588],
 [15984, 15893],
 [15984, 14588, 15893],
 [15984, 13328],
 [15984, 3755, 3755],
 [15984, 18760, 739, 8603],
 [15984, 504, 5816],
 [15984, 6483, 18140, 5816],
 [15984, 19554, 18140, 5816],
 [15984, 11516, 18494, 4065],
 [15984, 4228],
 [15984, 4065],
 [15984, 4228],
 [15984, 13718, 15658, 5875],
 [15984, 19203],
 [15984, 10979],
 [15984, 4639, 3805, 11625, 2948, 17472],
 [15984, 11493, 3805, 11625, 15411, 17472],
 [15984, 6182, 11001, 3863, 14179],
 [15984, 6182, 11001, 3863],
 [15984, 6182, 14074],
 [15984, 6182, 11001, 18972],
 [15984, 6182, 11001, 1421],
 [15984, 11516, 18494, 10045],
 [15984, 11516, 18494, 18164],
 [15984, 11516, 18494, 1192],
 [15984, 11516, 18494, 4785, 11233],
 [15984, 6182, 19445, 16230],
 [15984, 5907, 504],
 [15984, 19667],
 [15984, 12873, 8939, 3349, 19825],
 [15984, 19120],
 [15984, 10002, 77, 12756],
 [15984, 5625, 17987, 2253],
 [15984, 12873, 8939, 16323, 17796, 16896],
 [15984, 14456, 240, 10002, 8939, 3349, 16896],
 [15984, 12873, 8939, 13638],
 [15984, 10002, 5566, 6957, 10499],
 [15984, 16323, 17796, 16896],
 [15984, 167],
 [15984, 7655],
 [15984, 6030, 15363],
 [15984, 13328],
 [15984, 6266, 2026],
 [15984, 5150, 16257, 3552],
 [15984, 5150, 3552, 13045],
 [15984, 5150, 18760, 16257, 8543],
 [15984, 5150, 18760, 8543, 13045],
 [15984, 5677, 1563],
 [15984, 3082],
 [15984, 12157, 6443],
 [15984, 18948, 6443],
 [15984, 18948, 16177],
 [15984, 12157, 19051, 16117],
 [15984, 12157, 7780],
 [15984, 18948, 7780],
 [15984, 18948, 2795],
 [15984, 12157, 14896],
 [15984, 18948, 14896],
 [15984, 18948, 2003],
 [15984, 12157, 11746],
 [15984, 12157, 11746],
 [15984, 12157, 4086],
 [15984, 18948, 11746],
 [15984, 18948, 4086],
 [15984, 18948, 10611],
 [15984, 18948, 276],
 [15984, 19051, 14571],
 [15984, 867, 3805],
 [15984, 313, 3805],
 [15984, 867, 5150],
 [15984, 4848, 5150],
 [15984, 5342],
 [15984, 4858],
 [15984, 4858],
 [15984, 5342],
 [15984, 6483],
 [15984, 6483],
 [15984, 7240],
 [15984, 12520],
 [15984, 12951, 11608],
 [15984, 16304, 11608],
 [15984, 12951, 7663, 11608],
 [15984, 16304, 7663, 11608],
 [15984, 504, 5232, 1563],
 [15984, 14256],
 [15984, 236],
 [15984, 14256],
 [15984, 236],
 [15984, 11854, 8603],
 [15984, 19051, 14571],
 [15984, 14926],
 [15984, 504, 5048, 8949, 13626],
 [15984, 14926],
 [15984, 19051, 14571],
 [15984, 5567, 7663, 2105],
 [15984, 14926, 19051, 8814],
 [15984, 504, 13718, 10002],
 [15984, 1397],
 [15984, 6483, 3720, 10002],
 [15984, 617, 547, 11163],
 [15984, 1256, 547, 11163],
 [15984, 1256, 18459, 8603],
 [15984, 617, 18459, 3720],
 [15984, 504, 1549],
 [15984, 6483, 1549],
 [15984, 7804],
 [15984, 547, 10457],
 [15984, 7777, 18247, 10515],
 [15984, 17859, 18247, 10515],
 [15984, 19132, 15363],
 [15984, 10496, 15363],
 [15984, 14456, 14870, 11608],
 [15984, 14456, 5907, 17612, 11608],
 [15984, 14456, 7868],
 [15984, 2341, 3805],
 [15984, 2341, 3805],
 [15984, 5865, 3805],
 [15984, 5865, 5150],
 [15984, 2341, 5150],
 [15984, 13233, 12671, 10952],
 [15984, 13233, 5360, 3349],
 [15984, 13038, 18247, 12873, 5529, 1563],
 [15984, 6182, 11001, 3810, 1242, 5439, 6453],
 [15984, 11516, 18494, 12044],
 [15984, 6182, 5439, 11001, 14177],
 [15984, 6182, 5439, 11001, 2018],
 [15984, 6182, 2934],
 [15984, 6182, 14225],
 [15984, 6182, 3591],
 [15984, 6182, 12385],
 [15984, 6182, 5439, 11001, 5164, 9558],
 [15984, 6182, 5439, 11001, 19414, 9558],
 [15984, 11516, 18494, 5935],
 [15984, 11516, 18494, 9558],
 [15984, 11516, 3291],
 [15984, 11516, 18494, 19248],
 [15984, 11516, 18494, 12810],
 [15984, 11516, 18494, 8663, 15882],
 [15984, 11516, 14651],
 [15984, 6182, 11001, 1563],
 [15984, 6182, 11001, 385],
 [15984, 6182, 11001, 1411],
 [15984, 6182, 11001, 10002, 10482],
 [15984, 6182, 11001, 15908],
 [15984, 6182, 11001, 15908, 14179],
 [15984, 6182, 11001, 4597],
 [15984, 6182, 11001, 17474],
 [15984, 6182, 11001, 7324],
 [15984, 6182, 11001, 6852],
 [15984, 6182, 11001, 6852, 14179],
 [15984, 12873, 8939, 16770],
 [15984, 18413, 3720],
 [15984, 18413, 3720, 5150],
 [15984, 10813, 7663],
 [15984, 12346, 7663],
 [15984, 4914, 3805],
 [15984, 13145, 3805],
 [15984, 3805, 712],
 [15984, 13, 3805],
 [15984, 13],
 [15984, 5607],
 [15984, 10952, 10824],
 [15984, 5239, 13718],
 [15984, 547, 6985],
 [15984, 10952],
 [15984, 10656, 3805],
 [15984, 13121, 3805],
 [15984, 9735, 3720],
 [15984, 16662, 547],
 [15984, 1060, 8603],
 [15984, 16662, 547],
 [15984, 547, 16662],
 [15984, 3349, 4730],
 [15984, 10952, 10824],
 [15984, 15889, 7663],
 [15984, 5776, 7663],
 [15984, 15889, 7663],
 [15984, 5776, 7663],
 [15984, 18227, 3805],
 [15984, 9341, 3805],
 [15984, 1563, 5907, 3552],
 [15984, 9679, 6431, 8603],
 [15984, 9679, 6431, 8603],
 [15984, 9679, 15675, 3720],
 [15984, 9679, 6431, 8603],
 [15984, 9679, 15675, 3720],
 [15984, 10749, 8603],
 [15984, 12434, 3720],
 [15984, 5150, 16539],
 [15984, 5150, 15261, 13045],
 [15984, 5150, 16257, 18164],
 [15984, 5150, 17025, 13045, 11217],
 [15984, 5150, 17025, 13045, 2123],
 [15984, 5150, 17025, 13045, 19051, 9814],
 [15984, 5150, 17025, 13045, 19051, 16856],
 [15984, 5150, 16257, 13718, 19051, 9814],
 [15984, 5150, 16257, 13718, 19051, 16856],
 [15984, 5150, 16257, 13718, 11217],
 [15984, 5150, 16257, 13718, 2123],
 [15984, 11694],
 [15984, 1560, 5907, 3552],
 [15984, 1560, 18760, 5907, 8543],
 [15984, 5455, 1093],
 [15984, 11001, 6182, 1411],
 [15984, 11001, 6182, 8328],
 [15984, 5677, 10194],
 [15984, 18576, 10194],
 [15984, 425],
 [15984, 84],
 [15984, 425],
 [15984, 84],
 [15984, 16201, 8603],
 [15984, 17083, 3720],
 [15984, 12157, 18247, 3739],
 [15984, 18948, 18247, 3739],
 [15984, 12157, 6443],
 [15984, 18948, 6443],
 [15984, 18948, 16177],
 [15984, 5566, 6057, 14179],
 [15984, 11516, 10002, 14074, 13626, 6940],
 [15984, 867, 1563],
 [15984, 4848, 1563],
 [15984, 8238],
 [15984, 19051, 8891, 8603],
 [15984, 7904, 7663],
 [15984, 7731],
 [15984, 3729],
 [15984, 6214, 5076],
 [15984, 14157, 5076],
 [15984, 15547, 1563],
 [15984, 18976, 1563],
 [15984, 9679, 11160, 5341],
 [15984, 9679, 10911, 5907],
 [15984, 18760, 14202, 8603],
 [15984, 12786],
 [15984, 18521],
 [15984, 18760, 14202, 8603],
 [15984, 18760, 18459, 3720],
 [15984, 504, 12759, 18353, 16286, 11516, 18140, 11001],
 [15984, 19051, 14571],
 [15984, 504, 12112, 11195],
 [15984, 12157, 9679, 5108],
 [15984, 4258, 2333],
 [15984, 19554, 18140],
 [15984, 7731],
 [15984, 19554, 18140],
 [15984, 10362],
 [15984, 4258, 2333],
 [15984, 19554, 18140],
 [15984, 16230, 17100],
 [15984, 15363, 17393],
 [15984, 12941, 19499],
 [15984, 5395, 7663],
 [15984, 11826, 7663],
 [15984, 13917, 8603, 16230],
 [15984, 18205, 3720, 16230],
 [15984, 14456, 2026],
 [15984, 14456, 8939, 6852],
 [15984, 2341, 1563],
 [15984, 5865, 1563],
 [15984, 3727, 18439, 17608],
 [15984, 15585, 12873, 8939, 119],
 [15984, 9440, 2762],
 [15984, 15585, 12873, 8939, 12776],
 [15984, 15585, 12873, 8939, 11746],
 [15984, 12873, 8939, 3810, 8838],
 [15984, 15585, 12873, 8939, 1239, 16367],
 [15984, 19051, 2464, 14202, 8603],
 [15984, 2998],
 [15984, 10104, 3720],
 [15984, 14675, 5907],
 [15984, 6182, 1242, 10002, 11001, 16230, 8970],
 [15984, 6182, 1242, 10002, 11001, 16230, 7625],
 [15984, 6182, 18760, 18494, 8663],
 [15984, 12873, 8939, 3805, 1560, 18760, 18494, 8663],
 [15984, 11516, 18494, 12437],
 [15984, 11516, 18494, 19586],
 [15984, 11516, 18494, 4228],
 [15984, 11516, 18494, 4228],
 [15984, 11516, 18494, 5875],
 [15984, 11516, 18494, 2836],
 [15984, 11516, 18494, 13301],
 [15984, 11516, 18494, 9281],
 [15984, 11516, 18494, 9679, 18760],
 [15984, 11516, 18494, 8663, 15882, 17796, 547, 13718, 5048],
 [15984, 11516, 18494, 3177, 5731],
 [15984, 6182, 13718, 18760, 10113],
 [15984, 11516, 18494, 13718, 18760, 14807],
 [15984, 6182, 9697],
 [15984, 6182, 7663, 9697],
 [15984, 6182, 5439, 11001, 8220],
 [15984, 6182, 5439, 11001, 8220, 14179],
 [15984, 6182, 18760, 18494, 16260],
 [15984, 6182, 18760, 18494, 16260],
 [15984, 11516, 18494, 3978],
 [15984, 6182, 11001, 3026],
 [15984, 6182, 11001, 3026, 14179],
 [15984, 11516, 18494, 6942],
 [15984, 6182, 18760, 16890],
 [15984, 11516, 10002, 13038, 18764],
 [15984, 6182, 1242, 10002, 15864],
 [15984, 6182, 10260],
 [15984, 6182, 19445, 774],
 [15984, 11516, 17931],
 [15984, 6182, 11001, 18403],
 [15984, 5439, 9982],
 [15984, 6182, 11001, 3963],
 [15984, 6182, 11001, 17400],
 [15984, 6182, 11001, 17400, 14179],
 [15984, 6182, 11001, 6443],
 [15984, 11516, 18494, 333],
 [15984, 6182, 11001, 19051, 16117],
 [15984, 6182, 11001, 19051, 3348],
 [15984, 6182, 11001, 8112],
 [15984, 6182, 11001, 19743],
 [15984, 11516, 10002, 18494, 16891],
 [15984, 6182, 11001, 7780],
 [15984, 11516, 18494, 547, 19654, 18886],
 [15984, 11516, 18494, 7663, 9784, 6237],
 [15984, 6182, 11001, 7744],
 [15984, 14214, 504, 16230],
 [15984, 6182, 19445, 16230],
 [15984, 5907, 504],
 [15984, 6182, 11001, 11208],
 [15984, 6182, 11001, 11208],
 [15984, 6182, 11001, 8289],
 [15984, 6182, 11001, 8983],
 [15984, 6182, 11001, 16040],
 [15984, 11516, 10002, 11001],
 [15984, 6182, 11001, 17796, 547, 1421],
 [15984, 6182, 11001, 12329],
 [15984, 6182, 11001, 18459, 3805],
 [15984, 6182, 11001, 10002, 16430],
 [15984, 6182, 11001, 9669],
 [15984, 6182, 11001, 7958, 3775],
 [15984, 6182, 11001, 18330],
 [15984, 6182, 11001, 7958, 5036],
 [15984, 6182, 19445, 16230],
 [15984, 6182, 5439, 6631, 16230],
 [15984, 6182, 11001, 2986],
 [15984, 6182, 11001, 10002, 8705, 16049],
 [15984, 6182, 11001, 4597],
 [15984, 11516, 10002, 11001, 2490],
 [15984, 6182, 11001, 2490],
 [15984, 11516, 10002, 11001, 8705, 9679],
 [15984, 11516, 10002, 11001, 8705, 10499],
 [15984, 6182, 11001, 16355],
 [15984, 6182, 11001, 14521],
 [15984, 6182, 11001, 3163],
 [15984, 6182, 11001, 3163, 14179],
 [15984, 6182, 11001, 7350],
 [15984, 6182, 11001, 1071],
 [15984, 6182, 11001, 11239],
 [15984, 6182, 19445, 16230],
 [15984, 6182, 5439, 6631, 16230],
 [15984, 11516, 18494, 3552],
 [15984, 6182, 18760, 18494, 8543],
 [15984, 5907, 2341],
 [15984, 5907, 8663, 9744],
 [15984, 16806, 16532],
 [15984, 5907, 5701],
 [15984, 12873, 8939, 1563],
 [15984, 12873, 8939, 5129],
 [15984, 12873, 8939, 14316],
 [15984, 12873, 8939, 7663, 8204],
 [15984, 12873, 8939, 547, 13017],
 [15984, 12873, 8939, 16786],
 [15984, 12873, 8939, 16903],
 [15984, 12873, 8939, 232],
 [15984, 14456, 8939, 19720],
 [15984, 12873, 8939, 17474],
 [15984, 19051, 4333, 19051, 4516],
 [15984, 240, 5342, 3349],
 [15984, 4914, 1563],
 [15984, 12951, 11608],
 [15984, 16304, 11608],
 [15984, 16304, 3805],
 [15984, 12951, 5150],
 [15984, 16304, 5150],
 [15984, 12372, 18140],
 [15984, 12372, 18140],
 [15984, 14535],
 [15984, 5244, 15285],
 [15984, 11918, 3805],
 [15984, 10817, 3805],
 [15984, 8813, 6182, 9377],
 [15984, 8813, 6182, 18140, 17500],
 [15984, 8813, 6182, 1242, 18140, 18260],
 [15984, 208, 1563],
 [15984, 2554, 1563],
 [15984, 17796, 12544],
 [15984, 16806, 8939, 11443],
 [15984, 16806, 8939, 9365],
 [15984, 16806, 7868],
 [15984, 1003, 8603],
 [15984, 7566, 3720],
 [15984, 1003, 8603],
 [15984, 1003, 8603, 8814],
 [15984, 7566, 3720, 8814],
 [15984, 10517, 10952, 4780],
 [15984, 116, 10952, 4780],
 [15984, 18760, 739, 8603],
 [15984, 17658, 5048, 1563],
 [15984, 12538, 1563],
 [15984, 15981, 5048, 7663],
 [15984, 15981, 5048, 547],
 [15984, 15981, 13420, 7663],
 [15984, 15981, 13420, 547],
 [15984, 18227, 7663, 1563],
 [15984, 17764, 10002, 1563],
 [15984, 13045, 14508],
 [15984, 7584],
 [15984, 7908],
 [15984, 12188, 3552, 6036],
 [15984, 5792, 3552, 6036],
 [15984, 12188, 8571, 3552],
 [15984, 5792, 8571, 3552],
 [15984, 1563, 8939, 17470],
 [15984, 1563, 8939, 9011],
 [15984, 1563, 9678],
 [15984, 1563, 8939, 18972],
 [15984, 1563, 13612],
 [15984, 1563, 5907, 10045],
 [15984, 1563, 10863],
 [15984, 1563, 5907, 18164],
 [15984, 1563, 5907, 1192],
 [15984, 15667, 10824],
 [15984, 16856, 3805, 15184],
 [15984, 13038, 3805, 15184],
 [15984, 13038, 18247, 17214],
 [15984, 13227, 10002],
 [15984, 16251, 10002],
 [15984, 7581, 5341],
 [15984, 16251, 5341],
 [15984, 16890, 5341],
 [15984, 782, 5341],
 [15984, 15005, 5341],
 [15984, 16405, 5341],
 [15984, 2406, 1563],
 [15984, 3670, 7240, 1563],
 [15984, 5244, 3805],
 [15984, 3592, 3805],
 [15984, 3592, 5150],
 [15984, 5244, 5150],
 [15984, 5150, 1450, 19051, 2303],
 [15984, 5150, 13352],
 [15984, 5150, 12372, 16230],
 [15984, 13252, 12544, 8949],
 [15984, 12544, 15363],
 [15984, 7251, 8939, 14862, 7251, 6266, 8705, 8939, 11074, 8705],
 [15984, 7251, 8939, 14862, 7251, 6266, 8705, 8939, 11074, 1850],
 [15984, 1560, 8939, 17470],
 [15984, 1560, 8939, 9011],
 [15984, 1560, 8939, 3863],
 [15984, 1560, 19051, 12289],
 [15984, 1560, 8939, 14456],
 [15984, 576, 3805],
 [15984, 8504, 3805],
 [15984, 5455, 15658, 18164],
 [15984, 3720, 9145, 18164],
 [15984, 4329, 8705, 3720],
 [15984, 10002, 16962, 5212],
 [15984, 11001, 6182, 10002, 16430],
 [15984, 9679, 10113, 3805],
 [15984, 1003, 8603],
 [15984, 7566, 3720],
 [15984, 18439, 11809, 10313],
 [15984, 2948, 1773],
 [15984, 867, 547, 11163],
 [15984, 16356, 3720],
 [15984, 6443, 8603],
 [15984, 16939, 5150, 9377],
 [15984, 16939, 5150, 5150, 10002, 17500],
 [15984, 16939, 5150, 18140, 17500],
 [15984, 5395, 1563],
 [15984, 11826, 1563],
 [15984, 8124, 7663],
 [15984, 6443, 8603],
 [15984, 17339],
 [15984, 8141],
 [15984, 7240, 8814],
 [15984, 12520, 18760],
 [15984, 7240],
 [15984, 12520],
 [15984, 12520, 8814],
 [15984, 7240, 18459, 5150],
 [15984, 12520, 18459, 5150],
 [15984, 7240, 18459, 3805],
 [15984, 12520, 18459, 3805],
 [15984, 7240, 5239, 13718],
 [15984, 12520, 5239, 13718],
 [15984, 16356, 3720],
 [15984, 18494, 6182, 3552],
 [15984, 18760, 18494, 6182, 8543],
 [15984, 8939, 14862, 3805, 1560, 18494, 3552],
 [15984, 16856, 7663, 5816],
 [15984, 667, 15569, 16616],
 [15984, 18439, 15569, 16616],
 [15984, 13233, 5677, 3349],
 [15984, 13233, 4166, 3349],
 [15984, 13233, 16143, 3349],
 [15984, 13233, 16971, 3349],
 [15984, 13233, 14041, 3349],
 [15984, 13233, 19221, 3349],
 [15984, 13233, 1093, 3349],
 [15984, 2542, 3805],
 [15984, 13728, 3805],
 [15984, 8144],
 [15984, 6182, 3720, 5677, 8144],
 [15984, 9678, 13718, 14456],
 [15984, 14870, 14456],
 [15984, 8144],
 [15984, 3082],
 [15984, 11589, 5907],
 [15984, 195, 5907],
 [15984, 16541, 5907],
 [15984, 371, 5907],
 [15984, 11001, 3805],
 [15984, 11001, 5150],
 [15984, 3294, 5150],
 [15984, 14699],
 [15984, 14699, 7663],
 [15984, 8904],
 [15984, 8904, 7663],
 [15984, 12951, 11608],
 [15984, 14699],
 [15984, 14699, 7663],
 [15984, 15547, 18247, 9238],
 [15984, 15547, 18247, 17393],
 [15984, 18976, 18247, 9238],
 [15984, 18976, 18247, 17393],
 [15984, 3670, 10911, 8603],
 [15984, 3670, 11160, 3720],
 [15984, 504, 7663, 5232],
 [15984, 6483, 7663, 5232],
 [15984, 5342],
 [15984, 504, 12112, 11320],
 [15984, 6483, 12112, 11320],
 [15984, 15031, 4738],
 [15984, 15031, 4738],
 [15984, 5395, 5907],
 [15984, 11826, 5907],
 [15984, 3180, 8603, 17796, 5907],
 [15984, 9904, 3720, 17796, 5907],
 [15984, 5395, 5907],
 [15984, 11826, 5907],
 [15984, 3349, 16541],
 [15984, 14456, 8939, 4597],
 [15984, 14456, 8939, 19384],
 [15984, 14456, 8939, 1837],
 [15984, 14456, 8939, 15363],
 [15984, 14456, 8939, 9669],
 [15984, 14456, 8939, 3805],
 [15984, 14456, 8939, 2986],
 [15984, 14456, 8939, 12628],
 [15984, 5439, 6876],
 [15984, 15960, 7221, 15465],
 [15984, 18616, 12112, 5212],
 [15984, 8514, 7663, 5212],
 [15984, 19132, 5907],
 [15984, 10496, 5907],
 [15984, 10496, 5341],
 [15984, 19132, 5341],
 [15984, 12873, 8939, 3780],
 [15984, 15585, 12873, 8939, 232],
 [15984, 4611, 1563, 504, 13718, 14456],
 [15984, 4611, 504, 1563],
 [15984, 11516, 18494, 333],
 [15984, 6182, 11001, 15363],
 [15984, 6182, 19445, 16230],
 [15984, 6182, 11001, 4597],
 [15984, 6182, 11001, 8705, 9679],
 [15984, 6182, 11001, 2490],
 [15984, 6182, 3720, 10002, 6308],
 [15984, 6182, 3720, 10002, 7869],
 [15984, 6182, 3720, 10002, 18189],
 [15984, 6182, 5048, 6308],
 [15984, 6182, 14074, 3112],
 [15984, 6182, 14074, 17323],
 [15984, 11516, 10091, 18247, 1401, 17796, 12807],
 [15984, 11516, 18494, 15189, 18247, 1401, 17796, 12807],
 [15984, 6182, 11001, 3306, 10002, 3805, 1242, 5439],
 [15984, 11516, 18494, 18739],
 [15984, 11516, 18494, 2771],
 [15984, 6182, 17030, 13402, 686, 12112, 14928],
 [15984, 11516, 10220],
 [15984, 6182, 5439, 11001, 18387, 11971, 16084],
 [15984, 6182, 5439, 11001, 549, 11971, 16084],
 [15984, 6182, 5439, 11001, 17256],
 [15984, 6182, 5439, 11001, 17256, 14179],
 [15984, 6182, 5439, 11001, 11074],
 [15984, 6182, 5439, 11001, 11074, 14179],
 [15984, 6182, 19051, 19799, 5907],
 [15984, 6182, 18760, 18494],
 [15984, 11516, 18494, 17544, 1563],
 [15984, 11516, 12284, 10499, 16230],
 [15984, 6182, 5439, 11001, 19051, 2464, 17839],
 [15984, 6182, 5439, 11001, 19051, 2464, 17839, 14179],
 [15984, 11516, 18494, 11721],
 [15984, 6182, 7663, 1127],
 [15984, 11516, 15681, 5907],
 [15984, 6182, 18760, 18494, 18164],
 [15984, 11516, 12065, 5907],
 [15984, 11516, 12065, 5907],
 [15984, 6182, 11001, 8705, 5937],
 [15984, 6182, 11001, 8705, 5937],
 [15984, 6182, 17876, 18140, 17500],
 [15984, 14456, 854, 3559, 11516, 18140, 10066],
 [15984, 14456, 5439, 854, 18140, 17500],
 [15984, 14456, 5439, 854, 9377],
 [15984, 14456, 5439, 854, 1242, 10002, 17500],
 [15984, 6182, 17876, 9377],
 [15984, 6182, 17876, 1242, 10002, 17500],
 [15984, 14456, 854, 3559, 6182, 1242, 10002, 10066],
 [15984, 11516, 10002, 18494, 16061],
 [15984, 14456, 5439, 7663, 854],
 [15984, 11516, 18494, 8158],
 [15984, 11516, 18494, 1192, 19051, 7731],
 [15984, 6182, 7663, 2792],
 [15984, 6182, 5439, 11001, 19051, 16117],
 [15984, 6182, 5439, 11001, 19051, 3348],
 [15984, 11516, 18494, 17924, 13402, 9847],
 [15984, 11516, 18494, 17114, 5257],
 [15984, 6182, 18760, 18494, 17114],
 [15984, 6182, 18760, 18494, 16260],
 [15984, 6182, 18760, 18494, 16260],
 [15984, 6182, 7663, 1100],
 [15984, 11516, 10002, 18494, 16260, 17233],
 [15984, 11516, 10002, 18494, 16260, 18247],
 [15984, 6182, 3720, 1100],
 [15984, 6182, 5048, 1100],
 [15984, 6182, 13718, 18494, 9726],
 [15984, 6182, 13718, 18494, 16260],
 [15984, 6182, 3720, 18494, 10765],
 [15984, 6182, 3720, 18494, 8134],
 [15984, 6182, 3720, 18494, 9726],
 [15984, 6182, 3720, 18494, 16260],
 [15984, 6182, 16434, 1563],
 [15984, 11516, 18494, 8067],
 [15984, 11516, 18494, 8038, 12711],
 [15984, 11516, 18494, 4479],
 [15984, 6182, 7663, 1698],
 [15984, 11516, 1060, 16786],
 [15984, 11516, 1060, 18062],
 [15984, 11516, 14651],
 [15984, 6182, 5439, 11001, 9679, 13237],
 [15984, 6182, 5439, 11001, 13237],
 [15984, 6182, 16753, 19051, 2303],
 [15984, 6182, 8132],
 [15984, 11516, 9472],
 [15984, 6182, 13091],
 [15984, 11516, 7013],
 [15984, 6182, 17678],
 [15984, 11516, 3177, 14651],
 [15984, 6182, 1508, 8617, 19061],
 [15984, 6182, 1508, 13402, 4061],
 [15984, 6182, 10370, 13045, 9180],
 [15984, 6182, 5576],
 [15984, 11516, 458],
 [15984, 6182, 15780],
 [15984, 11516, 17658, 16254],
 [15984, 6182, 9230],
 [15984, 6182, 9187],
 [15984, 6182, 19445, 13534],
 [15984, 11516, 11079],
 [15984, 6182, 19158],
 [15984, 6182, 19445, 4618],
 [15984, 6182, 9895],
 [15984, 6182, 11001, 15029],
 [15984, 6182, 11001, 18247, 3739],
 [15984, 6182, 11001, 10002, 16325],
 [15984, 6182, 11001, 5103],
 [15984, 6182, 11001, 19078],
 [15984, 6182, 11001, 5397],
 [15984, 6182, 11001, 15173],
 [15984, 6182, 11001, 15071],
 [15984, 6182, 11001, 10002, 325, 10499],
 [15984, 6182, 11001, 17671],
 [15984, 6182, 11001, 17671, 14179],
 [15984, 6182, 11001, 9679, 13237],
 [15984, 6182, 11001, 10425],
 [15984, 6182, 11001, 13180],

In [70]:
decoder_target=[one_hot(word, len(unique_words_output)) for word in decoder_target_data]
decoder_target

[[3727, 19918],
 [1093, 19918],
 [19221, 19918],
 [1560, 19918],
 [5907, 6280, 19918],
 [12112, 5212, 19918],
 [18760, 2341, 19918],
 [19635, 19918],
 [5907, 4033, 19918],
 [15408, 19918],
 [17658, 5048, 8603, 19918],
 [7777, 19918],
 [17859, 19918],
 [10362, 19918],
 [14157, 19918],
 [1873, 19918],
 [2571, 19918],
 [3727, 19918],
 [6182, 11514, 19918],
 [11516, 2026, 19918],
 [11516, 18494, 3552, 19918],
 [6182, 18760, 18494, 8543, 19918],
 [11516, 18494, 3552, 19918],
 [6047, 5257, 19918],
 [19902, 19918],
 [3588, 19918],
 [15893, 19918],
 [14588, 15893, 19918],
 [13328, 19918],
 [3755, 3755, 19918],
 [18760, 739, 8603, 19918],
 [504, 5816, 19918],
 [6483, 18140, 5816, 19918],
 [19554, 18140, 5816, 19918],
 [11516, 18494, 4065, 19918],
 [4228, 19918],
 [4065, 19918],
 [4228, 19918],
 [13718, 15658, 5875, 19918],
 [19203, 19918],
 [10979, 19918],
 [4639, 3805, 11625, 2948, 17472, 19918],
 [11493, 3805, 11625, 15411, 17472, 19918],
 [6182, 11001, 3863, 14179, 19918],
 [6182, 11001, 3863, 19918],
 [6182, 14074, 19918],
 [6182, 11001, 18972, 19918],
 [6182, 11001, 1421, 19918],
 [11516, 18494, 10045, 19918],
 [11516, 18494, 18164, 19918],
 [11516, 18494, 1192, 19918],
 [11516, 18494, 4785, 11233, 19918],
 [6182, 19445, 16230, 19918],
 [5907, 504, 19918],
 [19667, 19918],
 [12873, 8939, 3349, 19825, 19918],
 [19120, 19918],
 [10002, 77, 12756, 19918],
 [5625, 17987, 2253, 19918],
 [12873, 8939, 16323, 17796, 16896, 19918],
 [14456, 240, 10002, 8939, 3349, 16896, 19918],
 [12873, 8939, 13638, 19918],
 [10002, 5566, 6957, 10499, 19918],
 [16323, 17796, 16896, 19918],
 [167, 19918],
 [7655, 19918],
 [6030, 15363, 19918],
 [13328, 19918],
 [6266, 2026, 19918],
 [5150, 16257, 3552, 19918],
 [5150, 3552, 13045, 19918],
 [5150, 18760, 16257, 8543, 19918],
 [5150, 18760, 8543, 13045, 19918],
 [5677, 1563, 19918],
 [3082, 19918],
 [12157, 6443, 19918],
 [18948, 6443, 19918],
 [18948, 16177, 19918],
 [12157, 19051, 16117, 19918],
 [12157, 7780, 19918],
 [18948, 7780, 19918],
 [18948, 2795, 19918],
 [12157, 14896, 19918],
 [18948, 14896, 19918],
 [18948, 2003, 19918],
 [12157, 11746, 19918],
 [12157, 11746, 19918],
 [12157, 4086, 19918],
 [18948, 11746, 19918],
 [18948, 4086, 19918],
 [18948, 10611, 19918],
 [18948, 276, 19918],
 [19051, 14571, 19918],
 [867, 3805, 19918],
 [313, 3805, 19918],
 [867, 5150, 19918],
 [4848, 5150, 19918],
 [5342, 19918],
 [4858, 19918],
 [4858, 19918],
 [5342, 19918],
 [6483, 19918],
 [6483, 19918],
 [7240, 19918],
 [12520, 19918],
 [12951, 11608, 19918],
 [16304, 11608, 19918],
 [12951, 7663, 11608, 19918],
 [16304, 7663, 11608, 19918],
 [504, 5232, 1563, 19918],
 [14256, 19918],
 [236, 19918],
 [14256, 19918],
 [236, 19918],
 [11854, 8603, 19918],
 [19051, 14571, 19918],
 [14926, 19918],
 [504, 5048, 8949, 13626, 19918],
 [14926, 19918],
 [19051, 14571, 19918],
 [5567, 7663, 2105, 19918],
 [14926, 19051, 8814, 19918],
 [504, 13718, 10002, 19918],
 [1397, 19918],
 [6483, 3720, 10002, 19918],
 [617, 547, 11163, 19918],
 [1256, 547, 11163, 19918],
 [1256, 18459, 8603, 19918],
 [617, 18459, 3720, 19918],
 [504, 1549, 19918],
 [6483, 1549, 19918],
 [7804, 19918],
 [547, 10457, 19918],
 [7777, 18247, 10515, 19918],
 [17859, 18247, 10515, 19918],
 [19132, 15363, 19918],
 [10496, 15363, 19918],
 [14456, 14870, 11608, 19918],
 [14456, 5907, 17612, 11608, 19918],
 [14456, 7868, 19918],
 [2341, 3805, 19918],
 [2341, 3805, 19918],
 [5865, 3805, 19918],
 [5865, 5150, 19918],
 [2341, 5150, 19918],
 [13233, 12671, 10952, 19918],
 [13233, 5360, 3349, 19918],
 [13038, 18247, 12873, 5529, 1563, 19918],
 [6182, 11001, 3810, 1242, 5439, 6453, 19918],
 [11516, 18494, 12044, 19918],
 [6182, 5439, 11001, 14177, 19918],
 [6182, 5439, 11001, 2018, 19918],
 [6182, 2934, 19918],
 [6182, 14225, 19918],
 [6182, 3591, 19918],
 [6182, 12385, 19918],
 [6182, 5439, 11001, 5164, 9558, 19918],
 [6182, 5439, 11001, 19414, 9558, 19918],
 [11516, 18494, 5935, 19918],
 [11516, 18494, 9558, 19918],
 [11516, 3291, 19918],
 [11516, 18494, 19248, 19918],
 [11516, 18494, 12810, 19918],
 [11516, 18494, 8663, 15882, 19918],
 [11516, 14651, 19918],
 [6182, 11001, 1563, 19918],
 [6182, 11001, 385, 19918],
 [6182, 11001, 1411, 19918],
 [6182, 11001, 10002, 10482, 19918],
 [6182, 11001, 15908, 19918],
 [6182, 11001, 15908, 14179, 19918],
 [6182, 11001, 4597, 19918],
 [6182, 11001, 17474, 19918],
 [6182, 11001, 7324, 19918],
 [6182, 11001, 6852, 19918],
 [6182, 11001, 6852, 14179, 19918],
 [12873, 8939, 16770, 19918],
 [18413, 3720, 19918],
 [18413, 3720, 5150, 19918],
 [10813, 7663, 19918],
 [12346, 7663, 19918],
 [4914, 3805, 19918],
 [13145, 3805, 19918],
 [3805, 712, 19918],
 [13, 3805, 19918],
 [13, 19918],
 [5607, 19918],
 [10952, 10824, 19918],
 [5239, 13718, 19918],
 [547, 6985, 19918],
 [10952, 19918],
 [10656, 3805, 19918],
 [13121, 3805, 19918],
 [9735, 3720, 19918],
 [16662, 547, 19918],
 [1060, 8603, 19918],
 [16662, 547, 19918],
 [547, 16662, 19918],
 [3349, 4730, 19918],
 [10952, 10824, 19918],
 [15889, 7663, 19918],
 [5776, 7663, 19918],
 [15889, 7663, 19918],
 [5776, 7663, 19918],
 [18227, 3805, 19918],
 [9341, 3805, 19918],
 [1563, 5907, 3552, 19918],
 [9679, 6431, 8603, 19918],
 [9679, 6431, 8603, 19918],
 [9679, 15675, 3720, 19918],
 [9679, 6431, 8603, 19918],
 [9679, 15675, 3720, 19918],
 [10749, 8603, 19918],
 [12434, 3720, 19918],
 [5150, 16539, 19918],
 [5150, 15261, 13045, 19918],
 [5150, 16257, 18164, 19918],
 [5150, 17025, 13045, 11217, 19918],
 [5150, 17025, 13045, 2123, 19918],
 [5150, 17025, 13045, 19051, 9814, 19918],
 [5150, 17025, 13045, 19051, 16856, 19918],
 [5150, 16257, 13718, 19051, 9814, 19918],
 [5150, 16257, 13718, 19051, 16856, 19918],
 [5150, 16257, 13718, 11217, 19918],
 [5150, 16257, 13718, 2123, 19918],
 [11694, 19918],
 [1560, 5907, 3552, 19918],
 [1560, 18760, 5907, 8543, 19918],
 [5455, 1093, 19918],
 [11001, 6182, 1411, 19918],
 [11001, 6182, 8328, 19918],
 [5677, 10194, 19918],
 [18576, 10194, 19918],
 [425, 19918],
 [84, 19918],
 [425, 19918],
 [84, 19918],
 [16201, 8603, 19918],
 [17083, 3720, 19918],
 [12157, 18247, 3739, 19918],
 [18948, 18247, 3739, 19918],
 [12157, 6443, 19918],
 [18948, 6443, 19918],
 [18948, 16177, 19918],
 [5566, 6057, 14179, 19918],
 [11516, 10002, 14074, 13626, 6940, 19918],
 [867, 1563, 19918],
 [4848, 1563, 19918],
 [8238, 19918],
 [19051, 8891, 8603, 19918],
 [7904, 7663, 19918],
 [7731, 19918],
 [3729, 19918],
 [6214, 5076, 19918],
 [14157, 5076, 19918],
 [15547, 1563, 19918],
 [18976, 1563, 19918],
 [9679, 11160, 5341, 19918],
 [9679, 10911, 5907, 19918],
 [18760, 14202, 8603, 19918],
 [12786, 19918],
 [18521, 19918],
 [18760, 14202, 8603, 19918],
 [18760, 18459, 3720, 19918],
 [504, 12759, 18353, 16286, 11516, 18140, 11001, 19918],
 [19051, 14571, 19918],
 [504, 12112, 11195, 19918],
 [12157, 9679, 5108, 19918],
 [4258, 2333, 19918],
 [19554, 18140, 19918],
 [7731, 19918],
 [19554, 18140, 19918],
 [10362, 19918],
 [4258, 2333, 19918],
 [19554, 18140, 19918],
 [16230, 17100, 19918],
 [15363, 17393, 19918],
 [12941, 19499, 19918],
 [5395, 7663, 19918],
 [11826, 7663, 19918],
 [13917, 8603, 16230, 19918],
 [18205, 3720, 16230, 19918],
 [14456, 2026, 19918],
 [14456, 8939, 6852, 19918],
 [2341, 1563, 19918],
 [5865, 1563, 19918],
 [3727, 18439, 17608, 19918],
 [15585, 12873, 8939, 119, 19918],
 [9440, 2762, 19918],
 [15585, 12873, 8939, 12776, 19918],
 [15585, 12873, 8939, 11746, 19918],
 [12873, 8939, 3810, 8838, 19918],
 [15585, 12873, 8939, 1239, 16367, 19918],
 [19051, 2464, 14202, 8603, 19918],
 [2998, 19918],
 [10104, 3720, 19918],
 [14675, 5907, 19918],
 [6182, 1242, 10002, 11001, 16230, 8970, 19918],
 [6182, 1242, 10002, 11001, 16230, 7625, 19918],
 [6182, 18760, 18494, 8663, 19918],
 [12873, 8939, 3805, 1560, 18760, 18494, 8663, 19918],
 [11516, 18494, 12437, 19918],
 [11516, 18494, 19586, 19918],
 [11516, 18494, 4228, 19918],
 [11516, 18494, 4228, 19918],
 [11516, 18494, 5875, 19918],
 [11516, 18494, 2836, 19918],
 [11516, 18494, 13301, 19918],
 [11516, 18494, 9281, 19918],
 [11516, 18494, 9679, 18760, 19918],
 [11516, 18494, 8663, 15882, 17796, 547, 13718, 5048, 19918],
 [11516, 18494, 3177, 5731, 19918],
 [6182, 13718, 18760, 10113, 19918],
 [11516, 18494, 13718, 18760, 14807, 19918],
 [6182, 9697, 19918],
 [6182, 7663, 9697, 19918],
 [6182, 5439, 11001, 8220, 19918],
 [6182, 5439, 11001, 8220, 14179, 19918],
 [6182, 18760, 18494, 16260, 19918],
 [6182, 18760, 18494, 16260, 19918],
 [11516, 18494, 3978, 19918],
 [6182, 11001, 3026, 19918],
 [6182, 11001, 3026, 14179, 19918],
 [11516, 18494, 6942, 19918],
 [6182, 18760, 16890, 19918],
 [11516, 10002, 13038, 18764, 19918],
 [6182, 1242, 10002, 15864, 19918],
 [6182, 10260, 19918],
 [6182, 19445, 774, 19918],
 [11516, 17931, 19918],
 [6182, 11001, 18403, 19918],
 [5439, 9982, 19918],
 [6182, 11001, 3963, 19918],
 [6182, 11001, 17400, 19918],
 [6182, 11001, 17400, 14179, 19918],
 [6182, 11001, 6443, 19918],
 [11516, 18494, 333, 19918],
 [6182, 11001, 19051, 16117, 19918],
 [6182, 11001, 19051, 3348, 19918],
 [6182, 11001, 8112, 19918],
 [6182, 11001, 19743, 19918],
 [11516, 10002, 18494, 16891, 19918],
 [6182, 11001, 7780, 19918],
 [11516, 18494, 547, 19654, 18886, 19918],
 [11516, 18494, 7663, 9784, 6237, 19918],
 [6182, 11001, 7744, 19918],
 [14214, 504, 16230, 19918],
 [6182, 19445, 16230, 19918],
 [5907, 504, 19918],
 [6182, 11001, 11208, 19918],
 [6182, 11001, 11208, 19918],
 [6182, 11001, 8289, 19918],
 [6182, 11001, 8983, 19918],
 [6182, 11001, 16040, 19918],
 [11516, 10002, 11001, 19918],
 [6182, 11001, 17796, 547, 1421, 19918],
 [6182, 11001, 12329, 19918],
 [6182, 11001, 18459, 3805, 19918],
 [6182, 11001, 10002, 16430, 19918],
 [6182, 11001, 9669, 19918],
 [6182, 11001, 7958, 3775, 19918],
 [6182, 11001, 18330, 19918],
 [6182, 11001, 7958, 5036, 19918],
 [6182, 19445, 16230, 19918],
 [6182, 5439, 6631, 16230, 19918],
 [6182, 11001, 2986, 19918],
 [6182, 11001, 10002, 8705, 16049, 19918],
 [6182, 11001, 4597, 19918],
 [11516, 10002, 11001, 2490, 19918],
 [6182, 11001, 2490, 19918],
 [11516, 10002, 11001, 8705, 9679, 19918],
 [11516, 10002, 11001, 8705, 10499, 19918],
 [6182, 11001, 16355, 19918],
 [6182, 11001, 14521, 19918],
 [6182, 11001, 3163, 19918],
 [6182, 11001, 3163, 14179, 19918],
 [6182, 11001, 7350, 19918],
 [6182, 11001, 1071, 19918],
 [6182, 11001, 11239, 19918],
 [6182, 19445, 16230, 19918],
 [6182, 5439, 6631, 16230, 19918],
 [11516, 18494, 3552, 19918],
 [6182, 18760, 18494, 8543, 19918],
 [5907, 2341, 19918],
 [5907, 8663, 9744, 19918],
 [16806, 16532, 19918],
 [5907, 5701, 19918],
 [12873, 8939, 1563, 19918],
 [12873, 8939, 5129, 19918],
 [12873, 8939, 14316, 19918],
 [12873, 8939, 7663, 8204, 19918],
 [12873, 8939, 547, 13017, 19918],
 [12873, 8939, 16786, 19918],
 [12873, 8939, 16903, 19918],
 [12873, 8939, 232, 19918],
 [14456, 8939, 19720, 19918],
 [12873, 8939, 17474, 19918],
 [19051, 4333, 19051, 4516, 19918],
 [240, 5342, 3349, 19918],
 [4914, 1563, 19918],
 [12951, 11608, 19918],
 [16304, 11608, 19918],
 [16304, 3805, 19918],
 [12951, 5150, 19918],
 [16304, 5150, 19918],
 [12372, 18140, 19918],
 [12372, 18140, 19918],
 [14535, 19918],
 [5244, 15285, 19918],
 [11918, 3805, 19918],
 [10817, 3805, 19918],
 [8813, 6182, 9377, 19918],
 [8813, 6182, 18140, 17500, 19918],
 [8813, 6182, 1242, 18140, 18260, 19918],
 [208, 1563, 19918],
 [2554, 1563, 19918],
 [17796, 12544, 19918],
 [16806, 8939, 11443, 19918],
 [16806, 8939, 9365, 19918],
 [16806, 7868, 19918],
 [1003, 8603, 19918],
 [7566, 3720, 19918],
 [1003, 8603, 19918],
 [1003, 8603, 8814, 19918],
 [7566, 3720, 8814, 19918],
 [10517, 10952, 4780, 19918],
 [116, 10952, 4780, 19918],
 [18760, 739, 8603, 19918],
 [17658, 5048, 1563, 19918],
 [12538, 1563, 19918],
 [15981, 5048, 7663, 19918],
 [15981, 5048, 547, 19918],
 [15981, 13420, 7663, 19918],
 [15981, 13420, 547, 19918],
 [18227, 7663, 1563, 19918],
 [17764, 10002, 1563, 19918],
 [13045, 14508, 19918],
 [7584, 19918],
 [7908, 19918],
 [12188, 3552, 6036, 19918],
 [5792, 3552, 6036, 19918],
 [12188, 8571, 3552, 19918],
 [5792, 8571, 3552, 19918],
 [1563, 8939, 17470, 19918],
 [1563, 8939, 9011, 19918],
 [1563, 9678, 19918],
 [1563, 8939, 18972, 19918],
 [1563, 13612, 19918],
 [1563, 5907, 10045, 19918],
 [1563, 10863, 19918],
 [1563, 5907, 18164, 19918],
 [1563, 5907, 1192, 19918],
 [15667, 10824, 19918],
 [16856, 3805, 15184, 19918],
 [13038, 3805, 15184, 19918],
 [13038, 18247, 17214, 19918],
 [13227, 10002, 19918],
 [16251, 10002, 19918],
 [7581, 5341, 19918],
 [16251, 5341, 19918],
 [16890, 5341, 19918],
 [782, 5341, 19918],
 [15005, 5341, 19918],
 [16405, 5341, 19918],
 [2406, 1563, 19918],
 [3670, 7240, 1563, 19918],
 [5244, 3805, 19918],
 [3592, 3805, 19918],
 [3592, 5150, 19918],
 [5244, 5150, 19918],
 [5150, 1450, 19051, 2303, 19918],
 [5150, 13352, 19918],
 [5150, 12372, 16230, 19918],
 [13252, 12544, 8949, 19918],
 [12544, 15363, 19918],
 [7251, 8939, 14862, 7251, 6266, 8705, 8939, 11074, 8705, 19918],
 [7251, 8939, 14862, 7251, 6266, 8705, 8939, 11074, 1850, 19918],
 [1560, 8939, 17470, 19918],
 [1560, 8939, 9011, 19918],
 [1560, 8939, 3863, 19918],
 [1560, 19051, 12289, 19918],
 [1560, 8939, 14456, 19918],
 [576, 3805, 19918],
 [8504, 3805, 19918],
 [5455, 15658, 18164, 19918],
 [3720, 9145, 18164, 19918],
 [4329, 8705, 3720, 19918],
 [10002, 16962, 5212, 19918],
 [11001, 6182, 10002, 16430, 19918],
 [9679, 10113, 3805, 19918],
 [1003, 8603, 19918],
 [7566, 3720, 19918],
 [18439, 11809, 10313, 19918],
 [2948, 1773, 19918],
 [867, 547, 11163, 19918],
 [16356, 3720, 19918],
 [6443, 8603, 19918],
 [16939, 5150, 9377, 19918],
 [16939, 5150, 5150, 10002, 17500, 19918],
 [16939, 5150, 18140, 17500, 19918],
 [5395, 1563, 19918],
 [11826, 1563, 19918],
 [8124, 7663, 19918],
 [6443, 8603, 19918],
 [17339, 19918],
 [8141, 19918],
 [7240, 8814, 19918],
 [12520, 18760, 19918],
 [7240, 19918],
 [12520, 19918],
 [12520, 8814, 19918],
 [7240, 18459, 5150, 19918],
 [12520, 18459, 5150, 19918],
 [7240, 18459, 3805, 19918],
 [12520, 18459, 3805, 19918],
 [7240, 5239, 13718, 19918],
 [12520, 5239, 13718, 19918],
 [16356, 3720, 19918],
 [18494, 6182, 3552, 19918],
 [18760, 18494, 6182, 8543, 19918],
 [8939, 14862, 3805, 1560, 18494, 3552, 19918],
 [16856, 7663, 5816, 19918],
 [667, 15569, 16616, 19918],
 [18439, 15569, 16616, 19918],
 [13233, 5677, 3349, 19918],
 [13233, 4166, 3349, 19918],
 [13233, 16143, 3349, 19918],
 [13233, 16971, 3349, 19918],
 [13233, 14041, 3349, 19918],
 [13233, 19221, 3349, 19918],
 [13233, 1093, 3349, 19918],
 [2542, 3805, 19918],
 [13728, 3805, 19918],
 [8144, 19918],
 [6182, 3720, 5677, 8144, 19918],
 [9678, 13718, 14456, 19918],
 [14870, 14456, 19918],
 [8144, 19918],
 [3082, 19918],
 [11589, 5907, 19918],
 [195, 5907, 19918],
 [16541, 5907, 19918],
 [371, 5907, 19918],
 [11001, 3805, 19918],
 [11001, 5150, 19918],
 [3294, 5150, 19918],
 [14699, 19918],
 [14699, 7663, 19918],
 [8904, 19918],
 [8904, 7663, 19918],
 [12951, 11608, 19918],
 [14699, 19918],
 [14699, 7663, 19918],
 [15547, 18247, 9238, 19918],
 [15547, 18247, 17393, 19918],
 [18976, 18247, 9238, 19918],
 [18976, 18247, 17393, 19918],
 [3670, 10911, 8603, 19918],
 [3670, 11160, 3720, 19918],
 [504, 7663, 5232, 19918],
 [6483, 7663, 5232, 19918],
 [5342, 19918],
 [504, 12112, 11320, 19918],
 [6483, 12112, 11320, 19918],
 [15031, 4738, 19918],
 [15031, 4738, 19918],
 [5395, 5907, 19918],
 [11826, 5907, 19918],
 [3180, 8603, 17796, 5907, 19918],
 [9904, 3720, 17796, 5907, 19918],
 [5395, 5907, 19918],
 [11826, 5907, 19918],
 [3349, 16541, 19918],
 [14456, 8939, 4597, 19918],
 [14456, 8939, 19384, 19918],
 [14456, 8939, 1837, 19918],
 [14456, 8939, 15363, 19918],
 [14456, 8939, 9669, 19918],
 [14456, 8939, 3805, 19918],
 [14456, 8939, 2986, 19918],
 [14456, 8939, 12628, 19918],
 [5439, 6876, 19918],
 [15960, 7221, 15465, 19918],
 [18616, 12112, 5212, 19918],
 [8514, 7663, 5212, 19918],
 [19132, 5907, 19918],
 [10496, 5907, 19918],
 [10496, 5341, 19918],
 [19132, 5341, 19918],
 [12873, 8939, 3780, 19918],
 [15585, 12873, 8939, 232, 19918],
 [4611, 1563, 504, 13718, 14456, 19918],
 [4611, 504, 1563, 19918],
 [11516, 18494, 333, 19918],
 [6182, 11001, 15363, 19918],
 [6182, 19445, 16230, 19918],
 [6182, 11001, 4597, 19918],
 [6182, 11001, 8705, 9679, 19918],
 [6182, 11001, 2490, 19918],
 [6182, 3720, 10002, 6308, 19918],
 [6182, 3720, 10002, 7869, 19918],
 [6182, 3720, 10002, 18189, 19918],
 [6182, 5048, 6308, 19918],
 [6182, 14074, 3112, 19918],
 [6182, 14074, 17323, 19918],
 [11516, 10091, 18247, 1401, 17796, 12807, 19918],
 [11516, 18494, 15189, 18247, 1401, 17796, 12807, 19918],
 [6182, 11001, 3306, 10002, 3805, 1242, 5439, 19918],
 [11516, 18494, 18739, 19918],
 [11516, 18494, 2771, 19918],
 [6182, 17030, 13402, 686, 12112, 14928, 19918],
 [11516, 10220, 19918],
 [6182, 5439, 11001, 18387, 11971, 16084, 19918],
 [6182, 5439, 11001, 549, 11971, 16084, 19918],
 [6182, 5439, 11001, 17256, 19918],
 [6182, 5439, 11001, 17256, 14179, 19918],
 [6182, 5439, 11001, 11074, 19918],
 [6182, 5439, 11001, 11074, 14179, 19918],
 [6182, 19051, 19799, 5907, 19918],
 [6182, 18760, 18494, 19918],
 [11516, 18494, 17544, 1563, 19918],
 [11516, 12284, 10499, 16230, 19918],
 [6182, 5439, 11001, 19051, 2464, 17839, 19918],
 [6182, 5439, 11001, 19051, 2464, 17839, 14179, 19918],
 [11516, 18494, 11721, 19918],
 [6182, 7663, 1127, 19918],
 [11516, 15681, 5907, 19918],
 [6182, 18760, 18494, 18164, 19918],
 [11516, 12065, 5907, 19918],
 [11516, 12065, 5907, 19918],
 [6182, 11001, 8705, 5937, 19918],
 [6182, 11001, 8705, 5937, 19918],
 [6182, 17876, 18140, 17500, 19918],
 [14456, 854, 3559, 11516, 18140, 10066, 19918],
 [14456, 5439, 854, 18140, 17500, 19918],
 [14456, 5439, 854, 9377, 19918],
 [14456, 5439, 854, 1242, 10002, 17500, 19918],
 [6182, 17876, 9377, 19918],
 [6182, 17876, 1242, 10002, 17500, 19918],
 [14456, 854, 3559, 6182, 1242, 10002, 10066, 19918],
 [11516, 10002, 18494, 16061, 19918],
 [14456, 5439, 7663, 854, 19918],
 [11516, 18494, 8158, 19918],
 [11516, 18494, 1192, 19051, 7731, 19918],
 [6182, 7663, 2792, 19918],
 [6182, 5439, 11001, 19051, 16117, 19918],
 [6182, 5439, 11001, 19051, 3348, 19918],
 [11516, 18494, 17924, 13402, 9847, 19918],
 [11516, 18494, 17114, 5257, 19918],
 [6182, 18760, 18494, 17114, 19918],
 [6182, 18760, 18494, 16260, 19918],
 [6182, 18760, 18494, 16260, 19918],
 [6182, 7663, 1100, 19918],
 [11516, 10002, 18494, 16260, 17233, 19918],
 [11516, 10002, 18494, 16260, 18247, 19918],
 [6182, 3720, 1100, 19918],
 [6182, 5048, 1100, 19918],
 [6182, 13718, 18494, 9726, 19918],
 [6182, 13718, 18494, 16260, 19918],
 [6182, 3720, 18494, 10765, 19918],
 [6182, 3720, 18494, 8134, 19918],
 [6182, 3720, 18494, 9726, 19918],
 [6182, 3720, 18494, 16260, 19918],
 [6182, 16434, 1563, 19918],
 [11516, 18494, 8067, 19918],
 [11516, 18494, 8038, 12711, 19918],
 [11516, 18494, 4479, 19918],
 [6182, 7663, 1698, 19918],
 [11516, 1060, 16786, 19918],
 [11516, 1060, 18062, 19918],
 [11516, 14651, 19918],
 [6182, 5439, 11001, 9679, 13237, 19918],
 [6182, 5439, 11001, 13237, 19918],
 [6182, 16753, 19051, 2303, 19918],
 [6182, 8132, 19918],
 [11516, 9472, 19918],
 [6182, 13091, 19918],
 [11516, 7013, 19918],
 [6182, 17678, 19918],
 [11516, 3177, 14651, 19918],
 [6182, 1508, 8617, 19061, 19918],
 [6182, 1508, 13402, 4061, 19918],
 [6182, 10370, 13045, 9180, 19918],
 [6182, 5576, 19918],
 [11516, 458, 19918],
 [6182, 15780, 19918],
 [11516, 17658, 16254, 19918],
 [6182, 9230, 19918],
 [6182, 9187, 19918],
 [6182, 19445, 13534, 19918],
 [11516, 11079, 19918],
 [6182, 19158, 19918],
 [6182, 19445, 4618, 19918],
 [6182, 9895, 19918],
 [6182, 11001, 15029, 19918],
 [6182, 11001, 18247, 3739, 19918],
 [6182, 11001, 10002, 16325, 19918],
 [6182, 11001, 5103, 19918],
 [6182, 11001, 19078, 19918],
 [6182, 11001, 5397, 19918],
 [6182, 11001, 15173, 19918],
 [6182, 11001, 15071, 19918],
 [6182, 11001, 10002, 325, 10499, 19918],
 [6182, 11001, 17671, 19918],
 [6182, 11001, 17671, 14179, 19918],
 [6182, 11001, 9679, 13237, 19918],
 [6182, 11001, 10425, 19918],
 [6182, 11001, 13180, 19918],

In [80]:
decoder_input_data=pad_sequences(decoder_input, maxlen=max_len_output, padding='post')
decoder_input_data.shape

(175621, 55)

In [85]:
decoder_target_data=pad_sequences(decoder_target, maxlen=max_len_output, padding='post')
decoder_target_data.shape

(175621, 55)

In [87]:
from tensorflow.keras.utils import to_categorical

decoder_target_data = to_categorical(
    max_len_output,  # shape: (num_samples, max_len)
    num_classes=len(unique_words_output)     # same as your output layer vocab size
)
decoder_target_data.shape

(19931,)

In [73]:

decoder_inputs = Input(shape=(None,))
embedding_layer_decoder = Embedding(input_dim=len(unique_words_output), output_dim=256)
decoder_embeddings = embedding_layer(decoder_inputs)
decoder_outputs, state_h, state_c = LSTM(256, return_state=True)(decoder_embeddings)

In [74]:
# ===== Encoder =====
encoder_inputs = Input(shape=(None,))   # input is a sequence of word indices
x = Embedding(input_dim=len(unique_words_input), output_dim=127, input_length=max_len_input)(encoder_inputs)

# LSTM encoder
encoder_lstm = LSTM(256, return_state=True)  # return_state gives hidden + cell states
encoder_outputs, state_h, state_c = encoder_lstm(x)

# Encoder states (to pass into decoder)
encoder_states = [state_h, state_c]

/home/hammadali08/.local/lib/python3.12/site-packages/keras/src/layers/core/embedding.py:97: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(

In [75]:
# ===== Decoder =====
decoder_inputs = Input(shape=(None,))  # target sequence input
decoder_embedding = Embedding(input_dim=len(unique_words_output), output_dim=127, input_length=max_len_output)(decoder_inputs)

# LSTM decoder, initialized with encoder states
decoder_lstm = LSTM(256, return_sequences=True, return_state=True)
decoder_outputs, _, _ = decoder_lstm(decoder_embedding, initial_state=encoder_states)

In [76]:
# Final dense layer to predict word probabilities
from tensorflow.keras.layers import Dense
decoder_dense = Dense(len(unique_words_output), activation='softmax')
decoder_outputs = decoder_dense(decoder_outputs)

In [77]:
from tensorflow.keras.models import Model
model = Model([encoder_inputs, decoder_inputs], decoder_outputs)
model.compile(optimizer="adam", loss="categorical_crossentropy", metrics=["accuracy"])

In [88]:
model.fit([input_padding, decoder_input_data], decoder_target_data,
          batch_size=664,
          epochs=2,
          validation_split=0.2)

ValueError: Data cardinality is ambiguous. Make sure all arrays contain the same number of samples.'x' sizes: 140496, 140496
'y' sizes: 19931