In [4]:
import pandas as pd
dataset=pd.read_json('/home/hammadali08/Personal/FYP Datasets/News_Category_Dataset_v3.json',lines=True)
dataset=dataset.head(1000)

In [5]:
dataset.shape

(1000, 6)

In [6]:
from nltk.stem import WordNetLemmatizer
import nltk
import re
import numpy as np
import gensim
from nltk.corpus import stopwords
lemmatizer = WordNetLemmatizer()

In [7]:
corpus = []
for i in range(0, len(dataset)):
    review = re.sub('[^a-zA-Z0-9]', ' ', dataset['headline'][i])
    review = review.lower()
    review = review.split()

    review = [lemmatizer.lemmatize(word) for word in review if word not in set(stopwords.words('english'))]
    review = ' '.join(review)
    corpus.append(review)

In [34]:
from nltk import sent_tokenize
from gensim.utils import simple_preprocess
words=[]
for sent in corpus:
    sent_token=sent_tokenize(sent)
    for sent in sent_token:
        words.append(simple_preprocess(sent))

In [37]:
## Lets train Word2vec from scratch
model=gensim.models.Word2Vec(words,window=5,min_count=2)

In [38]:
def avg_word2vec(doc):
    # remove out-of-vocabulary words
    #sent = [word for word in doc if word in model.wv.index_to_key]
    #print(sent)

    return np.mean([model.wv[word] for word in doc if word in model.wv.index_to_key], axis=0)
    #or [np.zeros(len(model.wv.index_to_key))], axis=0)


from tqdm import tqdm
#apply for the entire sentences
import numpy as np

X = []
for i in tqdm(range(len(words))):
    X.append(avg_word2vec(words[i]))
X

  0%|          | 0/1000 [00:00<?, ?it/s]/home/hammadali08/.local/lib/python3.12/site-packages/numpy/core/fromnumeric.py:3504: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/hammadali08/.local/lib/python3.12/site-packages/numpy/core/_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
100%|██████████| 1000/1000 [00:00<00:00, 7916.86it/s]

[array([-1.6921196e-03,  2.0784950e-03,  3.8814349e-03, -2.7629535e-03,
         9.3014132e-05,  9.6167298e-04, -2.2096403e-03,  2.9958428e-03,
         4.6977033e-03, -2.8722312e-03, -2.1449395e-03, -4.2890650e-03,
        -1.6617781e-03,  1.0750800e-03, -1.2179512e-03, -1.9372813e-03,
        -3.2389434e-03, -1.2493186e-03,  1.2771926e-03,  1.2484988e-03,
         2.6109123e-03,  1.5733488e-03,  4.4209821e-04,  2.2072280e-03,
         2.1083672e-03, -1.4151200e-03,  4.9952767e-04,  5.8912984e-03,
         1.4522159e-03, -2.6346141e-04,  1.1347936e-03,  1.4072629e-03,
        -1.8243060e-03,  5.9361430e-04,  1.5076337e-03, -3.7120797e-03,
         2.6054625e-04, -8.5458643e-04,  6.5410143e-04, -1.4623461e-03,
        -2.4656106e-03, -7.0436019e-04, -3.1714675e-03,  2.2772143e-03,
        -3.7160746e-04, -1.7235487e-03, -9.3436847e-04, -1.3909076e-03,
         5.6403875e-03,  2.0921221e-03,  2.8710980e-03, -1.8718028e-03,
         7.7804155e-04, -2.4812913e-03,  4.0624980e-03,  2.5384305e-03,
        -2.7661442e-03,  1.6876142e-03, -5.1689864e-04,  8.1272173e-04,
        -4.2922278e-03,  1.8652862e-04, -4.2120917e-03, -3.3007795e-03,
        -2.1573964e-03,  3.8154635e-03,  1.1425697e-03, -7.5411977e-04,
        -3.8752537e-03, -7.1616500e-04,  3.3806419e-04,  3.0367114e-03,
         2.2597979e-03, -4.7585639e-04, -1.0964925e-03,  2.0828522e-03,
         4.1642827e-03, -4.8117083e-03, -3.7421957e-03,  1.8281308e-03,
        -3.5489572e-03,  4.2731757e-03, -2.8349434e-03,  5.9026391e-03,
        -1.4358448e-03, -2.9757115e-04,  3.4869406e-03,  2.9017089e-04,
        -2.0239523e-03,  1.9744164e-03, -1.0162743e-03, -2.9158257e-03,
         4.1977642e-04, -1.3952460e-03,  3.1894757e-04,  7.9299352e-04,
         2.5429588e-03,  1.5686179e-03, -4.7374392e-04, -7.8321103e-04],
       dtype=float32),
 array([ 1.98438461e-03, -3.74788907e-03,  2.59529823e-03, -1.83019380e-03,
         1.20704633e-03, -4.71968064e-03, -4.46890335e-04, -5.48765645e-04,
        -2.53545283e-03, -1.95750827e-03,  1.88407989e-03,  3.78608890e-03,
        -1.85317174e-03,  4.86644072e-04,  1.17121264e-04, -3.81720182e-03,
        -1.20472012e-03, -1.19732425e-03, -3.02365585e-03, -3.69159784e-03,
         4.21779556e-03,  5.92138444e-04, -1.91277519e-04,  1.34779990e-03,
        -2.46355473e-03, -2.31123087e-03, -1.26026047e-03,  1.25996675e-03,
         6.75169227e-04, -1.37210160e-03,  3.05416365e-03,  2.37397384e-03,
        -2.04339088e-03, -1.82947796e-03,  3.56578734e-03, -2.07896903e-03,
        -1.14600186e-03, -2.72295740e-03,  2.21356400e-03, -4.29500081e-03,
         2.54349061e-03, -3.47467209e-03, -3.40439752e-03, -5.41027170e-04,
         1.48207357e-03,  2.39378982e-03,  5.43324975e-04,  1.16879400e-03,
         5.48449950e-03,  1.06685038e-03,  9.41777078e-04, -1.59108627e-03,
        -2.39220751e-03, -7.41982367e-04,  1.73140818e-03,  5.63947426e-04,
         3.28974356e-03,  8.91373493e-05,  3.99336265e-03, -1.93278247e-03,
        -3.81120481e-06,  4.72766813e-03, -3.48072057e-03, -8.92014432e-05,
        -1.82012469e-03,  6.12472417e-04, -7.16249051e-04, -2.07382231e-03,
        -6.36549806e-03, -2.48089922e-03, -1.58455118e-03,  1.49609672e-03,
         2.73794401e-03, -5.08131518e-04,  1.67719368e-03,  2.51803314e-03,
         1.92299063e-04, -1.15320273e-03, -1.75453618e-03, -2.21494189e-03,
        -1.94998982e-03, -2.88790761e-04, -2.09536008e-03,  4.04221984e-03,
        -1.40705938e-03, -1.66060182e-03, -3.13255773e-03, -9.11132302e-05,
         1.08315924e-03,  3.58987221e-04,  1.23301195e-03, -1.81263499e-03,
         1.18155789e-03,  5.20663336e-04, -2.00107996e-03, -5.40742709e-04,
         3.29267047e-03,  2.67934520e-04, -9.71059722e-04,  8.18718865e-04],
       dtype=float32),
 array([ 6.1860713e-03,  5.9676780e-03,  1.8460341e-03, -2.0433592e-03,
         2.1110151e-03, -3.2239109e-03,  2.7918568e-05,  5.0389697e-03,
        -1.5305737e-03,  1.6573748e-03, -3.5201807e-03, -7.9967827e-04,
         1.5589910e-03, -3.8843174e-04, -7.6088618e-04, -1.4907910e-03,
        -1.2529517e-03,  3.1031840e-04,  1.6566552e-03, -7.7252281e-03,
         3.3913907e-03,  1.5822145e-03, -4.2527253e-03, -1.4127953e-03,
        -3.5215940e-03, -8.3738216e-04, -1.7520128e-03, -5.1120934e-03,
        -2.8169376e-03, -2.6210933e-04,  8.1513230e-05,  1.4686169e-03,
         9.2561683e-04, -8.6037844e-04, -4.0757019e-04,  5.6613889e-03,
        -3.3455780e-03, -3.7006028e-03,  2.3254075e-03, -4.9427673e-03,
         3.8917561e-03, -2.1149258e-03,  4.2822245e-03, -2.1402093e-03,
         2.7826114e-03, -2.7719634e-03, -4.2547509e-03, -3.0269783e-03,
         1.9637623e-03,  8.0229342e-04, -2.8884849e-03,  1.3848064e-03,
        -2.1078484e-04, -1.0747829e-03,  4.6764039e-03, -8.5585425e-04,
         3.0456972e-04, -6.4153789e-04,  1.3246731e-03, -4.6788943e-03,
         2.5397118e-03,  1.5161224e-03, -1.8492768e-03, -1.3301944e-03,
         3.8477939e-03,  2.9172350e-03,  2.4222657e-03,  6.2171672e-04,
        -3.3158816e-03, -1.1955026e-03, -2.3707647e-03, -4.8642689e-03,
         3.3275955e-04,  1.1885826e-04,  3.7219541e-03,  4.9306988e-03,
         1.8091321e-04,  1.2733246e-03, -3.0155033e-03,  4.9508861e-03,
         3.7582957e-03,  4.1725496e-03, -1.2804666e-03,  2.1682021e-03,
         4.0856279e-03, -7.1085693e-04,  6.3144006e-03,  5.8074971e-03,
         5.4571913e-03,  5.4602773e-04,  1.6477844e-03,  1.8078219e-03,
         2.2715798e-03,  2.9900085e-04,  3.0129158e-03, -1.4348781e-03,
        -4.0281271e-03, -1.5369995e-03,  2.1449756e-05, -1.0591552e-03],
       dtype=float32),
 array([ 5.0722659e-03,  5.6620305e-03, -6.3141144e-04, -4.1023139e-03,
        -1.1632820e-04, -1.2338670e-03,  3.9590365e-04,  3.8321547e-03,
         5.9698883e-04,  1.7620086e-03, -2.1077180e-03, -2.5679646e-03,
         3.3591003e-03, -5.3711981e-05, -1.7852638e-03, -1.8304866e-03,
         2.0454088e-03,  2.5819105e-03, -2.7221535e-05, -5.8125379e-03,
         3.8313544e-03, -1.1272619e-03, -6.5002055e-03, -6.2481547e-04,
        -4.5677181e-03, -2.5571167e-04, -2.4090610e-03, -7.5683980e-03,
        -2.6824924e-03,  5.1773060e-04, -2.3338408e-03,  8.6255913e-04,
         1.7295585e-03, -4.7693625e-03, -3.1292853e-03,  9.3267076e-03,
         5.9837906e-04, -7.4934372e-04, -6.2428846e-04, -3.4217704e-03,
         2.4960993e-03, -3.0543127e-03,  5.0458619e-03, -3.1059973e-03,
         4.3287072e-03, -4.4374224e-03, -2.0597847e-03, -1.4074041e-03,
         2.9380755e-03,  1.8309100e-03, -2.4617705e-03,  1.9278895e-03,
        -1.9565208e-03, -4.5092357e-03,  4.5853211e-03, -2.7518440e-03,
         2.1883841e-03, -3.6817044e-04,  4.1519362e-04, -4.8220195e-03,
         1.8916854e-03, -1.8753654e-03, -3.0150688e-03,  4.2212970e-04,
         4.1214949e-03,  2.3312990e-03,  1.4508164e-03,  2.8631014e-03,
        -4.5578470e-03, -3.0809978e-03,  4.8389705e-04, -2.9006540e-03,
         1.5157117e-03,  2.8276038e-03,  7.4337423e-03,  6.0638241e-03,
         1.3034948e-03,  1.1449249e-03, -5.4773164e-04,  5.7047522e-03,
         4.7540647e-04,  1.9698490e-03, -1.5214778e-03,  8.3195546e-04,
         3.0394425e-03, -2.2502141e-03,  4.9882061e-03,  7.1574552e-03,
         5.9519587e-03,  2.8820126e-03, -6.3269494e-05,  1.9852114e-03,
         7.1352571e-03, -6.4521871e-04,  3.4971791e-03,  1.6354111e-03,
        -2.5555312e-03,  1.1358175e-03,  7.7715877e-04, -7.0804654e-04],
       dtype=float32),
 array([ 5.4853718e-04, -4.6624424e-04, -2.4182606e-03,  4.3196193e-04,
        -7.6723599e-04,  3.2993394e-04,  2.4319685e-03,  1.3467058e-03,
        -6.1887340e-04, -2.5737558e-03, -2.5272240e-05, -2.3081594e-03,
        -3.0726460e-03,  1.4222496e-03,  1.5180119e-03,  1.8512910e-03,
         1.7943238e-03, -1.3906478e-03, -2.1020503e-04, -1.7368963e-03,
         2.0323566e-03,  2.0069694e-03,  1.1535101e-03, -3.3551278e-03,
        -4.4376124e-04,  2.7637649e-04, -4.2695669e-03, -2.2255236e-03,
        -3.1628413e-03,  2.0355375e-03,  2.0944998e-03,  1.2684934e-03,
         2.7846817e-03, -2.9344938e-03,  1.8663933e-03,  1.4836817e-03,
        -6.1565649e-04,  1.0509798e-03, -3.3449633e-03,  1.3387433e-03,
         5.6480817e-03, -1.0589344e-04,  1.4831519e-03,  1.6007585e-03,
        -1.9821003e-03, -8.4820180e-04,  5.9302087e-04,  2.1857000e-03,
         2.6059963e-03, -3.7632242e-04, -2.1471325e-03,  1.1079825e-03,
         2.2896592e-04,  1.8302481e-04, -1.3131524e-03,  2.9126205e-03,
         2.2443726e-03, -5.9443555e-04, -1.3232417e-03,  3.4997256e-03,
         1.6688081e-03,  7.3155836e-04,  1.1810303e-03,  5.9783243e-04,
        -3.5949606e-03,  1.5164820e-03, -2.2514004e-03, -3.7826609e-04,
         1.8527628e-04, -1.1887717e-03,  6.8338669e-04, -7.5153017e-04,
         1.8889649e-03,  4.5966899e-05,  1.2061055e-03,  3.6517668e-03,
         1.5126789e-03, -8.7590754e-04, -2.1554760e-03, -7.2338653e-04,
        -2.9382852e-03,  9.3362958e-04,  2.3038306e-03,  4.3225307e-03,
        -1.8439980e-04,  8.0637611e-04,  4.4040624e-03,  2.0827467e-03,
         1.5013282e-03,  1.1139592e-03,  2.0553828e-03,  1.5156231e-03,
        -2.0829355e-03,  4.4705519e-03,  8.9204748e-04, -8.5919362e-04,
         9.9971110e-04, -3.3708687e-03,  1.2521704e-03,  3.6281133e-03],
       dtype=float32),
 array([ 7.8350655e-04,  2.6033178e-03,  5.2387506e-04,  2.7167825e-03,
        -1.0755592e-03, -9.7612495e-04,  3.1726155e-04,  5.9931409e-03,
         5.8501377e-04, -2.1705097e-04,  1.0228461e-03,  1.2050179e-03,
        -1.3952795e-04,  5.5486746e-03, -1.8566245e-03,  1.4499988e-03,
        -3.2948193e-03, -5.5246516e-03, -3.6069434e-04, -4.2366907e-03,
        -1.4202701e-03,  2.2265890e-04, -2.2279094e-03,  4.9470173e-04,
        -9.5343468e-04,  2.8196024e-03,  1.6980398e-03, -6.1540939e-03,
         2.3882666e-04,  3.7413680e-03,  3.1991166e-03, -1.9170577e-03,
         7.7488850e-04, -4.9780873e-03, -2.2039942e-03,  2.6687228e-03,
        -1.0482427e-03, -1.6734237e-04, -2.6964475e-04, -3.9414312e-03,
        -1.3861415e-03, -6.0864538e-03, -9.6192211e-04,  9.2416577e-04,
         2.6375197e-03,  7.0981128e-04, -4.4288551e-03, -2.4282411e-03,
         1.7453153e-03,  2.2405684e-03,  1.9778258e-03,  2.7983051e-03,
        -3.7431095e-03,  3.7176844e-06, -4.0371739e-04, -2.7593067e-03,
        -5.3548706e-03, -4.1689971e-04, -7.4618203e-03, -7.5816899e-04,
         1.3166281e-03,  1.3920212e-03, -7.5953407e-04,  4.0056375e-03,
        -2.6148327e-03,  9.5040385e-05, -2.5116075e-03,  3.1738091e-04,
        -8.2837831e-04,  4.0379628e-03,  2.8704612e-03,  2.7736009e-03,
        -9.2628226e-04, -2.4965308e-03,  2.7232401e-03, -4.7476315e-03,
         3.5074551e-03, -2.9285576e-03,  4.5787538e-03, -1.7585866e-03,
         1.6545182e-03, -6.2652230e-03,  1.3277865e-03, -8.2000840e-04,
        -1.5416136e-03, -5.2931072e-04, -1.2474667e-03,  3.5547113e-04,
        -1.8785592e-03,  8.0552447e-04,  3.3863762e-03, -7.0030947e-04,
         5.4350100e-03,  7.0527116e-05, -2.5675350e-03,  3.8613854e-03,
        -5.0907223e-03, -2.6194139e-03, -1.0604026e-03,  4.4029090e-03],
       dtype=float32),
 array([ 1.8901337e-03, -4.5067244e-03,  2.7860447e-03, -1.7815436e-03,
        -2.8445444e-03, -2.6890605e-03, -7.9980440e-04, -1.4989473e-03,
         3.6213098e-03, -8.2881458e-04, -1.4302209e-03, -4.1158120e-03,
         1.6698499e-03, -6.9897046e-04, -2.2657627e-04, -1.5891258e-03,
         6.1758264e-04, -1.0199193e-04, -7.1268401e-04, -9.2441443e-04,
         1.0200049e-03,  1.1187026e-03, -1.8606418e-03,  1.7417746e-03,
        -5.0354633e-04,  1.8620903e-04, -2.2371390e-03,  6.4225029e-04,
        -2.4310795e-03,  3.6297871e-03,  1.5386541e-03,  8.9189311e-04,
        -2.5934572e-04, -4.1540973e-03,  1.5854248e-03,  3.4713685e-03,
        -1.5546724e-03, -9.5973496e-04, -2.3467853e-03, -1.1180438e-03,
         3.5560180e-03, -1.7453926e-03, -1.1973510e-03, -2.4807956e-03,
         2.4437641e-03, -3.4751899e-03,  3.0641328e-03, -5.3480611e-04,
         3.8917360e-03, -2.6469582e-03, -3.5586192e-05, -2.9757950e-03,
         2.2996108e-03, -3.4534845e-03, -1.4520705e-03,  3.7849907e-04,
        -2.9984058e-03,  1.8076458e-03, -3.4650922e-05,  1.3251606e-03,
         1.3468692e-03,  9.0485706e-04, -4.2095128e-04,  3.6190092e-04,
        -1.6448732e-03,  4.4937180e-05, -1.8595738e-03, -2.5806145e-03,
        -5.1029166e-03,  1.1845411e-03, -5.7868874e-03,  9.6325864e-05,
         1.0816129e-03,  1.3326366e-03,  6.1444711e-04,  9.9895231e-04,
        -1.0591403e-03, -3.1572862e-03,  7.8735605e-04,  2.1151346e-03,
        -1.5688350e-03, -7.1607583e-04, -2.3587551e-03, -2.1344276e-04,
        -3.6688922e-05,  2.9251021e-03, -1.9964266e-03,  3.7135526e-03,
         3.1092179e-03,  2.7396029e-03,  9.4478315e-04,  1.6082021e-03,
        -2.0049424e-03, -7.3953427e-04,  3.9185183e-03,  1.1519858e-03,
        -9.0811598e-05,  2.0821660e-03, -3.7014877e-04, -2.9000321e-03],
       dtype=float32),
 array([ 1.7322106e-03,  3.6191121e-03, -3.5701611e-03,  2.7865067e-03,
         1.6322788e-03, -1.3373017e-03, -2.9635814e-03,  7.7274052e-04,
         7.1501668e-04,  2.2902016e-03, -2.7766109e-03,  1.0958615e-03,
         3.3209461e-03,  2.9292593e-03,  3.9972556e-03,  1.4079025e-03,
         2.9031505e-04, -7.6607990e-05, -3.3513890e-03, -3.0895495e-03,
        -1.1791026e-03, -1.3279717e-03, -9.5310144e-04,  7.6677493e-04,
         1.6585868e-03, -6.8603654e-04, -1.3546608e-04, -1.6037942e-04,
         1.1565957e-03,  2.0103531e-03,  2.0956043e-03, -8.7330074e-05,
        -1.7344557e-03,  2.1710581e-04,  1.8879538e-03,  1.9797548e-03,
        -5.3746719e-04, -2.8715096e-05,  1.7898947e-03, -4.5624044e-04,
         1.8802953e-03, -9.1293937e-04, -3.1170363e-03,  5.7232445e-03,
         2.2504218e-04, -4.1437568e-03, -1.8777252e-04, -3.4057847e-03,
         1.0545263e-04,  1.8649396e-03,  3.3581519e-04, -3.0423054e-03,
         2.2678338e-03, -3.9483681e-03, -4.8547564e-03, -1.2721651e-03,
        -9.6754095e-04, -3.9452147e-03,  1.5653615e-04,  3.5013608e-03,
        -1.0736580e-03,  4.1710539e-04, -1.9574969e-03, -1.3464143e-03,
         3.3806781e-03, -2.1966426e-03, -1.6916028e-03,  2.8740752e-03,
        -1.7555088e-03, -3.0421978e-03, -5.7052276e-03, -1.3947704e-04,
         3.4434459e-04,  3.8453992e-04, -2.1635504e-03,  1.6196759e-03,
         7.1118199e-03,  8.7775628e-04, -1.1337902e-04,  1.0365711e-03,
        -4.2205420e-03,  4.1765738e-03, -1.4730315e-03,  2.7974672e-03,
        -7.2553777e-03,  3.2627124e-03, -3.1819590e-03, -1.9383866e-03,
         9.5010380e-04, -3.2550127e-03,  4.4823210e-03,  4.9531800e-03,
         9.5163623e-04,  7.0753030e-04,  7.5829290e-03, -4.0076380e-03,
        -3.7364259e-03,  8.2716066e-04,  4.0468848e-03, -4.4441111e-03],
       dtype=float32),
 array([ 3.1561088e-03,  1.7335184e-03, -1.4623024e-03, -3.4304886e-04,
         4.9239630e-03, -2.5164343e-03,  3.5120230e-03,  7.5731362e-04,
        -2.6242691e-03,  2.9171575e-03, -1.9097847e-03, -1.7252468e-03,
         3.1287153e-04,  4.7203479e-03, -1.8503342e-03, -6.6005596e-04,
        -2.5476033e-03,  4.4318670e-03, -4.1796798e-03, -3.2839342e-03,
        -4.0814155e-03,  4.7255987e-03,  3.3996000e-03, -1.4540877e-03,
        -3.5673956e-04,  3.9769942e-04,  1.0526709e-03,  2.3939949e-03,
        -2.1072903e-03,  1.6644408e-04,  2.9615252e-03, -2.4836222e-03,
         2.4744361e-03, -7.6993246e-04,  4.7003254e-04, -1.6460360e-03,
         3.9638984e-03,  3.3262596e-03,  1.5452011e-04, -4.5815781e-03,
         3.3660412e-03, -6.1222870e-04, -3.2185632e-04,  5.8331559e-03,
         8.8619336e-04,  4.0892707e-03,  2.6520735e-03, -2.6675363e-03,
        -1.9013605e-03,  1.7712805e-03, -6.8124168e-04, -6.7584048e-04,
        -3.9117504e-04, -6.3455859e-03, -2.9626701e-03, -2.1977692e-03,
        -3.5536104e-05, -4.7446004e-04, -4.5994855e-03, -1.0083194e-03,
        -1.1114115e-03,  1.7405655e-04,  1.6946953e-03,  5.1663705e-04,
        -1.1248732e-03,  4.2460347e-03,  3.8738712e-03, -3.2043149e-04,
        -1.3783500e-04,  9.8319794e-04, -4.3480447e-03,  1.9474284e-03,
        -1.7290290e-03,  3.8575989e-03,  1.7244279e-03,  1.6021300e-03,
         2.5501554e-03,  5.0264038e-03, -1.1496315e-03,  2.5631068e-03,
         2.6635327e-03, -6.3194305e-04, -5.0168755e-03,  1.9541585e-03,
         4.8355474e-03,  2.3424597e-03, -2.5647646e-04, -1.5236284e-03,
        -3.9229556e-03,  1.0040394e-03,  1.7932597e-04, -2.9757475e-03,
         1.3574809e-03, -3.8548000e-03,  4.0203119e-03,  5.0633051e-03,
        -1.4606458e-03, -2.5211927e-03,  1.4318060e-04, -2.9197328e-03],
       dtype=float32),
 array([-4.4499631e-03,  1.6115032e-03,  1.1582075e-03, -1.6843807e-03,
         9.8857947e-04, -2.2813457e-04,  3.2227964e-03,  1.9544081e-03,
        -1.4850035e-03,  2.1339569e-03, -2.2063169e-03, -4.7114776e-03,
        -3.0766206e-03, -4.4616479e-03, -2.3079470e-03, -4.5203255e-03,
        -4.7005950e-03, -4.5209243e-03,  1.0550747e-03, -4.2379000e-03,
         2.3644569e-03, -4.2380220e-03,  3.0060781e-03,  6.0032069e-04,
        -2.2844018e-03,  1.1083515e-03,  9.7674446e-04, -4.0606069e-03,
        -3.4029486e-03, -3.0923457e-04,  3.4719743e-03,  1.5169907e-03,
         2.6389677e-04, -4.2572841e-03,  8.0490462e-04, -3.0831823e-05,
         1.6716700e-03,  7.6599250e-04, -4.0949355e-03, -3.2165982e-03,
         1.3372892e-03, -6.9692172e-03, -2.0851290e-03,  3.3394934e-03,
        -9.8593220e-05, -3.6883510e-03, -1.1000581e-03, -6.6162007e-05,
         1.7160614e-03, -2.9050279e-06,  3.7146523e-04, -1.2401033e-03,
         2.3087466e-03,  3.0049633e-03, -4.5044292e-03, -2.5965523e-03,
         1.1529629e-03, -2.6993372e-03, -5.3803674e-03, -4.9226702e-04,
         6.6107712e-03, -1.8795669e-03,  1.6754566e-03, -1.0270207e-03,
        -1.0702137e-03,  8.2608574e-04,  1.4918732e-03,  3.2757677e-03,
        -2.0751236e-03,  1.1607643e-03, -2.7883064e-03,  4.4143344e-03,
         3.6041646e-03,  2.6826158e-03,  3.1104814e-03,  1.7767187e-03,
        -1.6060006e-03, -1.5718064e-04,  2.1250453e-03, -3.3090049e-03,
        -1.5864506e-03, -4.9414481e-03, -1.6691386e-03, -1.5295685e-03,
        -2.2879040e-03, -3.0502009e-03,  3.8757399e-03,  5.2509219e-03,
        -5.3499709e-04, -8.8508631e-04,  2.8126144e-03,  4.7947993e-03,
        -1.3431000e-03, -1.0056354e-03,  8.8744145e-03,  2.5578695e-03,
        -4.9895683e-05, -2.1026589e-03,  1.0303035e-03, -2.6574575e-03],
       dtype=float32),
 array([-3.6958158e-03, -4.6972133e-04,  4.4957036e-03,  1.3808266e-03,
        -3.8874182e-03,  1.7276513e-03, -2.7293884e-03,  1.3832934e-05,
        -3.1601791e-03, -5.2817579e-04,  6.8536185e-04, -9.8039419e-04,
         1.4547049e-04,  3.3354664e-03, -4.0759281e-03, -4.9653114e-05,
        -3.9015731e-03, -4.4150616e-04,  3.5006341e-03,  1.4471973e-03,
        -1.8611802e-03,  2.1222997e-03,  5.5127841e-04, -3.1586953e-03,
         2.7673605e-03,  1.6614228e-03,  1.1505483e-03,  4.1544866e-03,
        -1.4786671e-03,  3.6345250e-03, -1.7877503e-03,  3.8546065e-03,
        -2.5233519e-03, -5.2215543e-04, -2.4587109e-03,  1.9581742e-03,
         2.1396110e-04, -1.6585391e-04, -5.3472659e-03, -8.0823398e-04,
         2.7125054e-03, -6.0102819e-03,  1.5279924e-03,  2.6420073e-03,
        -4.3535046e-04, -4.0043229e-03,  6.1506551e-04,  7.7347463e-04,
         5.0858161e-03,  2.6434420e-03, -4.8335148e-03, -2.9408941e-03,
         3.0278985e-03,  5.4129316e-03, -4.8388802e-03,  5.1442074e-04,
        -1.6638222e-03, -1.4518133e-03,  1.7437853e-03,  6.8926270e-04,
        -2.1289920e-03,  9.5177640e-04,  5.0765923e-03, -1.5663470e-03,
         3.8671473e-03, -7.7031821e-04,  1.3144255e-03, -2.0797108e-03,
         3.2079974e-03,  2.7151662e-03, -5.0432226e-03,  2.8713811e-03,
         1.7031817e-03, -2.1083578e-03, -2.3223744e-03,  1.2746713e-03,
         2.9844083e-03, -1.8018268e-03, -2.1265771e-03, -3.4931551e-03,
        -3.0780395e-03,  2.3093191e-03, -2.9517119e-03,  4.9092714e-03,
        -2.8405902e-03,  2.6913657e-04, -3.6705448e-04,  3.6602924e-03,
         2.6973092e-04, -3.5540727e-03, -2.6355593e-03,  7.5384509e-04,

In [60]:
df_list = []
for i in range(len(X)):
    df_list.append(pd.DataFrame(X[i].reshape(1, -1)))

df = pd.concat(df_list, ignore_index=True)
df

/tmp/ipykernel_40536/578229423.py:5: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(df_list, ignore_index=True)

,0,1,2,3,4,5,6,7,8,9,...,90,91,92,93,94,95,96,97,98,99
0,-0.001692,0.002078,0.003881,-0.002763,0.000093,0.000962,-0.002210,0.002996,0.004698,-0.002872,...,-0.001016,-0.002916,0.000420,-0.001395,0.000319,0.000793,0.002543,0.001569,-0.000474,-0.000783
1,0.001984,-0.003748,0.002595,-0.001830,0.001207,-0.004720,-0.000447,-0.000549,-0.002535,-0.001958,...,0.001233,-0.001813,0.001182,0.000521,-0.002001,-0.000541,0.003293,0.000268,-0.000971,0.000819
2,0.006186,0.005968,0.001846,-0.002043,0.002111,-0.003224,0.000028,0.005039,-0.001531,0.001657,...,0.001648,0.001808,0.002272,0.000299,0.003013,-0.001435,-0.004028,-0.001537,0.000021,-0.001059
3,0.005072,0.005662,-0.000631,-0.004102,-0.000116,-0.001234,0.000396,0.003832,0.000597,0.001762,...,-0.000063,0.001985,0.007135,-0.000645,0.003497,0.001635,-0.002556,0.001136,0.000777,-0.000708
4,0.000549,-0.000466,-0.002418,0.000432,-0.000767,0.000330,0.002432,0.001347,-0.000619,-0.002574,...,0.002055,0.001516,-0.002083,0.004471,0.000892,-0.000859,0.001000,-0.003371,0.001252,0.003628
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,-0.000224,0.005231,0.001365,-0.001957,0.000204,0.002336,-0.001827,0.005380,0.002253,-0.000982,...,0.001659,-0.000983,0.005122,-0.001444,0.000293,0.002726,0.000942,0.000421,-0.000267,-0.002971
996,-0.003956,0.002360,0.000243,-0.002932,-0.001079,-0.004802,-0.000447,0.001851,-0.002673,-0.000905,...,-0.000659,0.001369,-0.002304,0.002567,0.003615,-0.001689,0.004574,0.000007,-0.001543,-0.003086
997,0.000249,0.001959,0.004581,-0.001466,0.001937,-0.002239,0.000344,-0.001580,-0.000349,-0.004969,...,-0.000142,0.001420,-0.002876,-0.000320,0.001499,0.000786,-0.001490,0.000840,0.000955,-0.005181
998,0.004997,-0.002942,0.003928,0.001445,-0.001802,-0.004976,-0.001886,0.001343,-0.002747,-0.001113,...,0.002659,0.004035,0.001571,-0.003239,-0.000814,0.004924,0.001295,-0.000343,0.001765,-0.000232
999,0.000541,0.000171,0.000161,0.000679,0.001900,-0.000739,-0.002198,0.001902,0.001161,-0.000334,...,0.001914,-0.001859,0.000113,-0.000922,-0.001012,0.001736,-0.001618,0.002927,-0.002067,-0.002615

# Output Preprocessing

In [35]:
corpus1 = []
for i in range(0, len(dataset)):
    review1 = re.sub('[^a-zA-Z0-9]', ' ', dataset['short_description'][i])
    review1 = review1.lower()
    review1 = review1.split()

    review1 = [lemmatizer.lemmatize(word) for word in review1 if word not in set(stopwords.words('english'))]
    review1 = ' '.join(review1)
    corpus1.append(review1)

In [36]:
decoder_input_data = ["<start> " + txt + "" for txt in corpus1]
decoder_target_data= ["" + txt + " <end>" for txt in corpus1]
decoder_input_data

['<start> health expert said early predict whether demand would match 171 million dos new booster u ordered fall',
 '<start> subdued passenger crew fled back aircraft confrontation according u attorney office los angeles',
 '<start> dog understand could eaten',
 '<start> accidentally put grown toothpaste toddler toothbrush screamed like cleaning teeth carolina reaper dipped tabasco sauce',
 '<start> amy cooper accused investment firm franklin templeton unfairly firing branding racist video central park encounter went viral',
 '<start> 63 year old woman seen working south carolina store thursday found dead monday family reported missing authority said',
 '<start> behind anchor new york pix11 asked journalist michelle ross finished interview',
 '<start> half million people remained without water service three day storm lashed u territory',
 '<start> mija director isabel castro combined music documentary style euphoria clueless tell nuanced immigration story',
 '<start> white house official say crux president visit u n year full throated condemnation russia brutal war',
 '<start> fifa come pressure several european soccer federation want support human right campaign discrimination world cup',
 '<start> incident underscore growing wave protest funeral shinzo abe one divisive leader postwar japanese politics',
 '<start> hurricane fiona lashed turk caicos island forecast squeeze past bermuda later week',
 '<start> one man claim scammed people platform caused several popular streamer consider twitch boycott',
 '<start> conservative activist virginia thomas wife supreme court justice clarence thomas agreed participate voluntary interview house panel investigating jan 6 insurrection',
 '<start> polyakov record breaking trip outer space saw orbit earth 7 075 time travel nearly 187 million mile',
 '<start> starring keegan michael key judy greer johnny knoxville hulu show follows revival fictional early 2000s sitcom',
 '<start> maury will helped los angeles dodger win three world series title base stealing prowess died',
 '<start> concerted quickening kremlin backed effort swallow four region could set stage moscow escalate war',
 '<start> turk caicos island government imposed curfew intensifying storm kept dropping copious rain dominican republic puerto rico',
 '<start> past 18 month hollywood effectively boycotted globe report hfpa 87 member non american journalist included black member',
 '<start> president issue vow tension china rise',
 '<start> storm knocked power grid unleashed flood landslide puerto rico governor said damage catastrophic',
 '<start> single engine plane participating national championship air race sunday crashed field killing pilot official said',
 '<start> annual celebration took different feel russia invasion dragged day 206',
 '<start> mark frerichs navy veteran civilian contractor kidnapped afghanistan january 2020',
 '<start> la vega never professional sport champion sunday',
 '<start> president joe biden first lady jill biden among thousand mourner local tourist royal world leader pay respect',
 '<start> avatar director said aspect 2009 movie still competitive everything day',
 '<start> alain robert known french spider man climbed burj khalifa empire state building',
 '<start> u president joe biden london funeral queen elizabeth ii say heart went royal family adding queen death left giant hole',
 '<start> despite entering false information work redone fully case census taker received bonus office inspector general reported',
 '<start> monday world first public database fossil fuel production reserve emission launch',
 '<start> 19 year old reportedly fled thames failed bid escape police',
 '<start> 10 year people referring september 2022 storm benchmark storm',
 '<start> puerto rico hurricane watch saturday storm barreled towards u territory',
 '<start> world health organization raising alarm second disaster wake deadly flood pakistan summer doctor medical worker ground race battle outbreak waterborne disease',
 '<start> study repeatedly shown ending public administration water supply work table mississippi',
 '<start> never history duesseldorf custom office trail slime led u smuggled good spokesman michael walk told medium',
 '<start> director original 1982 film join writer 2017 sequel newest installment sci fi franchise',
 '<start> republican outrage shoddy u withdrawal afghanistan spurred support resettling refugee',
 '<start> sarah collins rudolph lost eye piece glass inside body ku klux klan bombing killed sister three black girl inside alabama church 59 year ago',
 '<start> boil water advisory lifted mississippi capital state stop handing free bottled water saturday',
 '<start> phantom opera broadway longest running show scheduled close february 2023 victim post pandemic softening theater attendance new york',
 '<start> former white house chief staff turned record part federal investigation jan 6 2021 assault capitol',
 '<start> colombian american author new book lightlark rejected numerous time went directly reader support',
 '<start> mykel gordon rushed woman aid held assailant police arrived remarkably first time gordon may saved life',
 '<start> oscar winner said worked five hour day role new action movie',
 '<start> reality star told james corden branching clearly working whatever',
 '<start> la vega podcasters hoping find shot rap icon 26 year ago',
 '<start> grammy winning rapper surprised star struck child alexander macomb school morris height make announcement',
 '<start> richardson former u ambassador united nation frequent emissary hostage negotiation held meeting russian leader',
 '<start> television award ceremony lost roughly 1 5 million viewer compared 2021 program',
 '<start> white house press secretary karine jean pierre said rail shutdown acceptable would harm family well business',
 '<start> state general treasurer slated face former cranston mayor allan fung r general election',
 '<start> u firm monitor false online claim report search information prominent news topic tiktok likely turn result riddled misinformation',
 '<start> monthly basis price rose 0 1 flat reading july',
 '<start> director best known groundbreaking movie breathless',
 '<start> pressing salary increase say help improve patient care resolving understaffing stress worsened pandemic',
 '<start> cancer discriminate red blue president said monday beating cancer something together',
 '<start> field gonna play scott told fox news sunday',
 '<start> race organizer say nonbinary athlete register men woman division provided qualifying time guide training',
 '<start> varvaro pitched mostly atlanta brave started law enforcement career 2016',
 '<start> democrat state moderate house district deciding take popular republican former mayor',
 '<start> biden plan draw attention new federally backed study seek validate using blood test screen multiple cancer',
 '<start> research based artist found dynamic way confront conversation female empowerment motherhood labor artwork',
 '<start> sensationalizing even tarnishing reputation sidney poitier rather new documentary honor humanity every facet',
 '<start> carlos alcaraz defeated casper ruud u open final earn first grand slam age 19 become youngest man move 1 ranking',
 '<start> firefighter made progress huge northern california wildfire still growing threatening thousand mountain home',
 '<start> president joe biden marked 21st anniversary sept 11 attack taking part somber wreath laying ceremony held pentagon steady rain',
 '<start> september 11th remains point reflection 2001 attack reconfigured national security policy spurred u war terror worldwide',
 '<start> plant one 10 biggest atomic power station world occupied russian force since early war marked 200th day sunday',
 '<start> visa adoption significant largest payment network likely add pressure mastercard american express adopt code well',
 '<start> justice department proposed two retired judge role trump team proposed retired judge lawyer',
 '<start> director told audience super excited finally finishing movie two three additional installment work',
 '<start> russia defense ministry announced troop pulled back two area ukrainian counter offensive made significant advance',
 '<start> 10 day heat wave nearly overwhelmed electrical grid southern california got cooler weather also ferocious tropical storm',
 '<start> ukrainian force claiming new success counteroffensive russian force east',
 '<start> please join round applause 70 year service pop star told crowd paused madison square garden performance',
 '<start> derrell mcdavid testimony could major blow r b singer hope acquittal',
 '<start> british international newspaper honor passing u k longest reigning monarch',
 '<start> 19 year old singer dancer youtube icon receive 2022 gamechanger award focus anti bullying effort',
 '<start> speaking islamabad antonio guterres said country bearing responsibility climate change faced challenge',
 '<start> clark county public administrator robert telles arrested fatal stabbing jeff german investigating office',
 '<start> internet ignited approval former first lady hairstyle choice monumental day',
 '<start> actor said badly concussed shooting series finale feared life holding onto wall recovering',
 '<start> opponent measure claimed typo made qualifying petition incomprehensible state highest court rejected argument',
 '<start> lawsuit say allowing homeless people tent block city sidewalk make difficult people using wheelchair walker cane use',
 '<start> fire thuan city began late tuesday trapped worker customer inside multi story venue',
 '<start> mlb player association finally member afl cio affiliating 57 union across industry',
 '<start> 200 scripted show researcher analyzed muslim character typically violent dehumanized disparaged existed',
 '<start> state cutting back congress unlikely step even pandemic exposed unemployment system shortcoming',
 '<start> airport official austin texas say early morning power outage causing flight delay even electricity restored',
 '<start> head international atomic energy agency warned u n security council something catastrophic could take place zaporizhzhia',
 '<start> attack become growing threat u school several high profile incident reported since last year',
 '<start> second fire killed two people northern california weekend',
 '<start> detroit tiger rookie utility player got pressed relief pitching duty 10 0 loss angel',
 '<start> city remains boil water notice first went effect july 30',
 '<start> social medium giant fined violation data privacy law related information child instagram',
 '<start> new high fencing around texas community public school still finished heavy police patrol many family trust',
 '<start> finding come biden administration confirmed russian military august took delivery iranian manufactured drone use ukraine',
 '<start> singer said also see many parallel music acting',
 '<start> jocelyn benson said misinformation fuel potential additional threat harassment even violence election day',
 '<start> cloudflare ceo matthew prince previously resisted call block site',
 '<start> welcome yard long kill family homeowner quipped',
 '<start> elsa avila look scar run torso help remember may 24 gunman stormed fourth grade wing robb elementary uvalde texas killing 19 child two teacher leaving others wounded',
 '<start> tim michels call supporter go medium following milwaukee journal sentinel story reporting multimillionaire donation anti abortion group',
 '<start> police tennessee say arrest made disappearance woman abducted jogging',
 '<start> resident mississippi majority black capital still clean water rain worsened existing infrastructure',
 '<start> authority warn flooding expected lake manchar swell unprecedented monsoon rain killed nearly 1 300 people',
 '<start> student survived may 24 shooting robb elementary texas spending summer host mental health issue including ptsd',
 '<start> thunderstorm heavy rain pounded part northwest georgia sunday sparking flash flooding dangerously high water area',
 '<start> millennials might remember family mtv reality series early 2000s bbc series filmed 350 acre osbourne estate england',
 '<start> pilot arrested circling small airplane tupelo mississippi threatening crash walmart store',
 '<start> part space agency artemis program rocket powerful date',
 '<start> tragic toll followed hazardous crossing desperate dozen said official',
 '<start> nashua police charged chanphanou sab pou three misdemeanor count violation privacy could face one year jail charge',
 '<start> cipollone former deputy patrick philbin also reportedly scheduled provide testimony grand jury friday',
 '<start> storm first hurricane unusually quiet storm season centered 885 mile west azores',
 '<start> low key funeral reflects kremlin uneasiness legacy gorbachev despised many home collapse soviet union',
 '<start> inaugural flight 322 foot artemis rocket powerful ever built nasa delayed late countdown monday',
 '<start> unemployment rate rose 3 7 half century low 3 5 july american came sideline look job',
 '<start> brandy bottone referred roe v wade texas penal code identifies unborn child individual first stopped using lane',
 '<start> freezer overflowing tired carrying around ice pack bottle pumped milk option could',
 '<start> nun held kidnapper nearly five month following armed raid burkina faso home',
 '<start> plaque show hooded man holding weapon',
 '<start> unprecedented red tide creating foul odor may get worse oncoming heat wave',
 '<start> stay missed artist reflects pushing culture female singer songwriter expected fit certain mold make big',
 '<start> 36 page filing described trump representative hand classified material property',
 '<start> soviet union last leader reportedly earned nearly 1 million even though refused eat pizza camera',
 '<start> gop continuing contort defense donald trump despite new information relating classified document held florida estate',
 '<start> biggest secret world steve doocy said response ex president keeping top secret document private residence',
 '<start> prosecutor rested case singer stand accused producing child sexual abuse video latest trial',
 '<start> one thing another donald trump problem plagued truth social',
 '<start> beyond toothache common red flag dealing nighttime teeth grinding',
 '<start> going play nine inning artemis mission manager said first launch scrubbed',
 '<start> ornato one point served white house political adviser said witnessed trump lunge secret service agent capitol attack',
 '<start> hbo release six part follow series beginning october infamous sex cult led keith raniere',
 '<start> mom dysphoric milk ejection reflex mer feel intense brief wave depression anxiety negative emotion letdown common might think',
 '<start> tiktok star mom sheri easterling betty rapper made romance public ex monty lopez happy',
 '<start> house member supposed use proxy voting cannot present due covid 19 stopping representative voting remotely campaign trail',
 '<start> republican including believe come trump law graham said fox news getting',
 '<start> pirate caribbean actor appeared virtually mtv video music award moon person sunday night',
 '<start> actor made first camera appearance since defamation verdict ex wife amber heard june',
 '<start> singer channeled inner barb danced along lizzo fangirled blackpink',
 '<start> pakistani authority reported casualty since monsoon season began earlier normal year destroying nearly 300 000 home',
 '<start> celebrity showed showed award sunday night new jersey',
 '<start> man hired organize looked like mass shooting charged multiple terrorism count',
 '<start> message posted truth social patel called vicious attack doj fbi',
 '<start> startling case underscore security challenge donald trump resort even former president stashed top secret u government file',
 '<start> butler told pitchfork consensual relationship outside marriage disputed detail allegation',
 '<start> hang mr president goof one die hard fan',
 '<start> former president legal team followed judge order polish filing fbi seizure government document estate',
 '<start> six 43 student kidnapped 2014 kept alive day handed local army commander ordered killed according new report',
 '<start> nebraska man said initially believed underwater find skeleton catfish deer',
 '<start> nasty',
 '<start> one safe speed roast targeting politician',
 '<start> heavily redacted document lay justification department justice provided judge permission search seize highly classified document fbi raid trump florida home',
 '<start> major vendor claim stiffed trump social medium operation suggesting finance significant disarray reported fox business',
 '<start> two mad marsupial went canberra nature reserve',
 '<start> american company including federal contractor continue buy everything birch wood flooring weapon grade titanium russian corporation',
 '<start> ban set take effect friday two month supreme court overturned roe v wade',
 '<start> follow footstep rei worker new york city formed union earlier year',
 '<start> judge presiding special grand jury investigating possible illegal attempt influence 2020 election georgia',
 '<start> national police agency chief itaru nakamura announcement came agency released report failed protect abe life july 8',
 '<start> lawsuit look name law enforcement agency shop accused shooter bought gun used uvalde shooting',
 '<start> congressional race officially called rival yuh line niou declined concede',
 '<start> five term house member known staunch president biden critic loyal donald trump supporter',
 '<start> crist making second run governor democrat served one term job republican decade ago',
 '<start> internal revenue service say conducting comprehensive review safety facility',
 '<start> biden plan survives legal challenge almost certain come could offer windfall swath nation run fall midterm election',
 '<start> game throne spinoff pulled largest audience original series premiere hbo history',
 '<start> former louisville police detective helped falsify warrant led deadly police raid taylor apartment pleaded guilty federal charge',
 '<start> rock roll hall fame member also co wrote classic song like day peggy sue',
 '<start> actor revealed abstained sex month starved prepare role',
 '<start> hanged yet arizona gop leader told guardian powerful interview holy moly crazy place lost mind',
 '<start> precise detail president joe biden plan kept unusually small circle within biden administration',
 '<start> democrat cusp transforming paid leave child care home care figuring came short might get opportunity try',
 '<start> 60 minute program described satirical send life time duke set musical score',
 '<start> class scheduled resume two day',
 '<start> russian invasion ukraine began feb 24',
 '<start> jennifer granholm said u produce record amount oil next year',
 '<start> charge accuse khan threatening police officer judge country sedition act',
 '<start> minneapolis teacher settled 14 day strike earlier year celebrated groundbreaking provision new contract meant shield teacher color traditional seniority based layoff',
 '<start> native hawaiian say use sacred mauna kea summit scientist',
 '<start> francesca teal plea help facebook got attention local man spent two day searching water wetsuit headlamp metal detector',
 '<start> leon vitali barry lyndon actor became one stanley kubrick closest associate died',
 '<start> idris elba may go head head lion beast action flick match latest dragon ball movie',
 '<start> nikolas cruz attorney monday present 23 year old carried attack make case life prison instead death',
 '<start> voting right group dismayed ruling upholds ban giving drink snack people waiting vote',
 '<start> court said woman legal parent daughter born transition one born afterward',

In [45]:
words_output_input=[]
for sent in decoder_input_data:
    sent_token=sent_tokenize(sent)
    for sent in sent_token:
        words_output_input.append(simple_preprocess(sent))

In [46]:
words_output_target=[]
for sent in decoder_target_data:
    sent_token=sent_tokenize(sent)
    for sent in sent_token:
        words_output_target.append(simple_preprocess(sent))

In [47]:
model_output=gensim.models.Word2Vec(words_output_input,window=5,min_count=2)

In [48]:
def avg_word2vec_output(doc_output):
    # remove out-of-vocabulary words
    #sent = [word for word in doc if word in model.wv.index_to_key]
    #print(sent)

    return np.mean([model_output.wv[word]for word in doc_output if word in model_output.wv.index_to_key],axis=0)
                           #or [np.zeros(len(model.wv.index_to_key))], axis=0)

In [50]:
Y_decoder_input_data = []
for i in tqdm(range(len(words_output_input))):
    Y_decoder_input_data.append(avg_word2vec_output(words_output_input[i]))
Y_decoder_input_data

100%|██████████| 1000/1000 [00:00<00:00, 4721.33it/s]

[array([-0.00995481,  0.01255069,  0.00248424,  0.00274645, -0.00113236,
        -0.02029816,  0.00578677,  0.02837395, -0.01379669, -0.010314  ,
        -0.00523877, -0.01965367,  0.00021725,  0.00293196,  0.0085965 ,
        -0.01065332,  0.00719154, -0.0132163 ,  0.00054096, -0.02466753,
         0.00170329,  0.00599145,  0.01076173, -0.00994472, -0.00306757,
        -0.0088687 , -0.01779817, -0.00885704, -0.01168091,  0.00640739,
         0.0080679 ,  0.0018776 ,  0.00486152, -0.01260315, -0.00843052,
         0.01799867,  0.00155224, -0.01707185, -0.00361557, -0.02357236,
        -0.00441941, -0.00929202, -0.00460561,  0.00399182,  0.009019  ,
        -0.00628071, -0.0147532 , -0.0043939 ,  0.00432628,  0.00953387,
         0.00455845, -0.00586212, -0.00689808,  0.00257978, -0.00991385,
         0.00833921,  0.00818354, -0.0064026 , -0.0169968 ,  0.00773275,
         0.00256443,  0.00278742, -0.00327614, -0.00128959, -0.0190476 ,
         0.0112001 , -0.00182214,  0.00719454, -0.01398513,  0.01531892,
        -0.00779763,  0.00640537,  0.01175906, -0.00715104,  0.01454247,
         0.0061029 , -0.00193355,  0.00027238, -0.0066107 , -0.00445677,
        -0.0023457 , -0.0030575 , -0.0060776 ,  0.01805774, -0.00279526,
        -0.00261148,  0.00305595,  0.01544417,  0.01544917,  0.007484  ,
         0.01915988,  0.01034453,  0.00842541,  0.00023759,  0.02269863,
         0.01228322,  0.00220047, -0.01972837, -0.00321621,  0.00095508],
       dtype=float32),
 array([-7.1884906e-03,  9.9790702e-03,  5.4600975e-03,  5.1373439e-03,
        -5.4786373e-03, -1.8264130e-02,  5.1669683e-03,  2.3589373e-02,
        -1.0809917e-02, -3.3467291e-03, -6.8771695e-03, -1.3356366e-02,
         2.3779131e-03,  1.9415899e-03,  7.0207287e-03, -9.7366832e-03,
         6.7541632e-03, -1.0701517e-02,  1.5509640e-03, -2.0192867e-02,
         1.0275611e-03,  7.5677771e-04,  3.9380044e-03, -3.8066432e-03,
        -4.9730460e-03, -3.5569023e-03, -1.3745684e-02, -5.2816924e-03,
        -9.1554131e-03,  3.6405278e-03,  3.2467572e-03,  2.3330103e-03,
         5.2406341e-03, -1.0750297e-02, -6.3674739e-03,  1.3411241e-02,
         1.7259208e-03, -1.4470854e-02, -3.2246704e-03, -1.8895661e-02,
        -7.6005734e-03, -7.7972179e-03, -7.5929603e-03,  1.0497788e-03,
         4.7739493e-03, -9.6714478e-03, -1.4751230e-02, -6.9863693e-04,
         4.0399646e-03,  9.4964430e-03,  3.1924297e-03, -5.6892885e-03,
        -4.9312357e-03,  2.8599028e-03, -5.9876190e-03,  4.5025116e-03,
         7.6938560e-03, -5.8602067e-03, -1.2054182e-02,  6.3171587e-03,
         1.6787105e-03,  5.5714333e-03, -2.9336242e-03, -7.2084856e-04,
        -1.5828639e-02,  1.2288660e-02,  2.6051183e-03,  5.5781021e-03,
        -1.1427546e-02,  1.1920903e-02, -4.7464576e-03,  3.2321485e-03,
         1.0966194e-02, -9.6138455e-03,  1.1652818e-02,  7.5944718e-03,
        -7.1402123e-05, -1.7363434e-03, -3.9840699e-03, -3.6432007e-03,
        -1.8826739e-03, -1.6916431e-03, -4.5705386e-03,  1.5639523e-02,
        -2.6833988e-03, -1.1387339e-03,  4.8006568e-03,  1.1693606e-02,
         1.5476856e-02,  4.5945835e-03,  1.9381216e-02,  8.5754432e-03,
         6.5742796e-03, -1.7750880e-03,  2.0104203e-02,  6.3381041e-03,
        -2.1338968e-03, -2.0095496e-02, -4.9431837e-04,  1.1480731e-03],
       dtype=float32),
 array([-0.01853874,  0.01784325,  0.00664317,  0.00140794, -0.00196292,
        -0.03703123,  0.01089772,  0.04200987, -0.02469927, -0.01354343,
        -0.008699  , -0.0314189 , -0.00534743,  0.00176476,  0.00776146,
        -0.01750324,  0.00791487, -0.01823978,  0.00094759, -0.04345233,
         0.00357781,  0.0064165 ,  0.01805165, -0.01309932, -0.00699047,
        -0.00670149, -0.03252201, -0.01323032, -0.01972886,  0.00743791,
         0.01134908,  0.00391564,  0.01226262, -0.02029874, -0.01720942,
         0.02435254, -0.00447794, -0.02630655, -0.00890764, -0.04001737,
        -0.00652916, -0.00678076, -0.00695827,  0.00606789,  0.01114357,
        -0.01205825, -0.02006699, -0.00922371,  0.00633162,  0.01947123,
         0.00310812, -0.01079839, -0.00803417,  0.00656134, -0.01669814,
         0.00780899,  0.01132936, -0.01281505, -0.02053521,  0.00913641,
         0.00396827,  0.00172192, -0.00303734,  0.00161577, -0.02797347,
         0.01648305, -0.0016691 ,  0.0104196 , -0.0233523 ,  0.02245511,
        -0.00678861,  0.0154212 ,  0.02181309, -0.01562334,  0.02491312,
         0.01337045, -0.00648424, -0.00061935, -0.01835072, -0.00477549,
        -0.00384271, -0.00094668, -0.01073829,  0.03212231, -0.00376492,
        -0.00850933,  0.00238334,  0.0238917 ,  0.01784711,  0.00780972,
         0.03326001,  0.01228602,  0.01445892, -0.00077297,  0.03986741,
         0.01528599,  0.00192673, -0.0293399 , -0.00602318, -0.00434586],
       dtype=float32),
 array([-0.01268006,  0.01527408,  0.00417877,  0.00599545,  0.00039124,
        -0.02353999,  0.00392484,  0.03445574, -0.01963256, -0.00735906,
        -0.0070394 , -0.02721518, -0.00041397, -0.00027483,  0.01124659,
        -0.01417696,  0.00498836, -0.01953388,  0.00371455, -0.03275349,
         0.00610266,  0.0086468 ,  0.01538841, -0.0100734 , -0.00570818,
        -0.00939172, -0.01836224, -0.01035748, -0.01513011, -0.0002355 ,
         0.00571233,  0.00184276,  0.00749352, -0.01576835, -0.01250756,
         0.02440205, -0.00328039, -0.02007503, -0.00991454, -0.02814762,
        -0.0027915 , -0.0094612 , -0.00885843,  0.00571567,  0.00333002,
        -0.01446519, -0.01787012, -0.00720128,  0.00152368,  0.00919058,
         0.00545969, -0.00504525, -0.00946113,  0.00021653, -0.00677631,
         0.00634784,  0.01394911, -0.00699533, -0.01890758,  0.0118493 ,
         0.00487043,  0.00106988, -0.00259217, -0.00437413, -0.01631336,
         0.01696936, -0.00245374,  0.00911932, -0.01961457,  0.01625702,
        -0.0086118 ,  0.01496444,  0.012978  , -0.01103013,  0.02132988,
         0.00634667, -0.00301434, -0.00156657, -0.00962384, -0.00287806,
        -0.00112083, -0.00074268, -0.00746   ,  0.02017907, -0.00332013,
        -0.0072626 ,  0.00602551,  0.01690621,  0.01992853,  0.00714563,
         0.02161324,  0.01274641,  0.00755801,  0.00187308,  0.0289901 ,
         0.01727988,  0.00433065, -0.02400699, -0.00239352,  0.00095747],
       dtype=float32),
 array([-0.00754614,  0.00612516,  0.00268843,  0.00556653, -0.0027994 ,
        -0.01862398,  0.00305768,  0.01902002, -0.01197109, -0.00511575,
        -0.00148055, -0.01441599, -0.0001926 ,  0.00078719,  0.00388448,
        -0.00907083,  0.00447763, -0.00795706,  0.00145489, -0.01812398,
         0.0030902 ,  0.00429812,  0.00706857, -0.00678152, -0.00432412,
        -0.00540235, -0.01105688, -0.00531842, -0.01055046,  0.00186789,
         0.00479778, -0.0012975 ,  0.00535677, -0.00833058, -0.00454468,
         0.00906536,  0.00063371, -0.00973914, -0.00104303, -0.01634441,
        -0.00486592, -0.00775213, -0.00192063,  0.0046745 ,  0.00558669,
        -0.0076354 , -0.00954911, -0.00484485,  0.00385025,  0.00904361,
         0.00161188, -0.00514134, -0.00713991,  0.00114534, -0.00442268,
         0.00683195,  0.00547057, -0.00836321, -0.01057118,  0.00783716,
         0.00079568,  0.00265343,  0.00082063, -0.00072775, -0.01126185,
         0.01118483,  0.00055915,  0.00502938, -0.01205404,  0.00933185,
        -0.00486508,  0.00543499,  0.00988112, -0.00625697,  0.00649082,
         0.00359266, -0.0009783 , -0.0005962 , -0.00392415, -0.00046525,
        -0.00081942,  0.00118703, -0.00468222,  0.01553346, -0.00130174,
        -0.00349037,  0.0035421 ,  0.01388441,  0.01094039,  0.00830831,
         0.01432914,  0.00506506,  0.00607185,  0.00018783,  0.01531983,
         0.00800937,  0.00334321, -0.01564593, -0.00208587,  0.00409421],
       dtype=float32),
 array([-8.85591097e-03,  9.79270134e-03,  3.10891494e-03,  1.09975541e-03,
         1.39222713e-03, -1.81176048e-02,  3.11270403e-03,  2.73818038e-02,
        -1.38502419e-02, -6.65370887e-03, -6.09804410e-03, -1.80001725e-02,
        -4.56293928e-04,  2.06449698e-03,  7.04824599e-03, -9.10185557e-03,
         4.63728234e-03, -1.29270833e-02,  8.93684628e-04, -2.41457131e-02,
        -1.00135186e-03,  3.39580467e-03,  1.20692365e-02, -5.44508081e-03,
        -4.35457285e-03, -6.38968870e-03, -1.54354041e-02, -7.33790966e-03,
        -1.10168597e-02,  4.75892937e-03,  8.25650431e-03,  8.56543134e-04,
         4.70130704e-03, -8.84546991e-03, -8.25491361e-03,  1.51601583e-02,
        -1.54498359e-03, -1.38720265e-02, -5.94770769e-03, -2.17806064e-02,
        -1.44257536e-03, -8.60984344e-03, -7.02003622e-03,  3.19258124e-03,
         7.78572029e-03, -9.19560343e-03, -8.43858719e-03, -3.21957003e-03,
         1.75049470e-03,  9.98354424e-03,  4.08924511e-03, -5.98245626e-03,
        -5.57414023e-03,  1.98849780e-03, -6.81256270e-03,  6.24658680e-03,
         9.42026265e-03, -3.52022634e-03, -1.20155066e-02,  6.18567504e-03,
         5.49087999e-04,  3.33195925e-03, -3.55909602e-03,  8.04492505e-04,
        -1.54160149e-02,  1.00476136e-02, -8.51342164e-04,  4.87530604e-03,
        -1.24875205e-02,  1.43570835e-02, -4.18109260e-03,  5.87426079e-03,
         1.18372850e-02, -6.58672862e-03,  1.16737103e-02,  5.83227538e-03,
        -2.75501516e-03, -5.68300457e-05, -8.26185010e-03, -5.35153691e-03,
        -1.29116885e-03, -9.48805071e-04, -5.04732970e-03,  1.67347156e-02,
        -4.52955253e-03, -2.17194529e-03,  1.97741599e-03,  1.38786584e-02,
         1.41819073e-02,  5.52751776e-03,  1.71315838e-02,  5.35873743e-03,
         6.96757855e-03,  3.03426967e-03,  2.15307567e-02,  8.59534368e-03,
         3.42644798e-03, -1.89097598e-02, -1.23958813e-03, -1.22846314e-03],
       dtype=float32),
 array([-0.01018908,  0.01235858,  0.00212769,  0.00260518, -0.00102045,
        -0.01584354,  0.00274785,  0.02922849, -0.01574373, -0.0043659 ,
        -0.00316824, -0.01627496,  0.00290502,  0.00153751,  0.00444539,
        -0.01281463,  0.00802484, -0.0131144 ,  0.00278866, -0.02572829,
         0.00097187,  0.00550017,  0.01146978, -0.00898453, -0.00469124,
        -0.00962386, -0.01865787, -0.00884505, -0.01432349,  0.00399141,
         0.01018952, -0.00114745,  0.00545575, -0.01285912, -0.01088859,
         0.01696257, -0.00264644, -0.01778062, -0.002714  , -0.02215621,
        -0.00379045, -0.00489548, -0.0043569 ,  0.0056346 ,  0.00693577,
        -0.00545636, -0.01235357, -0.00652736,  0.0017417 ,  0.01053526,
         0.00394746, -0.0069435 , -0.00676549,  0.00171563, -0.00828325,
         0.00659916,  0.00814622, -0.00824746, -0.01798248,  0.004719  ,
        -0.00030463,  0.00461361, -0.00102915, -0.0010502 , -0.01664013,
         0.01011077, -0.00230551,  0.00546982, -0.0154277 ,  0.0093183 ,
        -0.00688659,  0.00890856,  0.01341722, -0.00799495,  0.01036439,
         0.00646456, -0.00318594, -0.00017635, -0.00790598, -0.00445693,
         0.00099533, -0.00221068, -0.00486264,  0.01565383, -0.00447212,
        -0.00129672,  0.00069235,  0.01484479,  0.01452588,  0.00476389,
         0.01420188,  0.00955609,  0.01082514,  0.00209252,  0.02225477,
         0.01208459, -0.00117344, -0.01750751,  0.0013507 , -0.00404842],
       dtype=float32),
 array([-1.23356069e-02,  1.02819232e-02,  7.55103119e-03,  6.05939562e-03,
         7.21408360e-05, -2.05696579e-02,  4.50578006e-03,  3.03653032e-02,
        -1.44094983e-02, -1.00573311e-02, -5.47503494e-03, -2.40937620e-02,
         1.30342937e-03,  2.89971172e-03,  8.76855943e-03, -1.31503642e-02,
         4.20107134e-03, -1.55354226e-02,  1.11319544e-03, -2.77683754e-02,
         1.25204679e-03,  4.77239257e-03,  1.12120910e-02, -6.52421312e-03,
        -4.15895367e-03, -7.60686910e-03, -2.19671503e-02, -9.10109468e-03,
        -1.03247212e-02,  6.75018551e-03,  5.51220402e-03,  3.76947597e-03,
         6.86619291e-03, -1.04833851e-02, -1.20170368e-02,  1.86998267e-02,
         1.05225912e-03, -1.83221344e-02, -5.62780583e-03, -2.90763769e-02,
        -6.85551530e-03, -8.25227704e-03, -5.16484911e-03,  4.86814091e-03,
         6.76730694e-03, -1.00162616e-02, -1.61304343e-02, -3.85707687e-03,
         5.04993228e-03,  9.49869398e-03,  5.74239669e-03, -7.52235437e-03,
        -4.81409254e-03,  1.41079165e-03, -1.02240341e-02,  8.52918252e-03,
         8.14747252e-03, -1.01240370e-02, -1.72544643e-02,  7.84622971e-03,
         1.01800695e-04,  3.38707422e-03, -7.25597609e-04,  1.40332372e-03,
        -2.29961555e-02,  1.12219928e-02,  2.00728280e-03,  8.73318035e-03,
        -1.37792416e-02,  1.72923822e-02, -8.69602431e-03,  8.86293314e-03,
         1.34352818e-02, -1.01630753e-02,  1.64690800e-02,  1.10932579e-02,
        -4.18182462e-03, -7.76088156e-04, -6.05451874e-03, -4.18877834e-03,
        -2.17524357e-03, -1.05709223e-04, -5.76554984e-03,  2.08398774e-02,
        -4.35300218e-03, -3.25677567e-03,  7.70177518e-04,  1.62442457e-02,
         1.60888433e-02,  7.62909977e-03,  2.35609207e-02,  1.14596672e-02,
         8.99001490e-03, -6.42077823e-04,  2.62818430e-02,  1.36015974e-02,
         1.96762593e-03, -2.03713123e-02, -1.65948679e-03, -1.60863495e-03],
       dtype=float32),
 array([-7.73394620e-03,  7.55501958e-03,  3.17515875e-03,  1.24478713e-03,
        -2.23531481e-03, -1.68462321e-02,  3.57390032e-03,  2.08256952e-02,
        -8.61438736e-03, -1.48113351e-03, -4.78076888e-03, -1.15354853e-02,
        -2.60875234e-03, -3.58955527e-04,  5.06958365e-03, -9.63530783e-03,
         2.61131395e-03, -1.23174442e-02, -6.97720156e-04, -2.01005600e-02,
         2.75831949e-03,  5.66875748e-03,  1.16505912e-02, -4.68926365e-03,
        -5.26013412e-03, -7.16611743e-03, -1.21343713e-02, -5.61939087e-03,
        -8.65737442e-03,  4.47885739e-03,  7.13361287e-03,  1.42410980e-03,
         7.53702968e-03, -9.42533650e-03, -8.05430766e-03,  1.01700667e-02,
        -1.89137994e-03, -1.22346971e-02, -2.80079944e-03, -1.82003081e-02,
        -6.14228949e-04, -4.28163679e-03, -4.67385352e-03,  3.15586594e-03,
         5.91190718e-03, -8.74423515e-03, -6.95510302e-03, -2.91354465e-03,
         4.70406003e-03,  8.31092056e-03,  1.11600617e-03, -5.83589589e-03,
        -5.30213676e-03,  1.87971955e-03, -4.51489585e-03,  3.68683669e-03,
         6.01396523e-03, -6.46246038e-03, -1.14430450e-02,  8.34954437e-03,
         6.07668934e-03,  2.50924332e-03, -2.23934231e-03, -6.69831701e-04,
        -1.11591704e-02,  9.71074682e-03,  9.96765448e-04,  7.39902444e-03,
        -9.22989007e-03,  1.30459238e-02, -3.05707403e-03,  3.81244253e-03,
         8.52335244e-03, -5.14439680e-03,  1.01615321e-02,  3.87804164e-03,
         4.44493635e-05,  2.53685121e-03, -3.24535579e-03, -6.07335474e-03,
        -2.62245373e-03,  1.94860087e-03, -3.65930307e-03,  1.51407318e-02,
        -3.64863593e-03, -2.27909419e-03,  4.05996718e-04,  1.28105441e-02,
         1.00886552e-02,  5.45775937e-03,  1.63845215e-02,  5.76557964e-03,
         6.90005207e-03, -8.87050584e-04,  1.64605491e-02,  1.01614185e-02,
         2.93451920e-03, -1.53551502e-02, -3.81291565e-03,  6.96532195e-04],
       dtype=float32),
 array([-0.015863  ,  0.01390015,  0.0008518 ,  0.00219603, -0.00166675,
        -0.02695119,  0.00442223,  0.03362972, -0.01850827, -0.01058957,
        -0.00344257, -0.02407934, -0.00102391,  0.00058881,  0.00776345,
        -0.01222679,  0.00964687, -0.01653991,  0.0021779 , -0.03280687,
         0.00285526,  0.00613567,  0.01238964, -0.00863754, -0.00653526,
        -0.00671723, -0.02244974, -0.01036172, -0.01400006,  0.00312675,
         0.01234058,  0.00290531,  0.0095962 , -0.01368553, -0.00909753,
         0.02053268, -0.00192199, -0.01821837, -0.01035772, -0.02806614,
        -0.00364782, -0.00904677, -0.00585366,  0.00534858,  0.00786469,
        -0.01256524, -0.01601958, -0.00562167,  0.00627767,  0.0117439 ,
         0.00730819, -0.00642142, -0.00846155,  0.00451348, -0.01106312,
         0.00634387,  0.01259346, -0.00917801, -0.01801584,  0.00777457,
         0.00225948,  0.00325315, -0.00200096, -0.00047874, -0.02243208,
         0.01189911, -0.00061678,  0.01045655, -0.01629288,  0.0177022 ,
        -0.00673587,  0.00803325,  0.0151961 , -0.01016689,  0.01890986,
         0.00791243, -0.00324846,  0.0032687 , -0.00900275, -0.00576409,
        -0.00240387, -0.00222162, -0.00689781,  0.02156007, -0.00254244,
        -0.00546781,  0.00291967,  0.02302361,  0.01833728,  0.00628181,
         0.02556516,  0.0116247 ,  0.00925197,  0.00171648,  0.02924179,
         0.01343992,  0.00200458, -0.0259254 , -0.0014152 ,  0.00070584],
       dtype=float32),
 array([-6.3955658e-03,  8.1314873e-03,  4.8636138e-03,  2.5983150e-03,
        -1.5251990e-03, -1.7575508e-02,  6.3226684e-03,  1.6488882e-02,
        -1.2664719e-02, -8.2213450e-03, -3.7087426e-03, -1.6045449e-02,
        -1.0642734e-03, -4.6264383e-04,  4.9243071e-03, -9.2774779e-03,
         3.6040756e-03, -1.0672547e-02,  5.8819068e-04, -2.0240286e-02,
         5.2701362e-04,  6.3429927e-03,  7.8410991e-03, -2.5590733e-03,
        -6.7340019e-03, -4.4593737e-03, -1.5433676e-02, -6.7376764e-03,
        -8.3908122e-03,  2.3192407e-04,  7.5210328e-03, -1.3458075e-03,
         6.6399057e-03, -9.2932861e-03, -5.3416756e-03,  1.3816750e-02,
         8.1425568e-04, -1.1038615e-02, -3.0503492e-03, -2.1202806e-02,
        -2.1531212e-03, -7.8285141e-03, -5.8912155e-03,  2.3144491e-03,
         1.2400439e-03, -3.8425811e-03, -9.3999356e-03, -3.6058878e-03,
         3.4987496e-03,  1.0106568e-02,  1.9985852e-03, -4.4248994e-03,
        -5.4935678e-03,  1.5984105e-03, -6.9044461e-03,  5.0874166e-03,
         6.2500411e-03, -3.9709643e-03, -1.2912254e-02,  8.1521207e-03,
         2.3643449e-03,  1.5571400e-03, -1.2468414e-03,  5.3587329e-04,
        -1.4081193e-02,  8.0621792e-03, -3.8522031e-04,  5.7670814e-03,
        -1.0456463e-02,  9.8093729e-03, -4.3318244e-03,  5.9939935e-03,
         8.3119869e-03, -7.3728180e-03,  1.3845415e-02,  6.5343501e-03,
        -4.3281610e-03,  3.5281465e-04, -6.0782363e-03, -3.0445787e-03,
        -2.0893447e-03, -9.4151031e-04, -7.9346178e-03,  1.5449306e-02,
        -4.4054808e-03, -1.8833844e-03,  6.5989845e-04,  1.4072673e-02,
         1.1294512e-02,  2.8678204e-03,  1.6357942e-02,  6.4014606e-03,
         4.9276203e-03,  7.0335809e-06,  1.5641237e-02,  9.7473906e-03,
         2.0123473e-03, -1.4052582e-02, -5.3433992e-04, -3.5409248e-04],
       dtype=float32),
 array([-0.00751572,  0.00723219,  0.00283696,  0.00039225,  0.00202198,
        -0.01666393,  0.00359603,  0.02350689, -0.01230106, -0.00586029,
        -0.00504112, -0.01460901,  0.00196314,  0.00164941,  0.00143151,
        -0.00953093,  0.00385876, -0.0108233 ,  0.00212447, -0.02158681,
         0.00394188,  0.00579379,  0.00517908, -0.00518934, -0.00482781,
        -0.00424859, -0.01290418, -0.00824674, -0.01044778,  0.00096239,
         0.00664405,  0.00115821,  0.0058056 , -0.01081867, -0.00497236,
         0.01109379, -0.0024035 , -0.0106815 , -0.00563236, -0.01691428,
        -0.0027393 , -0.00307184, -0.0046212 ,  0.00100801,  0.00198305,
        -0.0084443 , -0.00889198, -0.00261047,  0.00485025,  0.01015421,
         0.00305604, -0.00966411, -0.00189054, -0.00011609, -0.00324599,
         0.00745917,  0.00403995, -0.00455858, -0.01169985,  0.00491807,
         0.00392869,  0.00228636, -0.00075152,  0.00103654, -0.01234225,
         0.01059966, -0.00242041,  0.00513883, -0.00914304,  0.00886291,
        -0.0041806 ,  0.00700342,  0.00901315, -0.00707236,  0.00620632,
         0.00347555, -0.00217603,  0.00410959, -0.00388586, -0.0047492 ,
        -0.00378878, -0.00036526, -0.0060338 ,  0.01391419, -0.00411075,
        -0.00494154,  0.00311582,  0.01215666,  0.01219581,  0.00455736,
         0.01659643,  0.00265182,  0.00295258,  0.00199816,  0.01571975,
         0.00939828,  0.00150368, -0.01589393,  0.00029503,  0.00063948],
       dtype=float32),
 array([-0.00667804,  0.00983107,  0.00268283,  0.00109559, -0.00089163,
        -0.0154935 ,  0.00392713,  0.02078321, -0.01208227, -0.00583928,

In [51]:
Y_decoder_target_data = []
for i in tqdm(range(len(words_output_target))):
    Y_decoder_target_data.append(avg_word2vec_output(words_output_target[i]))
Y_decoder_target_data

100%|██████████| 1000/1000 [00:00<00:00, 4738.86it/s]

[array([-7.38353841e-03,  9.78512689e-03,  2.03370326e-03,  2.25377199e-03,
        -6.16411737e-04, -1.53670413e-02,  4.48533148e-03,  2.08123401e-02,
        -1.04866019e-02, -8.75060167e-03, -5.09402761e-03, -1.55330729e-02,
         6.68313369e-05,  2.59572524e-03,  6.99929893e-03, -8.25479720e-03,
         5.37188118e-03, -9.86631680e-03, -1.75673762e-04, -1.75207816e-02,
         3.89258028e-04,  3.91151989e-03,  7.25405384e-03, -8.71638861e-03,
        -2.67217797e-03, -7.30671734e-03, -1.37819434e-02, -6.74920017e-03,
        -8.33642855e-03,  5.34839788e-03,  6.90716552e-03,  1.38578692e-03,
         3.31836985e-03, -9.38469451e-03, -6.71511702e-03,  1.43838078e-02,
         1.93268096e-03, -1.34091955e-02, -2.45600333e-03, -1.75047759e-02,
        -2.43999693e-03, -7.55551225e-03, -2.54391856e-03,  3.25594074e-03,
         8.11898522e-03, -4.37058415e-03, -1.12003377e-02, -3.98336444e-03,
         3.46148154e-03,  6.13835920e-03,  3.96363111e-03, -4.51035658e-03,
        -5.14046382e-03,  1.51642272e-03, -7.81938992e-03,  6.54775370e-03,
         6.08420325e-03, -4.85949637e-03, -1.33564258e-02,  5.84332785e-03,
         1.69509684e-03,  1.76534394e-03, -1.92244176e-03, -1.35260867e-03,
        -1.51710063e-02,  8.18241481e-03, -1.72696286e-03,  4.80673509e-03,
        -1.10299643e-02,  1.12856375e-02, -6.33656979e-03,  4.38768370e-03,
         8.42237100e-03, -3.83724575e-03,  1.09505532e-02,  4.18262603e-03,
        -1.59719761e-03, -3.73668328e-04, -5.06939087e-03, -3.28668649e-03,
        -1.55495864e-03, -2.38682074e-03, -4.58420627e-03,  1.40049933e-02,
        -1.41676317e-03, -1.38389342e-03,  2.06406508e-03,  1.13423755e-02,
         1.14283115e-02,  5.69297420e-03,  1.39766280e-02,  8.50690249e-03,
         6.97481725e-03, -1.96185327e-04,  1.71991661e-02,  9.57676396e-03,
         1.54968095e-03, -1.42232226e-02, -2.30864971e-03,  1.32191682e-03],
       dtype=float32),
 array([-2.9030335e-03,  5.3697992e-03,  4.7091981e-03,  4.3162103e-03,
        -4.6187285e-03, -1.0045595e-02,  2.9979059e-03,  1.0986683e-02,
        -5.2931001e-03, -7.4107305e-04, -6.6359332e-03, -6.4886995e-03,
         2.1272162e-03,  1.3811946e-03,  4.3587321e-03, -5.7391436e-03,
         3.7214048e-03, -5.1182080e-03,  3.5657163e-04, -8.2816035e-03,
        -1.1624973e-03, -2.7097682e-03, -1.9081221e-03, -1.7594182e-03,
        -4.3140613e-03, -9.5359172e-04, -7.0519727e-03, -1.7686238e-03,
        -3.5812785e-03,  1.8755461e-03,  1.3122065e-03,  1.5133279e-03,
         2.6687139e-03, -5.3861984e-03, -3.5084661e-03,  7.3864758e-03,
         2.3599879e-03, -8.3664181e-03, -1.2920628e-03, -8.7830229e-03,
        -4.3015573e-03, -4.9030352e-03, -4.1568098e-03, -1.7669093e-04,
         3.2739318e-03, -6.4879023e-03, -8.8297930e-03, -1.4409475e-05,
         2.5986368e-03,  3.8372609e-03,  2.2010647e-03, -3.4363538e-03,
        -2.0018721e-03,  1.0876353e-03, -2.4968488e-03,  1.5167524e-03,
         4.1949577e-03, -3.2883668e-03, -5.9868833e-03,  3.1681268e-03,
         2.2981911e-04,  3.8679796e-03, -6.7745708e-04, -8.2587788e-04,
        -9.3676513e-03,  7.2591957e-03,  2.7637400e-03,  1.5984291e-03,
        -6.5022707e-03,  5.1987628e-03, -2.3113564e-03, -1.3065535e-04,
         5.4050544e-03, -4.0908540e-03,  5.6662899e-03,  4.3940153e-03,
         4.8918842e-04, -2.8130899e-03, -1.4152285e-03, -1.6930611e-03,
        -5.6477811e-04, -5.7384913e-04, -2.0815455e-03,  8.8849403e-03,
        -3.8590143e-04,  9.0725027e-04,  3.1475083e-03,  4.8572901e-03,
         8.7754251e-03,  1.6095410e-03,  1.0742465e-02,  5.5127246e-03,
         4.1566179e-03, -2.4980530e-03,  1.0938426e-02,  1.8273371e-03,
        -3.2185421e-03, -1.0920252e-02,  1.0182803e-03,  1.7594735e-03],
       dtype=float32),
 array([-8.8964617e-03,  7.4723954e-03,  4.9536405e-03, -4.3961452e-04,
        -2.8121634e-05, -1.8539529e-02,  6.0173320e-03,  1.3653829e-02,
        -1.2286436e-02, -7.6807085e-03, -8.1562167e-03, -1.5966650e-02,
        -5.9114965e-03,  5.0387351e-04,  1.7719693e-03, -8.5087810e-03,
         1.0911624e-03, -5.6773359e-03, -1.7397896e-03, -1.6651992e-02,
        -1.3498183e-03, -1.3832275e-03,  4.8978673e-03, -8.4930640e-03,
        -5.5077560e-03, -8.4403949e-04, -1.7461158e-02, -5.3259209e-03,
        -7.1870564e-03,  3.4667016e-03,  6.9963373e-03,  2.0713587e-03,
         6.4758025e-03, -8.2295211e-03, -1.0776657e-02,  1.0796823e-02,
        -3.0512852e-03, -1.2571573e-02, -4.5592710e-03, -1.7263934e-02,
         8.9362485e-04, -2.6884675e-04,  7.7306619e-04,  3.3083376e-03,
         7.7685323e-03, -4.8952755e-03, -6.7437543e-03, -7.6841963e-03,
         3.0886335e-03,  6.7380746e-03,  8.7754457e-04, -5.7292874e-03,
        -1.4430963e-03,  2.5737397e-03, -8.8439081e-03,  1.0910289e-03,
         3.4568370e-03, -7.0284121e-03, -6.8837916e-03,  2.0510864e-03,
         7.0826791e-04, -2.1108536e-03,  2.0390390e-03,  1.3794496e-03,
        -1.3436249e-02,  5.1667527e-03, -1.3122016e-03,  1.4653384e-03,
        -1.2270433e-02,  7.3302900e-03, -1.3096344e-03,  7.8548947e-03,
         9.3005234e-03, -3.1966032e-03,  1.1443425e-02,  6.1694216e-03,
        -5.2229147e-03, -3.0420341e-03, -1.2570834e-02, -3.8767350e-04,
        -8.7744719e-04,  1.5683578e-03, -5.1380498e-03,  1.6924500e-02,
         1.4044532e-03, -3.9058665e-03, -1.3362416e-03,  8.5099870e-03,
         2.7688891e-03,  1.0933785e-03,  1.3822824e-02,  5.3949049e-03,
         9.0191793e-03, -2.3996462e-03,  1.9244414e-02,  5.1367651e-03,
        -5.1371811e-04, -8.6955912e-03, -2.6198304e-03, -2.9702089e-03],
       dtype=float32),
 array([-4.9662357e-03,  6.9773942e-03,  2.8271461e-03,  4.5174127e-03,
         1.9390810e-03, -8.7466277e-03,  2.0525093e-05,  1.1770901e-02,
        -9.7022923e-03, -2.6688795e-03, -6.6051693e-03, -1.4853385e-02,
        -8.6522446e-04, -1.2835419e-03,  6.4549977e-03, -6.9813868e-03,
        -4.7060376e-04, -9.4839269e-03,  1.5646396e-03, -1.1313218e-02,
         2.1605561e-03,  2.4070144e-03,  4.8653819e-03, -6.3883914e-03,
        -4.5220056e-03, -4.7057592e-03, -6.3135563e-03, -4.0339576e-03,
        -5.0966693e-03, -3.4124691e-03,  2.2301369e-03,  3.6732928e-04,
         2.8640674e-03, -6.1129709e-03, -7.3613464e-03,  1.3557474e-02,
        -2.1390703e-03, -9.0870466e-03, -6.4358464e-03, -9.9448729e-03,
         3.1467243e-03, -4.2516682e-03, -2.6733582e-03,  3.5080202e-03,
         6.2998699e-04, -8.7348046e-03, -7.2115362e-03, -5.9696743e-03,
        -1.0707139e-03, -9.9594821e-04,  3.6752298e-03, -9.8997215e-04,
        -4.1882750e-03, -2.9735561e-03, -4.9292651e-04,  9.7347796e-04,
         7.6510943e-03, -2.3660143e-03, -7.9864394e-03,  6.1810436e-03,
         2.2624214e-03, -1.9963363e-03,  1.4689340e-03, -4.5631854e-03,
        -4.6835891e-03,  7.9163220e-03, -2.1682163e-03,  1.9559069e-03,
        -1.0749075e-02,  4.1571693e-03, -4.2286203e-03,  8.9113908e-03,
         2.9679441e-03, -1.0887460e-03,  1.0554122e-02,  5.8585149e-04,
        -2.0052795e-03, -3.5047163e-03, -4.9999296e-03,  6.3218939e-04,
         1.2513847e-03,  1.2693497e-03, -2.9798138e-03,  8.0208164e-03,
         8.1536185e-04, -3.5798252e-03,  3.0498418e-03,  4.6008392e-03,
         7.8659486e-03,  1.7725512e-03,  6.0634916e-03,  7.2335131e-03,
         3.2062228e-03,  5.7174050e-04,  1.2491705e-02,  9.1604963e-03,
         2.3782842e-03, -7.4915392e-03,  3.2916098e-04,  2.0579903e-03],
       dtype=float32),
 array([-0.00403985,  0.00235394,  0.00207406,  0.00489469, -0.00209584,
        -0.01189972,  0.00128299,  0.00870873, -0.00745733, -0.00298385,
        -0.00128317, -0.00879699, -0.00039771,  0.00032868,  0.00170648,
        -0.00580012,  0.00199628, -0.0033889 ,  0.00047766, -0.0083784 ,
         0.00129833,  0.00146186,  0.00228538, -0.00510652, -0.00378495,
        -0.00327237, -0.00558021, -0.00244409, -0.0059898 ,  0.00042381,
         0.00321497, -0.00196814,  0.00325248, -0.00394177, -0.00220549,
         0.004136  ,  0.00115249, -0.0047446 ,  0.00053819, -0.00807043,
        -0.00216673, -0.00538416,  0.00089077,  0.00367102,  0.0043594 ,
        -0.00503068, -0.00470429, -0.00428503,  0.00267098,  0.00441337,
         0.00080077, -0.00329803, -0.00474316, -0.0003047 , -0.00156659,
         0.00438906,  0.00260783, -0.00625898, -0.00560702,  0.00526068,
        -0.00038977,  0.0012597 ,  0.00266658, -0.00081369, -0.00597559,
         0.00706981,  0.00068893,  0.00177329, -0.00802427,  0.00383191,
        -0.00287272,  0.00268361,  0.0053311 , -0.00173816,  0.00159275,
         0.00097411, -0.00051963, -0.00147717, -0.00182237,  0.00113032,
         0.00025885,  0.00210159, -0.00264578,  0.01000698,  0.00057803,
        -0.00181638,  0.00218952,  0.00829106,  0.0054574 ,  0.005866  ,
         0.00726107,  0.0025592 ,  0.00409376, -0.00040369,  0.00782056,
         0.00431875,  0.00245577, -0.00813891, -0.00084829,  0.00459445],
       dtype=float32),
 array([-0.00671318,  0.00748807,  0.00273346,  0.00068919,  0.00182218,
        -0.01400834,  0.00202817,  0.02108046, -0.01109184, -0.00535088,
        -0.00597743, -0.01456634, -0.00058164,  0.0017843 ,  0.00571725,
        -0.00710309,  0.0031209 , -0.01013543,  0.00029649, -0.01819008,
        -0.00209638,  0.00166253,  0.00914617, -0.00442147, -0.00402508,
        -0.00508803, -0.01208855, -0.00558138, -0.00822979,  0.00387644,
         0.00728923,  0.0004467 ,  0.00341535, -0.00616342, -0.00682541,
         0.01214778, -0.00122795, -0.01081981, -0.0049814 , -0.01672429,
         0.00020693, -0.00716275, -0.00530196,  0.00257935,  0.00703571,
        -0.00760383, -0.00547787, -0.00287746,  0.00102983,  0.00715395,
         0.00359356, -0.00485599, -0.00410946,  0.00110236, -0.00506718,
         0.00475371,  0.00767081, -0.00223431, -0.00898186,  0.00461116,
        -0.00017536,  0.00248023, -0.00243101,  0.00075198, -0.01218552,
         0.00753288, -0.00077203,  0.00288547, -0.01002489,  0.01099601,
        -0.00296354,  0.00419286,  0.00905671, -0.00382523,  0.00868045,
         0.00423205, -0.00247472, -0.0005952 , -0.00697743, -0.00437647,
        -0.00063222, -0.00038991, -0.00380283,  0.01335742, -0.0033808 ,
        -0.00114895,  0.00115084,  0.0104605 ,  0.01083119,  0.004035  ,
         0.01281221,  0.00382738,  0.00575875,  0.00267279,  0.01694787,
         0.00633996,  0.00288412, -0.01432214, -0.00048329, -0.00092276],
       dtype=float32),
 array([-0.00633217,  0.00821024,  0.00145188,  0.00186616, -0.00024653,
        -0.00844686,  0.00079569,  0.01788606, -0.01077859, -0.00202081,
        -0.00295112, -0.01009406,  0.00267939,  0.00103315,  0.00204959,
        -0.00921685,  0.00529536, -0.00808942,  0.00171371, -0.01500815,
        -0.00099918,  0.00238027,  0.00620827, -0.00714203, -0.00409816,
        -0.00728088, -0.01263353, -0.00568329, -0.00930677,  0.00240292,
         0.00844842, -0.00188516,  0.00314102, -0.00803143, -0.00831548,
         0.01154028, -0.00207578, -0.01228663, -0.00097465, -0.01305483,
        -0.00082134, -0.00229072, -0.00126436,  0.00453078,  0.00558576,
        -0.00259117, -0.00702427, -0.00591156,  0.0004445 ,  0.005442  ,
         0.00305523, -0.00491586, -0.00412907,  0.00012059, -0.00514156,
         0.00391198,  0.00499722, -0.0059328 , -0.01252191,  0.00188487,
        -0.00160863,  0.0030805 ,  0.0010014 , -0.00114472, -0.01082524,
         0.00558425, -0.00216275,  0.00188812, -0.01099495,  0.00326837,
        -0.004695  ,  0.00588203,  0.00841219, -0.00302426,  0.00497651,
         0.00358415, -0.00268141, -0.00114542, -0.00559402, -0.0027018 ,
         0.00218143, -0.00120466, -0.00262254,  0.00957471, -0.00240437,
         0.00054466, -0.00079548,  0.00869211,  0.00849459,  0.00207735,
         0.006427  ,  0.00679964,  0.00864924,  0.00144185,  0.01400557,
         0.00802489, -0.00214962, -0.00924979,  0.00271203, -0.00349816],
       dtype=float32),
 array([-9.12151486e-03,  6.82497164e-03,  6.98785670e-03,  5.44354552e-03,
         7.17072748e-04, -1.44057544e-02,  2.87898351e-03,  2.09132880e-02,
        -1.02718882e-02, -8.10309034e-03, -5.29410690e-03, -1.89430118e-02,
         1.11540663e-03,  2.47941539e-03,  6.77206181e-03, -1.01522096e-02,
         1.92650303e-03, -1.13479421e-02,  2.17401190e-04, -1.88349281e-02,
        -3.90496716e-04,  2.17248313e-03,  6.82749646e-03, -4.98879328e-03,
        -3.66471522e-03, -5.65438718e-03, -1.69468690e-02, -6.46629324e-03,
        -6.14412082e-03,  5.42644924e-03,  4.06129146e-03,  3.15471436e-03,
         4.93725343e-03, -6.46031322e-03, -9.87278018e-03,  1.41812535e-02,
         1.52780954e-03, -1.37438104e-02, -4.17834939e-03, -2.14918982e-02,
        -4.38125199e-03, -6.08163886e-03, -2.58773589e-03,  3.94828897e-03,
         5.64229442e-03, -7.62860244e-03, -1.16893565e-02, -3.34390625e-03,
         3.96893593e-03,  5.25430730e-03,  4.99887299e-03, -5.83265303e-03,
        -2.61706952e-03,  8.15909589e-05, -7.60595687e-03,  6.28986349e-03,
         5.52329794e-03, -8.19515716e-03, -1.27039896e-02,  5.48445620e-03,
        -9.84867918e-04,  2.10948428e-03,  9.66527965e-04,  1.32455176e-03,
        -1.81504134e-02,  7.44989468e-03,  2.12624925e-03,  5.74842654e-03,
        -1.00852847e-02,  1.22507764e-02, -6.86969934e-03,  6.34083152e-03,
         9.26442631e-03, -6.02083094e-03,  1.19791823e-02,  8.69291462e-03,
        -3.76138114e-03, -1.58364791e-03, -4.12788801e-03, -2.72617373e-03,
        -1.18682196e-03,  7.32636370e-04, -3.89880501e-03,  1.57739390e-02,
        -2.62987963e-03, -1.72228704e-03, -4.69684455e-04,  1.11170085e-02,
         1.10627702e-02,  5.39031764e-03,  1.70818586e-02,  9.16262995e-03,
         7.17676850e-03, -1.18430145e-03,  1.94075089e-02,  1.02185216e-02,
         1.15414185e-03, -1.34898759e-02, -5.25037642e-04, -1.15008478e-03],
       dtype=float32),
 array([-3.4484891e-03,  2.9457503e-03,  2.4242585e-03,  4.2365363e-04,
        -1.3754057e-03, -8.6276941e-03,  1.4048375e-03,  8.2230084e-03,
        -3.0975700e-03,  1.1245222e-03, -4.5395326e-03, -4.6678190e-03,
        -2.8594488e-03, -9.1935106e-04,  2.4075871e-03, -5.6377705e-03,
        -4.2144401e-04, -6.7341351e-03, -1.8921127e-03, -8.1892991e-03,
         5.6826160e-04,  2.2022119e-03,  5.8044652e-03, -2.6420385e-03,
        -4.6011489e-03, -4.5628068e-03, -5.4406598e-03, -2.1063227e-03,
        -3.0832386e-03,  2.7138758e-03,  5.1990622e-03,  6.0442765e-04,
         4.9651098e-03, -4.0612379e-03, -5.1953001e-03,  4.1453009e-03,
        -1.2573129e-03, -6.1302613e-03, -8.6819194e-04, -8.0876714e-03,
         2.6847865e-03, -1.3874531e-03, -1.2377041e-03,  1.9293968e-03,
         4.4118902e-03, -5.5606877e-03, -1.0336640e-03, -2.2293171e-03,
         3.2627317e-03,  2.6517394e-03,  1.2464139e-04, -3.5829602e-03,
        -2.3727724e-03,  1.0745222e-04, -1.0241255e-03,  7.0107728e-04,
         2.5150669e-03, -3.8906198e-03, -5.3757480e-03,  5.2005141e-03,
         4.6277978e-03,  8.0579077e-04,  1.6824550e-05, -7.7486073e-04,
        -4.6981839e-03,  4.6812803e-03,  1.1553874e-03,  3.4193506e-03,
        -4.3046144e-03,  6.3237818e-03, -6.2197191e-04,  4.4963922e-04,
         2.9622114e-03,  3.7859581e-04,  4.1750018e-03,  6.7758461e-04,
         6.0503988e-04,  1.4601049e-03, -6.7651470e-04, -4.1232156e-03,
        -1.3045580e-03,  3.0663949e-03, -1.1703089e-03,  8.3861481e-03,
        -1.3511385e-03, -2.3310988e-04, -1.2471522e-03,  5.9742280e-03,
         3.3872221e-03,  2.4727166e-03,  7.7457735e-03,  2.7028609e-03,
         4.4823913e-03, -1.6100159e-03,  7.2947699e-03,  5.6506521e-03,
         1.8498743e-03, -6.1799032e-03, -2.3003160e-03,  1.3079323e-03],
       dtype=float32),
 array([-0.01289615,  0.01070912,  0.00033195,  0.00162756, -0.00107143,
        -0.02126144,  0.00292058,  0.02490479, -0.01468894, -0.00878566,
        -0.00327556, -0.0193248 , -0.00119747,  0.00020084,  0.00592053,
        -0.00945926,  0.00754727, -0.01267454,  0.00135102, -0.02456061,
         0.00133907,  0.00373575,  0.00834232, -0.00722023, -0.00607904,
        -0.00491494, -0.01781564, -0.00792959, -0.01014105,  0.00190484,
         0.01100127,  0.00233784,  0.00781564, -0.00997193, -0.00711822,
         0.01636169, -0.00148302, -0.01399223, -0.00901976, -0.02106508,
        -0.00136388, -0.0070431 , -0.00347478,  0.00449949,  0.00682622,
        -0.01036125, -0.01192012, -0.00514798,  0.00527982,  0.00782601,
         0.00662185, -0.0048617 , -0.00643353,  0.00328653, -0.00864644,
         0.00427681,  0.01017115, -0.0073975 , -0.0138154 ,  0.00559447,
         0.00125641,  0.00207383, -0.000439  , -0.00055145, -0.01795909,
         0.00841718, -0.00050697,  0.00770139, -0.01288307,  0.01304841,
        -0.00505003,  0.00570516,  0.01134608, -0.00634328,  0.01476534,
         0.00569673, -0.00286036,  0.00252326, -0.00722432, -0.00441399,
        -0.00149148, -0.00144776, -0.00517466,  0.01688382, -0.00095187,
        -0.00405136,  0.00177519,  0.01829078,  0.01369782,  0.00421524,
         0.01958449,  0.00950435,  0.0075782 ,  0.00121597,  0.02289625,
         0.01031709,  0.00125367, -0.0195733 , -0.00036801,  0.00112912],
       dtype=float32),
 array([-3.6406291e-03,  5.1683853e-03,  4.3808925e-03,  2.0704435e-03,
        -9.7240054e-04, -1.2292164e-02,  4.9282713e-03,  8.3871521e-03,
        -9.1181928e-03, -6.5462803e-03, -3.5536624e-03, -1.1630522e-02,
        -1.2254355e-03, -8.2289806e-04,  3.2130238e-03, -6.7076315e-03,
         1.6544461e-03, -7.0832758e-03, -1.7963300e-04, -1.2583046e-02,
        -8.8088092e-04,  4.1144979e-03,  4.0828744e-03, -1.2429998e-03,
        -6.3103684e-03, -2.7858168e-03, -1.1130577e-02, -4.4792751e-03,
        -4.8074401e-03, -9.0270722e-04,  6.2773931e-03, -1.8727463e-03,
         4.9865283e-03, -5.8449362e-03, -3.5037429e-03,  9.9436855e-03,
         1.2218701e-03, -7.1143354e-03, -1.8079585e-03, -1.4701824e-02,
        -3.2325774e-05, -5.9679677e-03, -3.6822620e-03,  1.5260043e-03,
         2.7574733e-04, -1.7960159e-03, -5.5932989e-03, -3.1660269e-03,
         2.5721812e-03,  6.4685224e-03,  1.3612795e-03, -2.9765838e-03,
        -3.6104058e-03,  4.5909555e-04, -4.6603796e-03,  3.1679999e-03,
         4.0007499e-03, -2.3176388e-03, -9.0118507e-03,  6.1277440e-03,
         1.4329150e-03,  4.6206333e-04,  2.0355170e-04,  4.6835461e-04,
        -9.9277031e-03,  4.8289527e-03, -2.8324919e-04,  3.2087197e-03,
        -7.2902148e-03,  5.4879957e-03, -2.7664013e-03,  3.8321917e-03,
         4.7369669e-03, -3.8223225e-03,  9.9969311e-03,  4.4769146e-03,
        -3.9677816e-03, -3.3937927e-04, -4.4268384e-03, -1.7909176e-03,
        -1.2421260e-03, -2.2292846e-04, -6.3345502e-03,  1.1107072e-02,
        -2.9285180e-03, -5.6810863e-04, -4.0284038e-04,  9.6779009e-03,
         6.9864467e-03,  9.4886508e-04,  1.0804459e-02,  4.4325697e-03,
         3.3734099e-03, -4.5772974e-04,  9.7489515e-03,  6.8476121e-03,
         1.3150756e-03, -8.1542088e-03,  4.3804501e-04,  3.8950504e-05],
       dtype=float32),
 array([-4.0094401e-03,  3.4609670e-03,  2.2225848e-03, -2.7959023e-04,
         2.7255404e-03, -9.9396743e-03,  1.8213415e-03,  1.3195601e-02,
        -7.7873040e-03, -3.7283925e-03, -4.8437449e-03, -8.9900084e-03,
         1.7580218e-03,  1.1909048e-03, -7.4648444e-04, -6.2602106e-03,
         1.3774150e-03, -6.2551405e-03,  1.1472399e-03, -1.1841228e-02,
         2.1500115e-03,  2.9575273e-03,  3.9588532e-04, -3.5143383e-03,
        -4.2886441e-03, -2.1186098e-03, -7.4275066e-03, -5.3724097e-03,
        -5.8871266e-03, -4.8168487e-04,  5.0612371e-03,  4.8756303e-04,
         3.7013046e-03, -6.4298660e-03, -2.6331716e-03,  6.1644348e-03,
        -1.8847163e-03, -5.6869658e-03, -4.0511335e-03, -8.6403005e-03,
        -4.0105882e-05, -7.0387317e-04, -1.8098094e-03,  4.5364300e-06,
         7.5576419e-04, -5.8395793e-03, -4.0471721e-03, -2.0506466e-03,
         3.6709784e-03,  5.5239741e-03,  2.2449198e-03, -7.8207962e-03,
         5.0621311e-04, -1.5661287e-03, -3.8990405e-04,  5.0162757e-03,
         1.1772159e-03, -2.4543514e-03, -6.7357002e-03,  2.3415894e-03,

In [62]:
df_list_ = []
for i in range(len(Y_decoder_input_data)):
    df_list_.append(pd.DataFrame(Y_decoder_input_data[i].reshape(1, -1)))

df_ = pd.concat(df_list_, ignore_index=True)
df_

,0,1,2,3,4,5,6,7,8,9,...,90,91,92,93,94,95,96,97,98,99
0,-0.009955,0.012551,0.002484,0.002746,-0.001132,-0.020298,0.005787,0.028374,-0.013797,-0.010314,...,0.019160,0.010345,0.008425,0.000238,0.022699,0.012283,0.002200,-0.019728,-0.003216,0.000955
1,-0.007188,0.009979,0.005460,0.005137,-0.005479,-0.018264,0.005167,0.023589,-0.010810,-0.003347,...,0.019381,0.008575,0.006574,-0.001775,0.020104,0.006338,-0.002134,-0.020095,-0.000494,0.001148
2,-0.018539,0.017843,0.006643,0.001408,-0.001963,-0.037031,0.010898,0.042010,-0.024699,-0.013543,...,0.033260,0.012286,0.014459,-0.000773,0.039867,0.015286,0.001927,-0.029340,-0.006023,-0.004346
3,-0.012680,0.015274,0.004179,0.005995,0.000391,-0.023540,0.003925,0.034456,-0.019633,-0.007359,...,0.021613,0.012746,0.007558,0.001873,0.028990,0.017280,0.004331,-0.024007,-0.002394,0.000957
4,-0.007546,0.006125,0.002688,0.005567,-0.002799,-0.018624,0.003058,0.019020,-0.011971,-0.005116,...,0.014329,0.005065,0.006072,0.000188,0.015320,0.008009,0.003343,-0.015646,-0.002086,0.004094
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,-0.006824,0.009871,0.006499,0.001674,-0.002281,-0.016478,0.007642,0.018748,-0.010715,-0.004472,...,0.018645,0.006083,0.007192,0.000145,0.018403,0.009782,0.004868,-0.017317,0.000694,-0.000169
996,-0.012747,0.012922,0.002222,0.002085,0.000298,-0.025251,0.007296,0.030650,-0.013960,-0.009967,...,0.022810,0.007603,0.007809,0.002342,0.025725,0.012830,0.003111,-0.023820,0.000172,0.000663
997,-0.011331,0.013144,0.003116,0.005349,-0.002119,-0.022164,0.004783,0.029302,-0.016676,-0.003722,...,0.020390,0.006513,0.007725,-0.002829,0.022800,0.011216,0.003407,-0.018849,-0.003032,-0.002001
998,-0.006830,0.008778,0.004206,0.005936,0.002437,-0.016957,0.003999,0.021440,-0.014588,-0.002215,...,0.016114,0.008240,0.010023,0.003568,0.019607,0.011270,0.005063,-0.020272,-0.001103,-0.002642
999,-0.011255,0.014370,0.007148,0.002892,-0.001855,-0.022887,0.003253,0.029959,-0.016648,-0.010271,...,0.023743,0.006575,0.011662,0.001194,0.025589,0.016393,0.007153,-0.023892,-0.001012,-0.002369

In [64]:
df_list_ = []
for i in range(len(Y_decoder_input_data)):
    df_list_.append(pd.DataFrame(Y_decoder_input_data[i].reshape(1, -1)))

df_target = pd.concat(df_list_, ignore_index=True)
df_target

,0,1,2,3,4,5,6,7,8,9,...,90,91,92,93,94,95,96,97,98,99
0,-0.009955,0.012551,0.002484,0.002746,-0.001132,-0.020298,0.005787,0.028374,-0.013797,-0.010314,...,0.019160,0.010345,0.008425,0.000238,0.022699,0.012283,0.002200,-0.019728,-0.003216,0.000955
1,-0.007188,0.009979,0.005460,0.005137,-0.005479,-0.018264,0.005167,0.023589,-0.010810,-0.003347,...,0.019381,0.008575,0.006574,-0.001775,0.020104,0.006338,-0.002134,-0.020095,-0.000494,0.001148
2,-0.018539,0.017843,0.006643,0.001408,-0.001963,-0.037031,0.010898,0.042010,-0.024699,-0.013543,...,0.033260,0.012286,0.014459,-0.000773,0.039867,0.015286,0.001927,-0.029340,-0.006023,-0.004346
3,-0.012680,0.015274,0.004179,0.005995,0.000391,-0.023540,0.003925,0.034456,-0.019633,-0.007359,...,0.021613,0.012746,0.007558,0.001873,0.028990,0.017280,0.004331,-0.024007,-0.002394,0.000957
4,-0.007546,0.006125,0.002688,0.005567,-0.002799,-0.018624,0.003058,0.019020,-0.011971,-0.005116,...,0.014329,0.005065,0.006072,0.000188,0.015320,0.008009,0.003343,-0.015646,-0.002086,0.004094
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,-0.006824,0.009871,0.006499,0.001674,-0.002281,-0.016478,0.007642,0.018748,-0.010715,-0.004472,...,0.018645,0.006083,0.007192,0.000145,0.018403,0.009782,0.004868,-0.017317,0.000694,-0.000169
996,-0.012747,0.012922,0.002222,0.002085,0.000298,-0.025251,0.007296,0.030650,-0.013960,-0.009967,...,0.022810,0.007603,0.007809,0.002342,0.025725,0.012830,0.003111,-0.023820,0.000172,0.000663
997,-0.011331,0.013144,0.003116,0.005349,-0.002119,-0.022164,0.004783,0.029302,-0.016676,-0.003722,...,0.020390,0.006513,0.007725,-0.002829,0.022800,0.011216,0.003407,-0.018849,-0.003032,-0.002001
998,-0.006830,0.008778,0.004206,0.005936,0.002437,-0.016957,0.003999,0.021440,-0.014588,-0.002215,...,0.016114,0.008240,0.010023,0.003568,0.019607,0.011270,0.005063,-0.020272,-0.001103,-0.002642
999,-0.011255,0.014370,0.007148,0.002892,-0.001855,-0.022887,0.003253,0.029959,-0.016648,-0.010271,...,0.023743,0.006575,0.011662,0.001194,0.025589,0.016393,0.007153,-0.023892,-0.001012,-0.002369

In [21]:
df_.dropna(inplace=True)
df_.shape

(998, 100)