In [1]:
import nltk
import pandas as pd

In [2]:
dataset=pd.read_csv('/home/hammadali08/Personal/CSV file/IMDB Dataset.csv')
dataset

                                                  review sentiment
0      One of the other reviewers has mentioned that ...  positive
1      A wonderful little production. <br /><br />The...  positive
2      I thought this was a wonderful way to spend ti...  positive
3      Basically there's a family where a little boy ...  negative
4      Petter Mattei's "Love in the Time of Money" is...  positive
...                                                  ...       ...
49995  I thought this movie did a down right good job...  positive
49996  Bad plot, bad dialogue, bad acting, idiotic di...  negative
49997  I am a Catholic taught in parochial elementary...  negative
49998  I'm going to have to disagree with the previou...  negative
49999  No one expects the Star Trek movies to be high...  negative

[50000 rows x 2 columns]

In [3]:
import re
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
lemmatizer=WordNetLemmatizer()
corpus=[]
stop_words = set([w.lower() for w in stopwords.words('english')])

for i in range(0, len(dataset)):
    review = re.sub('[^a-zA-Z0-9]', ' ', dataset['review'][i])
    review = review.lower()
    review = review.split()

    review = [lemmatizer.lemmatize(word) for word in review if word not in stop_words]
    review = ' '.join(review)
    corpus.append(review)

In [4]:
len(corpus)

50000

In [5]:
from tensorflow.keras.preprocessing.text import one_hot
vocab_size=7000

2025-08-25 18:44:38.499566: I external/local_xla/xla/tsl/cuda/cudart_stub.cc:32] Could not find cuda drivers on your machine, GPU will not be used.
2025-08-25 18:44:38.503179: I external/local_xla/xla/tsl/cuda/cudart_stub.cc:32] Could not find cuda drivers on your machine, GPU will not be used.
2025-08-25 18:44:38.513111: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:467] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1756129478.529361   50701 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1756129478.534017   50701 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
W0000 00:00:1756129478.545874   50701 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1756129478.545896   50701 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1756129478.545898   50701 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1756129478.545899   50701 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
2025-08-25 18:44:38.550088: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.

In [6]:
ohe=[one_hot(words,vocab_size) for words in corpus]
ohe

[[5076,
  1336,
  6075,
  2737,
  2568,
  953,
  5303,
  2810,
  2220,
  3647,
  1962,
  4646,
  4646,
  969,
  284,
  1953,
  953,
  3907,
  3148,
  2851,
  1853,
  3151,
  2220,
  510,
  6970,
  6743,
  2218,
  148,
  1344,
  4107,
  2218,
  6577,
  306,
  2553,
  1143,
  2681,
  1853,
  5177,
  2733,
  3366,
  510,
  4646,
  4646,
  3683,
  953,
  1376,
  1312,
  6600,
  3042,
  2973,
  469,
  2029,
  1647,
  710,
  6666,
  4980,
  6093,
  1561,
  5813,
  117,
  32,
  1879,
  4328,
  5973,
  6097,
  4167,
  6958,
  3126,
  4980,
  234,
  3858,
  5533,
  6308,
  19,
  2975,
  6698,
  2338,
  6602,
  6837,
  6211,
  1514,
  2683,
  6222,
  5804,
  1858,
  6878,
  523,
  190,
  4646,
  4646,
  3923,
  2846,
  3886,
  27,
  2218,
  3,
  1931,
  6970,
  2218,
  1642,
  5144,
  3275,
  5597,
  2112,
  2649,
  3429,
  5144,
  1914,
  5144,
  2985,
  953,
  4180,
  2417,
  969,
  5303,
  1785,
  3787,
  1953,
  4784,
  353,
  2846,
  3896,
  5547,
  2918,
  2468,
  953,
  2353,
  4273,
  4167,
  1846,
  599,
  1853,
  1853,
  904,
  6303,
  542,
  1107,
  1495,
  2688,
  4524,
  4196,
  6017,
  190,
  6188,
  3962,
  2323,
  6392,
  2688,
  496,
  5813,
  1259,
  3,
  121,
  4056,
  6148,
  5813,
  5230,
  2737,
  953,
  6741,
  6336,
  529,
  2123,
  687,
  5313,
  6017,
  3312,
  4207,
  6689],
 [1101,
  881,
  6872,
  4646,
  4646,
  770,
  3842,
  2497,
  3854,
  5842,
  542,
  5037,
  4653,
  4850,
  1738,
  6581,
  4381,
  5705,
  1193,
  6436,
  4646,
  4646,
  4600,
  6142,
  6188,
  890,
  1767,
  2561,
  2353,
  4011,
  6984,
  1099,
  5634,
  643,
  1132,
  714,
  3993,
  3069,
  4674,
  3427,
  527,
  6188,
  2777,
  2737,
  753,
  2700,
  3753,
  6436,
  5316,
  6872,
  5076,
  3890,
  1889,
  4639,
  3464,
  4646,
  4646,
  5705,
  6685,
  4861,
  234,
  881,
  284,
  2684,
  542,
  840,
  3366,
  6583,
  4454,
  3842,
  900,
  6308,
  601,
  4241,
  900,
  6726,
  683,
  2851,
  606,
  6360,
  6972,
  3151,
  683,
  1204,
  6972,
  5036,
  2627,
  6379,
  119,
  6094,
  6188,
  4739],
 [578,
  1101,
  4540,
  647,
  5842,
  3940,
  6920,
  1195,
  5050,
  6532,
  3582,
  4755,
  2737,
  2485,
  1344,
  4639,
  862,
  6997,
  3147,
  5169,
  3779,
  432,
  4395,
  6188,
  823,
  5378,
  4844,
  5722,
  6741,
  4961,
  6535,
  1332,
  1508,
  3435,
  4587,
  2575,
  578,
  29,
  2517,
  1222,
  1388,
  6986,
  594,
  1241,
  3858,
  5804,
  4985,
  4963,
  4646,
  4646,
  2025,
  5076,
  2517,
  4639,
  4567,
  1642,
  2846,
  5217,
  6878,
  2349,
  6433,
  256,
  4482,
  6851,
  436,
  531,
  196,
  2220,
  6530,
  6087,
  3846,
  2334,
  4646,
  4646,
  6741,
  3276,
  453,
  351,
  5338,
  3329,
  6897,
  5468,
  4356,
  1813,
  3890,
  4639,
  6970,
  643,
  2359],
 [3629,
  1001,
  881,
  6649,
  936,
  2607,
  252,
  1395,
  6062,
  2640,
  5842,
  4646,
  4646,
  5561,
  1617,
  6454,
  849,
  636,
  936,
  6349,
  6336,
  1296,
  4524,
  252,
  4646,
  4646,
  4715,
  969,
  6383,
  6167,
  4930,
  559,
  1680,
  6104,
  493,
  493,
  5561,
  1688,
  6062,
  1628,
  4749,
  2747,
  3330,
  3464,
  936,
  1395,
  441,
  4334,
  4930,
  3947,
  643,
  1033,
  1033,
  5561,
  3853,
  5547,
  493,
  2192,
  6104,
  2036,
  4646,
  4646,
  6076,
  6491,
  6188,
  4247,
  6062,
  2809,
  2346,
  647,
  936,
  5499],
 [5512,
  5740,
  4963,
  5842,
  5937,
  1709,
  5629,
  4930,
  2175,
  6365,
  5740,
  3955,
  5804,
  2293,
  3451,
  6546,
  135,
  5561,
  37,
  1524,
  5804,
  5937,
  1249,
  6619,
  3741,
  5411,
  812,
  1573,
  4646,
  4646,
  3511,
  2017,
  4491,
  4241,
  5296,
  2603,
  2415,
  4320,
  6427,
  5842,
  6949,
  4473,
  5411,
  3779,
  1395,
  5683,
  5076,
  6419,
  5076,
  4540,
  4849,
  2338,
  1787,
  5076,
  37,
  5053,
  2360,
  1508,
  342,
  1742,
  4930,
  1657,
  6052,
  177,
  2414,
  643,
  3741,
  2619,
  6512,
  2619,
  6363,
  4646,
  4646,
  284,
  5076,
  6017,
  1079,
  5597,
  5411,
  1479,
  4140,
  5076,
  2614,
  1704,
  4980,
  3647,
  6978,
  5441,
  6546,
  135,
  5822,
  1049,
  1498,
  5076,
  5716,
  5468,
  3741,
  1573,
  4646,
  4646,
  5143,
  5334,
  6365,
  5740,
  6212,
  3445,
  2661,
  4205,
  4938,
  4101,
  3467,
  1767,
  1567,
  3967,
  3147,
  6723,
  6596,
  5546,
  6167,
  3779,
  4861,
  1701,
  4646,
  4646,
  5966,
  6365,
  5740,
  5334,
  4863,
  11,
  5722,
  2338,
  5107],
 [5767,
  5842,
  172,
  5561,
  3944,
  107,
  6666,
  1888,
  2871,
  4831,
  4696,
  4869,
  6878,
  6017,
  3854,
  1914,
  6591,
  4748,
  5842,
  1541,
  1459,
  4567,
  4312,
  5443,
  4542,
  1332,
  4587,
  371,
  5817,
  2712,
  5076,
  5634,
  5261,
  440,
  5045,
  87,
  2333,
  2846,
  2747,
  5300,
  6750,
  1029,
  6167,
  2314,
  2175,
  4963,
  4111,
  3693,
  2853,
  6512,
  6877,
  2165,
  1808,
  6955,
  3901,
  5561],
 [6459,
  3923,
  2747,
  643,
  4929,
  4613,
  6627,
  6838,
  2748,
  4433,
  3923,
  469,
  2464,
  87,
  801,
  3050,
  5930,
  2493,
  552,
  6627,
  6670,
  4923,
  6379,
  2003,
  6896,
  1943,
  6949,
  3354,
  4485,
  4533,
  3486,
  5877,
  552,
  3923,
  5107,
  6512,
  378,
  1208,
  541,
  4540,
  5304,
  4231,
  2747,
  1886,
  3858,
  3181,
  552,
  3858,
  5561,
  1629,
  4540,
  4541,
  2353,
  2209,
  2846,
  3923,
  6529,
  4085,
  6108,
  1508,
  3354,
  4485,
  2702,
  3923,
  6491,
  961,
  3923,
  934,
  4709,
  6187,
  2872,
  1265,
  559,
  6970,
  934],
 [2218,
  2186,
  1589,
  149,
  27,
  3936,
  969,
  1362,
  969,
  2459,
  2069,
  4567,
  5974,
  284,
  6897,
  5386,
  2218,
  6685,
  2688,
  2961,
  3787,
  1649,
  5193,
  3443,
  5842,
  4433,
  4646,
  4646,
  5634,
  1212,
  523,
  2218,
  4563,
  1768,
  3236,
  2630,
  4542,
  3867,
  2630,
  3471,
  5272,
  5926,
  5889,
  5838,
  2218,
  5767,
  1388,
  6532,
  5822,
  5572,
  4541,
  505,
  4158,
  2225,
  3470,
  5546,
  3618,
  4405,
  1054,
  4391,
  3516,
  5076,
  6548,
  4441,
  643,
  5288,
  4767,
  6684,
  4008,
  559,
  4653,
  3435,
  664,
  5042,
  3470,
  5546,
  810,
  2218,
  2912,
  6619,
  2218,
  4011,
  4541,
  1388,
  6532],
 [940,
  1049,
  5081,
  4930,
  1441,
  2197,
  2737,
  4930,
  2630,
  3525,
  6591,
  3573,
  4930,
  5634,
  5076,
  1404,
  4011,
  3867,
  6379,
  4540,
  714,
  4705,
  3341,
  5143,
  2102,
  4930,
  6352,
  110,
  6759,
  684,
  497,
  5926,
  5953,
  5842,
  4930,
  177,
  1530,
  4784,
  4869,
  5388,
  1014,
  430,
  643,
  1201,
  4247,
  4930,
  4646,
  4646,
  284,
  4735,
  2723,
  2568,
  3607,
  3491,
  5344,
  523,
  6978,
  4542,
  165,
  37,
  6692,
  6468,
  3690,
  5076,
  5344,
  6202],
 [2747,
  3470,
  1360,
  2782,
  1462,
  2747,
  5561,
  3846,
  3854,
  4963,
  5561,
  4562,
  4395,
  5811,
  1212,
  4646,
  4646,
  3890,
  1814],
 [2767,
  6765,
  5076,
  2969,
  4930,
  5898,
  2052,
  2417,
  1536,
  387,
  840,
  4280,
  6269,
  4646,
  4646,
  969,
  3738,
  3275,
  2688,
  5561,
  1557,
  5822,
  3391,
  1536,
  2688,
  2961,
  4646,
  4646,
  2343,
  5699,
  4930,
  5313,
  6878,
  3198,
  3275,
  4356,
  3779,
  3704,
  3390,
  6336,
  4646,
  4646,
  6579,
  4930,
  3923,
  27,
  2641,
  2927,
  4039,
  4646,
  4646,
  87,
  1033,
  2710,
  433,
  6966,
  4849,
  2944],
 [3787,
  5561,
  3322,
  1081,
  4379,
  4611,
  2851,
  1704,
  2724,
  1411,
  1212,
  177,
  3191,
  7,
  2220,
  6532,
  4458,
  4458,
  4646,
  4646,
  3846,
  87,
  6383,
  2220,
  5269,
  4930,
  3204,
  3637,
  1388,
  2795,
  4198,
  6495,
  331,
  5561,
  2219,
  5217,
  4923,
  4043,
  2334,
  2165,
  1565,
  194,
  430,
  154,
  6495,
  888,
  1201,
  4662,
  6603,
  3839,
  4150,
  3322,
  4567,
  3854,
  6528,
  862,
  4963,
  4363,
  351,
  4646,
  4646,
  4567,
  1257,
  3787,
  5659,
  1081,
  2294,
  664,
  1555,
  1590,
  5252,
  172,
  4930,
  5919,
  2065,
  3507,
  1508,
  3254,
  1787,
  6692,
  3944,
  6167,
  1741,
  169,
  6188,
  675,
  4198,
  4342],
 [3908,
  1704,
  2182,
  139,
  5107,
  3858,
  4431,
  5561,
  4713,
  764,
  3908,
  5076,
  139,
  3753,
  4151,
  2220,
  3366,
  523,
  375,
  2093,
  4082,
  4395,
  2067,
  4395,
  1884,
  4646,
  4646,
  3741,
  4431,
  5945,
  2091,
  2242,
  6840,
  319,
  5537,
  2887,
  117,
  4417,
  562,
  523,
  375,
  87,
  6365,
  139,
  6918,
  2472,
  3455,
  5676,
  1335,
  4202,
  1119,
  3151,
  6365,
  139,
  3684,
  2829,
  6963,
  4241,
  2387,
  6970,
  781,
  5042,
  3146,
  5842,
  4485,
  1880,
  3553,
  4646,
  4646,
  2829,
  781,
  268,
  810,
  3635,
  3275,
  1704,
  5561,
  3764,
  2829,
  6970,
  2747,
  580,
  6166,
  497,
  5042,
  3146,
  6562,
  6166,
  6169,
  4179,
  3273,
  1411,
  5963,
  1458,
  5822,
  2128,
  5143,
  5561,
  3275,
  6124,
  3741,
  3928,
  6685,
  3960,
  2689,
  1921,
  6166,
  6958,
  3787,
  6166,
  969,
  1787,
  5646,
  6685,
  5053,
  4943,
  2747,
  4408,
  4646,
  4646,
  1458,
  3341,
  4930,
  3119,
  5504,
  643,
  6974,
  6171,
  1675,
  4742,
  4078,
  497,
  5842,
  4485,
  6692,
  5488,
  1062,
  2947,
  1883,
  3683,
  2114,
  6691,
  6840,
  319,
  4417,
  4910,
  6019,
  4553,
  3854,
  5313,
  2220,
  6922,
  4415,
  3853,
  2353,
  6529,
  6159,
  3165,
  5693,
  4395,
  4144,
  523,
  3911,
  375,
  1229,
  4010,
  6970,
  2209,
  5062,
  2689,
  139,
  6068,
  6970,
  643,
  5561,
  4961,
  3301,
  2689,
  139,
  5230,
  6996,
  5661,
  4646,
  4646,
  284,
  2777,
  2828,
  3923,
  673,
  139,
  5334,
  5107,
  177,
  4930,
  6529,
  4702,
  2640,
  2851,
  1921,
  6646,
  6096,
  1883,
  5082,
  1134,
  2851,
  387,
  6167,
  3667,
  5561,
  523,
  375,
  3574,
  878,
  6832,
  1836,
  1921,
  5987,
  2209,
  2342,
  1625,
  6970,
  2304,
  5049,
  6166,
  6017,
  2645,
  216,
  6167,
  2209,
  3999,
  969,
  2829,
  277,
  4608],
 [5546,
  497,
  1319,
  4646,
  4646,
  1319,
  3390,
  4646,
  4646,
  1428,
  3097,
  469,
  1319,
  4322,
  4334,
  87,
  5334,
  4646,
  4646,
  4976,
  4241,
  172,
  1319,
  5053,
  5053,
  565,
  335,
  409,
  6524,
  13,
  1027,
  87,
  1033,
  4139,
  926,
  4646,
  4646,
  510,
  4010,
  3867,
  5548,
  4646,
  4646,
  1058,
  1058,
  165,
  6407,
  961,
  1588,
  6494,
  6733,
  6878,
  4604,
  5848,
  6383,
  2846,
  5561,
  2366,
  6970,
  2693],
 [2212,
  5561,
  2829,
  3671,
  6336,
  3613,
  5076,
  4600,
  5499,
  3736,
  2182,
  5088,
  2630,
  4849,
  5334,
  284,
  5561,
  2102,
  2071,
  1434,
  6010,
  5779,
  5561,
  6530,
  2386,
  1861],
 [6540,
  3347,
  154,
  2851,
  6535,
  5076,
  831,
  6168,
  6468,
  4930,
  1785,
  6591,
  271,
  2747,
  4167,
  6317,
  4930,
  1007,
  5342,
  3744,
  4981,
  714,
  3779,
  4682,
  4459,
  4512,
  4942,
  3275,
  5572,
  6017,
  3884,
  5076,
  4332,
  6132,
  5974,
  4483,
  4823,
  2620,
  4780,
  221,
  276,
  6893,
  2964,
  5222,
  3398,
  6006,
  6117,
  551,
  1573,
  5008,
  4770,
  6530,
  4247,
  3153,
  440,
  4653,
  5076,
  3204,
  2747,
  5507,
  544,
  2630,
  3393,
  4930,
  5937,
  3221,
  3689,
  3580,
  1029,
  5177,
  559],
 [4930,
  4579,
  6325,
  5076,
  2630,
  4930,
  1708,
  6351,
  135,
  4499,
  2591,
  4930,
  778,
  748,
  2713,
  3776,
  2879,
  5546,
  4465,
  1126,
  4446,
  5287,
  469,
  2220,
  2407,
  3779,
  6535,
  6487,
  4643,
  6360,
  6418,
  523,
  138,
  955,
  3944,
  2040,
  3368,
  3390,
  4558,
  6752,
  4930,
  6568,
  5435,
  4918,
  3034,
  2846,
  2630,
  4930,
  4067,
  5211,
  4499,
  435,
  6360,
  6603],
 [5561,
  810,
  5076,
  6691,
  6491,
  4011,
  5561,
  4659,
  4646,
  4646,
  871,
  277,
  3993,
  5076,
  6495,
  4849,
  2212,
  3779,
  2983,
  5705,
  3659,
  5076,
  6578,
  3993,
  4849,
  635,
  2294,
  2850,
  1704,
  2630,
  6734,
  6724,
  5965,
  4646,
  4646,
  2851,
  1010,
  4375,
  5561,
  1837,
  664,
  667,
  5767,
  4646,
  4646,
  2483,
  4646,
  4646,
  1620,
  2851,
  1201,
  4375,
  178,
  2851,
  3854,
  664,
  667,
  2542,
  6692,
  5076,
  1984,
  4646,
  4646,
  5453,
  6734,
  1120,
  3647,
  2747,
  2867,
  3283,
  5453,
  710,
  1635,
  2999,
  5693,
  3903,
  4930,
  1899,
  5864,
  6899,
  3903,
  768,
  2519,
  2311,
  4646,
  4646,
  1921,
  6734,
  6539,
  6546,
  5296,
  5767,
  527,
  4646,
  4646,
  2483,
  3443,
  5842,
  1602,
  1227,
  6425,
  6425,
  4646,
  4646,
  2191,
  3944,
  961,
  6933,
  2191,
  6816,
  5561,
  3221,
  1680,
  1029,
  5561,
  2640,
  5561,
  6603,
  5405,
  4646,
  4646,
  4011,
  3330,
  4869,
  2846,
  165,
  2471,
  5937],
 [3739,
  4930,
  969,
  4930,
  5547,
  6266,
  5597,
  6581,
  5441,
  5174,
  2464,
  5202,
  3301,
  3066,
  2065,
  6966,
  1039,
  3643,
  6266,
  3643,
  6722,
  216,
  4379,
  889,
  221,
  3280,
  4930,
  3618,
  3724,
  3666,
  6568,
  4600,
  5226,
  4207,
  2607,
  5076,
  889,
  6017,
  647,
  5576,
  4208,
  5053,
  5822,
  309,
  4430,
  3287,
  934,
  5053,
  6266,
  496,
  1700,
  6801,
  1704,
  828,
  1647,
  6266,
  5660,
  544,
  190,
  3923,
  4963,
  3788,
  4344,
  6591,
  4930,
  2747],
 [4011,
  4930,
  559,
  3330,
  5628,
  6914,
  6395,
  1441,
  2414,
  3944,
  969,
  3613,
  2007,
  4370,
  4783,
  4952,
  3119,
  4993,
  6155,
  2414,
  2221,
  1931,
  3944,
  5334,
  3923,
  3146,
  6331,
  4579,
  4682,
  6081,
  2689,
  3944,
  455,
  3923,
  810,
  523,
  2710,
  4930,
  4861,
  3949,
  5682,
  3067,
  4929,
  2923,
  5666,
  3741,
  5788,
  6360,
  4089,
  411,
  1201,
  788,
  455,
  3464,
  3221,
  5377,
  2670,
  6469,
  376,
  6723,
  4930,
  39],
 [6619,
  5936,
  5572,
  161,
  5261,
  6685,
  6281,
  2555,
  5936,
  5572,
  5561,
  2291,
  3038,
  917,
  3038,
  5441,
  3038,
  5842,
  6031,
  4108,
  5936,
  5572,
  2441,
  5842,
  6403,
  5516,
  2720,
  5811,
  3999,
  4672,
  351,
  4646,
  4646,
  4108,
  5076,
  1704,
  4464,
  4360,
  4454,
  2733,
  6400,
  2441,
  2777,
  2003,
  463,
  85,
  334,
  3476,
  5143,
  6148,
  1822,
  1053,
  2576,
  4930,
  5076,
  2553,
  3891,
  4186,
  4672,
  4395,
  4482,
  6017,
  3377,
  3762,
  1458,
  5144,
  5222,
  268,
  2354,
  1160,
  5272,
  2762,
  3301,
  1804,
  4558,
  163,
  1804,
  3667,
  4646,
  4646,
  2353,
  4963,
  4428,
  766,
  4812,
  4706,
  1591,
  6379,
  5164,
  1054,
  2162,
  6978,
  5580,
  1007,
  3933,
  1467,
  5579,
  1548,
  1258,
  2865,
  4646,
  4646,
  6741,
  5866,
  3451,
  4844,
  5722,
  1767,
  6994,
  5621,
  996,
  3416,
  4542,
  1807,
  2349,
  236,
  6469,
  509,
  972,
  5694,
  2071,
  6878,
  4475,
  4552,
  2466,
  3892,
  6685,
  177,
  2747,
  2613,
  397,
  6160,
  3779,
  2748,
  3735,
  6480,
  6211,
  4646,
  4646,
  5076,
  559,
  6970,
  3953,
  4573,
  4015,
  4600,
  5139,
  4154,
  1970,
  2630,
  917,
  4861,
  1936,
  2466,
  5190,
  1807,
  6546,
  2088,
  6562,
  2036,
  4067,
  6468,
  1807,
  4718,
  5334,
  4408,
  4646,
  4646,
  5144,
  2710,
  6337,
  4662,
  3221,
  6878,
  5151,
  5440,
  5143,
  1775,
  2482,
  5627,
  4067,
  1441,
  3078,
  5076,
  4297,
  3705],
 [4832,
  4701,
  1886,
  5269,
  5561,
  5709,
  4646,
  4646,
  2846,
  2471,
  5842,
  5937,
  2353,
  1404,
  5269,
  5561,
  5842,
  4395,
  3683,
  5269,
  5561,
  2747,
  5407,
  5561,
  1708,
  2226,
  6167,
  5334,
  5561,
  3944,
  4356,
  4600,
  4844,
  4357,
  2165,
  2630,
  6212,
  4320,
  5715,
  1947,
  3867,
  2688,
  3867,
  4646,
  4646,
  5561,
  5629,
  1822,
  2538,
  5076,
  99,
  1111,
  1787,
  3221,
  5822,
  5705,
  165,
  881,
  6468,
  4646,
  4646,
  5561,
  4459,
  6379,
  6207,
  1212,
  2334,
  1025,
  256,
  2733,
  3854,
  4708,
  284,
  4861,
  6207,
  1201,
  433,
  4654,
  436,
  4960,
  4659,
  6341,
  4074,
  215,
  4646,
  4646,
  4395,
  4780,
  5269,
  5561,
  1388,
  4653,
  3667,
  509,
  2175],
 [3358,
  5629,
  5561,
  3435,
  5551,
  4725,
  4524,
  2175,
  4291,
  6603,
  2314,
  4552,
  4092,
  5561,
  1625,
  957,
  4769,
  1388,
  1212,
  1407,
  5987,
  4987,
  2342,
  5842,
  2708,
  2248,
  5842,
  6685,
  422,
  5313],
 [969,
  934,
  6017,
  284,
  666,
  5651,
  2182,
  2879,
  598,
  1931,
  3031,
  2175,
  6000,
  5102,
  5842,
  3210,
  5269,
  2747,
  3152,
  5269,
  5561,
  1044,
  6258,
  2747,
  580,
  5561,
  221,
  4646,
  4646,
  1948,
  5561,
  969,
  4861,
  37,
  2747,
  6383,
  3458,
  5269,
  5561,
  2538,
  3294,
  4925,
  5732,
  5651,
  4861,
  5561,
  6970,
  1637,
  1488,
  4646,
  4646,
  5982,
  2630,
  1530,
  4395,
  1138,
  3739,
  6000,
  5102,
  4333,
  1931,
  1530,
  5076,
  2851,
  5561,
  6633,
  3739,
  3905,
  87,
  4740,
  6317,
  87,
  3294,
  4832,
  6456,
  177,
  1138,
  580,
  1379,
  1375,
  2619,
  4320,
  5982,
  409,
  3147,
  6984,
  2733,
  6494,
  4366,
  1114,
  712,
  477,
  3066,
  2342,
  3652,
  309,
  2195,
  2387,
  284,
  561,
  287,
  3021,
  3391,
  5081,
  2747,
  6789,
  1325,
  1902,
  2760,
  6224,
  6285,
  6354,
  4540,
  3120,
  4067,
  5561,
  4292,
  5842,
  4646,
  4646,
  173,
  5499,
  2218,
  4849,
  4788,
  416,
  4984,
  115,
  4668,
  5269,
  5561,
  712,
  3389,
  3275,
  509,
  2175,
  163,
  1044,
  5842,
  2723,
  5561,
  6076,
  6491,
  3531,
  5351,
  5551,
  6491,
  6217,
  6383,
  4653,
  4646,
  4646,
  4740,
  4408,
  6622,
  6076,
  6491,
  5238,
  3275,
  6603,
  4869,
  2630,
  2314,
  2977,
  2829,
  6742,
  5822,
  4540,
  6167,
  2314,
  6336,
  2314,
  2977,
  4748],
 [1404,
  5561,
  3787,
  6301,
  3618,
  1198,
  165,
  534,
  1245,
  2817,
  2607,
  6627,
  4993,
  2052,
  534,
  3082,
  4600,
  4930,
  3890,
  643,
  3205,
  462,
  5561,
  277,
  5945,
  6603,
  2710,
  4499,
  6432,
  4487,
  6723,
  5143,
  5572,
  2395,
  5561,
  4780,
  6528,
  3886,
  3779,
  441,
  2606,
  5190,
  2665,
  2175,
  3330,
  635,
  4978,
  3944,
  5561,
  3876,
  4600,
  6017,
  5107,
  2407,
  3470,
  2983,
  2832,
  2407,
  2747,
  5076,
  3858,
  666,
  1996,
  5561,
  3787,
  2464,
  4319,
  4395,
  5334,
  5076,
  4052,
  4646,
  4646],
 [6584,
  737,
  3944,
  2218,
  881,
  3074,
  6584,
  737,
  5256,
  3464,
  5371,
  1708,
  2723,
  4001,
  1931,
  105,
  4646,
  4646,
  5187,
  6770,
  1087,
  6584,
  6331,
  2663,
  5334,
  4499,
  4241,
  4750,
  271,
  5836,
  6584,
  737,
  2607,
  440,
  4718,
  6946,
  3779,
  1602,
  6946,
  2047,
  4646,
  4646,
  4404,
  2807,
  440,
  4259,
  737,
  3909,
  3890,
  3859,
  6584,
  4963,
  4646,
  4646,
  3890,
  6352,
  3221,
  5217,
  2102,
  2620,
  6582,
  5371,
  5561,
  6691,
  3388,
  517,
  3152,
  6759],
 [117,
  2900,
  2218,
  2925,
  1885,
  4902,
  4810,
  4844,
  5722,
  3618,
  5076,
  6596,
  2603,
  6127,
  3895,
  6312,
  6546,
  763,
  3743,
  6176,
  6328,
  5375,
  5107,
  3300,
  1623,
  578,
  2177,
  4198,
  5030,
  4722,
  87,
  5634,
  5860,
  6978,
  5561,
  4567,
  3496,
  4646,
  4646,
  4085,
  4462,
  6155,
  4930,
  1235,
  1241,
  6541,
  3353,
  5546,
  3779,
  2630,
  5143,
  6166,
  1029,
  4930,
  4843,
  1508,
  5561,
  6741,
  3903,
  330,
  5623,
  5561,
  2275,
  5749,
  117,
  1157,
  6261,
  4849,
  6512,
  6328,
  849,
  6261,
  4328,
  1227,
  2603,
  2001,
  4822,
  3853,
  4132,
  3923,
  5630,
  4849,
  5561,
  2001,
  3923,
  4963,
  643,
  1602,
  433,
  3814,
  4646,
  4646,
  2248,
  4409,
  6383,
  6672,
  4810,
  4844,
  5722,
  6562,
  949,
  6374,
  6468,
  4145,
  4319,
  1822,
  5561,
  3097,
  6798,
  6167,
  4844,
  5722,
  1591,
  713,
  6117,
  117,
  3503,
  5523,
  1312,
  6949,
  4407,
  3396,
  5958,
  4810,
  5779,
  3836,
  5926,
  5663,
  178,
  684,
  691,
  598,
  1785,
  1766,
  4646,
  4646,
  2747,
  5561,
  3725,
  5804,
  6603,
  3524,
  4633,
  3097,
  4557,
  4586,
  2968,
  268,
  6017,
  4665,
  6113,
  4849,
  3853,
  5149,
  605,
  3862,
  5430,
  177,
  2747,
  6685,
  2093,
  3769,
  4840,
  4849,
  5911,
  117,
  3853,
  934,
  643,
  2819,
  3741,
  2747,
  2689,
  2747,
  5029,
  5561,
  5561,
  907,
  4172,
  6949,
  688,
  559,
  934,
  1231,
  4579,
  2342,
  4646,
  4646,
  5096,
  4930,
  6581,
  489,
  983,
  764,
  155,
  6942,
  2932,
  6672,
  6113,
  4849,
  4742,
  3151,
  6030,
  4579,
  1999,
  6995,
  4930,
  2065,
  234,
  4692,
  2075,
  6978,
  6341,
  6978,
  2603,
  2747,
  165,

## Padding now:

In [32]:
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding
from tensorflow.keras.layers import Dense,LSTM,Dropout
from tensorflow.keras.callbacks import EarlyStopping

In [8]:
max_sent=50
padding=pad_sequences(ohe,maxlen=max_sent,padding='post')
padding

array([[ 353, 2846, 3896, ..., 3312, 4207, 6689],
       [2777, 2737,  753, ..., 6094, 6188, 4739],
       [1222, 1388, 6986, ..., 6970,  643, 2359],
       ...,
       [5192, 2007,  290, ..., 1474, 5022, 2189],
       [2022, 1921, 2515, ...,  967, 1884,  469],
       [2164, 6864,  523, ..., 2695, 5119, 5561]], dtype=int32)

In [33]:
model=Sequential()
model.add(Embedding(vocab_size,100,input_length=max_sent))
model.add(Dropout(0.2))
model.add(LSTM(200))
model.add(Dense(1,activation='sigmoid'))
model.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

/home/hammadali08/.local/lib/python3.12/site-packages/keras/src/layers/core/embedding.py:97: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(

In [34]:
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_1 (Embedding)         │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout (Dropout)               │ ?                      │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_1 (LSTM)                   │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [35]:
Y=pd.get_dummies(dataset['sentiment'],drop_first=True)
Y=Y.astype('int64')
Y

       positive
0             1
1             1
2             1
3             0
4             1
...         ...
49995         1
49996         0
49997         0
49998         0
49999         0

[50000 rows x 1 columns]

In [36]:
import numpy as np
X=np.array(padding)
Y=np.array(Y)

In [37]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(X,Y,test_size=0.2,random_state=0)

# Model Training

In [38]:
model.fit(x_train,y_train,epochs=10,batch_size=50,validation_data=(x_test,y_test),callbacks=EarlyStopping())

Epoch 1/10
800/800 ━━━━━━━━━━━━━━━━━━━━ 60s 72ms/step - accuracy: 0.8068 - loss: 0.4194 - val_accuracy: 0.8392 - val_loss: 0.3694
Epoch 2/10
800/800 ━━━━━━━━━━━━━━━━━━━━ 62s 78ms/step - accuracy: 0.8638 - loss: 0.3193 - val_accuracy: 0.8373 - val_loss: 0.3664
Epoch 3/10
800/800 ━━━━━━━━━━━━━━━━━━━━ 69s 86ms/step - accuracy: 0.8919 - loss: 0.2645 - val_accuracy: 0.8304 - val_loss: 0.3888

In [39]:
y_pred=model.predict(x_test)
y_pred=np.where(y_pred>0.7,1,0) # AUC ROC Curve

313/313 ━━━━━━━━━━━━━━━━━━━━ 6s 20ms/step

In [44]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test,y_pred)

array([[4507,  528],
       [1340, 3625]])

In [45]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.77      0.90      0.83      5035
           1       0.87      0.73      0.80      4965

    accuracy                           0.81     10000
   macro avg       0.82      0.81      0.81     10000
weighted avg       0.82      0.81      0.81     10000

In [46]:
from sklearn.metrics import roc_auc_score
roc_auc_score(y_test,y_pred)

0.8126224184985064

In [47]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.8132