In [1]:
import nltk
import pandas as pd

In [2]:
dataset=pd.read_csv('/home/hammadali08/Personal/CSV file/IMDB Dataset.csv')
dataset

                                                  review sentiment
0      One of the other reviewers has mentioned that ...  positive
1      A wonderful little production. <br /><br />The...  positive
2      I thought this was a wonderful way to spend ti...  positive
3      Basically there's a family where a little boy ...  negative
4      Petter Mattei's "Love in the Time of Money" is...  positive
...                                                  ...       ...
49995  I thought this movie did a down right good job...  positive
49996  Bad plot, bad dialogue, bad acting, idiotic di...  negative
49997  I am a Catholic taught in parochial elementary...  negative
49998  I'm going to have to disagree with the previou...  negative
49999  No one expects the Star Trek movies to be high...  negative

[50000 rows x 2 columns]

In [3]:
import re
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
lemmatizer=WordNetLemmatizer()
corpus=[]
stop_words = set([w.lower() for w in stopwords.words('english')])

for i in range(0, len(dataset)):
    review = re.sub('[^a-zA-Z0-9]', ' ', dataset['review'][i])
    review = review.lower()
    review = review.split()

    review = [lemmatizer.lemmatize(word) for word in review if word not in stop_words]
    review = ' '.join(review)
    corpus.append(review)

In [4]:
len(corpus)

50000

In [5]:
from tensorflow.keras.preprocessing.text import one_hot
vocab_size=7000

2025-08-25 18:06:54.495070: I external/local_xla/xla/tsl/cuda/cudart_stub.cc:32] Could not find cuda drivers on your machine, GPU will not be used.
2025-08-25 18:06:54.560595: I external/local_xla/xla/tsl/cuda/cudart_stub.cc:32] Could not find cuda drivers on your machine, GPU will not be used.
2025-08-25 18:06:54.585834: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:467] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1756127214.661999   48711 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1756127214.674218   48711 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
W0000 00:00:1756127214.822263   48711 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1756127214.822306   48711 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1756127214.822310   48711 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1756127214.822313   48711 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
2025-08-25 18:06:54.835576: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.

In [6]:
ohe=[one_hot(words,vocab_size) for words in corpus]
ohe

[[1555,
  2835,
  835,
  1198,
  1292,
  3171,
  2784,
  5053,
  5314,
  2840,
  1995,
  4546,
  4546,
  1855,
  4372,
  1820,
  3171,
  4167,
  2320,
  5743,
  1083,
  1889,
  5314,
  5730,
  2339,
  3975,
  416,
  6274,
  1052,
  2767,
  416,
  1001,
  4694,
  2820,
  6071,
  1184,
  1083,
  2788,
  4033,
  1586,
  5730,
  4546,
  4546,
  2039,
  3171,
  4465,
  5540,
  2944,
  5171,
  5116,
  5844,
  5823,
  1151,
  2396,
  1868,
  6931,
  4552,
  6311,
  4427,
  517,
  6438,
  1772,
  4354,
  4822,
  4922,
  1357,
  3763,
  4358,
  6931,
  4224,
  6911,
  6413,
  3378,
  2263,
  168,
  2704,
  6466,
  1146,
  95,
  2644,
  433,
  1945,
  4318,
  4093,
  4776,
  6647,
  4009,
  2473,
  4546,
  4546,
  3532,
  1305,
  333,
  6183,
  416,
  3083,
  96,
  2339,
  416,
  1961,
  6109,
  4611,
  2503,
  6369,
  240,
  6547,
  6109,
  1285,
  6109,
  6091,
  3171,
  1605,
  1834,
  1855,
  2784,
  3880,
  1104,
  1820,
  5998,
  4388,
  1305,
  1896,
  6274,
  4792,
  2155,
  3171,
  2250,
  399,
  1357,
  2166,
  5043,
  1083,
  1083,
  1594,
  407,
  2243,
  5029,
  2618,
  2629,
  1887,
  4185,
  5115,
  2473,
  4020,
  1763,
  1646,
  2502,
  2629,
  5141,
  4427,
  6511,
  3083,
  665,
  6625,
  5446,
  4427,
  4443,
  1198,
  3171,
  5344,
  377,
  1712,
  5546,
  2127,
  4992,
  5115,
  3900,
  1288,
  6945],
 [1777,
  4680,
  3972,
  4546,
  4546,
  6700,
  1076,
  4514,
  4230,
  6911,
  3100,
  1104,
  5858,
  2592,
  427,
  3130,
  4317,
  3519,
  206,
  6834,
  4546,
  4546,
  1452,
  859,
  4020,
  1513,
  1832,
  6101,
  2250,
  5626,
  6568,
  1464,
  3330,
  5119,
  1105,
  6094,
  5829,
  6469,
  2769,
  6055,
  2361,
  4020,
  2473,
  1198,
  449,
  558,
  134,
  6834,
  2035,
  3972,
  1555,
  610,
  82,
  5974,
  3452,
  4546,
  4546,
  3519,
  3687,
  1082,
  4224,
  4680,
  4372,
  5990,
  2243,
  6156,
  1586,
  3297,
  1499,
  1076,
  169,
  3518,
  5219,
  329,
  2370,
  6404,
  5684,
  5743,
  4605,
  6628,
  3294,
  1889,
  5684,
  5736,
  3294,
  2376,
  4645,
  83,
  4598,
  2355,
  4020,
  1700],
 [3834,
  1777,
  4102,
  1876,
  6911,
  5266,
  1176,
  5448,
  5866,
  655,
  2707,
  270,
  1198,
  1242,
  1052,
  5974,
  1583,
  6688,
  2530,
  3347,
  1550,
  933,
  4640,
  4020,
  5157,
  4899,
  625,
  348,
  5344,
  4051,
  2865,
  1671,
  646,
  3100,
  5525,
  4000,
  3834,
  2665,
  3032,
  734,
  5953,
  3531,
  374,
  6248,
  6911,
  6306,
  6927,
  4625,
  4546,
  4546,
  5040,
  1555,
  3032,
  5974,
  6914,
  1961,
  1305,
  6415,
  6647,
  1365,
  4848,
  3538,
  1951,
  6521,
  4923,
  5218,
  4443,
  5314,
  4256,
  4902,
  3481,
  4804,
  4546,
  4546,
  5344,
  1792,
  1429,
  498,
  2988,
  5741,
  1603,
  3821,
  6131,
  3660,
  610,
  5974,
  2339,
  5119,
  5182],
 [3417,
  4809,
  4680,
  598,
  425,
  934,
  1024,
  1297,
  5769,
  6128,
  6911,
  4546,
  4546,
  5869,
  5100,
  4371,
  3120,
  6855,
  425,
  5566,
  377,
  3209,
  1887,
  1024,
  4546,
  4546,
  4437,
  1855,
  434,
  5161,
  1364,
  603,
  1625,
  6120,
  1620,
  1620,
  5869,
  768,
  5769,
  1463,
  6145,
  5133,
  4583,
  3452,
  425,
  1297,
  6350,
  5125,
  1364,
  3805,
  5119,
  5175,
  5539,
  5869,
  6961,
  6274,
  1620,
  5139,
  6120,
  4136,
  4546,
  4546,
  365,
  1842,
  4020,
  5851,
  5769,
  2409,
  2099,
  2753,
  425,
  5161],
 [4252,
  6044,
  4625,
  6911,
  1156,
  1360,
  3144,
  1364,
  6385,
  3184,
  6044,
  563,
  6306,
  2801,
  4971,
  172,
  185,
  5869,
  4799,
  160,
  6306,
  1156,
  1315,
  3370,
  2371,
  3509,
  997,
  5963,
  4546,
  4546,
  5384,
  5880,
  574,
  329,
  1633,
  2264,
  1985,
  5310,
  3923,
  6911,
  4486,
  5536,
  3509,
  1550,
  1952,
  5644,
  1555,
  2416,
  1555,
  4102,
  5427,
  2118,
  1646,
  1555,
  4799,
  6374,
  4986,
  646,
  4032,
  6950,
  1364,
  2308,
  3179,
  1847,
  3141,
  5119,
  2371,
  5021,
  4487,
  5021,
  4930,
  4546,
  4546,
  4372,
  1555,
  5115,
  6734,
  2503,
  3509,
  283,
  1423,
  1555,
  1837,
  5683,
  6931,
  2840,
  6414,
  6498,
  172,
  185,
  4179,
  5417,
  6369,
  1555,
  2165,
  1456,
  2371,
  5963,
  4546,
  4546,
  2590,
  972,
  3184,
  6044,
  3990,
  3490,
  5305,
  4913,
  3048,
  3257,
  811,
  1832,
  4370,
  3357,
  5032,
  2896,
  1728,
  4939,
  5161,
  1550,
  1082,
  419,
  4546,
  4546,
  3228,
  3184,
  6044,
  972,
  2631,
  3547,
  73,
  2118,
  1178],
 [4611,
  6911,
  2170,
  5869,
  978,
  6934,
  6250,
  4283,
  6714,
  2180,
  3665,
  927,
  6647,
  5115,
  4230,
  908,
  2429,
  5937,
  6911,
  6875,
  6508,
  6914,
  3712,
  3177,
  584,
  2620,
  6582,
  3665,
  4529,
  3112,
  1555,
  3330,
  3607,
  1109,
  914,
  6954,
  5679,
  1305,
  5133,
  3539,
  5025,
  4003,
  5161,
  6875,
  6385,
  3004,
  3142,
  834,
  4001,
  4487,
  2212,
  2406,
  4683,
  5861,
  161,
  5869],
 [6099,
  3532,
  5133,
  5119,
  5606,
  1484,
  5660,
  6012,
  5531,
  4244,
  3532,
  41,
  4307,
  6954,
  5363,
  4611,
  2720,
  2347,
  3855,
  5660,
  5594,
  6249,
  83,
  2367,
  4897,
  1865,
  4486,
  3137,
  5320,
  2501,
  5586,
  4726,
  3855,
  3532,
  1178,
  4487,
  6185,
  3917,
  2853,
  4102,
  6391,
  4817,
  5133,
  772,
  6911,
  2899,
  3855,
  6911,
  5869,
  468,
  4102,
  2157,
  2250,
  5910,
  1305,
  3532,
  226,
  5822,
  2036,
  646,
  3137,
  5320,
  5939,
  3532,
  1842,
  2376,
  3532,
  2506,
  1502,
  289,
  474,
  26,
  603,
  2339,
  2506],
 [416,
  3222,
  2972,
  3933,
  328,
  3010,
  1855,
  701,
  1855,
  5845,
  4000,
  6914,
  6330,
  4372,
  2759,
  4657,
  416,
  3687,
  4156,
  6677,
  3751,
  4191,
  6216,
  6524,
  6911,
  4244,
  4546,
  4546,
  3330,
  2431,
  4009,
  416,
  6305,
  5047,
  1066,
  3690,
  584,
  2595,
  3690,
  1240,
  6330,
  629,
  506,
  4345,
  416,
  4611,
  5953,
  655,
  4179,
  858,
  2157,
  456,
  1919,
  2036,
  785,
  4939,
  5091,
  3545,
  4368,
  5643,
  3769,
  1555,
  2838,
  6447,
  5119,
  5815,
  2725,
  3578,
  4220,
  603,
  5858,
  3100,
  6357,
  2239,
  785,
  4939,
  2842,
  416,
  2543,
  3370,
  416,
  5099,
  2157,
  5953,
  655],
 [5332,
  5813,
  2532,
  1364,
  6170,
  2970,
  1198,
  1364,
  3690,
  2820,
  2429,
  2360,
  1364,
  3330,
  1555,
  3211,
  5099,
  2595,
  83,
  4102,
  6094,
  4364,
  3253,
  2590,
  3618,
  1364,
  5951,
  3417,
  4122,
  5667,
  2578,
  4741,
  3312,
  6911,
  1364,
  1847,
  3538,
  5998,
  927,
  3933,
  4136,
  6292,
  5119,
  774,
  3219,
  1364,
  4546,
  4546,
  4372,
  2873,
  3104,
  1292,
  6024,
  890,
  4682,
  4009,
  6414,
  584,
  2028,
  4799,
  534,
  5514,
  4408,
  1555,
  4682,
  5469],
 [5133,
  785,
  1591,
  6085,
  1981,
  5133,
  5869,
  3481,
  4230,
  4625,
  5869,
  3081,
  4640,
  5805,
  3039,
  4546,
  4546,
  610,
  1178],
 [2636,
  3069,
  1555,
  2780,
  1364,
  4398,
  5672,
  1834,
  5902,
  3801,
  6156,
  5768,
  4747,
  4546,
  4546,
  1855,
  2496,
  4611,
  4156,
  5869,
  5483,
  4179,
  3453,
  5902,
  4156,
  6677,
  4546,
  4546,
  4860,
  3274,
  1364,
  4992,
  6647,
  5858,
  4611,
  6131,
  1550,
  3825,
  3757,
  5213,
  4546,
  4546,
  5805,
  1364,
  3532,
  6183,
  3594,
  3700,
  1617,
  4546,
  4546,
  388,
  5539,
  5896,
  3832,
  693,
  5427,
  1179],
 [1104,
  5869,
  6938,
  1443,
  5883,
  5312,
  5743,
  5683,
  2502,
  3151,
  2829,
  4510,
  3410,
  2866,
  5314,
  655,
  3846,
  3846,
  4546,
  4546,
  3481,
  6954,
  434,
  4511,
  1654,
  1364,
  1078,
  4436,
  5953,
  296,
  955,
  3364,
  547,
  5869,
  2718,
  3492,
  6249,
  6961,
  4804,
  1182,
  5730,
  2626,
  6292,
  4078,
  3364,
  1306,
  774,
  2504,
  491,
  2749,
  4731,
  6938,
  6914,
  4230,
  4290,
  1583,
  4625,
  1006,
  3989,
  4546,
  4546,
  6914,
  6075,
  1104,
  1325,
  1443,
  436,
  6357,
  1751,
  1934,
  6201,
  5596,
  1364,
  5692,
  3757,
  6928,
  646,
  4130,
  3516,
  534,
  978,
  5161,
  5944,
  6691,
  4020,
  53,
  955,
  4640],
 [2281,
  5683,
  3520,
  5794,
  1178,
  6911,
  4075,
  5869,
  469,
  6796,
  2281,
  1555,
  5794,
  3159,
  1091,
  5314,
  1586,
  4009,
  3959,
  5888,
  1148,
  4640,
  3765,
  4640,
  4239,
  4546,
  4546,
  2371,
  4075,
  3274,
  3376,
  1770,
  6811,
  660,
  1596,
  3832,
  1845,
  1453,
  701,
  4009,
  3959,
  388,
  3184,
  5794,
  3065,
  4491,
  1157,
  1246,
  4400,
  5859,
  655,
  1889,
  3184,
  5794,
  3516,
  4523,
  227,
  329,
  2019,
  2339,
  6567,
  6714,
  961,
  1232,
  6470,
  3995,
  3024,
  4546,
  4546,
  4523,
  6567,
  4882,
  2842,
  3034,
  4611,
  5683,
  5869,
  4429,
  1721,
  2339,
  5133,
  2921,
  5999,
  2578,
  6714,
  961,
  4096,
  5999,
  418,
  2619,
  6605,
  3151,
  5965,
  6389,
  4179,
  6463,
  2590,
  5869,
  4611,
  6507,
  2371,
  5919,
  3687,
  6703,
  4174,
  2256,
  5999,
  3763,
  1104,
  5999,
  1855,
  1646,
  6712,
  3687,
  6374,
  844,
  5133,
  41,
  4546,
  4546,
  6389,
  3253,
  1364,
  1775,
  6925,
  5119,
  1531,
  3419,
  3576,
  6316,
  2640,
  2578,
  1232,
  6470,
  534,
  3878,
  557,
  329,
  6639,
  2039,
  6702,
  4372,
  6811,
  660,
  1453,
  4723,
  5470,
  1445,
  5321,
  4992,
  5314,
  6009,
  3915,
  6961,
  2250,
  226,
  5660,
  2114,
  4735,
  4640,
  4000,
  4009,
  1421,
  3959,
  1817,
  817,
  2339,
  5910,
  6803,
  4174,
  5794,
  171,
  2339,
  5119,
  5869,
  4051,
  3371,
  4174,
  5794,
  4443,
  4991,
  493,
  4546,
  4546,
  4372,
  2473,
  6305,
  3532,
  950,
  5794,
  972,
  1178,
  4095,
  1364,
  226,
  6482,
  6128,
  5743,
  2256,
  6978,
  3002,
  6639,
  3648,
  5207,
  5743,
  3801,
  5161,
  4027,
  5869,
  4009,
  3959,
  3308,
  2228,
  6175,
  6551,
  1880,
  6561,
  5910,
  2446,
  1247,
  2339,
  1455,
  6155,
  5999,
  5115,
  74,
  3839,
  5161,
  5910,
  493,
  1855,
  4523,
  3935,
  3800],
 [4939,
  2578,
  4653,
  4546,
  4546,
  4653,
  3757,
  4546,
  4546,
  4407,
  2932,
  41,
  4653,
  3256,
  5125,
  388,
  972,
  4546,
  4546,
  5249,
  329,
  2170,
  4653,
  6374,
  6374,
  5140,
  5800,
  997,
  3237,
  6793,
  1282,
  388,
  5539,
  5931,
  5948,
  4546,
  4546,
  5730,
  817,
  2972,
  1810,
  4546,
  4546,
  5457,
  5457,
  2028,
  3775,
  2376,
  5227,
  6295,
  528,
  6647,
  1148,
  975,
  434,
  1305,
  5869,
  5799,
  2339,
  4084],
 [916,
  5869,
  4523,
  4472,
  377,
  6667,
  1555,
  1452,
  5680,
  3602,
  3520,
  4057,
  3690,
  5427,
  972,
  4372,
  5869,
  3618,
  4981,
  42,
  6316,
  4738,
  5869,
  2539,
  6520,
  2882],
 [4430,
  1899,
  6905,
  5743,
  2865,
  1555,
  4724,
  372,
  5514,
  1364,
  3880,
  2429,
  5446,
  5133,
  1357,
  448,
  1364,
  2502,
  5657,
  1092,
  6499,
  2872,
  1550,
  5948,
  5578,
  4213,
  1575,
  4611,
  858,
  5115,
  1810,
  1555,
  3436,
  2678,
  6330,
  2570,
  6649,
  4443,
  6384,
  4757,
  595,
  910,
  1995,
  4339,
  6768,
  6360,
  6112,
  2475,
  5963,
  1152,
  5026,
  2539,
  5851,
  5575,
  1109,
  5858,
  1555,
  3612,
  5133,
  4475,
  3196,
  3690,
  5118,
  1364,
  1156,
  1588,
  4505,
  4340,
  4003,
  4676,
  970],
 [1364,
  2280,
  5215,
  1555,
  3690,
  1364,
  717,
  5534,
  2104,
  3225,
  5507,
  1364,
  6272,
  4582,
  1691,
  3903,
  6863,
  4939,
  1396,
  3094,
  1022,
  6979,
  41,
  5314,
  2881,
  1550,
  3488,
  3711,
  1767,
  6533,
  2528,
  4009,
  5832,
  165,
  978,
  5307,
  4398,
  3757,
  4717,
  4240,
  1364,
  6293,
  5555,
  2183,
  3022,
  1305,
  3690,
  1364,
  4478,
  6659,
  3225,
  2478,
  6533,
  491],
 [5869,
  2842,
  1555,
  4372,
  1842,
  5099,
  5869,
  3819,
  4546,
  4546,
  3517,
  3935,
  1677,
  1555,
  3364,
  5427,
  1619,
  1550,
  6729,
  4441,
  3654,
  1555,
  1876,
  1677,
  5427,
  6882,
  212,
  1779,
  5683,
  3690,
  3920,
  4181,
  3941,
  4546,
  4546,
  5743,
  1075,
  5795,
  5869,
  538,
  6357,
  1817,
  2588,
  4546,
  4546,
  4003,
  4546,
  4546,
  2695,
  5743,
  774,
  5795,
  4040,
  5743,
  4230,
  6357,
  1817,
  3860,
  6669,
  1555,
  6922,
  4546,
  4546,
  1066,
  3920,
  694,
  2840,
  5133,
  1648,
  1422,
  1066,
  2785,
  3105,
  5904,
  4735,
  1963,
  1364,
  535,
  3529,
  5623,
  1963,
  5280,
  2268,
  6863,
  4546,
  4546,
  2256,
  3920,
  1523,
  172,
  1633,
  2588,
  5551,
  4546,
  4546,
  4003,
  6524,
  6911,
  3792,
  40,
  6486,
  6486,
  4546,
  4546,
  2753,
  978,
  2376,
  3334,
  2753,
  4320,
  5869,
  1588,
  1625,
  4003,
  5869,
  408,
  5869,
  491,
  1358,
  4546,
  4546,
  5099,
  4583,
  2514,
  1305,
  2028,
  1895,
  1156],
 [3539,
  1364,
  1855,
  1364,
  6274,
  2300,
  2503,
  6190,
  6498,
  904,
  4307,
  4650,
  6364,
  4148,
  3757,
  693,
  1460,
  2307,
  2300,
  2307,
  6148,
  2333,
  5883,
  514,
  4757,
  6488,
  1364,
  5091,
  4876,
  70,
  140,
  1452,
  1685,
  2419,
  934,
  1555,
  514,
  5115,
  2753,
  4352,
  2324,
  6374,
  4179,
  45,
  889,
  1351,
  2506,
  6374,
  2300,
  5141,
  6178,
  4958,
  5683,
  1625,
  6752,
  2300,
  1761,
  3196,
  2473,
  3532,
  4625,
  4392,
  947,
  2429,
  1364,
  5133],
 [5099,
  1364,
  603,
  4583,
  3981,
  1925,
  989,
  2238,
  3141,
  978,
  1855,
  6667,
  5146,
  4017,
  6940,
  3214,
  1775,
  6614,
  6411,
  3141,
  2735,
  96,
  978,
  972,
  3532,
  120,
  967,
  2280,
  5948,
  4400,
  4174,
  978,
  3562,
  3532,
  2842,
  4009,
  5896,
  1364,
  1082,
  1397,
  4204,
  3873,
  3184,
  1916,
  6032,
  2371,
  4222,
  6533,
  3340,
  5021,
  774,
  4562,
  3562,
  3452,
  1588,
  6051,
  1414,
  2645,
  1882,
  2896,
  1364,
  129],
 [3370,
  4639,
  858,
  6416,
  798,
  3687,
  1870,
  1702,
  4639,
  858,
  5869,
  4059,
  6131,
  3451,
  6131,
  6498,
  6131,
  6911,
  6425,
  5770,
  4639,
  858,
  5450,
  6911,
  1606,
  3178,
  455,
  5805,
  493,
  1860,
  498,
  4546,
  4546,
  5770,
  1555,
  5683,
  4959,
  5005,
  1499,
  4053,
  6304,
  5450,
  6693,
  2885,
  4359,
  3292,
  3043,
  1073,
  2590,
  5446,
  3669,
  6979,
  3319,
  1364,
  1555,
  2586,
  1457,
  3788,
  1860,
  4640,
  1951,
  5115,
  6832,
  832,
  6389,
  6109,
  4339,
  4882,
  439,
  6880,
  6330,
  2675,
  3371,
  1252,
  4717,
  4797,
  1252,
  4027,
  4546,
  4546,
  2250,
  4625,
  4496,
  3216,
  3099,
  6341,
  1574,
  83,
  5361,
  4368,
  2008,
  6414,
  5921,
  6760,
  792,
  51,
  4972,
  2263,
  2537,
  3637,
  4546,
  4546,
  5344,
  3463,
  4971,
  625,
  348,
  1832,
  3244,
  5965,
  5619,
  2502,
  584,
  2200,
  4952,
  6991,
  6672,
  869,
  1338,
  2500,
  4981,
  6647,
  2303,
  2608,
  4447,
  6716,
  3687,
  1847,
  5133,
  4428,
  1786,
  2490,
  1550,
  823,
  2218,
  111,
  2644,
  4546,
  4546,
  1598,
  603,
  2339,
  526,
  2643,
  4822,
  1452,
  3473,
  1898,
  1489,
  3690,
  3451,
  1082,
  2289,
  4447,
  3828,
  2200,
  172,
  4301,
  4096,
  5884,
  4478,
  5514,
  2200,
  79,
  972,
  41,
  4546,
  4546,
  6109,
  5896,
  6812,
  2504,
  1588,
  6647,
  4844,
  4833,
  2590,
  440,
  3751,
  4323,
  4478,
  6170,
  3812,
  1555,
  4196,
  3069],
 [5013,
  2031,
  772,
  1654,
  5869,
  6770,
  4546,
  4546,
  1305,
  1895,
  6911,
  1156,
  2250,
  3211,
  1654,
  5869,
  6911,
  4640,
  2039,
  1654,
  5869,
  5133,
  1056,
  5869,
  717,
  2733,
  5161,
  972,
  5869,
  978,
  6131,
  1452,
  2640,
  4938,
  2406,
  3690,
  3990,
  5310,
  2328,
  571,
  2595,
  4156,
  2595,
  4546,
  4546,
  5869,
  2435,
  3669,
  1864,
  1555,
  478,
  4507,
  1646,
  1588,
  4179,
  3634,
  2028,
  4680,
  5514,
  4546,
  4546,
  5869,
  5578,
  3291,
  1433,
  2829,
  4804,
  2450,
  5360,
  4053,
  4230,
  2264,
  4372,
  1082,
  1433,
  774,
  3832,
  2876,
  4923,
  5945,
  3819,
  6812,
  2104,
  334,
  4546,
  4546,
  4640,
  6384,
  1654,
  5869,
  5953,
  5858,
  4027,
  869,
  6385],
 [4413,
  3144,
  5869,
  3100,
  1708,
  6204,
  1887,
  6385,
  3946,
  491,
  6875,
  1005,
  2420,
  5869,
  960,
  1581,
  386,
  5953,
  3039,
  1823,
  6561,
  5263,
  2446,
  6911,
  745,
  352,
  6911,
  3687,
  4951,
  6558],
 [1855,
  2506,
  5115,
  4372,
  6638,
  1688,
  3520,
  6863,
  3326,
  96,
  6178,
  6385,
  995,
  1774,
  6911,
  2776,
  1654,
  5133,
  3468,
  1654,
  5869,
  470,
  4126,
  5133,
  1639,
  5869,
  4757,
  4546,
  4546,
  1839,
  5869,
  1855,
  1082,
  4799,
  5133,
  434,
  3693,
  1654,
  5869,
  1864,
  5787,
  6380,
  1789,
  1688,
  1082,
  5869,
  2339,
  5792,
  1442,
  4546,
  4546,
  1349,
  3690,
  3538,
  4640,
  3758,
  3539,
  995,
  1774,
  2936,
  96,
  3538,
  1555,
  5743,
  5869,
  5340,
  3539,
  2699,
  6954,
  3730,
  448,
  6954,
  5787,
  5013,
  689,
  1847,
  3758,
  1639,
  1151,
  4209,
  5021,
  5310,
  1349,
  3274,
  2530,
  6568,
  4053,
  6295,
  982,
  6610,
  2629,
  1,
  4148,
  2446,
  4721,
  45,
  6068,
  2019,
  4372,
  2641,
  6100,
  2409,
  3453,
  2532,
  5133,
  220,
  4764,
  1016,
  224,
  2515,
  1257,
  2286,
  4102,
  4397,
  4478,
  5869,
  5198,
  6911,
  4546,
  4546,
  64,
  4457,
  416,
  5427,
  5443,
  4812,
  2124,
  782,
  3180,
  1654,
  5869,
  906,
  71,
  4611,
  869,
  6385,
  4797,
  470,
  6911,
  3104,
  5869,
  365,
  1842,
  2657,
  3921,
  1708,
  1842,
  6586,
  434,
  5858,
  4546,
  4546,
  1490,
  6266,
  6379,
  365,
  1842,
  3103,
  4611,
  491,
  927,
  3690,
  6875,
  5200,
  4523,
  5312,
  4179,
  4102,
  5161,
  6875,
  377,
  6875,
  5200,
  5937],
 [3211,
  5869,
  1104,
  1500,
  5091,
  631,
  2028,
  4150,
  390,
  6687,
  934,
  3941,
  6614,
  5672,
  4150,
  5053,
  1452,
  1364,
  610,
  5119,
  4446,
  6464,
  5869,
  3935,
  43,
  491,
  5896,
  2241,
  680,
  5974,
  2896,
  2590,
  858,
  2202,
  5869,
  6384,
  4290,
  333,
  1550,
  6350,
  3023,
  4490,
  3612,
  6385,
  4583,
  6882,
  5190,
  978,
  5869,
  6298,
  1452,
  5115,
  1178,
  2881,
  785,
  6729,
  1278,
  2881,
  5133,
  1555,
  6911,
  6638,
  6568,
  5869,
  1104,
  4307,
  3320,
  4640,
  972,
  1555,
  6915,
  4546,
  4546],
 [4027,
  2852,
  978,
  416,
  4680,
  2394,
  4027,
  2852,
  1046,
  3452,
  3612,
  717,
  3104,
  1169,
  96,
  502,
  4546,
  4546,
  1334,
  232,
  3581,
  4027,
  967,
  4814,
  972,
  2241,
  329,
  10,
  5446,
  4342,
  4027,
  2852,
  934,
  1109,
  79,
  935,
  1550,
  3792,
  935,
  2758,
  4546,
  4546,
  4262,
  436,
  1109,
  1010,
  2852,
  399,
  610,
  1450,
  4027,
  3004,
  4546,
  4546,
  610,
  5951,
  1588,
  3492,
  3618,
  4686,
  6587,
  3612,
  5869,
  4372,
  3543,
  4367,
  3468,
  4122],
 [517,
  5256,
  3930,
  2530,
  3748,
  4610,
  4386,
  625,
  348,
  5091,
  1555,
  1728,
  2264,
  3862,
  1576,
  3274,
  172,
  4840,
  2718,
  5233,
  3998,
  1471,
  1178,
  6729,
  6230,
  3834,
  1309,
  955,
  3049,
  4885,
  388,
  3330,
  6353,
  6414,
  5869,
  6914,
  716,
  4546,
  4546,
  5822,
  5577,
  6411,
  1364,
  6721,
  6248,
  453,
  4830,
  4939,
  1550,
  3690,
  2590,
  2495,
  5760,
  1364,
  1622,
  646,
  5869,
  5344,
  5931,
  5502,
  5554,
  5869,
  2739,
  3352,
  517,
  6111,
  1942,
  5427,
  4487,
  3998,
  2741,
  1942,
  4354,
  40,
  2264,
  4696,
  344,
  454,
  2849,
  3532,
  2246,
  5427,
  5869,
  4696,
  3532,
  4625,
  5119,
  3792,
  3832,
  2388,
  4546,
  4546,
  352,
  4456,
  434,
  803,
  4386,
  625,
  348,
  4096,
  653,
  1160,
  5514,
  1555,
  3320,
  3669,
  5869,
  2932,
  5522,
  5161,
  625,
  348,
  1574,
  4370,
  761,
  517,
  6773,
  3425,
  5540,
  4486,
  1435,
  5599,
  4928,
  4386,
  6948,
  6954,
  4741,
  1657,
  4530,
  5254,
  6855,
  3326,
  3880,
  4247,
  4546,
  4546,
  5133,
  5869,
  63,
  6306,
  491,
  3078,
  888,
  2932,
  4518,
  412,
  5104,
  4882,
  5115,
  6648,
  519,
  5427,
  6961,
  931,
  497,
  5977,
  993,
  1847,
  5133,
  3687,
  5888,
  1990,
  6874,
  5427,
  6113,
  517,
  454,
  2506,
  5119,
  3064,
  2371,
  5133,
  4174,
  5133,
  4760,
  5869,
  5869,
  537,
  3229,
  4486,
  3301,
  603,
  2506,
  1536,
  2280,
  2446,
  4546,
  4546,
  601,
  1364,
  6190,
  5317,
  2892,
  6796,
  1303,
  1250,
  270,
  803,
  519,
  5427,
  327,
  1889,
  1333,
  2280,
  6271,
  2766,
  1364,
  3757,
  4224,
  5025,
  303,
  6414,
  6812,
  6414,

## Padding now:

In [21]:
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding
from tensorflow.keras.layers import Dense,LSTM,BatchNormalization

In [8]:
max_sent=50
padding=pad_sequences(ohe,maxlen=max_sent,padding='post')
padding

array([[4388, 1305, 1896, ..., 3900, 1288, 6945],
       [2473, 1198,  449, ..., 2355, 4020, 1700],
       [ 734, 5953, 3531, ..., 2339, 5119, 5182],
       ...,
       [6909, 5146, 6324, ...,  160, 1556, 5225],
       [5394, 2256, 2298, ..., 2854, 4587,   41],
       [5814, 3860, 4009, ..., 2235, 2595, 5869]], dtype=int32)

In [28]:
model=Sequential()
model.add(Embedding(vocab_size,100,input_length=max_sent))
model.add(LSTM(200))
model.add(Dense(1,activation='sigmoid'))
model.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

/home/hammadali08/.local/lib/python3.12/site-packages/keras/src/layers/core/embedding.py:97: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(

In [29]:
model.summary()

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_2 (Embedding)         │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_2 (LSTM)                   │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [30]:
Y=pd.get_dummies(dataset['sentiment'],drop_first=True)
Y=Y.astype('int64')
Y

       positive
0             1
1             1
2             1
3             0
4             1
...         ...
49995         1
49996         0
49997         0
49998         0
49999         0

[50000 rows x 1 columns]

In [31]:
import numpy as np
X=np.array(padding)
Y=np.array(Y)

In [32]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(X,Y,test_size=0.2,random_state=0)

# Model Training

In [33]:
model.fit(x_train,y_train,epochs=8,batch_size=100,validation_data=(x_test,y_test))

Epoch 1/8
400/400 ━━━━━━━━━━━━━━━━━━━━ 50s 119ms/step - accuracy: 0.8008 - loss: 0.4247 - val_accuracy: 0.8311 - val_loss: 0.3805
Epoch 2/8
400/400 ━━━━━━━━━━━━━━━━━━━━ 49s 123ms/step - accuracy: 0.8634 - loss: 0.3211 - val_accuracy: 0.8245 - val_loss: 0.3979
Epoch 3/8
400/400 ━━━━━━━━━━━━━━━━━━━━ 51s 127ms/step - accuracy: 0.8881 - loss: 0.2709 - val_accuracy: 0.8225 - val_loss: 0.3894
Epoch 4/8
400/400 ━━━━━━━━━━━━━━━━━━━━ 54s 134ms/step - accuracy: 0.9107 - loss: 0.2243 - val_accuracy: 0.8209 - val_loss: 0.4226
Epoch 5/8
400/400 ━━━━━━━━━━━━━━━━━━━━ 51s 129ms/step - accuracy: 0.9316 - loss: 0.1788 - val_accuracy: 0.8132 - val_loss: 0.5208
Epoch 6/8
400/400 ━━━━━━━━━━━━━━━━━━━━ 47s 118ms/step - accuracy: 0.9493 - loss: 0.1418 - val_accuracy: 0.8079 - val_loss: 0.5651
Epoch 7/8
189/400 ━━━━━━━━━━━━━━━━━━━━ 23s 112ms/step - accuracy: 0.9685 - loss: 0.0949

KeyboardInterrupt:

In [16]:
y_pred=model.predict(x_test)
y_pred=np.where(y_pred>0.5,1,0) # AUC ROC Curve

313/313 ━━━━━━━━━━━━━━━━━━━━ 7s 23ms/step

In [17]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test,y_pred)

array([[4166,  869],
       [1057, 3908]])

In [18]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.80      0.83      0.81      5035
           1       0.82      0.79      0.80      4965

    accuracy                           0.81     10000
   macro avg       0.81      0.81      0.81     10000
weighted avg       0.81      0.81      0.81     10000

In [19]:
from sklearn.metrics import roc_auc_score
roc_auc_score(y_test,y_pred)

0.8072589556888288

In [20]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.8074